/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/vi/chinese",{"dateFormatItem-Ehm":"E h:mm a","field-second-relative+0":"b\u00e2y gi\u1edd","field-weekday":"Ng\u00e0y trong tu\u1ea7n","field-wed-relative+0":"th\u1ee9 t\u01b0 tu\u1ea7n n\u00e0y","dateFormatItem-GyMMMEd":"E, d MMM, U","dateFormatItem-MMMEd":"E, d MMM","field-wed-relative+1":"th\u1ee9 t\u01b0 tu\u1ea7n sau","field-tue-relative+-1":"th\u1ee9 ba tu\u1ea7n tr\u01b0\u1edbc","dateFormat-long":"d MMMM, U","field-fri-relative+-1":"th\u1ee9 s\u00e1u tu\u1ea7n tr\u01b0\u1edbc",
"field-wed-relative+-1":"th\u1ee9 t\u01b0 tu\u1ea7n tr\u01b0\u1edbc","months-format-wide":"Th\u00e1ng1 Th\u00e1ng2 Th\u00e1ng3 Th\u00e1ng4 Th\u00e1ng5 Th\u00e1ng6 Th\u00e1ng7 Th\u00e1ng8 Th\u00e1ng9 Th\u00e1ng10 Th\u00e1ng11 Th\u00e1ng12".split(" "),"dateFormatItem-yyyyQQQ":"QQQ U","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"EEEE, d MMMM, U","dateFormatItem-yyyyMEd":"E, d/M/y","field-thu-relative+-1":"th\u1ee9 n\u0103m tu\u1ea7n tr\u01b0\u1edbc","dateFormatItem-Md":"d/M","dateFormatItem-yMd":"d/M/y",
"field-era":"K\u1ef7 nguy\u00ean","field-year":"N\u0103m","field-hour":"Gi\u1edd","months-format-abbr":"T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11 T12".split(" "),"field-sat-relative+0":"th\u1ee9 b\u1ea3y tu\u1ea7n n\u00e0y","field-sat-relative+1":"th\u1ee9 b\u1ea3y tu\u1ea7n sau","field-day-relative+0":"h\u00f4m nay","field-day-relative+1":"ng\u00e0y mai","field-thu-relative+0":"th\u1ee9 n\u0103m tu\u1ea7n n\u00e0y","dateFormatItem-GyMMMd":"d MMM, U","field-thu-relative+1":"th\u1ee9 n\u0103m tu\u1ea7n sau",
"dateFormatItem-H":"HH","dateFormatItem-Gy":"U","dateFormatItem-yyyyMMMEd":"E, d MMM, U","dateFormatItem-M":"L","dateFormatItem-yyyyMMM":"MMM U","dateFormatItem-yyyyMMMd":"d MMM, U","field-sun-relative+0":"ch\u1ee7 nh\u1eadt tu\u1ea7n n\u00e0y","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"ch\u1ee7 nh\u1eadt tu\u1ea7n sau","field-minute":"Ph\u00fat","field-dayperiod":"SA/CH","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","field-day-relative+-1":"h\u00f4m qua","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} 'l\u00fac' {0}",
"dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E, d/M","dateTimeFormat-full":"{1} 'l\u00fac' {0}","field-fri-relative+0":"th\u1ee9 s\u00e1u tu\u1ea7n n\u00e0y","field-fri-relative+1":"th\u1ee9 s\u00e1u tu\u1ea7n sau","field-day":"Ng\u00e0y","field-zone":"M\u00fai gi\u1edd","dateFormatItem-y":"U","field-year-relative+-1":"n\u0103m ngo\u00e1i","field-month-relative+-1":"th\u00e1ng tr\u01b0\u1edbc","dateFormatItem-hm":"h:mm a","dateFormatItem-yyyyMd":"d/M/y","field-month":"Th\u00e1ng","dateFormatItem-MMM":"LLL",
"field-tue-relative+0":"th\u1ee9 ba tu\u1ea7n n\u00e0y","field-tue-relative+1":"th\u1ee9 ba tu\u1ea7n sau","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"th\u1ee9 hai tu\u1ea7n n\u00e0y","field-mon-relative+1":"th\u1ee9 hai tu\u1ea7n sau","dateFormat-short":"d/M/yy","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","field-second":"Gi\u00e2y","field-sat-relative+-1":"th\u1ee9 b\u1ea3y tu\u1ea7n tr\u01b0\u1edbc","field-sun-relative+-1":"ch\u1ee7 nh\u1eadt tu\u1ea7n tr\u01b0\u1edbc",
"field-month-relative+0":"th\u00e1ng n\u00e0y","field-month-relative+1":"th\u00e1ng sau","dateFormatItem-Ed":"d E","field-week":"Tu\u1ea7n","dateFormat-medium":"d MMM, U","field-year-relative+0":"n\u0103m nay","field-week-relative+-1":"tu\u1ea7n tr\u01b0\u1edbc","dateFormatItem-yyyyM":"M/y","field-year-relative+1":"n\u0103m sau","dateFormatItem-yyyyQQQQ":"QQQQ U","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM U","field-mon-relative+-1":"th\u1ee9 hai tu\u1ea7n tr\u01b0\u1edbc",
"dateFormatItem-yyyy":"U","field-week-relative+0":"tu\u1ea7n n\u00e0y","field-week-relative+1":"tu\u1ea7n sau"});