/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/vi/generic",{"dateFormatItem-Ehm":"E h:mm a","field-second-relative+0":"b\u00e2y gi\u1edd","field-weekday":"Ng\u00e0y trong tu\u1ea7n","field-wed-relative+0":"th\u1ee9 t\u01b0 tu\u1ea7n n\u00e0y","dateFormatItem-GyMMMEd":"E, d, MMM, y G","dateFormatItem-MMMEd":"E, d MMM","field-wed-relative+1":"th\u1ee9 t\u01b0 tu\u1ea7n sau","field-tue-relative+-1":"th\u1ee9 ba tu\u1ea7n tr\u01b0\u1edbc","dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM, y G","field-fri-relative+-1":"th\u1ee9 s\u00e1u tu\u1ea7n tr\u01b0\u1edbc",
"field-wed-relative+-1":"th\u1ee9 t\u01b0 tu\u1ea7n tr\u01b0\u1edbc","dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"EEEE, d MMMM, y G","dateFormatItem-yyyyMEd":"E, d/M/y GGGGG","field-thu-relative+-1":"th\u1ee9 n\u0103m tu\u1ea7n tr\u01b0\u1edbc","dateFormatItem-Md":"d/M","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","field-era":"K\u1ef7 nguy\u00ean","field-year":"N\u0103m","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Gi\u1edd","field-sat-relative+0":"th\u1ee9 b\u1ea3y tu\u1ea7n n\u00e0y",
"field-sat-relative+1":"th\u1ee9 b\u1ea3y tu\u1ea7n sau","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"h\u00f4m nay","field-day-relative+1":"ng\u00e0y mai","field-thu-relative+0":"th\u1ee9 n\u0103m tu\u1ea7n n\u00e0y","dateFormatItem-GyMMMd":"d MMM, y G","field-thu-relative+1":"th\u1ee9 n\u0103m tu\u1ea7n sau","dateFormatItem-H":"HH","dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, d, MMM, y G","dateFormatItem-M":"L","dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d MMM, y G",
"field-sun-relative+0":"ch\u1ee7 nh\u1eadt tu\u1ea7n n\u00e0y","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"ch\u1ee7 nh\u1eadt tu\u1ea7n sau","field-minute":"Ph\u00fat","field-dayperiod":"SA/CH","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","field-day-relative+-1":"h\u00f4m qua","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} 'l\u00fac' {0}","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E, d/M","dateTimeFormat-full":"{1} 'l\u00fac' {0}","field-fri-relative+0":"th\u1ee9 s\u00e1u tu\u1ea7n n\u00e0y",
"field-fri-relative+1":"th\u1ee9 s\u00e1u tu\u1ea7n sau","field-day":"Ng\u00e0y","field-zone":"M\u00fai gi\u1edd","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y G","field-year-relative+-1":"n\u0103m ngo\u00e1i","field-month-relative+-1":"th\u00e1ng tr\u01b0\u1edbc","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dateFormatItem-yyyyMd":"d/M/y GGGGG","field-month":"Th\u00e1ng","dateFormatItem-MMM":"LLL",
"field-tue-relative+0":"th\u1ee9 ba tu\u1ea7n n\u00e0y","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","field-tue-relative+1":"th\u1ee9 ba tu\u1ea7n sau","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"th\u1ee9 hai tu\u1ea7n n\u00e0y","field-mon-relative+1":"th\u1ee9 hai tu\u1ea7n sau","dateFormat-short":"d/M/y GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a",
"field-second":"Gi\u00e2y","field-sat-relative+-1":"th\u1ee9 b\u1ea3y tu\u1ea7n tr\u01b0\u1edbc","field-sun-relative+-1":"ch\u1ee7 nh\u1eadt tu\u1ea7n tr\u01b0\u1edbc","field-month-relative+0":"th\u00e1ng n\u00e0y","field-month-relative+1":"th\u00e1ng sau","dateFormatItem-Ed":"d E","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"Tu\u1ea7n","dateFormat-medium":"d MMM, y G","field-year-relative+0":"n\u0103m nay","field-week-relative+-1":"tu\u1ea7n tr\u01b0\u1edbc","dateFormatItem-yyyyM":"M/y GGGGG",
"field-year-relative+1":"n\u0103m sau","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"th\u1ee9 hai tu\u1ea7n tr\u01b0\u1edbc","dateFormatItem-yyyy":"y G","field-week-relative+0":"tu\u1ea7n n\u00e0y","field-week-relative+1":"tu\u1ea7n sau"});