define(
   ({
    addDistance: "Längeneinheit hinzufügen",
    addArea: "Flächeneinheit hinzufügen",
    label: "Beschriftung",
    abbr: "Abkürzung",
    conversion: "Konvertierung",
    actions: "Aktionen",
    areaUnits: "Flächeneinheiten",
    distanceUnits: "Längeneinheiten",
    kilometers: "Kilometer",
    miles: "Meilen",
    meters: "Meter",
    feet: "Fuß",
    yards: "Yards",
    squareKilometers: "Quadratkilometer",
    squareMiles: "Quadratmeilen",
    acres: "Acres",
    hectares: "Hektar",
    squareMeters: "Quadratmeter",
    squareFeet: "Quadratfuß",
    squareYards: "Quadratyard",
    distance: "Entfernungen",
    area: "Flächen",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "km²",
    squareMilesAbbreviation: "mi²",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m²",
    squareFeetAbbreviation: "ft²",
    squareYardsAbbreviation: "yd²"
  })
);