// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/metadata/form/iso/gemet/templates/ConceptPane.html":'\x3cdiv class\x3d"gxeGemetPane"\x3e\r\n\r\n\t\x3cdiv class\x3d"gxeTop" data-dojo-attach-point\x3d"topNode"\x3e\r\n\t  \x3cdiv class\x3d"gxeLeft gxeFloatLeft"\x3e\r\n\t    \x3cselect data-dojo-attach-point\x3d"languageSelect" \r\n\t    \tdata-dojo-attach-event\x3d"onchange: _onLanguageChange"\x3e\x3c/select\x3e\r\n\t  \x3c/div\x3e\r\n\t  \x3cdiv class\x3d"gxeRight gxeFloatRight"\x3e\r\n\t    \x3clabel for\x3d"${id}_searchText"\x3e${i18nIso.gemet.concept.searchLabel}\x3c/label\x3e\r\n\t  \t\x3cinput id\x3d"${id}_searchText" type\x3d"text" size\x3d"30" data-dojo-attach-point\x3d"searchText"\x3e\r\n\t    \x3cdiv class\x3d"gxeIconSearch" title\x3d"${i18nIso.gemet.concept.searchTip}"\r\n\t    \tdata-dojo-attach-event\x3d"onclick: _onSearchClick"\x3e\x3c/div\x3e\r\n\t  \x3c/div\x3e\r\n\t  \x3cdiv class\x3d"gxeClear"\x3e\x3c/div\x3e\r\n\t\x3c/div\x3e\r\n  \r\n  \x3cdiv class\x3d"gxeOptions" data-dojo-attach-point\x3d"resultsNode"\x3e\x3c/div\x3e\r\n  \r\n  \x3cdiv class\x3d"gxeDialogActionBar" data-dojo-attach-point\x3d"bottomNode"\x3e\r\n\t  \x3cdiv class\x3d"gxeLeft gxeFloatLeft"\x3e\r\n\t\t\t\x3cspan class\x3d"gxeMessage" data-dojo-attach-point\x3d"workingNode"\x3e${i18nIso.gemet.searching}\x3c/span\x3e\r\n\t  \x3c/div\x3e\r\n    \x3cdiv class\x3d"gxeRight gxeFloatRight gxeButtons"\x3e\r\n\t    \x3cbutton class\x3d"gxeButton" data-dojo-attach-point\x3d"cancelButton"\r\n\t      data-dojo-attach-event\x3d"onclick: _onCancelClick"\x3e${i18nBase.general.cancel}\x3c/button\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"gxeClear"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n   \r\n\x3c/div\x3e'}});
define("esri/dijit/metadata/form/iso/gemet/ConceptPane","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/on dojo/keys dojo/dom-construct dojo/has ../../../base/Templated dojo/text!./templates/ConceptPane.html dojo/i18n!../../../nls/i18nBase dojo/i18n!../../../nls/i18nIso ../../../base/etc/docUtil ./gemet ../../../../../request ../../../../../kernel".split(" "),function(h,e,m,n,p,c,q,r,s,t,l,k,f,u,v){h=h([r],{dialogBroker:null,gxeDocument:null,initialValue:null,i18nBase:t,i18nIso:l,templateString:s,
gemetUrl:null,gemetConceptThesaurus:null,initialLanguage:null,_activePromise:null,postCreate:function(){this.inherited(arguments);this.workingNode.style.display="none";var a=this.gxeDocument.gxeContext;this.gemetUrl=a.gemetUrl;this.gemetConceptThesaurus=a.gemetConceptThesaurus;f.populateLanguages(this.gxeDocument,this.languageSelect);this.initialLanguage=f.getSelectedLanguage(this.languageSelect);this.searchText.value=f.getSessionConceptQuery();this._query();this.own(n(this.searchText,"keyup",e.hitch(this,
function(a){a.keyCode==p.ENTER&&this._query()})))},_addOption:function(a,b,d){var g="Unknown";b=null;a.preferredLabel&&"string"===typeof a.preferredLabel.string&&(g=e.trim(a.preferredLabel.string));a.definition&&"string"===typeof a.definition.string&&(b=e.trim(a.definition.string),0===b.length&&(b=null));var f=g,h=this;a=c.create("div",{"class":"gxeOption"},d);d=c.create("div",{"class":"gxeClickableText",onclick:function(){h._onSelect(f)}},a);k.setNodeText(d,g);null!==b&&0<b.length&&(g=c.create("div",
{"class":"gxeDescription gxeSmallText"},a),k.setNodeText(g,b))},_fetch:function(a,b){var d=this.gemetUrl+"/getConceptsMatchingRegexByThesaurus",d=d+("?thesaurus_uri\x3d"+encodeURIComponent(this.gemetConceptThesaurus)),d=d+("\x26language\x3d"+encodeURIComponent(a)),d=d+("\x26regex\x3d"+encodeURIComponent(b));return u({url:d,handleAs:"json",callbackParamName:"jsonp"},{})},_getSearchText:function(){return e.trim(this.searchText.value)},_handleError:function(a){this.workingNode.style.display="none";console.error(a);
a=l.gemet.ioerror.replace("{url}",this.gemetUrl);c.empty(this.resultsNode);var b=c.create("div",{"class":"gxeMessagePane"},this.resultsNode);c.create("div",{"class":"gxeIcon gxeIconError"},b);b=c.create("div",{"class":"gxeMessageText"},b);k.setNodeText(b,a)},_onCancelClick:function(a){this.onCancelClick(a)},onCancelClick:function(a){},_onLanguageChange:function(a){this._query()},_onSearchClick:function(a){this._query()},_onSelect:function(a){var b=f.getSelectedLanguage(this.languageSelect);this.initialLanguage!==
b&&f.saveSessionLanguage(b);this.onSelect(a)},onSelect:function(a){},_query:function(){var a=f.getSelectedLanguage(this.languageSelect),b=this._getSearchText();if(!(null===b||0===b.length)&&null===this._activePromise)this.workingNode.style.display="inline-block",c.empty(this.resultsNode),(this._activePromise=this._fetch(a,b)).then(e.hitch(this,function(a){this._activePromise=null;try{this._render(a,b)}catch(c){this._handleError(c)}}),e.hitch(this,function(a){this._activePromise=null;this._handleError(a)}))},
_render:function(a,b){var d=0,g=this.resultsNode;c.empty(g);m.forEach(a,function(a,b){d++;this._addOption(a,b,g)},this);this.workingNode.style.display="none";var e;0===d?(c.empty(g),e=c.create("div",{"class":"gxeMessagePane"},this.resultsNode),c.create("div",{"class":"gxeIcon gxeIconWarning"},e),e=c.create("div",{"class":"gxeMessageText"},e),k.setNodeText(e,l.gemet.noMatch)):f.saveSessionConceptQuery(b)}});q("extend-esri")&&e.setObject("dijit.metadata.form.iso.gemet.ConceptPane",h,v);return h});