/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/lt/buddhist",{"field-second-relative+0":"dabar","field-weekday":"Savait\u0117s diena","field-wed-relative+0":"\u0161is tre\u010diadienis","field-wed-relative+1":"kitas tre\u010diadienis","dateFormatItem-GyMMMEd":"E, MMM d, y G","dateFormatItem-MMMEd":"E, MMM d","field-tue-relative+-1":"paskutinis antradienis","days-format-short":"Sk Pr An Tr Kt Pn \u0160t".split(" "),"dateFormat-long":"MMMM d, y G","field-fri-relative+-1":"paskutinis penktadienis","field-wed-relative+-1":"paskutinis tre\u010diadienis",
"months-format-wide":"sausio vasario kovo baland\u017eio gegu\u017e\u0117s bir\u017eelio liepos rugpj\u016b\u010dio rugs\u0117jo spalio lapkri\u010dio gruod\u017eio".split(" "),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"EEEE, MMMM d, y G","dateFormatItem-yyyyMEd":"E, M/d/y GGGGG","field-thu-relative+-1":"paskutinis ketvirtadienis","dateFormatItem-Md":"M/d","field-era":"Era","timeFormat-short":"HH:mm","quarters-format-wide":["1-as ketvirtis","2-as ketvirtis",
"3-ias ketvirtis","4-as ketvirtis"],"timeFormat-long":"h:mm:ss a z","field-year":"Metai","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Valanda","months-format-abbr":"Sau Vas Kov Bal Geg Bir Lie Rgp Rgs Spl Lap Grd".split(" "),"field-sat-relative+0":"\u0161is \u0161e\u0161tadienis","field-sat-relative+1":"kitas \u0161e\u0161tadienis","timeFormat-full":"h:mm:ss a zzzz","field-day-relative+0":"\u0161iandien","field-thu-relative+0":"\u0161is ketvirtadienis","field-day-relative+1":"rytoj","field-thu-relative+1":"kitas ketvirtadienis",
"dateFormatItem-GyMMMd":"MMM d, y G","dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, MMM d, y G","dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"MMM d, y G","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"\u0161is sekmadienis","field-sun-relative+1":"kitas sekmadienis",eraAbbr:["BE"],"field-minute":"Minut\u0117","field-dayperiod":"iki piet\u0173 / po piet\u0173","field-day-relative+-1":"vakar","dateTimeFormat-long":"{1} {0}","dateFormatItem-MEd":"E, M/d","dateTimeFormat-full":"{1} {0}",
"field-fri-relative+0":"\u0161is penktadienis","field-fri-relative+1":"kitas penktadienis","field-day":"Diena","days-format-wide":"Sekmadienis Pirmadienis Antradienis Tre\u010diadienis Ketvirtadienis Penktadienis \u0160e\u0161tadienis".split(" "),"field-zone":"Laiko juosta","dateFormatItem-y":"y G","months-standAlone-narrow":"SVKBGBLRRSLG".split(""),"field-year-relative+-1":"pra\u0117j\u0119 metai","field-month-relative+-1":"pra\u0117j\u0119s m\u0117nuo","dateTimeFormats-appendItem-Year":"{0} {1}",
"dateFormatItem-yyyyMd":"M/d/y GGGGG","field-month":"M\u0117nuo","field-tue-relative+0":"\u0161is antradienis","field-tue-relative+1":"kitas antradienis","field-mon-relative+0":"\u0161is pirmadienis","field-mon-relative+1":"kitas pirmadienis","dateFormat-short":"M/d/y GGGGG","field-second":"Sekund\u0117","field-sat-relative+-1":"paskutinis \u0161e\u0161tadienis","field-sun-relative+-1":"paskutinis sekmadienis","field-month-relative+0":"\u0161is m\u0117nuo","field-month-relative+1":"kitas m\u0117nuo",
"dateFormatItem-Ed":"d E","field-week":"Savait\u0117","dateFormat-medium":"MMM d, y G","field-year-relative+0":"\u0161ie metai","field-week-relative+-1":"pra\u0117jusi savait\u0117","dateFormatItem-yyyyM":"M/y GGGGG","field-year-relative+1":"kiti metai","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"paskutinis pirmadienis","dateFormatItem-yyyy":"y G","field-week-relative+0":"\u0161i savait\u0117","field-week-relative+1":"kita savait\u0117"});