/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/lt/chinese",{"dateFormatItem-Ehm":"hh:mm a, E","field-second-relative+0":"dabar","field-weekday":"Savait\u0117s diena","field-wed-relative+0":"\u0161is tre\u010diadienis","dateFormatItem-GyMMMEd":"U MMM d, E","dateFormatItem-MMMEd":"MMM d, E","field-wed-relative+1":"kitas tre\u010diadienis","field-tue-relative+-1":"paskutinis antradienis","dateFormat-long":"U MMMM d","field-fri-relative+-1":"paskutinis penktadienis","field-wed-relative+-1":"paskutinis tre\u010diadienis","months-format-wide":"M\u0117nuo1 M\u0117nuo2 M\u0117nuo3 M\u0117nuo4 M\u0117nuo5 M\u0117nuo6 M\u0117nuo7 M\u0117nuo8 M\u0117nuo9 M\u0117nuo10 M\u0117nuo11 M\u0117nuo12".split(" "),
"dateFormatItem-yyyyQQQ":"U QQQ","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"U MMMM d, EEEE","dateFormatItem-yyyyMEd":"y-MM-dd, E","field-thu-relative+-1":"paskutinis ketvirtadienis","dateFormatItem-Md":"MM-dd","dateFormatItem-yMd":"y-MM-dd","field-era":"Era","field-year":"Metai","field-hour":"Valanda","months-format-abbr":"M\u0117n1 M\u0117n2 M\u0117n3 M\u0117n4 M\u0117n5 M\u0117n6 M\u0117n7 M\u0117n8 M\u0117n9 M\u0117n10 M\u0117n11 M\u0117n12".split(" "),"field-sat-relative+0":"\u0161is \u0161e\u0161tadienis",
"field-sat-relative+1":"kitas \u0161e\u0161tadienis","field-day-relative+0":"\u0161iandien","field-day-relative+1":"rytoj","field-thu-relative+0":"\u0161is ketvirtadienis","dateFormatItem-GyMMMd":"U MMM d","field-thu-relative+1":"kitas ketvirtadienis","dateFormatItem-H":"HH","dateFormatItem-Gy":"U","dateFormatItem-yyyyMMMEd":"U MMM d, E","dateFormatItem-M":"L","dateFormatItem-yyyyMMM":"U MMM","dateFormatItem-yyyyMMMd":"U MMM d","field-sun-relative+0":"\u0161is sekmadienis","dateFormatItem-Hm":"HH:mm",
"field-sun-relative+1":"kitas sekmadienis","field-minute":"Minut\u0117","field-dayperiod":"iki piet\u0173 / po piet\u0173","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","field-day-relative+-1":"vakar","dateFormatItem-h":"H a","dateTimeFormat-long":"{1} {0}","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"\u0161is penktadienis","field-fri-relative+1":"kitas penktadienis","field-day":"Diena","field-zone":"Laiko juosta","dateFormatItem-y":"U",
"field-year-relative+-1":"pra\u0117j\u0119 metai","field-month-relative+-1":"pra\u0117j\u0119s m\u0117nuo","dateFormatItem-hm":"hh:mm a","dateFormatItem-yyyyMd":"y-MM-dd","field-month":"M\u0117nuo","dateFormatItem-MMM":"LLL","field-tue-relative+0":"\u0161is antradienis","field-tue-relative+1":"kitas antradienis","dateFormatItem-EHm":"HH:mm, E","field-mon-relative+0":"\u0161is pirmadienis","field-mon-relative+1":"kitas pirmadienis","dateFormat-short":"y-MM-dd","dateFormatItem-EHms":"HH:mm:ss, E","dateFormatItem-Ehms":"hh:mm:ss a, E",
"field-second":"Sekund\u0117","field-sat-relative+-1":"paskutinis \u0161e\u0161tadienis","field-sun-relative+-1":"paskutinis sekmadienis","field-month-relative+0":"\u0161is m\u0117nuo","field-month-relative+1":"kitas m\u0117nuo","dateFormatItem-Ed":"E, d","field-week":"Savait\u0117","dateFormat-medium":"U MMM d","field-year-relative+0":"\u0161ie metai","field-week-relative+-1":"pra\u0117jusi savait\u0117","dateFormatItem-yyyyM":"y-MM","field-year-relative+1":"kiti metai","dateFormatItem-yyyyQQQQ":"U QQQQ",
"dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"hh:mm:ss a","dateFormatItem-GyMMM":"U MMM","field-mon-relative+-1":"paskutinis pirmadienis","dateFormatItem-yyyy":"U","field-week-relative+0":"\u0161i savait\u0117","field-week-relative+1":"kita savait\u0117"});