/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/lt/islamic",{"field-second-relative+0":"dabar","field-weekday":"Savait\u0117s diena","field-wed-relative+0":"\u0161is tre\u010diadienis","field-wed-relative+1":"kitas tre\u010diadienis","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"MMM d, E","field-tue-relative+-1":"paskutinis antradienis","days-format-short":"Sk Pr An Tr Kt Pn \u0160t".split(" "),"dateFormat-long":"G y 'm'. MMMM d 'd'.","field-fri-relative+-1":"paskutinis penktadienis","field-wed-relative+-1":"paskutinis tre\u010diadienis",
"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"G y 'm'. MMMM d 'd'., EEEE","dateFormatItem-yyyyMEd":"y-MM-dd G, E","field-thu-relative+-1":"paskutinis ketvirtadienis","dateFormatItem-Md":"MM-d","field-era":"Era","timeFormat-short":"hh:mm a","quarters-format-wide":["1-as ketvirtis","2-as ketvirtis","3-ias ketvirtis","4-as ketvirtis"],"timeFormat-long":"HH:mm:ss z","field-year":"Metai","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Valanda","field-sat-relative+0":"\u0161is \u0161e\u0161tadienis",
"field-sat-relative+1":"kitas \u0161e\u0161tadienis","timeFormat-full":"HH:mm:ss zzzz","field-day-relative+0":"\u0161iandien","field-thu-relative+0":"\u0161is ketvirtadienis","field-day-relative+1":"rytoj","field-thu-relative+1":"kitas ketvirtadienis","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"y MMM d G","timeFormat-medium":"hh:mm:ss a","field-sun-relative+0":"\u0161is sekmadienis",
"field-sun-relative+1":"kitas sekmadienis",eraAbbr:["AH"],"field-minute":"Minut\u0117","field-dayperiod":"iki piet\u0173 / po piet\u0173","field-day-relative+-1":"vakar","dateTimeFormat-long":"{1} {0}","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"\u0161is penktadienis","field-fri-relative+1":"kitas penktadienis","field-day":"Diena","days-format-wide":"Sekmadienis Pirmadienis Antradienis Tre\u010diadienis Ketvirtadienis Penktadienis \u0160e\u0161tadienis".split(" "),
"field-zone":"Laiko juosta","dateFormatItem-y":"G y","field-year-relative+-1":"pra\u0117j\u0119 metai","field-month-relative+-1":"pra\u0117j\u0119s m\u0117nuo","dateTimeFormats-appendItem-Year":"{0} {1}","dateFormatItem-yyyyMd":"GGGGG y-MM-dd","field-month":"M\u0117nuo","field-tue-relative+0":"\u0161is antradienis","field-tue-relative+1":"kitas antradienis","field-mon-relative+0":"\u0161is pirmadienis","field-mon-relative+1":"kitas pirmadienis","dateFormat-short":"GGGGG y-MM-dd","field-second":"Sekund\u0117",
"field-sat-relative+-1":"paskutinis \u0161e\u0161tadienis","field-sun-relative+-1":"paskutinis sekmadienis","field-month-relative+0":"\u0161is m\u0117nuo","field-month-relative+1":"kitas m\u0117nuo","dateFormatItem-Ed":"E, d","field-week":"Savait\u0117","dateFormat-medium":"G y MMM d","field-year-relative+0":"\u0161ie metai","field-week-relative+-1":"pra\u0117jusi savait\u0117","dateFormatItem-yyyyM":"GGGGG y-MM","field-year-relative+1":"kiti metai","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1}, {0}",
"dateFormatItem-GyMMM":"G y MMM","field-mon-relative+-1":"paskutinis pirmadienis","dateFormatItem-yyyy":"G y","field-week-relative+0":"\u0161i savait\u0117","field-week-relative+1":"kita savait\u0117"});