/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/lt/japanese",{"field-sat-relative+0":"\u0161is \u0161e\u0161tadienis","field-sat-relative+1":"kitas \u0161e\u0161tadienis","field-dayperiod":"Iki piet\u0173 / po piet\u0173","field-sun-relative+-1":"paskutinis sekmadienis","field-mon-relative+-1":"paskutinis pirmadienis","field-minute":"Minut\u0117","field-day-relative+-1":"vakar","field-weekday":"Savait\u0117s diena","field-era":"era","field-hour":"Valanda","field-sun-relative+0":"\u0161is sekmadienis","field-sun-relative+1":"kitas sekmadienis",
"field-wed-relative+-1":"paskutinis tre\u010diadienis","field-day-relative+0":"\u0161iandien","field-day-relative+1":"rytoj","dateFormat-long":"G y 'm'. MMMM d 'd'.","field-tue-relative+0":"\u0161is antradienis","field-zone":"Laiko juosta","field-tue-relative+1":"kitas antradienis","field-week-relative+-1":"pra\u0117jusi savait\u0117","dateFormat-medium":"G y MMM d","field-year-relative+0":"\u0161ie metai","field-year-relative+1":"kiti metai","field-sat-relative+-1":"paskutinis \u0161e\u0161tadienis",
"field-year-relative+-1":"pra\u0117j\u0119 metai","field-year":"Metai","field-fri-relative+0":"\u0161is penktadienis","field-fri-relative+1":"kitas penktadienis","field-week":"Savait\u0117","field-week-relative+0":"\u0161i savait\u0117","field-week-relative+1":"kita savait\u0117","field-month-relative+0":"\u0161is m\u0117nuo","field-month":"M\u0117nuo","field-month-relative+1":"kitas m\u0117nuo","field-fri-relative+-1":"paskutinis penktadienis","field-second":"Sekund\u0117","field-tue-relative+-1":"paskutinis antradienis",
"field-day":"Diena","field-mon-relative+0":"\u0161is pirmadienis","field-mon-relative+1":"kitas pirmadienis","field-thu-relative+0":"\u0161is ketvirtadienis","field-second-relative+0":"dabar","dateFormat-short":"GGGGG y-MM-dd","field-thu-relative+1":"kitas ketvirtadienis","dateFormat-full":"G y 'm'. MMMM d 'd'., EEEE","field-wed-relative+0":"\u0161is tre\u010diadienis","field-wed-relative+1":"kitas tre\u010diadienis","field-month-relative+-1":"pra\u0117j\u0119s m\u0117nuo","field-thu-relative+-1":"paskutinis ketvirtadienis"});