define(
   ({
    placeholder: "Văn bản trình giữ chỗ",
    url: "URL Trình mã hóa địa lý",
    name: "Tên Trình mã hóa địa lý",
    example: "Ví dụ",
    singleLineFieldName: "SingleLineFieldName",
    portalConnectionError: 'Không thể tải cấu hình trình mã hóa địa lý từ cổng thông tin',
    actions: "Các hành động",
    warning: "Phiên bản dịch vụ mã hóa địa lý này không được hỗ trợ. Tiện ích này hỗ trợ dịch vụ mã hóa địa lý 10.1 trở lên.",
    instruction: "Thiết lập các trình mã hóa địa lý trong tiện ích này. Bấm vào Thêm Trình mã hóa địa lý để tham chiếu một URL, chỉ định tên thân thiện với người dùng và thiết lập các thuộc tính khác. Bạn cũng có thể sắp xếp lại, cấu hình hay xóa các trình mã hóa địa lý dưới đây.",
    layerInstruction1: "Bạn có thể cấu hình điều kiện tìm kiếm trong ",
    layerInstruction2: "trang chi tiết bản đồ web",
    searchAddress: "Tìm kiếm theo địa chỉ",
    searchLayer: "Tìm kiếm theo lớp",
    layer: "Lớp",
    field: "Trường",
    condition: "Điều kiện",
    contains: "Bao gồm",
    deleteLastGeocoderError: "Không thể xóa mã địa lý gần nhất.",
    noSearchFactorError: "Bạn phải chọn ít nhất một khả năng (Tìm kiếm theo địa chỉ hoặc Tìm kiếm theo lớp).",
    equals: "Bằng",
    add: "Thêm Trình mã hóa địa lý",
    edit: "Chỉnh sửa Trình mã hóa địa lý",
    ok: "OK",
    cancel: "Hủy",
    geocoderNamePlaceHolder: "Trình mã hóa địa lý của tôi",
    geocodePlaceHolder: "Tìm địa chỉ hoặc địa điểm",
    REPEATING_ERROR: "Lặp lại các trường sau: "
  })
);