define(
   ({
    addDistance: "เพิ่มระยะทาง",
    addArea: "เพิ่มพื้นที่",
    label: "ตัวอักษร",
    abbr: "ตัวย่อ",
    conversion: "การแปลงค่า",
    actions: "กระทำ",
    areaUnits: "หน่วยพื้นที่",
    distanceUnits: "หน่วยระยะทาง",
    kilometers: "กิโลเมตร",
    miles: "ไมล์",
    meters: "เมตร",
    feet: "ฟุต",
    yards: "หลา",
    squareKilometers: "ตารางกิโลเมตร",
    squareMiles: "ตารางไมล์",
    acres: "เอเคอร์",
    hectares: "เฮกตาร์",
    squareMeters: "ตารางเมตร",
    squareFeet: "ตารางนิ้ว",
    squareYards: "ตารางหลา",
    distance: "ระยะทาง",
    area: "พื้นที่",
    kilometersAbbreviation: "กม.",
    milesAbbreviation: "ไมล์",
    metersAbbreviation: "ม.",
    feetAbbreviation: "ฟุต",
    yardsAbbreviation: "หลา",
    squareKilometersAbbreviation: "ตร.กม.",
    squareMilesAbbreviation: "ตร.ไมล์",
    acresAbbreviation: "เอซี",
    hectaresAbbreviation: "เฮกเตอร์",
    squareMetersAbbreviation: "ตร.ม.",
    squareFeetAbbreviation: "ตร.ฟุต",
    squareYardsAbbreviation: "ตร.หลา"
  })
);