define(
   ({
    _widgetLabel: "Dessin",
    selectDrawMode: "Sélectionner le mode de dessin",
    clear: "Effacer",
    point: "Point",
    line: "Ligne",
    polyline: "Polyligne",
    freehandPolyline: "Polyligne à main levée",
    triangle: "Triangle",
    extent: "Enveloppe",
    circle: "Cercle",
    ellipse: "Ellipse",
    polygon: "Polygone",
    freehandPolygon: "Polygone à main levée",
    text: "Texte",
    style: "Style",
    alpha: "Transparence",
    width: "Largeur",
    size: "Taille",
    color: "Couleur",
    markerColor: "Couleur du symbole ponctuel",
    outlineColor: "Couleur du contour",
    lineColor: "Couleur de ligne",
    fillColor: "Couleur de remplissage",
    showMeasurements: "Afficher les mesures",
    areaUnits: "Unités de surface",
    distanceUnits: "Unités de distance",
    kilometers: "Kilomètres",
    miles: "Miles",
    meters: "Mètres",
    feet: "Pieds",
    yards: "Yards",
    squareKilometers: "Kilomètres carrés",
    squareMiles: "Miles carrés",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Mètres carrés",
    squareFeet: "Pieds carrés",
    squareYards: "Yards carrés",
    undo: "Annuler",
    redo: "Rétablir"
  })
);