define(
   ({
    addDistance: "Lägg till längdenhet",
    addArea: "Lägg till areaenhet",
    label: "Etikett",
    abbr: "Förkortning",
    conversion: "Konvertering",
    actions: "Åtgärder",
    areaUnits: "Areaenheter",
    distanceUnits: "Längdenheter",
    kilometers: "Kilometer",
    miles: "Engelska mil",
    meters: "Meter",
    feet: "Fot",
    yards: "Yard",
    squareKilometers: "Kvadratkilometer",
    squareMiles: "Square miles",
    acres: "Tunnland",
    hectares: "Hektar",
    squareMeters: "Kvadratmeter",
    squareFeet: "Square feet",
    squareYards: "Square yards",
    distance: "Distanser",
    area: "Ytor",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "kv.km",
    squareMilesAbbreviation: "eng. kv.m",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "kv.m",
    squareFeetAbbreviation: "kv.fot",
    squareYardsAbbreviation: "kv.yd"
  })
);