define(
   ({
    showArcgisBasemaps: "Įtraukti portalo pagrindo žemėlapius",
    settings: "Nustatymai",
    add: "Paspauskite norėdami pridėti naują pagrindo žemėlapį",
    edit: "Savybės",
    title: "Pavadinimas",
    titlePH: "Pagrindo žemėlapio pavadinimas",
    thumbnail: "Miniatiūra",
    thumbnailHint: "Paspauskite vaizdą norėdami atnaujinti",
    url: "URL",
    urlPH: "Sluoksnio URL",
    addlayer: "Pridėti pagrindo žemėlapį",
    actions: "Veiksmai",
    warning: "Klaidinga įvestis",
    save: "Atgal ir išsaugoti",
    back: "Atgal ir atšaukti",
    addUrl: "Pridėti URL",
    autoCheck: "Automatinė patikra",
    checking: "Tikrinama...",
    ok: "Gerai",
    cancel: "Atšaukti",
    result: "Išsaugota sėkmingai",
    spError: "Visi į galeriją pridėti pagrindo žemėlapiai privalo būti toje pačioje koordinačių sistemoje.",
    invalidTitle1:"Pagrindo žemėlapis '",
    invalidTitle2:"' jau yra. Pasirinkite kitą pavadinimą.",
    invalidBasemapUrl1: "Šis sluoksnio tipas negali būti naudojamas kaip pagrindo žemėlapis.",
    invalidBasemapUrl2: "Kita nei dabartinio žemėlapio koordinačių sistema.",
    addBaselayer: "Pridėti pagrindo žemėlapio sluoksnį"
  })
);