define(
   ({
    addDistance: "Προσθήκη μονάδας μήκους",
    addArea: "Προσθήκη μονάδας εμβαδού",
    label: "Ετικέτα",
    abbr: "Συντομογραφία",
    conversion: "Μετατροπή",
    actions: "Ενέργειες",
    areaUnits: "Μονάδες εμβαδού",
    distanceUnits: "Μονάδες μήκους",
    kilometers: "Χιλιόμετρα",
    miles: "Μίλια",
    meters: "Μέτρα",
    feet: "Πόδια",
    yards: "Γιάρδες",
    squareKilometers: "Τετραγωνικά χιλιόμετρα",
    squareMiles: "Τετραγωνικά μίλια",
    acres: "Έικρ",
    hectares: "Εκτάρια",
    squareMeters: "Τετραγωνικά μέτρα",
    squareFeet: "Τετραγωνικά πόδια",
    squareYards: "Τετραγωνικές γιάρδες",
    distance: "Αποστάσεις",
    area: "Εμβαδά",
    kilometersAbbreviation: "χλμ.",
    milesAbbreviation: "μίλ.",
    metersAbbreviation: "μ.",
    feetAbbreviation: "πόδ.",
    yardsAbbreviation: "γιάρδ.",
    squareKilometersAbbreviation: "τ.χλμ.",
    squareMilesAbbreviation: "τ.μίλ.",
    acresAbbreviation: "έικρ",
    hectaresAbbreviation: "εκτάρ.",
    squareMetersAbbreviation: "τ.μ.",
    squareFeetAbbreviation: "τ.πόδ",
    squareYardsAbbreviation: "τ.γιάρδ."
  })
);