define(
   ({
    _widgetLabel: "Tegn",
    selectDrawMode: "Velg tegnemodus",
    clear: "Fjern",
    point: "Punkt",
    line: "Linje",
    polyline: "Polylinje",
    freehandPolyline: "Frihåndspolylinje",
    triangle: "Trekant",
    extent: "Konvolutt",
    circle: "Sirkel",
    ellipse: "Ellipse",
    polygon: "Polygon",
    freehandPolygon: "Frihåndspolygon",
    text: "Tekst",
    style: "Stil",
    alpha: "Gjennomsiktighet",
    width: "Bredde",
    size: "Størrelse",
    color: "Farge",
    markerColor: "Markørfarge",
    outlineColor: "Omrissfarge",
    lineColor: "Linjefarge",
    fillColor: "Fyllfarge",
    showMeasurements: "Vis målinger",
    areaUnits: "Arealenheter",
    distanceUnits: "Avstandsenheter",
    kilometers: "Kilometer",
    miles: "Miles",
    meters: "Meter",
    feet: "Fot",
    yards: "Yards",
    squareKilometers: "Kvadratkilometer",
    squareMiles: "Kvadratmiles",
    acres: "Acre",
    hectares: "Hektar",
    squareMeters: "Kvadratmeter",
    squareFeet: "Kvadratfot",
    squareYards: "Kvadratyard",
    undo: "Angre",
    redo: "Gjør om"
  })
);