define({
  root: ({
    _widgetLabel: "Geocoder",
    locationTitle: "Location",
    notFound: "Location '${LOCATION}' could not be found.",
    currentLocation: "Current location",
    notWhatYouWanted: "Not what you wanted?",
    selectAnother: "Select another location"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});