define(
   ({
    _widgetLabel: "رسم",
    selectDrawMode: "تحديد وضع الرسم",
    clear: "مسح",
    point: "نقطة",
    line: "الخط",
    polyline: "متعدد الخطوط",
    freehandPolyline: "خط يدوي حر متعدد",
    triangle: "مثلث",
    extent: "مُغلف",
    circle: "دائرة",
    ellipse: "قطع ناقص",
    polygon: "مضلع",
    freehandPolygon: "مضلع مسوم بخط يدوي حر",
    text: "النص",
    style: "نمط",
    alpha: "معدل الشفافية:",
    width: "العرض",
    size: "الحجم",
    color: "لون",
    markerColor: "لون العلامة",
    outlineColor: "اللون الأساسي",
    lineColor: "لون الخط",
    fillColor: "لون التعبئة",
    showMeasurements: "إظهار القياسات",
    areaUnits: "وحدات المنطقة",
    distanceUnits: "وحدات المسافة",
    kilometers: "كيلومترات",
    miles: "أميال",
    meters: "مترات",
    feet: "قدم",
    yards: "ياردات",
    squareKilometers: "كيلو مترات مربعة",
    squareMiles: "أميال مربعة",
    acres: "فدان",
    hectares: "هكتار",
    squareMeters: "أمتار مربعة",
    squareFeet: "قدم مربع",
    squareYards: "ياردات مربعة",
    undo: "تراجع",
    redo: "تراجع"
  })
);