// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/tasks/locator","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/has ../kernel ../request ../deferredUtils ./Task ./AddressCandidate".split(" "),function(m,f,u,q,l,v,y,r,w,z,n){m=m(z,{declaredClass:"esri.tasks.Locator",_eventMap:{"address-to-locations-complete":["addresses"],"addresses-to-locations-complete":["addresses"],"location-to-address-complete":["address"],"suggest-locations-complete":["suggestions"]},constructor:function(a){this._geocodeHandler=
f.hitch(this,this._geocodeHandler);this._geocodeAddressesHandler=f.hitch(this,this._geocodeAddressesHandler);this._reverseGeocodeHandler=f.hitch(this,this._reverseGeocodeHandler);this.registerConnectEvents()},outSpatialReference:null,setOutSpatialReference:function(a){this.outSpatialReference=a},_geocodeHandler:function(a,b,k,g,c){try{var h=a.candidates,e;b=[];var d,p=h.length,s=a.spatialReference,f;for(d=0;d<p;d++){e=h[d];if(f=e.location)f.spatialReference=s;b[d]=new n(e)}this._successHandler([b],
"onAddressToLocationsComplete",k,c)}catch(l){this._errorHandler(l,g,c)}},_geocodeAddressesHandler:function(a,b,k,g,c){try{var h=a.locations;b=[];var e,d=h.length,p=a.spatialReference,f;for(e=0;e<d;e++){if(f=h[e].location)f.spatialReference=p;b[e]=new n(h[e])}this._successHandler([b],"onAddressesToLocationsComplete",k,c)}catch(l){this._errorHandler(l,g,c)}},addressToLocations:function(a,b,k,g,c){var h,e,d,p,s,m,n;a.address&&(g=k,k=b,b=a.outFields,c=a.searchExtent,n=a.countryCode,h=a.magicKey,e=a.distance,
m=a.categories,a.location&&this.normalization&&(d=a.location.normalize()),p=a.maxLocations,s=a.forStorage,a=a.address);c&&(c=c.shiftCentralMeridian());var x=this.outSpatialReference;a=this._encode(f.mixin({},this._url.query,a,{f:"json",outSR:x&&l.toJson(x.toJson()),outFields:b&&b.join(",")||null,searchExtent:c&&l.toJson(c.toJson()),category:m&&m.join(",")||null,countryCode:n||null,magicKey:h||null,distance:e||null,location:d||null,maxLocations:p||null,forStorage:s||null}));var u=this._geocodeHandler,
v=this._errorHandler,t=new q(w._dfdCanceller);t._pendingDfd=r({url:this._url.path+"/findAddressCandidates",content:a,callbackParamName:"callback",load:function(a,b){u(a,b,k,g,t)},error:function(a){v(a,g,t)}});return t},suggestLocations:function(a){var b;b=new q;a.hasOwnProperty("location")&&this.normalization&&(a.location=a.location.normalize());a.searchExtent&&(a.searchExtent=a.searchExtent.shiftCentralMeridian());a=this._encode(f.mixin({},this._url.query,{f:"json",text:a.text,searchExtent:a.searchExtent&&
l.toJson(a.searchExtent.toJson()),category:a.categories&&a.categories.join(",")||null,location:a.location||null,distance:a.distance||null},{f:"json"}));r({url:this._url.path+"/suggest",content:a,callbackParamName:"callback"}).then(f.hitch(this,function(a){a=a.suggestions||[];this.onSuggestLocationsComplete(a);b.resolve(a)}),f.hitch(this,function(a){this._errorHandler(a);b.reject(a)}));return b},addressesToLocations:function(a,b,k){var g=this.outSpatialReference,c=[];u.forEach(a.addresses,function(a,
b){c.push({attributes:a})});a=this._encode(f.mixin({},this._url.query,{addresses:l.toJson({records:c})},{f:"json",outSR:g&&l.toJson(g.toJson())}));var h=this._geocodeAddressesHandler,e=this._errorHandler,d=new q(w._dfdCanceller);d._pendingDfd=r({url:this._url.path+"/geocodeAddresses",content:a,callbackParamName:"callback",load:function(a,c){h(a,c,b,k,d)},error:function(a){e(a,k,d)}});return d},_reverseGeocodeHandler:function(a,b,f,g,c){try{var h=new n({address:a.address,location:a.location,score:100});
this._successHandler([h],"onLocationToAddressComplete",f,c)}catch(e){this._errorHandler(e,g,c)}},locationToAddress:function(a,b,k,g){a&&this.normalization&&(a=a.normalize());var c=this.outSpatialReference;a=this._encode(f.mixin({},this._url.query,{outSR:c&&l.toJson(c.toJson()),location:a&&l.toJson(a.toJson()),distance:b,f:"json"}));var h=this._reverseGeocodeHandler,e=this._errorHandler,d=new q(w._dfdCanceller);d._pendingDfd=r({url:this._url.path+"/reverseGeocode",content:a,callbackParamName:"callback",
load:function(a,b){h(a,b,k,g,d)},error:function(a){e(a,g,d)}});return d},onSuggestLocationsComplete:function(){},onAddressToLocationsComplete:function(){},onAddressesToLocationsComplete:function(){},onLocationToAddressComplete:function(){}});v("extend-esri")&&f.setObject("tasks.Locator",m,y);return m});