define(
   ({
    _widgetLabel: "Trasare",
    selectDrawMode: "Selectare mod de trasare",
    clear: "Golire",
    point: "Punct",
    line: "Linie",
    polyline: "Linie poligonală",
    freehandPolyline: "Linie poligonală trasată manual",
    triangle: "Triunghi",
    extent: "Plic",
    circle: "Cerc",
    ellipse: "Elipsă",
    polygon: "Poligon",
    freehandPolygon: "Poligon trasat manual",
    text: "Text",
    style: "Stil",
    alpha: "Transparenţă",
    width: "Lăţime",
    size: "Dimensiune",
    color: "Culoare",
    markerColor: "Culoare marcaj",
    outlineColor: "Culoare contur",
    lineColor: "Culoare linie",
    fillColor: "Culoare de umplere",
    showMeasurements: "Afişare dimensiuni",
    areaUnits: "Unităţi suprafaţă",
    distanceUnits: "Unităţi distanţă",
    kilometers: "Kilometri",
    miles: "Mile",
    meters: "Metri",
    feet: "Ft",
    yards: "Yarzi",
    squareKilometers: "Kilometri pătraţi",
    squareMiles: "Mile pătrate",
    acres: "Acri",
    hectares: "Hectare",
    squareMeters: "Metri pătraţi",
    squareFeet: "Ft. la pătrat",
    squareYards: "Yd. la pătrat",
    undo: "Anulare",
    redo: "Repetare"
  })
);