define(
   ({
    _widgetLabel: "Piirrä",
    selectDrawMode: "Valitse piirustustapa",
    clear: "Tyhjennä",
    point: "Piste",
    line: "Viiva",
    polyline: "Taiteviiva",
    freehandPolyline: "Vapaakädenpiirto, viiva",
    triangle: "Kolmio",
    extent: "Kirjekuori",
    circle: "Ympyrä",
    ellipse: "Ellipsi",
    polygon: "Alue",
    freehandPolygon: "Vapaankäden alue",
    text: "Teksti",
    style: "Tyyli",
    alpha: "Läpinäkyvyys",
    width: "Leveys",
    size: "Koko",
    color: "Väri",
    markerColor: "Merkitsimen väri",
    outlineColor: "Reunaviivan väri",
    lineColor: "Viivan väri",
    fillColor: "Täyttöväri",
    showMeasurements: "Näytä mittaukset",
    areaUnits: "Pinta-alayksiköt",
    distanceUnits: "Etäisyyden yksiköt",
    kilometers: "Kilometriä",
    miles: "Mailia",
    meters: "Metriä",
    feet: "Jalkaa",
    yards: "Jaardia",
    squareKilometers: "Neliökilometriä",
    squareMiles: "Neliömailia",
    acres: "Eekkeriä",
    hectares: "Hehtaaria",
    squareMeters: "Neliömetriä",
    squareFeet: "Neliöjalkaa",
    squareYards: "Neliöjaardia",
    undo: "Kumoa",
    redo: "Tee uudelleen"
  })
);