define(
   ({
    addDistance: "Pievienot garuma mērvienību",
    addArea: "Pievienot laukuma mērvienību",
    label: "Kartes teksts",
    abbr: "Saīsinājums",
    conversion: "Konvertācija",
    actions: "Darbības",
    areaUnits: "Laukuma vienības",
    distanceUnits: "Garuma mērvienības",
    kilometers: "Kilometri",
    miles: "Jūdzes",
    meters: "Metri",
    feet: "Pēdas",
    yards: "Jardi",
    squareKilometers: "Kvadrātkilometri",
    squareMiles: "Kvadrātjūdzes",
    acres: "Akri",
    hectares: "Hektāri",
    squareMeters: "Kvadrātmetri",
    squareFeet: "Kvadrātpēdas",
    squareYards: "Kvadrātjardi",
    distance: "Attālumi",
    area: "Apgabali",
    kilometersAbbreviation: "km",
    milesAbbreviation: "jūdzes",
    metersAbbreviation: "m",
    feetAbbreviation: "pēdas",
    yardsAbbreviation: "jardi",
    squareKilometersAbbreviation: "kvadrātkilometri",
    squareMilesAbbreviation: "kvadrātjūdzes",
    acresAbbreviation: "akri",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "kvadrātmetri",
    squareFeetAbbreviation: "kvadrātpēdas",
    squareYardsAbbreviation: "kvadrātjardi"
  })
);