define(
   ({
    placeholder: "Paikkamerkkiteksti",
    url: "Geokooderin URL-osoite",
    name: "Geokooderin nimi",
    example: "Esimerkki",
    singleLineFieldName: "SingleLine kentän nimi",
    portalConnectionError: 'Geokooderin konfigurointia ei voi noutaa portaalista',
    actions: "Toimet",
    warning: "Tätä geokoodauspalvelun versiota ei tueta. Tämä pienoisohjelma tukee geokoodauspalvelun versiota 10.1 ja sitä uudempia versioita.",
    instruction: "Luo tämän pienoisohjelman geokooderit. Luo viite URL-osoitteeseen napsauttamalla Lisää geokooderi -vaihtoehtoa, määritä käyttäjäystävällinen nimi ja määritä muut ominaisuudet. Alla voit myös järjestää osoitepaikantimet uudelleen, määrittää tai poistaa ne.",
    layerInstruction1: "Voit määrittää hakuehdon ",
    layerInstruction2: "Web-kartan tietosivulla",
    searchAddress: "Hae osoitteen perusteella",
    searchLayer: "Hae karttatason perusteella",
    layer: "Karttataso",
    field: "Kenttä",
    condition: "Ehto",
    contains: "Sisältää",
    deleteLastGeocoderError: "Viimeistä geokooderia ei voi poistaa.",
    noSearchFactorError: "Vähintään yksi ominaisuus (Hae osoitteen perusteella tai Hae karttatason perusteella) on valittava.",
    equals: "On yhtä suuri kuin",
    add: "Lisää geokooderi",
    edit: "Muokkaa geokooderia",
    ok: "OK",
    cancel: "Peruuta",
    geocoderNamePlaceHolder: "Oma geokooderi",
    geocodePlaceHolder: "Etsi osoite tai paikka",
    REPEATING_ERROR: "Seuraavat kentät toistetaan: "
  })
);