define(
   ({
    _widgetLabel: "Dibujar",
    selectDrawMode: "Seleccionar modo de dibujo",
    clear: "Borrar",
    point: "Punto",
    line: "Línea",
    polyline: "Polilínea",
    freehandPolyline: "Polilínea a mano alzada",
    triangle: "Triángulo",
    extent: "Contorno",
    circle: "Círculo",
    ellipse: "Elipse",
    polygon: "Polígono",
    freehandPolygon: "Polígono a mano alzada",
    text: "Texto",
    style: "Estilo",
    alpha: "Transparencia",
    width: "Ancho",
    size: "Tamaño",
    color: "Color",
    markerColor: "Color del marcador",
    outlineColor: "Color del contorno",
    lineColor: "Color de línea",
    fillColor: "Color de relleno",
    showMeasurements: "Mostrar medidas",
    areaUnits: "Unidades de área",
    distanceUnits: "Unidades de distancia",
    kilometers: "Kilómetros",
    miles: "Millas",
    meters: "Metros",
    feet: "Pies",
    yards: "Yardas",
    squareKilometers: "Kilómetros cuadrados",
    squareMiles: "Millas cuadradas",
    acres: "Acres",
    hectares: "Hectáreas",
    squareMeters: "Metros cuadrados",
    squareFeet: "Pies cuadrados",
    squareYards: "Yardas cuadradas",
    undo: "Deshacer",
    redo: "Rehacer"
  })
);