define(
   ({
    addDistance: "הוסף יחידת אורך",
    addArea: "הוסף יחידת שטח",
    label: "תווית",
    abbr: "קיצור",
    conversion: "המרה",
    actions: "פעולות",
    areaUnits: "יחידות שטח",
    distanceUnits: "יחידות אורך",
    kilometers: "קילומטרים",
    miles: "מיילים",
    meters: "מטרים",
    feet: "רגל",
    yards: "יארד",
    squareKilometers: "קילומטר מרובע",
    squareMiles: "מיילים מרובעים",
    acres: "אקרים",
    hectares: "הקטרים",
    squareMeters: "מ' מרובע",
    squareFeet: "רגל מרובע",
    squareYards: "יארדים מרובעים",
    distance: "מרחקים",
    area: "שטחים",
    kilometersAbbreviation: "קילומטר",
    milesAbbreviation: "מייל",
    metersAbbreviation: "מטר",
    feetAbbreviation: "רגל",
    yardsAbbreviation: "יארד",
    squareKilometersAbbreviation: "קילומטר רבוע",
    squareMilesAbbreviation: "מייל רבוע",
    acresAbbreviation: "אקר",
    hectaresAbbreviation: "האקטר‬",
    squareMetersAbbreviation: "מטר רבוע",
    squareFeetAbbreviation: "‏‫רגל רבוע",
    squareYardsAbbreviation: "יארד רבוע"
  })
);