define(
   ({
    _widgetLabel: "Attribuuttabel",
    ok: "OK",
    cancel: "Annuleren",
    unsupportQueryWarning: "De laag moet querybewerking ondersteunen voor weergave in de widget Attribuuttabel. Zorg ervoor dat de querybewerking in de service aan is.",
    exportMessage: "Gegevens exporteren naar CSV-bestand?",
    exportFiles: "Exporteren naar CSV",
    options: "Opties",
    zoomto: "Zoomen naar",
    highlight: "Grafische elementen markeren",
    selectAll: "Gegevens op alle pagina´s selecteren",
    selectPage: "Gegevens op huidige pagina selecteren",
    clearSelection: "Selectie wissen",
    filterByExtent: "Filteren op kaartextent",
    showSelectedRecords: "Geselecteerde records weergeven",
    showRelatedRecords: "Gerelateerde records weergeven",
    noRelatedRecords: "Geen gerelateerde records",
    refresh: "Vernieuwen",
    features: "objecten",
    selected: "geselecteerd",
    transparent: "Transparante modus",
    indicate: "Selectie zoeken",
    columns: "Kolommen weergeven/verbergen",
    selectionSymbol: "Selectiesymbool",
    closeMessage: "Tabel verbergen (opnieuw uitvouwen vanaf de onderkant)",
    dataNotAvailable: "Gegevens niet beschikbaar!<br>Klik op de knop [Vernieuwen] om het nog eens te proberen.",
    openTableTip: "Attributentabel openen",
    closeTableTip: "Attributentabel verbergen"
  })
);