define(
   ({
    _widgetLabel: "Wyświetl",
    selectDrawMode: "Wybierz tryb wyświetlania",
    clear: "Wyczyść",
    point: "Punkt",
    line: "Linia",
    polyline: "Polilinia",
    freehandPolyline: "Dowolna polilinia",
    triangle: "Trójkąt",
    extent: "Obwiednia",
    circle: "Koło",
    ellipse: "Elipsa",
    polygon: "Poligon",
    freehandPolygon: "Dowolny poligon",
    text: "Tekst",
    style: "Styl",
    alpha: "Przezroczystość",
    width: "Szerokość",
    size: "Rozmiar",
    color: "Kolor",
    markerColor: "Kolor sygnatury",
    outlineColor: "Kolor obrysu",
    lineColor: "Kolor linii",
    fillColor: "Kolor wypełnienia",
    showMeasurements: "Pokaż pomiary",
    areaUnits: "Jednostki powierzchni",
    distanceUnits: "Jednostki odległości",
    kilometers: "Kilometry",
    miles: "Mile",
    meters: "Metry",
    feet: "Stopy",
    yards: "Jardy",
    squareKilometers: "Kilometry kwadratowe",
    squareMiles: "Mile kwadratowe",
    acres: "Akry",
    hectares: "Hektary",
    squareMeters: "Metry kwadratowe",
    squareFeet: "Stopy kwadratowe",
    squareYards: "Jardy kwadratowe",
    undo: "Cofnij",
    redo: "Ponów"
  })
);