define(
   ({
    _widgetLabel: "绘图",
    selectDrawMode: "选择绘制模式",
    clear: "清除",
    point: "点",
    line: "线",
    polyline: "折线",
    freehandPolyline: "手绘折线",
    triangle: "三角形",
    extent: "包络矩形",
    circle: "圆形",
    ellipse: "椭圆",
    polygon: "面",
    freehandPolygon: "手绘面",
    text: "文本",
    style: "样式",
    alpha: "透明度",
    width: "宽度",
    size: "大小",
    color: "颜色",
    markerColor: "标记颜色",
    outlineColor: "轮廓颜色",
    lineColor: "线颜色",
    fillColor: "填充颜色",
    showMeasurements: "显示测量",
    areaUnits: "面积单位",
    distanceUnits: "距离单位",
    kilometers: "千米",
    miles: "英里",
    meters: "米",
    feet: "英尺",
    yards: "码",
    squareKilometers: "平方千米",
    squareMiles: "平方英里",
    acres: "英亩",
    hectares: "公顷",
    squareMeters: "平方米",
    squareFeet: "平方英尺",
    squareYards: "平方码",
    undo: "撤消",
    redo: "恢复"
  })
);