define(
   ({
    addDistance: "Lisa vahemaa ühik",
    addArea: "Lisa pindala ühik",
    label: "Märgis",
    abbr: "Lühend",
    conversion: "Teisendus",
    actions: "Tegevused",
    areaUnits: "Pindalaühikud",
    distanceUnits: "Vahemaa ühikud",
    kilometers: "Kilomeetrit",
    miles: "Miili",
    meters: "Meetrit",
    feet: "Jalga",
    yards: "Jardi",
    squareKilometers: "Ruutkilomeetrit",
    squareMiles: "Ruutmiili",
    acres: "Aakrit",
    hectares: "Hektarit",
    squareMeters: "Ruutmeetrit",
    squareFeet: "Ruutjalga",
    squareYards: "Ruutjardi",
    distance: "Vahemaad",
    area: "Pindalad",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "km²",
    squareMilesAbbreviation: "mi²",
    acresAbbreviation: "ak",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m²",
    squareFeetAbbreviation: "ft²",
    squareYardsAbbreviation: "yd²"
  })
);