define(
   ({
    addDistance: "Adicionar Unidade de Comprimento",
    addArea: "Adicionar Unidade de Área",
    label: "Rótulo",
    abbr: "Abreviação",
    conversion: "Conversão",
    actions: "Ações",
    areaUnits: "Unidades de Área",
    distanceUnits: "Unidades de Comprimento",
    kilometers: "Quilômetros",
    miles: "Milhas",
    meters: "Metros",
    feet: "Pés",
    yards: "Jardas",
    squareKilometers: "Quilômetros quadrados",
    squareMiles: "Milhas quadradas",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Metros quadrados",
    squareFeet: "Pés quadrados",
    squareYards: "Jardas quadradas",
    distance: "Distâncias",
    area: "Áreas",
    kilometersAbbreviation: "km",
    milesAbbreviation: "milhas",
    metersAbbreviation: "m",
    feetAbbreviation: "pés",
    yardsAbbreviation: "jarda",
    squareKilometersAbbreviation: "sq km",
    squareMilesAbbreviation: "sq mi",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "sq m",
    squareFeetAbbreviation: "sq ft",
    squareYardsAbbreviation: "sq yd"
  })
);