define(
   ({
    _widgetLabel: "Kreslit",
    selectDrawMode: "Vybrat režim kreslení",
    clear: "Vyprázdnit",
    point: "Bod",
    line: "Linie",
    polyline: "Polylinie",
    freehandPolyline: "Polylinie od ruky",
    triangle: "Trojúhelník",
    extent: "Obálka",
    circle: "Kruh",
    ellipse: "Elipsa",
    polygon: "Polygon",
    freehandPolygon: "Polygon od ruky",
    text: "Text",
    style: "Styl",
    alpha: "Průhlednost",
    width: "Šířka",
    size: "Velikost",
    color: "Barva",
    markerColor: "Barva značky",
    outlineColor: "Barva obrysu",
    lineColor: "Barva čáry",
    fillColor: "Barva výplně",
    showMeasurements: "Zobrazit měření",
    areaUnits: "Plošné jednotky",
    distanceUnits: "Jednotky vzdálenosti",
    kilometers: "Kilometry",
    miles: "Míle",
    meters: "Metry",
    feet: "Stopy",
    yards: "Yardy",
    squareKilometers: "Čtvereční kilometry",
    squareMiles: "Čtvereční míle",
    acres: "Akry",
    hectares: "Hektary",
    squareMeters: "Čtvereční metry",
    squareFeet: "Čtvereční stopy",
    squareYards: "Čtvereční yardy",
    undo: "Zpět",
    redo: "Znovu"
  })
);