define(
   ({
    addDistance: "Adăugare unitate lungime",
    addArea: "Adăugare unitate suprafaţă",
    label: "Etichetă",
    abbr: "Abreviere",
    conversion: "Conversie",
    actions: "Acţiuni",
    areaUnits: "Unităţi suprafaţă",
    distanceUnits: "Unităţi lungime",
    kilometers: "Kilometri",
    miles: "Mile",
    meters: "Metri",
    feet: "Ft",
    yards: "Yarzi",
    squareKilometers: "Kilometri pătraţi",
    squareMiles: "Mile pătrate",
    acres: "Acri",
    hectares: "Hectare",
    squareMeters: "Metri pătraţi",
    squareFeet: "Ft. la pătrat",
    squareYards: "Yd. la pătrat",
    distance: "Distanţe",
    area: "Suprafeţe",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "km pătraţi",
    squareMilesAbbreviation: "mi pătrate",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m pătraţi",
    squareFeetAbbreviation: "ft pătraţi",
    squareYardsAbbreviation: "yd pătraţi"
  })
);