define(
   ({
    addDistance: "Uzunluk Birimi Ekle",
    addArea: "Alan Birimi Ekle",
    label: "Etiket",
    abbr: "Kısaltma",
    conversion: "Dönüşüm",
    actions: "İşlemler",
    areaUnits: "Alan Birimi",
    distanceUnits: "Uzunluk Birimleri",
    kilometers: "Kilometre",
    miles: "Mil",
    meters: "Metre",
    feet: "Fit",
    yards: "Yarda",
    squareKilometers: "Kilometre kare",
    squareMiles: "Mil kare",
    acres: "İngiliz Dönümü",
    hectares: "Hektar",
    squareMeters: "Metre kare",
    squareFeet: "Feet kare",
    squareYards: "Yarda kare",
    distance: "Mesafeler",
    area: "Alanlar",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yrd",
    squareKilometersAbbreviation: "km²",
    squareMilesAbbreviation: "mil²",
    acresAbbreviation: "ar",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m²",
    squareFeetAbbreviation: "ft²",
    squareYardsAbbreviation: "yd kare"
  })
);