/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/et/buddhist",{"field-second-relative+0":"praegu","field-weekday":"N\u00e4dalap\u00e4ev","field-wed-relative+0":"k\u00e4esolev kolmap\u00e4ev","field-wed-relative+1":"j\u00e4rgmine kolmap\u00e4ev","dateFormatItem-GyMMMEd":"E, d. MMMM y G","dateFormatItem-MMMEd":"E, d. MMM","field-tue-relative+-1":"eelmine teisip\u00e4ev","days-format-short":"ETKNRLP".split(""),"dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"eelmine reede","field-wed-relative+-1":"eelmine kolmap\u00e4ev",
"months-format-wide":"Jaanuar Veebruar M\u00e4rts Aprill Mai Juuni Juuli August September Oktoober November Detsember".split(" "),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1}, {0}","dateFormat-full":"EEEE, d. MMMM y G","dateFormatItem-yyyyMEd":"E, d.M y G","field-thu-relative+-1":"eelmine neljap\u00e4ev","dateFormatItem-Md":"d.M","field-era":"Ajastu","timeFormat-short":"H:mm","quarters-format-wide":["Esimene kvartal","Teine kvartal","Kolmas kvartal","Neljas kvartal"],"timeFormat-long":"H:mm:ss z",
"field-year":"Aasta","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Tund","months-format-abbr":"jaan veebr m\u00e4rts apr mai juuni juuli aug sept okt nov dets".split(" "),"field-sat-relative+0":"k\u00e4esolev laup\u00e4ev","field-sat-relative+1":"j\u00e4rgmine laup\u00e4ev","timeFormat-full":"H:mm:ss zzzz","field-day-relative+0":"t\u00e4na","field-thu-relative+0":"k\u00e4esolev neljap\u00e4ev","field-day-relative+1":"homme","field-thu-relative+1":"j\u00e4rgmine neljap\u00e4ev","dateFormatItem-GyMMMd":"d. MMM y G",
"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, d. MMMM y G","dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"d. MMM y G","timeFormat-medium":"H:mm:ss","field-sun-relative+0":"k\u00e4esolev p\u00fchap\u00e4ev","field-sun-relative+1":"j\u00e4rgmine p\u00fchap\u00e4ev",eraAbbr:["BE"],"field-minute":"Minut","field-dayperiod":"enne/p\u00e4rast l\u00f5unat","field-day-relative+-1":"eile","dateTimeFormat-long":"{1} kell {0}","dateFormatItem-MEd":"E, d.M","dateTimeFormat-full":"{1} kell {0}",
"field-fri-relative+0":"k\u00e4esolev reede","field-fri-relative+1":"j\u00e4rgmine reede","field-day":"P\u00e4ev","days-format-wide":"Esmasp\u00e4ev Teisip\u00e4ev Kolmap\u00e4ev Neljap\u00e4ev Reede Laup\u00e4ev P\u00fchap\u00e4ev".split(" "),"field-zone":"Ajav\u00f6\u00f6nd","dateFormatItem-y":"y G","months-standAlone-narrow":"JVMAMJJASOND".split(""),"field-year-relative+-1":"eelmine aasta","field-month-relative+-1":"eelmine kuu","dateTimeFormats-appendItem-Year":"{0} {1}","dateFormatItem-yyyyMd":"dd.MM.y GGGGG",
"field-month":"Kuu","field-tue-relative+0":"k\u00e4esolev teisip\u00e4ev","field-tue-relative+1":"j\u00e4rgmine teisip\u00e4ev","field-mon-relative+0":"k\u00e4esolev esmap\u00e4ev","field-mon-relative+1":"j\u00e4rgmine esmasp\u00e4ev","dateFormat-short":"dd.MM.y GGGGG","field-second":"Sekund","field-sat-relative+-1":"eelmine laup\u00e4ev","field-sun-relative+-1":"eelmine p\u00fchap\u00e4ev","field-month-relative+0":"k\u00e4esolev kuu","field-month-relative+1":"j\u00e4rgmine kuu","dateFormatItem-Ed":"E, d",
"field-week":"N\u00e4dal","dateFormat-medium":"d. MMM y G","field-year-relative+0":"k\u00e4esolev aasta","field-week-relative+-1":"eelmine n\u00e4dal","dateFormatItem-yyyyM":"M.y G","field-year-relative+1":"j\u00e4rgmine aasta","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1}, {0}","dateFormatItem-GyMMM":"G y MMM","field-mon-relative+-1":"eelmine esmasp\u00e4ev","dateFormatItem-yyyy":"y G","field-week-relative+0":"k\u00e4esolev n\u00e4dal","field-week-relative+1":"j\u00e4rgmine n\u00e4dal"});