/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/cldr/nls/et/gregorian",{"dateFormatItem-Ehm":"E H:mm","days-standAlone-short":"ETKNRLP".split(""),"months-format-narrow":"JVMAMJJASOND".split(""),"field-second-relative+0":"praegu","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"N\u00e4dalap\u00e4ev","dateFormatItem-yQQQ":"QQQ y","dateFormatItem-yMEd":"E, dd.MM.yy","field-wed-relative+0":"k\u00e4esolev kolmap\u00e4ev","field-wed-relative+1":"j\u00e4rgmine kolmap\u00e4ev","dateFormatItem-GyMMMEd":"E, d. MMMM y G","dateFormatItem-MMMEd":"E, d.M",
eraNarrow:["B","A","AD","CE"],"field-tue-relative+-1":"eelmine teisip\u00e4ev","days-format-short":"ETKNRLP".split(""),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y","field-fri-relative+-1":"eelmine reede","field-wed-relative+-1":"eelmine kolmap\u00e4ev","months-format-wide":"Jaanuar Veebruar M\u00e4rts Aprill Mai Juuni Juuli August September Oktoober November Detsember".split(" "),"dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"p\u00e4rast l\u00f5unat",
"dateFormat-full":"EEEE, d. MMMM y","field-thu-relative+-1":"eelmine neljap\u00e4ev","dateFormatItem-Md":"d.M","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"keskp\u00e4ev","dateFormatItem-yMd":"d.M.y","field-era":"Ajastu","dateFormatItem-yM":"y-MM","months-standAlone-wide":"Jaanuar Veebruar M\u00e4rts Aprill Mai Juuni Juuli August September Oktoober November Detsember".split(" "),"timeFormat-short":"H:mm","quarters-format-wide":["Esimene kvartal","Teine kvartal",
"Kolmas kvartal","Neljas kvartal"],"dateFormatItem-yQQQQ":"QQQQ y","timeFormat-long":"H:mm:ss z","field-year":"Aasta","dateFormatItem-yMMM":"MMM y","dateTimeFormats-appendItem-Era":"{0} {1}","field-hour":"Tund","months-format-abbr":"jaan veebr m\u00e4rts apr mai juuni juuli aug sept okt nov dets".split(" "),"field-sat-relative+0":"k\u00e4esolev laup\u00e4ev","field-sat-relative+1":"j\u00e4rgmine laup\u00e4ev","timeFormat-full":"H:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"t\u00e4na",
"field-thu-relative+0":"k\u00e4esolev neljap\u00e4ev","field-day-relative+1":"homme","field-thu-relative+1":"j\u00e4rgmine neljap\u00e4ev","dateFormatItem-GyMMMd":"d. MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"jaan veebr m\u00e4rts apr mai juuni juuli aug sept okt nov dets".split(" "),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["Esimene kvartal","Teine kvartal","Kolmas kvartal","Neljas kvartal"],"dateFormatItem-Gy":"y G","dateFormatItem-M":"L","days-standAlone-wide":"Esmasp\u00e4ev Teisip\u00e4ev Kolmap\u00e4ev Neljap\u00e4ev Reede Laup\u00e4ev P\u00fchap\u00e4ev".split(" "),
"timeFormat-medium":"H:mm:ss","field-sun-relative+0":"k\u00e4esolev p\u00fchap\u00e4ev","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"j\u00e4rgmine p\u00fchap\u00e4ev",eraAbbr:["eKr","e.m.a","m.a.j","n.a."],"field-minute":"Minut","field-dayperiod":"enne/p\u00e4rast l\u00f5unat","dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","field-day-relative+-1":"eile","dateFormatItem-h":"h a","dateTimeFormat-long":"{1} kell {0}","dayPeriods-format-narrow-am":"m.a.j.","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E, d.M",
"dateTimeFormat-full":"{1} kell {0}","field-fri-relative+0":"k\u00e4esolev reede","field-fri-relative+1":"j\u00e4rgmine reede","field-day":"P\u00e4ev","days-format-wide":"Esmasp\u00e4ev Teisip\u00e4ev Kolmap\u00e4ev Neljap\u00e4ev Reede Laup\u00e4ev P\u00fchap\u00e4ev".split(" "),"field-zone":"Ajav\u00f6\u00f6nd","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","dateFormatItem-y":"y","months-standAlone-narrow":"JVMAMJJASOND".split(""),"field-year-relative+-1":"eelmine aasta","field-month-relative+-1":"eelmine kuu",
"dateFormatItem-hm":"H:mm","dateTimeFormats-appendItem-Year":"{0} {1}","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","days-format-abbr":"ETKNRLP".split(""),"dateFormatItem-yMMMd":"dd.MM.y",eraNames:["enne meie aega","enne n\u00fc\u00fcdisaega","meie aja j\u00e4rgi","n\u00fc\u00fcdisaeg"],"days-standAlone-narrow":"ETKNRLP".split(""),"dateFormatItem-MMM":"MMMM","field-month":"Kuu","field-tue-relative+0":"k\u00e4esolev teisip\u00e4ev","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","field-tue-relative+1":"j\u00e4rgmine teisip\u00e4ev",
"dayPeriods-format-wide-am":"e.k.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"k\u00e4esolev esmap\u00e4ev","field-mon-relative+1":"j\u00e4rgmine esmasp\u00e4ev","dateFormat-short":"y-MM-dd","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"k","field-second":"Sekund","field-sat-relative+-1":"eelmine laup\u00e4ev","dateFormatItem-yMMMEd":"E, d. MMM y",
"field-sun-relative+-1":"eelmine p\u00fchap\u00e4ev","field-month-relative+0":"k\u00e4esolev kuu","field-month-relative+1":"j\u00e4rgmine kuu","dateFormatItem-Ed":"E, d","dateTimeFormats-appendItem-Timezone":"{0} {1}","field-week":"N\u00e4dal","dateFormat-medium":"dd.MM.y","field-year-relative+0":"k\u00e4esolev aasta","field-week-relative+-1":"eelmine n\u00e4dal","field-year-relative+1":"j\u00e4rgmine aasta","dayPeriods-format-narrow-pm":"p\u00e4rast l\u00f5unat","dateTimeFormat-short":"{1}, {0}",
"dateFormatItem-Hms":"H:mm:ss","dateFormatItem-hms":"H:mm:ss","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"eelmine esmasp\u00e4ev","field-week-relative+0":"k\u00e4esolev n\u00e4dal","field-week-relative+1":"j\u00e4rgmine n\u00e4dal"});