define(
   ({
    showArcgisBasemaps: "Iekļaut portāla pamatkartes",
    settings: "Iestatījumi",
    add: "Noklikšķiniet, lai pievienotu jaunu pamatkarti",
    edit: "Īpašības",
    title: "Nosaukums",
    titlePH: "Pamatkartes nosaukums",
    thumbnail: "Sīktēls",
    thumbnailHint: "Noklikšķiniet uz attēla, lai atjauninātu",
    url: "URL",
    urlPH: "Slāņa URL",
    addlayer: "Pievienot pamatkarti",
    actions: "Darbības",
    warning: "Nepareiza ievade",
    save: "Atgriezties un saglabāt",
    back: "Atgriezties un atcelt",
    addUrl: "Pievienot URL",
    autoCheck: "Automātiskā pārbaude",
    checking: "Pārbaude...",
    ok: "Labi",
    cancel: "Atcelt",
    result: "Saglabāšana sekmīga",
    spError: "Visām galerijai pievienotajām pamatkartēm ir jābūt vienām un tām pašām telpiskajām atskaitēm.",
    invalidTitle1:"Pamatkarte '",
    invalidTitle2:"' jau pastāv. Lūdzu, izvēlieties citu nosaukumu.",
    invalidBasemapUrl1: "Šo slāņa tipu nevar izmantot kā pamatkarti.",
    invalidBasemapUrl2: "Telpiskā atskaite atšķiras no pašreizējās kartes.",
    addBaselayer: "Pievienot pamatkartes slāni"
  })
);