define(
   ({
    showArcgisBasemaps: "Inclure les fonds de carte du portail",
    settings: "Paramètres",
    add: "Cliquez pour ajouter un nouveau fond de carte",
    edit: "Propriétés",
    title: "Titre",
    titlePH: "Titre du fond de carte",
    thumbnail: "Miniature",
    thumbnailHint: "Cliquez sur l\'image pour la mettre à jour",
    url: "URL",
    urlPH: "URL de la couche",
    addlayer: "Ajouter un fond de carte",
    actions: "Actions",
    warning: "Entrée incorrecte",
    save: "Retour et enregistrer",
    back: "Retour et annuler",
    addUrl: "Ajouter une URL",
    autoCheck: "Vérification automatique",
    checking: "Vérification...",
    ok: "OK",
    cancel: "Annuler",
    result: "Enregistrement réussi",
    spError: "Tous les fonds de carte ajoutés à la bibliothèque doivent avoir les mêmes références spatiales.",
    invalidTitle1:"Un fond de carte nommé \'",
    invalidTitle2:"\' existe déjà. Choisissez un autre titre.",
    invalidBasemapUrl1: "Ce type de couche ne peut pas être utilisé comme fond de carte.",
    invalidBasemapUrl2: "Référence spatiale différente de la carte actuelle.",
    addBaselayer: "Ajouter une couche de fonds de carte"
  })
);