define(
   ({
    _widgetLabel: "Tegn",
    selectDrawMode: "Vælg tegnetilstand",
    clear: "Ryd",
    point: "Punkt",
    line: "Linje",
    polyline: "Polylinje",
    freehandPolyline: "Frihåndspolylinje",
    triangle: "Triangel",
    extent: "Konvolut",
    circle: "Cirkel",
    ellipse: "Ellipse",
    polygon: "Polygon",
    freehandPolygon: "Frihåndspolygon",
    text: "Tekst",
    style: "Typografi",
    alpha: "Gennemsigtighed",
    width: "Bredde",
    size: "Størrelse",
    color: "Farve",
    markerColor: "Mærkefarve",
    outlineColor: "Konturfarve",
    lineColor: "Linjefarve",
    fillColor: "Udfyldningsfarve",
    showMeasurements: "Vis målinger",
    areaUnits: "Områdeenheder",
    distanceUnits: "Afstandsenheder",
    kilometers: "Kilometer",
    miles: "Miles",
    meters: "Meter",
    feet: "Fod",
    yards: "Yards",
    squareKilometers: "Kvadratkilometer",
    squareMiles: "Square miles",
    acres: "Acres",
    hectares: "Hektar",
    squareMeters: "Kvadratmeter",
    squareFeet: "Square feet",
    squareYards: "Square yards",
    undo: "Fortryd",
    redo: "Annullér Fortryd"
  })
);