define(
   ({
    placeholder: "Texte de l\'espace réservé",
    url: "URL du géocodeur",
    name: "Nom du géocodeur",
    example: "Exemple",
    singleLineFieldName: "Nom de champ sur une seule ligne",
    portalConnectionError: 'Impossible d’obtenir les configurations du géocodeur auprès du portail',
    actions: "Actions",
    warning: "Cette version du service de géocodage n\'est pas prise en charge. Ce widget prend en charge le service de géocodage 10.1 et version supérieure.",
    instruction: "Paramétrez les géocodeurs dans ce widget. Cliquez sur Ajouter un géocodeur pour référencer une URL, spécifier un nom simple pour les utilisateurs et définir d\'autres propriétés. Vous pouvez également réorganiser, configurer ou supprimer vos géocodeurs ci-dessous.",
    layerInstruction1: "Vous pouvez configurer la condition de recherche dans la ",
    layerInstruction2: "page des détails de la carte Web",
    searchAddress: "Rechercher par adresse",
    searchLayer: "Rechercher par couche",
    layer: "Couche",
    field: "Champ",
    condition: "Condition",
    contains: "Contient",
    deleteLastGeocoderError: "Impossible de supprimer le dernier géocodeur.",
    noSearchFactorError: "Vous devez sélectionner une fonctionnalité (Rechercher par adresse ou Recherche par couche) au moins.",
    equals: "Est égal à",
    add: "Ajouter un géocodeur",
    edit: "Modifier le géocodeur",
    ok: "OK",
    cancel: "Annuler",
    geocoderNamePlaceHolder: "Mon géocodeur",
    geocodePlaceHolder: "Rechercher une adresse ou un lieu",
    REPEATING_ERROR: "Les champs suivants sont répétés : "
  })
);