define({
  root: ({
    placeholder: "Placeholder Text",
    url: "Geocoder URL",
    name: "Geocoder Name",
    example: "Example",
    singleLineFieldName: "SingleLineFieldName",
    portalConnectionError: 'Can not get the configurations of geocoder from portal',
    actions: "Actions",
    warning: "This is not a supported version of geocoding service. This widget supports geocoding service 10.1 and above.",
    instruction: "Establish the geocoders in this widget. Click Add Geocoder to reference a URL, specify a user friendly name, and set other properties. You can also reorder, configure, or delete your geocoders below.",
    layerInstruction1: "You can configure the search condition in ",
    layerInstruction2: "web map’s details page",
    searchAddress: "Search by address",
    searchLayer: "Search by layer",
    layer: "Layer",
    field: "Field",
    condition: "Condition",
    contains: "Contains",
    deleteLastGeocoderError: "The last geocoder cannot be deleted.",
    noSearchFactorError: "You have to select one capability (Search by address or Search by layer) at least.",
    equals: "Equals",
    add: "Add Geocoder",
    edit: "Edit Geocoder",
    ok: "OK",
    cancel: "Cancel",
    geocoderNamePlaceHolder: "My Geocoder",
    geocodePlaceHolder: "Find address or place",
    REPEATING_ERROR: "The following fields are repeated: "
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});