define(
   ({
    addDistance: "Adicionar Unidade de Distância",
    addArea: "Adicionar Unidade de Área",
    label: "Rótulo",
    abbr: "Abreviação",
    conversion: "Conversão",
    actions: "Ações",
    areaUnits: "Unidades de Área",
    distanceUnits: "Unidades de Distância",
    kilometers: "Quilômetros",
    miles: "Milhas",
    meters: "Metros",
    feet: "Pés",
    yards: "Jardas",
    squareKilometers: "Quilómetros quadrados",
    squareMiles: "Milhas quadradas",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Metros quadrados",
    squareFeet: "Pés quadrados",
    squareYards: "Jardas quadradas",
    distance: "Distâncias",
    area: "Áreas",
    kilometersAbbreviation: "km",
    milesAbbreviation: "milhas",
    metersAbbreviation: "m",
    feetAbbreviation: "pés",
    yardsAbbreviation: "jardas",
    squareKilometersAbbreviation: "km2",
    squareMilesAbbreviation: "milhas2",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m2",
    squareFeetAbbreviation: "pés2",
    squareYardsAbbreviation: "jardas2"
  })
);