define(
   ({
    placeholder: "Texto del marcador de posición",
    url: "Dirección URL del geocodificador",
    name: "Nombre del geocodificador",
    example: "Ejemplo",
    singleLineFieldName: "NombreCampoLíneaSimple",
    portalConnectionError: 'No se pueden obtener las configuraciones del geocodificador desde el portal',
    actions: "Acciones",
    warning: "No se admite esta versión de servicio de geocodificación. Este widget admite servicios de geocodificación 10.1 y superiores.",
    instruction: "Establece los geocodificadores en este widget. Haz clic en Agregar geocodificador para hacer referencia a una URL, especifica un nombre descriptivo y define otras propiedades. También puedes reordenar, configurar o eliminar los geocodificadores más abajo.",
    layerInstruction1: "Puedes configurar la condición de búsqueda en la ",
    layerInstruction2: "página de detalles del mapa web",
    searchAddress: "Búsqueda por dirección",
    searchLayer: "Búsqueda por capa",
    layer: "Capa",
    field: "Campo",
    condition: "Condición",
    contains: "Contiene",
    deleteLastGeocoderError: "No se puede eliminar el último geocodificador.",
    noSearchFactorError: "Debes seleccionar una función (Búsqueda por dirección o Búsqueda por capa) como mínimo.",
    equals: "Es igual a",
    add: "Agregar geocodificador",
    edit: "Editar geocodificador",
    ok: "Aceptar",
    cancel: "Cancelar",
    geocoderNamePlaceHolder: "Mi geocodificador",
    geocodePlaceHolder: "Buscar dirección o lugar",
    REPEATING_ERROR: "Los campos siguientes están repetidos: "
  })
);