// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/dijit/editing/nls/Editor_az",{"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"now","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"MMM d, E",eraNarrow:["AH"],
"field-tue-relative+-1":"last Tuesday","days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G y MMMM d","field-fri-relative+-1":"last Friday","field-wed-relative+-1":"last Wednesday","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1} {0}",
"dayPeriods-format-wide-pm":"PM","dateFormat-full":"G y MMMM d, EEEE","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E","field-thu-relative+-1":"last Thursday","dateFormatItem-Md":"MM-dd",_localized:{},"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"timeFormat-short":"HH:mm","quarters-format-wide":["Q1","Q2","Q3","Q4"],"timeFormat-long":"HH:mm:ss z","field-year":"Year","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hour","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"today",
"field-thu-relative+0":"this Thursday","field-day-relative+1":"tomorrow","field-thu-relative+1":"next Thursday","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-M":"L","days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"this Sunday","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"next Sunday","quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"Dayperiod","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1",
"2","3","4"],"field-day-relative+-1":"yesterday","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"this Friday","field-fri-relative+1":"next Friday","field-day":"Day","days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"field-zone":"Zone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})",
"field-year-relative+-1":"last year","field-month-relative+-1":"last month","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["AH"],"days-format-narrow":"SMTWTFS".split(""),"dateFormatItem-yyyyMd":"GGGGG y-MM-dd","field-month":"Month","days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"this Tuesday",
"field-tue-relative+1":"next Tuesday","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","dateFormat-short":"GGGGG y-MM-dd","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Second",
"field-sat-relative+-1":"last Saturday","field-sun-relative+-1":"last Sunday","field-month-relative+0":"this month","field-month-relative+1":"next month","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d, E","field-week":"Week","dateFormat-medium":"G y MMM d","field-week-relative+-1":"last week","field-year-relative+0":"this year","dateFormatItem-yyyyM":"GGGGG y-MM","field-year-relative+1":"next year","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1} {0}",
"dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G y MMM","field-mon-relative+-1":"last Monday","dateFormatItem-yyyy":"G y","field-week-relative+0":"this week","field-week-relative+1":"next week"},"dijit/_editor/nls/commands":{removeFormat:"Format\u0131 Sil",copy:"K\u00f6\u00e7\u00fcr",paste:"Yap\u0131\u015fd\u0131r",selectAll:"Ham\u0131s\u0131n\u0131 se\u00e7",insertOrderedList:"N\u00f6mr\u0259li siyah\u0131",insertTable:"C\u0259dv\u0259l \u0259lav\u0259 et",
print:"Yazd\u0131r",underline:"Alt\u0131x\u0259tli",foreColor:"\u00d6n plan r\u0259ngi",htmlToggle:"HTML kodu",formatBlock:"Abzas stili",newPage:"Yeni s\u0259hif\u0259",insertHorizontalRule:"\u00dcf\u00fcqi qayda","delete":"Sil",appleKey:"\u2318${0}",insertUnorderedList:"\u0130\u015far\u0259l\u0259nmi\u015f siyah\u0131",tableProp:"C\u0259dv\u0259l x\u00fcsusiyy\u0259tl\u0259ri",insertImage:"\u015e\u0259kil \u0259lav\u0259 et",superscript:"\u00dcst i\u015far\u0259",subscript:"Alt i\u015far\u0259",
createLink:"K\u00f6rp\u00fc yarat",undo:"Geriy\u0259 al",fullScreen:"Tam ekran a\u00e7",italic:"\u0130talik",fontName:"Yaz\u0131 tipi",justifyLeft:"Sol t\u0259r\u0259f\u0259 Do\u011frult",unlink:"K\u00f6rp\u00fcn\u00fc sil",toggleTableBorder:"C\u0259dv\u0259l k\u0259narlar\u0131n\u0131 g\u00f6st\u0259r/Gizl\u0259t",viewSource:"HTML qaynaq kodunu g\u00f6st\u0259r",ctrlKey:"ctrl+${0}",fontSize:"Yaz\u0131 tipi b\u00f6y\u00fckl\u00fc\u011f\u00fc",systemShortcut:'"${0}" prosesi yaln\u0131z printerinizd\u0259 klaviatura q\u0131sayolu il\u0259 istifad\u0259 oluna bil\u0259r. Bundan istifad\u0259 edin',
indent:"Girinti",redo:"Yenil\u0259",strikethrough:"\u00dcst\u00fcnd\u0259n x\u0259tt \u00e7\u0259kilmi\u015f",justifyFull:"Do\u011frult",justifyCenter:"Ortaya do\u011frult",hiliteColor:"Arxa plan r\u0259ngi",deleteTable:"C\u0259dv\u0259li sil",outdent:"\u00c7\u0131x\u0131nt\u0131",cut:"K\u0259s",_localized:{},plainFormatBlock:"Abzas stili",toggleDir:"\u0130stiqam\u0259ti d\u0259yi\u015fdir",bold:"Qal\u0131n",tabIndent:"Qulp girintisi",justifyRight:"Sa\u011fa do\u011frult"},"dijit/form/nls/ComboBox":{previousMessage:"\u018fvv\u0259lki variantlar",
_localized:{},nextMessage:"Ba\u015fqa variantlar"}});