// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/dijit/editing/nls/Editor-all_nb",{"dijit/_editor/nls/commands":{removeFormat:"Fjern format",copy:"Kopier",paste:"Lim inn",selectAll:"Velg alle",insertOrderedList:"Nummerert liste",insertTable:"Sett inn/rediger tabell",print:"Skriv ut",underline:"Understreking",foreColor:"Forgrunnsfarge",htmlToggle:"HTML-kilde",formatBlock:"Avsnittsstil",newPage:"Ny side",insertHorizontalRule:"Vannrett strek","delete":"Slett",appleKey:"\u2318${0}",insertUnorderedList:"Punktliste",tableProp:"Tabellegenskap",
insertImage:"Sett inn bilde",superscript:"Hevet skrift",subscript:"Senket skrift",createLink:"Opprett kobling",undo:"Angre",fullScreen:"Sl\u00e5 p\u00e5/av full skjerm",italic:"Kursiv",fontName:"Skriftnavn",justifyLeft:"Venstrejuster",unlink:"Fjern kobling",toggleTableBorder:"Bytt tabellkant",viewSource:"Vis HTML-kilde",ctrlKey:"ctrl+${0}",fontSize:"Skriftst\u00f8rrelse",systemShortcut:'Handlingen "${0}" er bare tilgjengelig i nettleseren ved hjelp av en tastatursnarvei. Bruk ${1}.',indent:"Innrykk",
redo:"Gj\u00f8r om",strikethrough:"Gjennomstreking",justifyFull:"Juster",justifyCenter:"Midtstill",hiliteColor:"Bakgrunnsfarge",deleteTable:"Slett tabell",outdent:"Fjern innrykk",cut:"Klipp ut",_localized:{},plainFormatBlock:"Avsnittsstil",toggleDir:"Bytt retning",bold:"Fet",tabIndent:"Tabulatorinnrykk",justifyRight:"H\u00f8yrejuster"},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),
"field-second-relative+0":"n\u00e5","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Ukedag","field-wed-relative+0":"onsdag denne uken","field-wed-relative+1":"onsdag neste uke","dateFormatItem-GyMMMEd":"E d. MMM y G","dateFormatItem-MMMEd":"E d. MMM",eraNarrow:["AH"],"field-tue-relative+-1":"tirsdag sist uke","days-format-short":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"fredag sist uke",
"field-wed-relative+-1":"onsdag sist uke","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE d. MMMM y G","dateFormatItem-yyyyMEd":"E d.M.y G","field-thu-relative+-1":"torsdag sist uke","dateFormatItem-Md":"d.M.",_localized:{},"dayPeriods-format-abbr-am":"a.m.",
"dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Tidsalder","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH.mm","quarters-format-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"timeFormat-long":"HH.mm.ss z","field-year":"\u00c5r","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Time",
"months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"l\u00f8rdag denne uken","field-sat-relative+1":"l\u00f8rdag neste uke","timeFormat-full":"HH.mm.ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"i dag","field-thu-relative+0":"torsdag denne uken","field-day-relative+1":"i morgen","field-thu-relative+1":"torsdag neste uke","dateFormatItem-GyMMMd":"d. MMM y G","field-day-relative+2":"i overmorgen",
"dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["1. kvartal","2. kvartal","3. kvartal","4. kvartal"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d. MMM y G","dateFormatItem-M":"L.","days-standAlone-wide":"s\u00f8ndag mandag tirsdag onsdag torsdag fredag l\u00f8rdag".split(" "),"dateFormatItem-yyyyMMM":"MMM y G",
"dateFormatItem-yyyyMMMd":"d. MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH.mm.ss","field-sun-relative+0":"s\u00f8ndag denne uken","dateFormatItem-Hm":"HH.mm","field-sun-relative+1":"s\u00f8ndag neste uke","quarters-standAlone-abbr":["K1","K2","K3","K4"],eraAbbr:["AH"],"field-minute":"Minutt","field-dayperiod":"AM/PM","days-standAlone-abbr":"s\u00f8. ma. ti. on. to. fr. l\u00f8.".split(" "),"dateFormatItem-d":"d.","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2",
"3","4"],"field-day-relative+-1":"i g\u00e5r","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","field-day-relative+-2":"i forg\u00e5rs","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E d.M","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"fredag denne uken","field-fri-relative+1":"fredag neste uke","field-day":"Dag","days-format-wide":"s\u00f8ndag mandag tirsdag onsdag torsdag fredag l\u00f8rdag".split(" "),"field-zone":"Tidssone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),
"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"I fjor","field-month-relative+-1":"Sist m\u00e5ned","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h.mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"p.m.","days-format-abbr":"s\u00f8n. man. tir. ons. tor. fre. l\u00f8r.".split(" "),eraNames:["AH"],"days-format-narrow":"SMTOTFL".split(""),"dateFormatItem-yyyyMd":"d.M.y G","field-month":"M\u00e5ned",
"days-standAlone-narrow":"SMTOTFL".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"tirsdag denne uken","field-tue-relative+1":"tirsdag neste uke","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"a.m.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"mandag denne uken","field-mon-relative+1":"mandag neste uke","dateFormat-short":"d.M. y G","dateFormatItem-EHms":"E HH:mm:ss",
"dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Sekund","field-sat-relative+-1":"l\u00f8rdag sist uke","field-sun-relative+-1":"s\u00f8ndag sist uke","field-month-relative+0":"Denne m\u00e5neden","field-month-relative+1":"Neste m\u00e5ned","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d.","field-week":"Uke","dateFormat-medium":"d. MMM y G","field-week-relative+-1":"Sist uke","field-year-relative+0":"Dette \u00e5ret","dateFormatItem-yyyyM":"M.y G",
"field-year-relative+1":"Neste \u00e5r","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"mandag sist uke","dateFormatItem-yyyy":"y G","field-week-relative+0":"Denne uken","field-week-relative+1":"Neste uke"},"dijit/form/nls/ComboBox":{previousMessage:"Tidligere valg",_localized:{},nextMessage:"Flere valg"}});