// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/dijit/editing/nls/Editor_de-de",{"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"So. Mo. Di. Mi. Do. Fr. Sa.".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"jetzt","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Wochentag","field-wed-relative+0":"Diesen Mittwoch","field-wed-relative+1":"N\u00e4chsten Mittwoch","dateFormatItem-GyMMMEd":"E, d. MMM y G","dateFormatItem-MMMEd":"E, d. MMM",
eraNarrow:["AH"],"field-tue-relative+-1":"Letzten Dienstag","days-format-short":"So. Mo. Di. Mi. Do. Fr. Sa.".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"Letzten Freitag","field-wed-relative+-1":"Letzten Mittwoch","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}",
"dayPeriods-format-wide-pm":"nachm.","dateFormat-full":"EEEE, d. MMMM y G","dateFormatItem-yyyyMEd":"E, d.M.y GGGGG","field-thu-relative+-1":"Letzten Donnerstag","dateFormatItem-Md":"d.M.",_localized:{},"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"Mittag","field-era":"Epoche","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"timeFormat-short":"HH:mm","quarters-format-wide":["1. Quartal","2. Quartal","3. Quartal","4. Quartal"],"timeFormat-long":"HH:mm:ss z","field-year":"Jahr","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Stunde","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"Diesen Samstag","field-sat-relative+1":"N\u00e4chsten Samstag","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})",
"field-day-relative+0":"Heute","field-thu-relative+0":"Diesen Donnerstag","field-day-relative+1":"Morgen","field-thu-relative+1":"N\u00e4chsten Donnerstag","dateFormatItem-GyMMMd":"d. MMM y G","field-day-relative+2":"\u00dcbermorgen","dateFormatItem-H":"HH 'Uhr'","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["1. Quartal","2. Quartal","3. Quartal",
"4. Quartal"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, d. MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"Sonntag Montag Dienstag Mittwoch Donnerstag Freitag Samstag".split(" "),"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d. MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"Diesen Sonntag","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"N\u00e4chsten Sonntag","quarters-standAlone-abbr":["Q1","Q2","Q3",
"Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"Tagesh\u00e4lfte","days-standAlone-abbr":"So Mo Di Mi Do Fr Sa".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"Gestern","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","field-day-relative+-2":"Vorgestern","dateFormatItem-MMMd":"d. MMM","dateFormatItem-MEd":"E, d.M.","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"Diesen Freitag",
"field-fri-relative+1":"N\u00e4chsten Freitag","field-day":"Tag","days-format-wide":"Sonntag Montag Dienstag Mittwoch Donnerstag Freitag Samstag".split(" "),"field-zone":"Zeitzone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"Letztes Jahr","field-month-relative+-1":"Letzter Monat","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})",
"dayPeriods-format-abbr-pm":"PM","days-format-abbr":"So. Mo. Di. Mi. Do. Fr. Sa.".split(" "),eraNames:["AH"],"days-format-narrow":"SMDMDFS".split(""),"dateFormatItem-yyyyMd":"d.M.y GGGGG","field-month":"Monat","days-standAlone-narrow":"SMDMDFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"Diesen Dienstag","field-tue-relative+1":"N\u00e4chsten Dienstag","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"vorm.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})",
"dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"Diesen Montag","field-mon-relative+1":"N\u00e4chsten Montag","dateFormat-short":"dd.MM.yy GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Sekunde","field-sat-relative+-1":"Letzten Samstag","field-sun-relative+-1":"Letzten Sonntag","field-month-relative+0":"Dieser Monat","field-month-relative+1":"N\u00e4chster Monat",
"dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d.","field-week":"Woche","dateFormat-medium":"dd.MM.y G","field-week-relative+-1":"Letzte Woche","field-year-relative+0":"Dieses Jahr","dateFormatItem-yyyyM":"M.y GGGGG","field-year-relative+1":"N\u00e4chstes Jahr","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"Letzten Montag",
"dateFormatItem-yyyy":"y G","field-week-relative+0":"Diese Woche","field-week-relative+1":"N\u00e4chste Woche"},"dijit/_editor/nls/commands":{removeFormat:"Formatierung entfernen",copy:"Kopieren",paste:"Einf\u00fcgen",selectAll:"Alles ausw\u00e4hlen",insertOrderedList:"Nummerierung",insertTable:"Tabelle einf\u00fcgen/bearbeiten",print:"Drucken",underline:"Unterstrichen",foreColor:"Vordergrundfarbe",htmlToggle:"HTML-Quelltext",formatBlock:"Absatzstil",newPage:"Neue Seite",insertHorizontalRule:"Horizontaler Strich",
"delete":"L\u00f6schen",appleKey:"\u2318${0}",insertUnorderedList:"Aufz\u00e4hlungszeichen",tableProp:"Tabelleneigenschaft",insertImage:"Grafik einf\u00fcgen",superscript:"Hochgestellt",subscript:"Tiefgestellt",createLink:"Link erstellen",undo:"R\u00fcckg\u00e4ngig",fullScreen:"Gesamtanzeige",italic:"Kursiv",fontName:"Schriftartname",justifyLeft:"Linksb\u00fcndig",unlink:"Link entfernen",toggleTableBorder:"Tabellenumrandung ein-/ausschalten",viewSource:"HTML-Quelle",ctrlKey:"Strg+${0}",fontSize:"Schriftgr\u00f6\u00dfe",
systemShortcut:'Die Aktion "${0}" ist nur \u00fcber einen Direktaufruf in Ihrem Browser verf\u00fcgbar. Verwenden Sie ${1}.',indent:"Einr\u00fccken",redo:"Wiederholen",strikethrough:"Durchgestrichen",justifyFull:"Blocksatz",justifyCenter:"Zentriert",hiliteColor:"Hintergrundfarbe",deleteTable:"Tabelle l\u00f6schen",outdent:"Ausr\u00fccken",cut:"Ausschneiden",_localized:{},plainFormatBlock:"Absatzstil",toggleDir:"Richtung wechseln",bold:"Fett",tabIndent:"Registerkarteneinr\u00fcckung",justifyRight:"Rechtsb\u00fcndig"},
"dijit/form/nls/ComboBox":{previousMessage:"Vorherige Auswahl",_localized:{},nextMessage:"Weitere Auswahlm\u00f6glichkeiten"}});