// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/dijit/editing/nls/Editor-all_tr",{"dijit/_editor/nls/commands":{removeFormat:"Bi\u00e7imi Kald\u0131r",copy:"Kopyala",paste:"Yap\u0131\u015ft\u0131r",selectAll:"T\u00fcm\u00fcn\u00fc Se\u00e7",insertOrderedList:"Numaral\u0131 Liste",insertTable:"Tablo Ekle/D\u00fczenle",print:"Yazd\u0131r",underline:"Alt\u0131 \u00c7izili",foreColor:"\u00d6n Plan Rengi",htmlToggle:"HTML Kayna\u011f\u0131",formatBlock:"Paragraf Stili",newPage:"Yeni Sayfa",insertHorizontalRule:"Yatay Kural","delete":"Sil",
appleKey:"\u2318${0}",insertUnorderedList:"Madde \u0130\u015faretli Liste",tableProp:"Tablo \u00d6zelli\u011fi",insertImage:"Resim Ekle",superscript:"\u00dcst Simge",subscript:"Alt Simge",createLink:"Ba\u011flant\u0131 Olu\u015ftur",undo:"Geri Al",fullScreen:"Tam Ekran\u0131 A\u00e7/Kapat",italic:"\u0130talik",fontName:"Yaz\u0131 Tipi Ad\u0131",justifyLeft:"Sola Hizala",unlink:"Ba\u011flant\u0131y\u0131 Kald\u0131r",toggleTableBorder:"Tablo Kenarl\u0131\u011f\u0131n\u0131 G\u00f6ster/Gizle",viewSource:"HTML Kayna\u011f\u0131n\u0131 G\u00f6r\u00fcnt\u00fcle",
ctrlKey:"ctrl+${0}",fontSize:"Yaz\u0131 Tipi Boyutu",systemShortcut:'"${0}" i\u015flemi yaln\u0131zca taray\u0131c\u0131n\u0131zda bir klavye k\u0131sayoluyla birlikte kullan\u0131labilir. \u015eunu kullan\u0131n: ${1}.',indent:"Girinti",redo:"Yinele",strikethrough:"\u00dcst\u00fc \u00c7izili",justifyFull:"Yasla",justifyCenter:"Ortaya Hizala",hiliteColor:"Arka Plan Rengi",deleteTable:"Tabloyu Sil",outdent:"\u00c7\u0131k\u0131nt\u0131",cut:"Kes",_localized:{},plainFormatBlock:"Paragraf Stili",toggleDir:"Y\u00f6n\u00fc De\u011fi\u015ftir",
bold:"Kal\u0131n",tabIndent:"Sekme Girintisi",justifyRight:"Sa\u011fa Hizala"},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Pa Pt Sa \u00c7a Pe Cu Ct".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"\u015fimdi","quarters-standAlone-narrow":["1.","2.","3.","4."],"field-weekday":"Haftan\u0131n G\u00fcn\u00fc","field-wed-relative+0":"bu \u00e7ar\u015famba","field-wed-relative+1":"gelecek \u00e7ar\u015famba","dateFormatItem-GyMMMEd":"G d MMM y E",
"dateFormatItem-MMMEd":"d MMM E",eraNarrow:["Hicri"],"field-tue-relative+-1":"ge\u00e7en sal\u0131","days-format-short":"Pa Pt Sa \u00c7a Pe Cu Ct".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G d MMMM y","field-fri-relative+-1":"ge\u00e7en cuma","field-wed-relative+-1":"ge\u00e7en \u00e7ar\u015famba","months-format-wide":"Muharrem Safer Rebi\u00fclevvel Rebi\u00fclahir Cemaziyelevvel Cemaziyelahir Recep \u015eaban Ramazan \u015eevval Zilkade Zilhicce".split(" "),
"dateFormatItem-yyyyQQQ":"G y/QQQ","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"\u00d6S","dateFormat-full":"G d MMMM y EEEE","dateFormatItem-yyyyMEd":"GGGGG dd.MM.y E","field-thu-relative+-1":"ge\u00e7en per\u015fembe","dateFormatItem-Md":"dd/MM",_localized:{},"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Miladi D\u00f6nem","months-standAlone-wide":"Muharrem Safer Rebi\u00fclevvel Rebi\u00fclahir Cemaziyelevvel Cemaziyelahir Recep \u015eaban Ramazan \u015eevval Zilkade Zilhicce".split(" "),
"timeFormat-short":"HH:mm","quarters-format-wide":["1. \u00e7eyrek","2. \u00e7eyrek","3. \u00e7eyrek","4. \u00e7eyrek"],"timeFormat-long":"HH:mm:ss z","field-year":"Y\u0131l","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Saat","months-format-abbr":"Muharrem Safer Rebi\u00fclevvel Rebi\u00fclahir Cemaziyelevvel Cemaziyelahir Recep \u015eaban Ramazan \u015eevval Zilkade Zilhicce".split(" "),"field-sat-relative+0":"bu cumartesi","field-sat-relative+1":"gelecek cumartesi","timeFormat-full":"HH:mm:ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"bug\u00fcn","field-thu-relative+0":"bu per\u015fembe","field-day-relative+1":"yar\u0131n","field-thu-relative+1":"gelecek per\u015fembe","dateFormatItem-GyMMMd":"G d MMM y","field-day-relative+2":"\u00f6b\u00fcr g\u00fcn","dateFormatItem-H":"HH","months-standAlone-abbr":"Muharrem Safer Rebi\u00fclevvel Rebi\u00fclahir Cemaziyelevvel Cemaziyelahir Recep \u015eaban Ramazan \u015eevval Zilkade Zilhicce".split(" "),"quarters-format-abbr":["\u00c71",
"\u00c72","\u00c73","\u00c74"],"quarters-standAlone-wide":["1. \u00e7eyrek","2. \u00e7eyrek","3. \u00e7eyrek","4. \u00e7eyrek"],"dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G d MMM y E","dateFormatItem-M":"L","days-standAlone-wide":"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),"dateFormatItem-yyyyMMM":"G MMM y","dateFormatItem-yyyyMMMd":"G dd MMM y","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"bu pazar",
"dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"gelecek pazar","quarters-standAlone-abbr":["\u00c71","\u00c72","\u00c73","\u00c74"],eraAbbr:["Hicri"],"field-minute":"Dakika","field-dayperiod":"\u00d6\u00d6/\u00d6S","days-standAlone-abbr":"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1.","2.","3.","4."],"field-day-relative+-1":"d\u00fcn","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a",
"field-day-relative+-2":"evvelsi g\u00fcn","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"dd/MM E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"bu cuma","field-fri-relative+1":"gelecek cuma","field-day":"G\u00fcn","days-format-wide":"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),"field-zone":"Saat Dilimi","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})",
"field-year-relative+-1":"ge\u00e7en y\u0131l","field-month-relative+-1":"ge\u00e7en ay","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),eraNames:["Hicri"],"days-format-narrow":"PPS\u00c7PCC".split(""),"dateFormatItem-yyyyMd":"GGGGG dd.MM.y","field-month":"Ay","days-standAlone-narrow":"PPS\u00c7PCC".split(""),"dateFormatItem-MMM":"LLL",
"field-tue-relative+0":"bu sal\u0131","field-tue-relative+1":"gelecek sal\u0131","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"\u00d6\u00d6","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"bu pazartesi","field-mon-relative+1":"gelecek pazartesi","dateFormat-short":"GGGGG d.MM.y","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n",
"field-second":"Saniye","field-sat-relative+-1":"ge\u00e7en cumartesi","field-sun-relative+-1":"ge\u00e7en pazar","field-month-relative+0":"bu ay","field-month-relative+1":"gelecek ay","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d E","field-week":"Hafta","dateFormat-medium":"G d MMM y","field-week-relative+-1":"ge\u00e7en hafta","field-year-relative+0":"bu y\u0131l","dateFormatItem-yyyyM":"GGGGG M/y","field-year-relative+1":"gelecek y\u0131l","dayPeriods-format-narrow-pm":"p",
"dateFormatItem-yyyyQQQQ":"G y/QQQQ","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G MMM y","field-mon-relative+-1":"ge\u00e7en pazartesi","dateFormatItem-yyyy":"G y","field-week-relative+0":"bu hafta","field-week-relative+1":"gelecek hafta"},"dijit/form/nls/ComboBox":{previousMessage:"\u00d6nceki se\u00e7enekler",_localized:{},nextMessage:"Di\u011fer se\u00e7enekler"}});