// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/dijit/editing/nls/Editor_ro",{"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Du Lu Ma Mi Jo Vi S\u00e2".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"acum","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"zi a s\u0103pt\u0103m\u00e2nii","field-wed-relative+0":"miercurea aceasta","field-wed-relative+1":"miercurea viitoare","dateFormatItem-GyMMMEd":"E, d MMM y G","dateFormatItem-MMMEd":"E, d MMM",
eraNarrow:["AH"],"field-tue-relative+-1":"mar\u021bea trecut\u0103","days-format-short":"Du Lu Ma Mi Jo Vi S\u00e2".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM y G","field-fri-relative+-1":"vinerea trecut\u0103","field-wed-relative+-1":"miercurea trecut\u0103","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G",
"dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"p.m.","dateFormat-full":"EEEE, d MMMM y G","dateFormatItem-yyyyMEd":"E, dd.MM.y G","field-thu-relative+-1":"joia trecut\u0103","dateFormatItem-Md":"dd.MM",_localized:{},"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"er\u0103","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"timeFormat-short":"HH:mm","quarters-format-wide":["trimestrul I","trimestrul al II-lea","trimestrul al III-lea","trimestrul al IV-lea"],"timeFormat-long":"HH:mm:ss z","field-year":"an","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"or\u0103","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"s\u00e2mb\u0103ta aceasta","field-sat-relative+1":"s\u00e2mb\u0103ta viitoare","timeFormat-full":"HH:mm:ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"azi","field-thu-relative+0":"joia aceasta","field-day-relative+1":"m\u00e2ine","field-thu-relative+1":"joia viitoare","dateFormatItem-GyMMMd":"d MMM y G","field-day-relative+2":"poim\u00e2ine","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["trim. I","trim. II","trim. III","trim. IV"],"quarters-standAlone-wide":["trimestrul I",
"trimestrul al II-lea","trimestrul al III-lea","trimestrul al IV-lea"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, d MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"duminic\u0103 luni mar\u021bi miercuri joi vineri s\u00e2mb\u0103t\u0103".split(" "),"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"duminica aceasta","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"duminica viitoare",
"quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["AH"],"field-minute":"minut","field-dayperiod":"a.m./p.m","days-standAlone-abbr":"Dum Lun Mar Mie Joi Vin S\u00e2m".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"ieri","dateTimeFormat-long":"{1}, {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","field-day-relative+-2":"alalt\u0103ieri","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E, dd.MM",
"dateTimeFormat-full":"{1}, {0}","field-fri-relative+0":"vinerea aceasta","field-fri-relative+1":"vinerea viitoare","field-day":"zi","days-format-wide":"duminic\u0103 luni mar\u021bi miercuri joi vineri s\u00e2mb\u0103t\u0103".split(" "),"field-zone":"fus orar","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"anul trecut","field-month-relative+-1":"luna trecut\u0103","dateTimeFormats-appendItem-Year":"{1} {0}",
"dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Dum Lun Mar Mie Joi Vin S\u00e2m".split(" "),eraNames:["AH"],"days-format-narrow":"DLMMJVS".split(""),"dateFormatItem-yyyyMd":"dd.MM.y G","field-month":"lun\u0103","days-standAlone-narrow":"DLMMJVS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"mar\u021bea aceasta","field-tue-relative+1":"mar\u021bea viitoare","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})",
"dayPeriods-format-wide-am":"a.m.","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"lunea aceasta","field-mon-relative+1":"lunea viitoare","dateFormat-short":"dd.MM.y GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"secund\u0103","field-sat-relative+-1":"s\u00e2mb\u0103ta trecut\u0103","field-sun-relative+-1":"duminica trecut\u0103",
"field-month-relative+0":"luna aceasta","field-month-relative+1":"luna viitoare","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d","field-week":"s\u0103pt\u0103m\u00e2n\u0103","dateFormat-medium":"dd.MM.y G","field-week-relative+-1":"s\u0103pt\u0103m\u00e2na trecut\u0103","field-year-relative+0":"anul acesta","dateFormatItem-yyyyM":"MM.y G","field-year-relative+1":"anul viitor","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}",
"dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"lunea trecut\u0103","dateFormatItem-yyyy":"y G","field-week-relative+0":"s\u0103pt\u0103m\u00e2na aceasta","field-week-relative+1":"s\u0103pt\u0103m\u00e2na viitoare"},"dijit/_editor/nls/commands":{removeFormat:"\u00cenl\u0103turare format",copy:"Copiere",paste:"Lipire",selectAll:"Selecteaz\u0103 tot",insertOrderedList:"List\u0103 numerotat\u0103",insertTable:"Inserare/Editare tabel\u0103",
print:"Tip\u0103rire",underline:"Subliniere",foreColor:"Culoare de prim-plan",htmlToggle:"Surs\u0103 HTML",formatBlock:"Stil paragraf",newPage:"Pagin\u0103 nou\u0103",insertHorizontalRule:"Linie delimitatoare","delete":"\u015etergere",appleKey:"\u2318${0}",insertUnorderedList:"List\u0103 cu marcator",tableProp:"Proprietate tabel\u0103",insertImage:"Inserare imagine",superscript:"Scriere indice superior",subscript:"Scriere indice inferior",createLink:"Creare leg\u0103tur\u0103",undo:"Anulare ac\u0163iune",
fullScreen:"Comutare ecran complet",italic:"Cursiv",fontName:"Nume font",justifyLeft:"Aliniere st\u00e2nga",unlink:"\u00cenl\u0103turare leg\u0103tur\u0103",toggleTableBorder:"Comutare bordur\u0103 tabel\u0103",viewSource:"Vizualizara surs\u0103 HTML",ctrlKey:"ctrl+${0}",fontSize:"Dimensiune font",systemShortcut:'Ac\u0163iunea "${0}" este disponibil\u0103 \u00een browser doar utiliz\u00e2nd o comand\u0103 rapid\u0103 de la tastatur\u0103. Utiliza\u0163i ${1}.',indent:"Mic\u015forare indent",redo:"Refacere ac\u0163iune",
strikethrough:"T\u0103iere text cu o linie",justifyFull:"Aliniere st\u00e2nga-dreapta",justifyCenter:"Aliniere centru",hiliteColor:"Culoare de fundal",deleteTable:"\u015etergere tabel\u0103",outdent:"M\u0103rire indent",cut:"T\u0103iere",_localized:{},plainFormatBlock:"Stil paragraf",toggleDir:"Comutare direc\u0163ie",bold:"Aldin",tabIndent:"Indentare Tab",justifyRight:"Aliniere dreapta"},"dijit/form/nls/ComboBox":{previousMessage:"Alegeri anterioare",_localized:{},nextMessage:"Mai multe alegeri"}});