/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
require({cache:{"dojox/mobile/_maskUtils":function(){define(["dojo/_base/window","dojo/dom-style","./sniff"],function(l,m,k){k.add("mask-image-css",function(b,e,d){return"function"===typeof e.getCSSCanvasContext&&"undefined"!==typeof d.style.webkitMaskImage});k.add("mask-image",function(){return k("mask-image-css")||k("svg")});var e={};return{createRoundMask:function(b,h,d,f,t,p,n,s,q,r){f=h+p+f;var a=d+n+t;if(k("mask-image-css"))t=("DojoMobileMask"+h+d+p+n+s+q).replace(/\./g,"_"),e[t]||(e[t]=1,f=
l.doc.getCSSCanvasContext("2d",t,f,a),f.beginPath(),s==q?2==s&&5==p?(f.fillStyle="rgba(0,0,0,0.5)",f.fillRect(1,0,3,2),f.fillRect(0,1,5,1),f.fillRect(0,n-2,5,1),f.fillRect(1,n-1,3,2),f.fillStyle="rgb(0,0,0)",f.fillRect(0,2,5,n-4)):2==s&&5==n?(f.fillStyle="rgba(0,0,0,0.5)",f.fillRect(0,1,2,3),f.fillRect(1,0,1,5),f.fillRect(p-2,0,1,5),f.fillRect(p-1,1,2,3),f.fillStyle="rgb(0,0,0)",f.fillRect(2,0,p-4,5)):(f.fillStyle="#000000",f.moveTo(h+s,d),f.arcTo(h,d,h,d+s,s),f.lineTo(h,d+n-s),f.arcTo(h,d+n,h+s,
d+n,s),f.lineTo(h+p-s,d+n),f.arcTo(h+p,d+n,h+p,d+s,s),f.lineTo(h+p,d+s),f.arcTo(h+p,d,h+p-s,d,s)):(n=Math.PI,f.scale(1,q/s),f.moveTo(h+s,d),f.arc(h+s,d+s,s,1.5*n,0.5*n,!0),f.lineTo(h+p-s,d+2*s),f.arc(h+p-s,d+s,s,0.5*n,1.5*n,!0)),f.closePath(),f.fill()),b.style.webkitMaskImage="-webkit-canvas("+t+")";else if(k("svg")){b._svgMask&&b.removeChild(b._svgMask);for(var g=null,c=b.parentNode;c&&(!(g=m.getComputedStyle(c).backgroundColor)||"transparent"==g||g.match(/rgba\(.*,\s*0\s*\)/));c=c.parentNode);c=
l.doc.createElementNS("http://www.w3.org/2000/svg","svg");c.setAttribute("width",f);c.setAttribute("height",a);c.style.position="absolute";c.style.pointerEvents="none";c.style.opacity="1";c.style.zIndex="2147483647";a=l.doc.createElementNS("http://www.w3.org/2000/svg","path");r=r||0;s+=r;q+=r;h=" M"+(h+s-r)+","+(d-r)+" a"+s+","+q+" 0 0,0 "+-s+","+q+" v"+-q+" h"+s+" Z M"+(h-r)+","+(d+n-q+r)+" a"+s+","+q+" 0 0,0 "+s+","+q+" h"+-s+" v"+-q+" z M"+(h+p-s+r)+","+(d+n+r)+" a"+s+","+q+" 0 0,0 "+s+","+-q+
" v"+q+" h"+-s+" z M"+(h+p+r)+","+(d+q-r)+" a"+s+","+q+" 0 0,0 "+-s+","+-q+" h"+s+" v"+q+" z";0<d&&(h+=" M0,0 h"+f+" v"+d+" h"+-f+" z");0<t&&(h+=" M0,"+(d+n)+" h"+f+" v"+t+" h"+-f+" z");a.setAttribute("d",h);a.setAttribute("fill",g);a.setAttribute("stroke",g);a.style.opacity="1";c.appendChild(a);b._svgMask=c;b.appendChild(c)}}}})},"dojox/mobile/EdgeToEdgeList":function(){define(["dojo/_base/declare","./RoundRectList"],function(l,m){return l("dojox.mobile.EdgeToEdgeList",m,{filterBoxClass:"mblFilteredEdgeToEdgeListSearchBox",
buildRendering:function(){this.inherited(arguments);this.domNode.className="mblEdgeToEdgeList"}})})},"dojo/touch":function(){define("./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(l,m,k,e,b,h,d,f,t,p){function n(g,b,d){return a&&d?function(c,a){return h(c,d,a)}:c?function(c,a){var d=h(c,b,function(c){a.call(this,c);B=(new Date).getTime()}),E=h(c,g,function(c){(!B||(new Date).getTime()>B+1E3)&&a.call(this,c)});return{remove:function(){d.remove();
E.remove()}}}:function(c,a){return h(c,g,a)}}function s(c){do if(void 0!==c.dojoClick)return c;while(c=c.parentNode)}function q(c,a,g){var d=s(c.target);if(v=!c.target.disabled&&d&&d.dojoClick)if(y=(w="useTarget"==v)?d:c.target,w&&c.preventDefault(),x=c.changedTouches?c.changedTouches[0].pageX-p.global.pageXOffset:c.clientX,z=c.changedTouches?c.changedTouches[0].pageY-p.global.pageYOffset:c.clientY,C=("object"==typeof v?v.x:"number"==typeof v?v:0)||4,D=("object"==typeof v?v.y:"number"==typeof v?v:
0)||4,!u){u=!0;var b=function(c){v=w?k.isDescendant(p.doc.elementFromPoint(c.changedTouches?c.changedTouches[0].pageX-p.global.pageXOffset:c.clientX,c.changedTouches?c.changedTouches[0].pageY-p.global.pageYOffset:c.clientY),y):v&&(c.changedTouches?c.changedTouches[0].target:c.target)==y&&Math.abs((c.changedTouches?c.changedTouches[0].pageX-p.global.pageXOffset:c.clientX)-x)<=C&&Math.abs((c.changedTouches?c.changedTouches[0].pageY-p.global.pageYOffset:c.clientY)-z)<=D};p.doc.addEventListener(a,function(c){b(c);
w&&c.preventDefault()},!0);p.doc.addEventListener(g,function(c){b(c);if(v){E=(new Date).getTime();var a=w?y:c.target;"LABEL"===a.tagName&&(a=k.byId(a.getAttribute("for"))||a);var g=c.changedTouches?c.changedTouches[0]:c,d=document.createEvent("MouseEvents");d._dojo_click=!0;d.initMouseEvent("click",!0,!0,c.view,c.detail,g.screenX,g.screenY,g.clientX,g.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,0,null);setTimeout(function(){h.emit(a,"click",d);E=(new Date).getTime()},0)}},!0);c=function(c){p.doc.addEventListener(c,
function(a){!a._dojo_click&&((new Date).getTime()<=E+1E3&&!("INPUT"==a.target.tagName&&e.contains(a.target,"dijitOffScreen")))&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),"click"==c&&(("INPUT"!=a.target.tagName||"radio"==a.target.type||"checkbox"==a.target.type)&&"TEXTAREA"!=a.target.tagName&&"AUDIO"!=a.target.tagName&&"VIDEO"!=a.target.tagName)&&a.preventDefault())},!0)};c("click");c("mousedown");c("mouseup")}}var r=5>d("ios"),a=d("pointer-events")||d("MSPointer"),
g=function(){var c={},a;for(a in{down:1,move:1,up:1,cancel:1,over:1,out:1})c[a]=d("MSPointer")?"MSPointer"+a.charAt(0).toUpperCase()+a.slice(1):"pointer"+a;return c}(),c=d("touch-events"),u,v,w=!1,y,x,z,C,D,E,B,A;a?t(function(){p.doc.addEventListener(g.down,function(c){q(c,g.move,g.up)},!0)}):c&&t(function(){function c(a){var g=b.delegate(a,{bubbles:!0});6<=d("ios")&&(g.touches=a.touches,g.altKey=a.altKey,g.changedTouches=a.changedTouches,g.ctrlKey=a.ctrlKey,g.metaKey=a.metaKey,g.shiftKey=a.shiftKey,
g.targetTouches=a.targetTouches);return g}A=p.body();p.doc.addEventListener("touchstart",function(c){B=(new Date).getTime();var a=A;A=c.target;h.emit(a,"dojotouchout",{relatedTarget:A,bubbles:!0});h.emit(A,"dojotouchover",{relatedTarget:a,bubbles:!0});q(c,"touchmove","touchend")},!0);h(p.doc,"touchmove",function(a){B=(new Date).getTime();var g=p.doc.elementFromPoint(a.pageX-(r?0:p.global.pageXOffset),a.pageY-(r?0:p.global.pageYOffset));g&&(A!==g&&(h.emit(A,"dojotouchout",{relatedTarget:g,bubbles:!0}),
h.emit(g,"dojotouchover",{relatedTarget:A,bubbles:!0}),A=g),h.emit(g,"dojotouchmove",c(a))||a.preventDefault())});h(p.doc,"touchend",function(a){B=(new Date).getTime();var g=p.doc.elementFromPoint(a.pageX-(r?0:p.global.pageXOffset),a.pageY-(r?0:p.global.pageYOffset))||p.body();h.emit(g,"dojotouchend",c(a))})});m={press:n("mousedown","touchstart",g.down),move:n("mousemove","dojotouchmove",g.move),release:n("mouseup","dojotouchend",g.up),cancel:n(f.leave,"touchcancel",a?g.cancel:null),over:n("mouseover",
"dojotouchover",g.over),out:n("mouseout","dojotouchout",g.out),enter:f._eventHandler(n("mouseover","dojotouchover",g.over)),leave:f._eventHandler(n("mouseout","dojotouchout",g.out))};return l.touch=m})},"dojox/mobile/iconUtils":function(){define("dojo/_base/array dojo/_base/config dojo/_base/connect dojo/_base/event dojo/_base/lang dojo/_base/window dojo/dom-class dojo/dom-construct dojo/dom-style ./sniff".split(" "),function(l,m,k,e,b,h,d,f,t,p){var n=b.getObject("dojox.mobile",!0);return new function(){this.setupSpriteIcon=
function(b,f){if(b&&f){var e=l.map(f.split(/[ ,]/),function(c){return c-0}),a=e[0],g=e[1];t.set(b,{position:"absolute",clip:"rect("+a+"px "+(e[1]+e[2])+"px "+(e[0]+e[3])+"px "+g+"px)",top:(b.parentNode?t.get(b,"top"):0)-a+"px",left:-g+"px"});d.add(b,"mblSpriteIcon")}};this.createDomButton=function(b,e,r){if(!this._domButtons)if(p("webkit")){var a=function(c,g){var b,d;if(!c){var e={};d=h.doc.styleSheets;for(b=0;b<d.length;b++)d[b]&&a(d[b],e);return e}e=c.cssRules||[];for(b=0;b<e.length;b++)if(d=e[b],
d.href&&d.styleSheet)a(d.styleSheet,g);else if(d.selectorText){var f=d.selectorText.split(/,/);for(d=0;d<f.length;d++){var u=f[d],v=u.split(/>/).length-1;if(u.match(/(mblDomButton\w+)/)&&(u=RegExp.$1,!g[u]||v>g[u]))g[u]=v}}return g};this._domButtons=a()}else this._domButtons={};var g=b.className,c=r||b;if(g.match(/(mblDomButton\w+)/)&&-1===g.indexOf("/")){var u=RegExp.$1,v=4;g.match(/(mblDomButton\w+_(\d+))/)?v=RegExp.$2-0:void 0!==this._domButtons[u]&&(v=this._domButtons[u]);g=null;p("bb")&&!1!==
m.mblBBBoxShadowWorkaround&&(g={style:"-webkit-box-shadow:none"});for(var n=0,k=c;n<v;n++)k=k.firstChild||f.create("div",g,k);r&&(setTimeout(function(){d.remove(b,u)},0),d.add(r,u))}else if(-1!==g.indexOf("."))f.create("img",{src:g},c);else return null;d.add(c,"mblDomButton");e&&t.set(c,e);return c};this.createIcon=function(b,h,r,a,g,c,u){a=a||"";if(b&&0===b.indexOf("mblDomButton"))r?r.className.match(/(mblDomButton\w+)/)&&d.remove(r,RegExp.$1):r=f.create("div",null,c||g,u),r.title=a,d.add(r,b),this.createDomButton(r);
else if(b&&"none"!==b){if(!r||"IMG"!==r.nodeName)r=f.create("img",{alt:a},c||g,u);r.src=(b||"").replace("${theme}",n.currentTheme);this.setupSpriteIcon(r,h);h&&g&&(b=h.split(/[ ,]/),t.set(g,{position:"relative",width:b[2]+"px",height:b[3]+"px"}),d.add(g,"mblSpriteIconParent"));k.connect(r,"ondragstart",e,"stop")}return r};this.iconWrapper=!1;this.setIcon=function(b,e,h,a,g,c,u){if(!g||!b&&!h)return null;if(b&&"none"!==b)return!this.iconWrapper&&0!==b.indexOf("mblDomButton")&&!e?(h&&"DIV"===h.tagName&&
(f.destroy(h),h=null),h=this.createIcon(b,null,h,a,g,c,u),d.add(h,"mblImageIcon")):(h&&"IMG"===h.tagName&&(f.destroy(h),h=null),h&&f.empty(h),h||(h=f.create("div",null,c||g,u)),this.createIcon(b,e,null,null,h),a&&(h.title=a)),d.remove(g,"mblNoIcon"),h;f.destroy(h);d.add(g,"mblNoIcon");return null}}})},"dojox/mobile/uacss":function(){define(["dojo/_base/kernel","dojo/_base/lang","dojo/_base/window","./sniff"],function(l,m,k,e){k=k.doc.documentElement;k.className=m.trim(k.className+" "+[e("bb")?"dj_bb":
"",e("android")?"dj_android":"",e("ios")?"dj_ios":"",6<=e("ios")?"dj_ios6":"",e("ios")?"dj_iphone":"",e("ipod")?"dj_ipod":"",e("ipad")?"dj_ipad":"",e("ie")?"dj_ie":""].join(" ").replace(/ +/g," "));return l})},"dojox/mobile/Pane":function(){define(["dojo/_base/array","dojo/_base/declare","dijit/_Contained","dijit/_WidgetBase"],function(l,m,k,e){return m("dojox.mobile.Pane",[e,k],{baseClass:"mblPane",buildRendering:function(){this.inherited(arguments);this.containerNode||(this.containerNode=this.domNode)},
resize:function(){l.forEach(this.getChildren(),function(b){b.resize&&b.resize()})}})})},"dojox/mobile/_css3":function(){define(["dojo/_base/window","dojo/_base/array","dojo/has"],function(l,m,k){var e=[],b=[],h=l.doc.createElement("div").style,d=["webkit"];k.add("css3-animations",function(b,e,h){var f=h.style;return void 0!==f.animation&&void 0!==f.transition||m.some(d,function(b){return void 0!==f[b+"Animation"]&&void 0!==f[b+"Transition"]})});k.add("t17164",function(b,d,e){return void 0!==e.style.transition&&
!("TransitionEvent"in window)});var f={name:function(f,p){var n=(p?b:e)[f];if(!n){if(/End|Start/.test(f))var l=f.length-(f.match(/End/)?3:5),q=f.substr(0,l),r=this.name(q),n=r==q?f.toLowerCase():r+f.substr(l);else if("keyframes"==f)l=this.name("animation",p),n="animation"==l?f:p?l.replace(/animation/,"keyframes"):l.replace(/Animation/,"Keyframes");else{var a=p?f.replace(/-(.)/g,function(a,c){return c.toUpperCase()}):f;void 0!==h[a]&&!k("t17164")?n=f:(a=a.charAt(0).toUpperCase()+a.slice(1),m.some(d,
function(g){void 0!==h[g+a]&&(n=p?"-"+g+"-"+f:g+a)}))}n||(n=f);(p?b:e)[f]=n}return n},add:function(b,d){for(var e in d)d.hasOwnProperty(e)&&(b[f.name(e)]=d[e]);return b}};return f})},"dojox/mobile/RoundRect":function(){define(["dojo/_base/declare","dojo/dom-class","./Container"],function(l,m,k){return l("dojox.mobile.RoundRect",k,{shadow:!1,baseClass:"mblRoundRect",buildRendering:function(){this.inherited(arguments);this.shadow&&m.add(this.domNode,"mblShadow")}})})},"dojox/mobile/ListItem":function(){define("dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-style dojo/dom-attr dijit/registry dijit/_WidgetBase ./iconUtils ./_ItemBase ./ProgressIndicator dojo/has dojo/has!dojo-bidi?dojox/mobile/bidi/ListItem".split(" "),
function(l,m,k,e,b,h,d,f,t,p,n,s,q,r){n=m(q("dojo-bidi")?"dojox.mobile.NonBidiListItem":"dojox.mobile.ListItem",n,{rightText:"",rightIcon:"",rightIcon2:"",deleteIcon:"",anchorLabel:!1,noArrow:!1,checked:!1,arrowClass:"",checkClass:"",uncheckClass:"",variableHeight:!1,rightIconTitle:"",rightIcon2Title:"",header:!1,tag:"li",busy:!1,progStyle:"",layoutOnResize:!1,paramsToInherit:"variableHeight,transition,deleteIcon,icon,rightIcon,rightIcon2,uncheckIcon,arrowClass,checkClass,uncheckClass,deleteIconTitle,deleteIconRole",
baseClass:"mblListItem",_selStartMethod:"touch",_selEndMethod:"timer",_delayedSelection:!0,_selClass:"mblListItemSelected",buildRendering:function(){this._templated=!!this.templateString;this._templated||(this.domNode=this.containerNode=this.srcNodeRef||b.create(this.tag));this.inherited(arguments);this.selected&&e.add(this.domNode,this._selClass);this.header&&e.replace(this.domNode,"mblEdgeToEdgeCategory",this.baseClass);if(!this._templated){this.labelNode=b.create("div",{className:"mblListItemLabel"});
var a=this.srcNodeRef;a&&(1===a.childNodes.length&&3===a.firstChild.nodeType)&&this.labelNode.appendChild(a.firstChild);this.domNode.appendChild(this.labelNode)}this._layoutChildren=[]},startup:function(){if(!this._started){var a=this.getParent();this.getTransOpts();if((!this._templated||this.labelNode)&&this.anchorLabel)this.labelNode.style.display="inline",this.labelNode.style.cursor="pointer",this.connect(this.labelNode,"onclick","_onClick"),this.onTouchStart=function(a){return a.target!==this.labelNode};
this.inherited(arguments);e.contains(this.domNode,"mblVariableHeight")&&(this.variableHeight=!0);this.variableHeight&&(e.add(this.domNode,"mblVariableHeight"),this.defer("layoutVariableHeight"));this._isOnLine||(this._isOnLine=!0,this.set({icon:void 0!==this._pending_icon?this._pending_icon:this.icon,deleteIcon:void 0!==this._pending_deleteIcon?this._pending_deleteIcon:this.deleteIcon,rightIcon:void 0!==this._pending_rightIcon?this._pending_rightIcon:this.rightIcon,rightIcon2:void 0!==this._pending_rightIcon2?
this._pending_rightIcon2:this.rightIcon2,uncheckIcon:void 0!==this._pending_uncheckIcon?this._pending_uncheckIcon:this.uncheckIcon}),delete this._pending_icon,delete this._pending_deleteIcon,delete this._pending_rightIcon,delete this._pending_rightIcon2,delete this._pending_uncheckIcon);a&&a.select&&(this.set("checked",void 0!==this._pendingChecked?this._pendingChecked:this.checked),d.set(this.domNode,"role","option"),(this._pendingChecked||this.checked)&&d.set(this.domNode,"aria-selected","true"),
delete this._pendingChecked);this.setArrow();this.layoutChildren()}},_updateHandles:function(){var a=this.getParent(),g=this.getTransOpts();g.moveTo||g.href||g.url||this.clickable||a&&a.select?(this._keydownHandle||(this._keydownHandle=this.connect(this.domNode,"onkeydown","_onClick")),this._handleClick=!0):(this._keydownHandle&&(this.disconnect(this._keydownHandle),this._keydownHandle=null),this._handleClick=!1);this.inherited(arguments)},layoutChildren:function(){var a;l.forEach(this.domNode.childNodes,
function(g){if(1===g.nodeType){var c=g.getAttribute("layout")||g.getAttribute("data-mobile-layout")||(f.byNode(g)||{}).layout;c&&(e.add(g,"mblListItemLayout"+c.charAt(0).toUpperCase()+c.substring(1)),this._layoutChildren.push(g),"center"===c&&(a=g))}},this);a&&this.domNode.insertBefore(a,this.domNode.firstChild)},resize:function(){this.layoutOnResize&&this.variableHeight&&this.layoutVariableHeight();if(!this._templated||this.labelNode)this.labelNode.style.display=this.labelNode.firstChild?"block":
"inline"},_onTouchStart:function(a){!a.target.getAttribute("preventTouch")&&(!a.target.getAttribute("data-mobile-prevent-touch")&&!(f.getEnclosingWidget(a.target)||{}).preventTouch)&&this.inherited(arguments)},_onClick:function(a){if(!(this.getParent().isEditing||a&&"keydown"===a.type&&13!==a.keyCode)&&!1!==this.onClick(a)){var g=this.labelNode;if((this._templated||g)&&this.anchorLabel&&a.currentTarget===g)e.add(g,"mblListItemLabelSelected"),this.defer(function(){e.remove(g,"mblListItemLabelSelected")},
this._duration),this.onAnchorLabelClicked(a);else{var c=this.getParent();c.select&&("single"===c.select?this.checked||this.set("checked",!0):"multiple"===c.select&&this.set("checked",!this.checked));this.defaultClickAction(a)}}},onClick:function(){},onAnchorLabelClicked:function(a){},layoutVariableHeight:function(){var a=this.domNode.offsetHeight;a!==this.domNodeHeight&&(this.domNodeHeight=a,l.forEach(this._layoutChildren.concat([this.rightTextNode,this.rightIcon2Node,this.rightIconNode,this.uncheckIconNode,
this.iconNode,this.deleteIconNode,this.knobIconNode]),function(a){if(a){var c=this.domNode,b=function(){var b=Math.round((c.offsetHeight-a.offsetHeight)/2)-h.get(c,"paddingTop");a.style.marginTop=b+"px"};0===a.offsetHeight&&"IMG"===a.tagName?a.onload=b:b()}},this))},setArrow:function(){if(!this.checked){var a="",b=this.getParent(),c=this.getTransOpts();if(c.moveTo||c.href||c.url||this.clickable)if(!this.noArrow&&(!b||!b.selectOne))a=this.arrowClass||"mblDomButtonArrow",d.set(this.domNode,"role","button");
a&&this._setRightIconAttr(a)}},_findRef:function(a){var b,c="deleteIcon icon rightIcon uncheckIcon rightIcon2 rightText".split(" ");for(a=l.indexOf(c,a)+1;a<c.length;a++)if(b=this[c[a]+"Node"])return b;for(a=c.length-1;0<=a;a--)if(b=this[c[a]+"Node"])return b.nextSibling;return this.domNode.firstChild},_setIcon:function(a,b){if(this._isOnLine){this._set(b,a);this[b+"Node"]=p.setIcon(a,this[b+"Pos"],this[b+"Node"],this[b+"Title"]||this.alt,this.domNode,this._findRef(b),"before");if(this[b+"Node"]){var c=
b.charAt(0).toUpperCase()+b.substring(1);e.add(this[b+"Node"],"mblListItem"+c)}(c=this[b+"Role"])&&this[b+"Node"].setAttribute("role",c)}else this["_pending_"+b]=a},_setDeleteIconAttr:function(a){this._setIcon(a,"deleteIcon")},_setIconAttr:function(a){this._setIcon(a,"icon")},_setRightTextAttr:function(a){!this._templated&&!this.rightTextNode&&(this.rightTextNode=b.create("div",{className:"mblListItemRightText"},this.labelNode,"before"));this.rightText=a;this.rightTextNode.innerHTML=this._cv?this._cv(a):
a},_setRightIconAttr:function(a){this._setIcon(a,"rightIcon")},_setUncheckIconAttr:function(a){this._setIcon(a,"uncheckIcon")},_setRightIcon2Attr:function(a){this._setIcon(a,"rightIcon2")},_setCheckedAttr:function(a){if(this._isOnLine){var b=this.getParent();b&&("single"===b.select&&a)&&l.forEach(b.getChildren(),function(c){c!==this&&c.checked&&c.set("checked",!1)&&d.set(c.domNode,"aria-selected","false")},this);this._setRightIconAttr(this.checkClass||"mblDomButtonCheck");this._setUncheckIconAttr(this.uncheckClass);
e.toggle(this.domNode,"mblListItemChecked",a);e.toggle(this.domNode,"mblListItemUnchecked",!a);e.toggle(this.domNode,"mblListItemHasUncheck",!!this.uncheckIconNode);this.rightIconNode.style.position=this.uncheckIconNode&&!a?"absolute":"";if(b&&this.checked!==a)b.onCheckStateChanged(this,a);this._set("checked",a);d.set(this.domNode,"aria-selected",a?"true":"false")}else this._pendingChecked=a},_setBusyAttr:function(a){var d=this._prog;a?(this._progNode||(this._progNode=b.create("div",{className:"mblListItemIcon"}),
d=this._prog=new s({size:25,center:!1,removeOnStop:!1}),e.add(d.domNode,this.progStyle),this._progNode.appendChild(d.domNode)),this.iconNode?this.domNode.replaceChild(this._progNode,this.iconNode):b.place(this._progNode,this._findRef("icon"),"before"),d.start()):this._progNode&&(this.iconNode?this.domNode.replaceChild(this.iconNode,this._progNode):this.domNode.removeChild(this._progNode),d.stop());this._set("busy",a)},_setSelectedAttr:function(a){this.inherited(arguments);e.toggle(this.domNode,this._selClass,
a)},_setClickableAttr:function(a){this._set("clickable",a);this._updateHandles()},_setMoveToAttr:function(a){this._set("moveTo",a);this._updateHandles()},_setHrefAttr:function(a){this._set("href",a);this._updateHandles()},_setUrlAttr:function(a){this._set("url",a);this._updateHandles()}});n.ChildWidgetProperties={layout:"",preventTouch:!1};k.extend(t,n.ChildWidgetProperties);return q("dojo-bidi")?m("dojox.mobile.ListItem",[n,r]):n})},"dojox/mobile/TransitionEvent":function(){define(["dojo/_base/declare",
"dojo/on"],function(l,m){return l("dojox.mobile.TransitionEvent",null,{constructor:function(k,e,b){this.transitionOptions=e;this.target=k;this.triggerEvent=b||null},dispatch:function(){m.emit(this.target,"startTransition",{bubbles:!0,cancelable:!0,detail:this.transitionOptions,triggerEvent:this.triggerEvent})}})})},"dijit/_Contained":function(){define(["dojo/_base/declare","./registry"],function(l,m){return l("dijit._Contained",null,{_getSibling:function(k){var e=this.domNode;do e=e[k+"Sibling"];
while(e&&1!=e.nodeType);return e&&m.byNode(e)},getPreviousSibling:function(){return this._getSibling("previous")},getNextSibling:function(){return this._getSibling("next")},getIndexInParent:function(){var k=this.getParent();return!k||!k.getIndexOfChild?-1:k.getIndexOfChild(this)}})})},"dojox/mobile/sniff":function(){define(["dojo/_base/kernel","dojo/sniff"],function(l,m){l.deprecated("dojox/mobile/sniff","Use dojo/sniff instead","2.0");m.add("iphone",m("ios"));return m})},"dojox/mobile/_ItemBase":function(){define("dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/_base/window dojo/dom-class dojo/touch dijit/registry dijit/_Contained dijit/_Container dijit/_WidgetBase ./TransitionEvent ./iconUtils ./sniff ./viewRegistry dojo/has!dojo-bidi?dojox/mobile/bidi/_ItemBase".split(" "),
function(l,m,k,e,b,h,d,f,t,p,n,s,q,r,a){k=m(q("dojo-bidi")?"dojox.mobile._NonBidiItemBase":"dojox.mobile._ItemBase",[p,t,f],{icon:"",iconPos:"",alt:"",href:"",hrefTarget:"",moveTo:"",scene:"",clickable:!1,url:"",urlTarget:"",back:!1,transition:"",transitionDir:1,transitionOptions:null,callback:null,label:"",toggle:!1,selected:!1,tabIndex:"0",_setTabIndexAttr:"",paramsToInherit:"transition,icon",_selStartMethod:"none",_selEndMethod:"none",_delayedSelection:!1,_duration:800,_handleClick:!0,buildRendering:function(){this.inherited(arguments);
this._isOnLine=this.inheritParams()},startup:function(){this._started||(this._isOnLine||this.inheritParams(),this._updateHandles(),this.inherited(arguments))},inheritParams:function(){var a=this.getParent();a&&l.forEach(this.paramsToInherit.split(/,/),function(c){if(c.match(/icon/i)){var b=c+"Base",d=c+"Pos";this[c]&&(a[b]&&"/"===a[b].charAt(a[b].length-1))&&(this[c]=a[b]+this[c]);this[c]||(this[c]=a[b]);this[d]||(this[d]=a[d])}this[c]||(this[c]=a[c])},this);return!!a},_updateHandles:function(){this._handleClick&&
"touch"===this._selStartMethod?this._onTouchStartHandle||(this._onTouchStartHandle=this.connect(this.domNode,h.press,"_onTouchStart")):this._onTouchStartHandle&&(this.disconnect(this._onTouchStartHandle),this._onTouchStartHandle=null)},getTransOpts:function(){var a=this.transitionOptions||{};l.forEach("moveTo href hrefTarget url target urlTarget scene transition transitionDir".split(" "),function(c){a[c]=a[c]||this[c]},this);return a},userClickAction:function(){},defaultClickAction:function(a){this.handleSelection(a);
!1!==this.userClickAction(a)&&this.makeTransition(a)},handleSelection:function(a){this._delayedSelection&&this.set("selected",!0);this._onTouchEndHandle&&(this.disconnect(this._onTouchEndHandle),this._onTouchEndHandle=null);a=this.getParent();this.toggle?this.set("selected",!this._currentSel):a&&a.selectOne?this.set("selected",!0):"touch"===this._selEndMethod?this.set("selected",!1):"timer"===this._selEndMethod&&this.defer(function(){this.set("selected",!1)},this._duration)},makeTransition:function(a){if(this.back&&
history)history.back();else if(this.href&&this.hrefTarget&&"_self"!=this.hrefTarget)e.global.open(this.href,this.hrefTarget||"_blank"),this._onNewWindowOpened(a);else{var c=this.getTransOpts(),b=!(!c.moveTo&&!c.href&&!c.url&&!c.target&&!c.scene);if(!1!==this._prepareForTransition(a,b?c:null)&&b)this.setTransitionPos(a),(new n(this.domNode,c,a)).dispatch()}},_onNewWindowOpened:function(){},_prepareForTransition:function(a,c){},_onTouchStart:function(a){if(!(this.getParent().isEditing||!1===this.onTouchStart(a))){var c=
r.getEnclosingScrollable(this.domNode);if(!c||!b.contains(c.containerNode,"mblScrollableScrollTo2"))!this._onTouchEndHandle&&"touch"===this._selStartMethod&&(this._onTouchMoveHandle=this.connect(e.body(),h.move,"_onTouchMove"),this._onTouchEndHandle=this.connect(e.body(),h.release,"_onTouchEnd")),this.touchStartX=a.touches?a.touches[0].pageX:a.clientX,this.touchStartY=a.touches?a.touches[0].pageY:a.clientY,this._currentSel=this.selected,this._delayedSelection?this._selTimer=this.defer(function(){this.set("selected",
!0)},100):this.set("selected",!0)}},onTouchStart:function(){},_onTouchMove:function(a){var c=a.touches?a.touches[0].pageY:a.clientY;if(4<=Math.abs((a.touches?a.touches[0].pageX:a.clientX)-this.touchStartX)||4<=Math.abs(c-this.touchStartY))this.cancel(),(a=this.getParent())&&a.selectOne?this._prevSel&&this._prevSel.set("selected",!0):this.set("selected",!1)},_disconnect:function(){this.disconnect(this._onTouchMoveHandle);this.disconnect(this._onTouchEndHandle);this._onTouchMoveHandle=this._onTouchEndHandle=
null},cancel:function(){this._selTimer&&(this._selTimer.remove(),this._selTimer=null);this._disconnect()},_onTouchEnd:function(a){if(this._selTimer||!this._delayedSelection)this.cancel(),this._onClick(a)},setTransitionPos:function(a){for(var c=this;!(c=c.getParent(),!c||b.contains(c.domNode,"mblView")););c&&(c.clickedPosX=a.clientX,c.clickedPosY=a.clientY)},transitionTo:function(a,c,b,d){(new n(this.domNode,a&&"object"===typeof a?a:{moveTo:a,href:c,url:b,scene:d,transition:this.transition,transitionDir:this.transitionDir})).dispatch()},
_setIconAttr:function(a){this._isOnLine?(this._set("icon",a),this.iconNode=s.setIcon(a,this.iconPos,this.iconNode,this.alt,this.iconParentNode,this.refNode,this.position)):this._pendingIcon=a},_setLabelAttr:function(a){this._set("label",a);this.labelNode.innerHTML=this._cv?this._cv(a):a},_setSelectedAttr:function(a){if(a){var c=this.getParent();c&&c.selectOne&&(c=l.filter(c.getChildren(),function(a){return a.selected}),l.forEach(c,function(a){this._prevSel=a;a.set("selected",!1)},this))}this._set("selected",
a)}});return q("dojo-bidi")?m("dojox.mobile._ItemBase",[k,a]):k})},"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(l,m,k){return k("dijit.Destroyable",null,{destroy:function(e){this._destroyed=!0},own:function(){var e=["destroyRecursive","destroy","remove"];l.forEach(arguments,function(b){function h(){f.remove();l.forEach(k,function(b){b.remove()})}var d,f=m.before(this,"destroy",function(f){b[d](f)}),k=[];b.then?(d="cancel",b.then(h,h)):l.forEach(e,
function(f){"function"===typeof b[f]&&(d||(d=f),k.push(m.after(b,f,h,!0)))})},this);return arguments}})})},"dojox/mobile/View":function(){define("dojo/_base/array dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/sniff dojo/_base/window dojo/_base/Deferred dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dijit/registry dijit/_Contained dijit/_Container dijit/_WidgetBase ./ViewController ./common ./transition ./viewRegistry ./_css3".split(" "),
function(l,m,k,e,b,h,d,f,t,p,n,s,q,r,a,g,c,u,v,w,y,x){b.getObject("dojox.mobile",!0);return e("dojox.mobile.View",[c,g,a],{selected:!1,keepScrollPos:!0,tag:"div",baseClass:"mblView",constructor:function(a,c){c&&(t.byId(c).style.visibility="hidden")},destroy:function(){y.remove(this.id);this.inherited(arguments)},buildRendering:function(){this.templateString||(this.domNode=this.containerNode=this.srcNodeRef||n.create(this.tag));this._animEndHandle=this.connect(this.domNode,x.name("animationEnd"),"onAnimationEnd");
this._animStartHandle=this.connect(this.domNode,x.name("animationStart"),"onAnimationStart");m.mblCSS3Transition||(this._transEndHandle=this.connect(this.domNode,x.name("transitionEnd"),"onAnimationEnd"));h("mblAndroid3Workaround")&&q.set(this.domNode,x.name("transformStyle"),"preserve-3d");y.add(this);this.inherited(arguments)},startup:function(){if(!this._started){if(void 0===this._visible){var a=this.getSiblingViews(),c=location.hash&&location.hash.substring(1).split(/,/),b,d,f;l.forEach(a,function(a,
e){-1!==l.indexOf(c,a.id)&&(b=a);0==e&&(f=a);a.selected&&(d=a);a._visible=!1},this);(b||d||f)._visible=!0}this._visible&&(this.show(!0,!0),this.defer(function(){this.onStartView();k.publish("/dojox/mobile/startView",[this])}));"hidden"===this.domNode.style.visibility&&(this.domNode.style.visibility="inherit");this.inherited(arguments);a=this.getParent();(!a||!a.resize)&&this.resize();this._visible||this.hide()}},resize:function(){l.forEach(this.getChildren(),function(a){a.resize&&a.resize()})},onStartView:function(){},
onBeforeTransitionIn:function(a,c,b,d,f){},onAfterTransitionIn:function(a,c,b,d,f){},onBeforeTransitionOut:function(a,c,b,d,f){},onAfterTransitionOut:function(a,c,b,d,f){},_clearClasses:function(a){if(a){var c=[];l.forEach(b.trim(a.className||"").split(/\s+/),function(a){(a.match(/^mbl\w*View$/)||-1===a.indexOf("mbl"))&&c.push(a)},this);a.className=c.join(" ")}},_fixViewState:function(a){for(var c=this.domNode.parentNode.childNodes,b=0;b<c.length;b++){var d=c[b];1===d.nodeType&&p.contains(d,"mblView")&&
this._clearClasses(d)}this._clearClasses(a);if(a=r.byNode(a))a._inProgress=!1},convertToId:function(a){return"string"==typeof a?a.replace(/^#?([^&?]+).*/,"$1"):a},_isBookmarkable:function(a){return a.moveTo&&(m.mblForceBookmarkable||"#"===a.moveTo.charAt(0))&&!a.hashchange},performTransition:function(a,c,f,e,u){if(!this._inProgress){this._inProgress=!0;var g,n;if(a&&"object"===typeof a)g=a,n=c;else{g={moveTo:a,transitionDir:c,transition:f,context:e,method:u};n=[];for(var w=5;w<arguments.length;w++)n.push(arguments[w])}this._detail=
g;this._optArgs=n;this._arguments=[g.moveTo,g.transitionDir,g.transition,g.context,g.method];if("#"!==g.moveTo){g.moveTo?n=this.convertToId(g.moveTo):(this._dummyNode||(this._dummyNode=d.doc.createElement("div"),d.body().appendChild(this._dummyNode)),n=this._dummyNode);this.addTransitionInfo&&("string"==typeof g.moveTo&&this._isBookmarkable(g))&&this.addTransitionInfo(this.id,g.moveTo,{transitionDir:g.transitionDir,transition:g.transition});var w=this.domNode,l=w.offsetTop;if(n=this.toNode=t.byId(n)){n.style.visibility=
"hidden";n.style.display="";this._fixViewState(n);var s=r.byNode(n);if(s){if(m.mblAlwaysResizeOnTransition||!s._resized)v.resizeAll(null,s),s._resized=!0;g.transition&&"none"!=g.transition&&s._addTransitionPaddingTop(l);s.load&&s.load();s.movedFrom=w.id}h("mblAndroidWorkaround")&&(!m.mblCSS3Transition&&g.transition&&"none"!=g.transition)&&(q.set(n,x.name("transformStyle"),"preserve-3d"),q.set(w,x.name("transformStyle"),"preserve-3d"),p.add(n,"mblAndroidWorkaround"));this.onBeforeTransitionOut.apply(this,
this._arguments);k.publish("/dojox/mobile/beforeTransitionOut",[this].concat(b._toArray(this._arguments)));if(s){if(this.keepScrollPos&&!this.getParent()){l=d.body().scrollTop||d.doc.documentElement.scrollTop||d.global.pageYOffset||0;w._scrollTop=l;var y=1==g.transitionDir?0:n._scrollTop||0;n.style.top="0px";if(1<l||0!==y)w.style.top=y-l+"px",!(7<=h("ios"))&&!1!==m.mblHideAddressBar&&this.defer(function(){d.global.scrollTo(0,y||1)})}else n.style.top="0px";s.onBeforeTransitionIn.apply(s,this._arguments);
k.publish("/dojox/mobile/beforeTransitionIn",[s].concat(b._toArray(this._arguments)))}n.style.display="none";n.style.visibility="inherit";v.fromView=this;v.toView=s;this._doTransition(w,n,g.transition,g.transitionDir)}else console.log("dojox/mobile/View.performTransition: destination view not found: "+g.moveTo)}}},_addTransitionPaddingTop:function(a){this.containerNode.style.paddingTop=a+"px"},_removeTransitionPaddingTop:function(){this.containerNode.style.paddingTop=""},_toCls:function(a){return"mbl"+
a.charAt(0).toUpperCase()+a.substring(1)},_doTransition:function(a,c,e,g){var n=-1==g?" mblReverse":"";c.style.display="";if(!e||"none"==e)this.domNode.style.display="none",this.invokeCallback();else if(m.mblCSS3Transition)f.when(w,b.hitch(this,function(d){var h=q.get(c,"position");q.set(c,"position","absolute");f.when(d(a,c,{transition:e,reverse:-1===g?!0:!1}),b.hitch(this,function(){q.set(c,"position",h);c.style.paddingTop="";this.invokeCallback()}))}));else{-1!=e.indexOf("cube")&&(h("ipad")?q.set(c.parentNode,
{webkitPerspective:1600}):h("ios")&&q.set(c.parentNode,{webkitPerspective:800}));var u=this._toCls(e);if(h("mblAndroidWorkaround")){var v=this;v.defer(function(){p.add(a,u+" mblOut"+n);p.add(c,u+" mblIn"+n);p.remove(c,"mblAndroidWorkaround");v.defer(function(){p.add(a,"mblTransition");p.add(c,"mblTransition")},30)},70)}else p.add(a,u+" mblOut"+n),p.add(c,u+" mblIn"+n),this.defer(function(){p.add(a,"mblTransition");p.add(c,"mblTransition")},100);var l="50% 50%",k="50% 50%",r;-1!=e.indexOf("swirl")||
-1!=e.indexOf("zoom")?(l=this.keepScrollPos&&!this.getParent()?d.body().scrollTop||d.doc.documentElement.scrollTop||d.global.pageYOffset||0:-s.position(a,!0).y,r=d.global.innerHeight/2+l,l="50% "+r+"px",k="50% "+r+"px"):-1!=e.indexOf("scale")&&(l=s.position(a,!0),k=(void 0!==this.clickedPosX?this.clickedPosX:d.global.innerWidth/2)-l.x,l=this.keepScrollPos&&!this.getParent()?d.body().scrollTop||d.doc.documentElement.scrollTop||d.global.pageYOffset||0:-l.y,r=(void 0!==this.clickedPosY?this.clickedPosY:
d.global.innerHeight/2)+l,l=k+"px "+r+"px",k=k+"px "+r+"px");q.set(a,x.add({},{transformOrigin:l}));q.set(c,x.add({},{transformOrigin:k}))}},onAnimationStart:function(a){},onAnimationEnd:function(a){var c=a.animationName||a.target.className;if(!(-1===c.indexOf("Out")&&-1===c.indexOf("In")&&-1===c.indexOf("Shrink"))){var b=!1;p.contains(this.domNode,"mblOut")?(b=!0,this.domNode.style.display="none",p.remove(this.domNode,[this._toCls(this._detail.transition),"mblIn","mblOut","mblReverse"])):this._removeTransitionPaddingTop();
q.set(this.domNode,x.add({},{transformOrigin:""}));-1!==c.indexOf("Shrink")&&(a=a.target,a.style.display="none",p.remove(a,"mblCloseContent"),(a=y.getEnclosingScrollable(this.domNode))&&a.onTouchEnd());b&&this.invokeCallback();this._clearClasses(this.domNode);this.clickedPosX=this.clickedPosY=void 0;-1!==c.indexOf("Cube")&&(-1!==c.indexOf("In")&&h("ios"))&&(this.domNode.parentNode.style[x.name("perspective")]="")}},invokeCallback:function(){this.onAfterTransitionOut.apply(this,this._arguments);k.publish("/dojox/mobile/afterTransitionOut",
[this].concat(this._arguments));var a=r.byNode(this.toNode);a&&(a.onAfterTransitionIn.apply(a,this._arguments),k.publish("/dojox/mobile/afterTransitionIn",[a].concat(this._arguments)),a.movedFrom=void 0,this.setFragIds&&this._isBookmarkable(this._detail)&&this.setFragIds(a));h("mblAndroidWorkaround")&&this.defer(function(){a&&q.set(this.toNode,x.name("transformStyle"),"");q.set(this.domNode,x.name("transformStyle"),"")});var c=this._detail.context,b=this._detail.method;if(c||b)b||(b=c,c=null),c=c||
d.global,"string"==typeof b?c[b].apply(c,this._optArgs):"function"==typeof b&&b.apply(c,this._optArgs);this._detail=this._optArgs=this._arguments=void 0;this._inProgress=!1},isVisible:function(a){if(a){for(a=this.domNode;"BODY"!==a.tagName;a=a.parentNode)if("none"===q.get(a,"display"))return!1;return!0}return"none"!==q.get(this.domNode,"display")},getShowingView:function(){for(var a=this.domNode.parentNode.childNodes,c=0;c<a.length;c++){var b=a[c];if(1===b.nodeType&&p.contains(b,"mblView")&&"none"!==
b.style.display)return r.byNode(b)}return null},getSiblingViews:function(){return!this.domNode.parentNode?[this]:l.map(l.filter(this.domNode.parentNode.childNodes,function(a){return 1===a.nodeType&&p.contains(a,"mblView")}),function(a){return r.byNode(a)})},show:function(a,c){var b=this.getShowingView();a||(b&&(b.onBeforeTransitionOut(b.id),k.publish("/dojox/mobile/beforeTransitionOut",[b,b.id])),this.onBeforeTransitionIn(this.id),k.publish("/dojox/mobile/beforeTransitionIn",[this,this.id]));c?this.domNode.style.display=
"":l.forEach(this.getSiblingViews(),function(a){a.domNode.style.display=a===this?"":"none"},this);this.load&&this.load();a||(b&&(b.onAfterTransitionOut(b.id),k.publish("/dojox/mobile/afterTransitionOut",[b,b.id])),this.onAfterTransitionIn(this.id),k.publish("/dojox/mobile/afterTransitionIn",[this,this.id]))},hide:function(){this.domNode.style.display="none"}})})},"dojox/mobile/_base":function(){define("./common ./View ./Heading ./RoundRect ./RoundRectCategory ./EdgeToEdgeCategory ./RoundRectList ./EdgeToEdgeList ./ListItem ./Container ./Pane ./Switch ./ToolBarButton ./ProgressIndicator".split(" "),
function(l,m,k,e,b,h,d,f,t,p,n,s){return l})},"dijit/main":function(){define(["dojo/_base/kernel"],function(l){return l.dijit})},"dojox/mobile/viewRegistry":function(){define(["dojo/_base/array","dojo/dom-class","dijit/registry"],function(l,m,k){return{length:0,hash:{},initialView:null,add:function(e){this.hash[e.id]=e;this.length++},remove:function(e){this.hash[e]&&(delete this.hash[e],this.length--)},getViews:function(){var e=[],b;for(b in this.hash)e.push(this.hash[b]);return e},getParentView:function(e){for(e=
e.getParent();e;e=e.getParent())if(m.contains(e.domNode,"mblView"))return e;return null},getChildViews:function(e){return l.filter(this.getViews(),function(b){return this.getParentView(b)===e},this)},getEnclosingView:function(e){for(;e&&"BODY"!==e.tagName;e=e.parentNode)if(1===e.nodeType&&m.contains(e,"mblView"))return k.byNode(e);return null},getEnclosingScrollable:function(e){for(e=k.getEnclosingWidget(e);e;e=e.getParent())if(e.scrollableParams&&e._v)return e;return null}}})},"dojox/mobile/Heading":function(){define("dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/_base/window dojo/dom-class dojo/dom-construct dojo/dom-style dojo/dom-attr dijit/registry ./common dijit/_Contained dijit/_Container dijit/_WidgetBase ./ProgressIndicator ./ToolBarButton ./View dojo/has dojo/has!dojo-bidi?dojox/mobile/bidi/Heading".split(" "),
function(l,m,k,e,b,h,d,f,t,p,n,s,q,r,a,g,c,u,v){e.getObject("dojox.mobile",!0);m=k(u("dojo-bidi")?"dojox.mobile.NonBidiHeading":"dojox.mobile.Heading",[r,q,s],{back:"",href:"",moveTo:"",transition:"slide",label:"",iconBase:"",tag:"h1",busy:!1,progStyle:"mblProgWhite",baseClass:"mblHeading",buildRendering:function(){this.templateString||(this.domNode=this.containerNode=this.srcNodeRef||b.doc.createElement(this.tag));this.inherited(arguments);this.templateString||(this.label||l.forEach(this.domNode.childNodes,
function(a){if(3==a.nodeType){var c=e.trim(a.nodeValue);c&&(this.label=c,this.labelNode=d.create("span",{innerHTML:c},a,"replace"))}},this),this.labelNode||(this.labelNode=d.create("span",null,this.domNode)),this.labelNode.className="mblHeadingSpanTitle",this.labelDivNode=d.create("div",{className:"mblHeadingDivTitle",innerHTML:this.labelNode.innerHTML},this.domNode));this.labelDivNode&&(t.set(this.labelDivNode,"role","heading"),t.set(this.labelDivNode,"aria-level","1"));n.setSelectable(this.domNode,
!1)},startup:function(){if(!this._started){var a=this.getParent&&this.getParent();if(!a||!a.resize){var c=this;c.defer(function(){c.resize()})}this.inherited(arguments)}},resize:function(){if(this.labelNode){for(var a,c,b=this.containerNode.childNodes,d=b.length-1;0<=d;d--){var e=b[d];1===e.nodeType&&"none"!==f.get(e,"display")&&(!c&&"right"===f.get(e,"float")&&(c=e),!a&&"left"===f.get(e,"float")&&(a=e))}!this.labelNodeLen&&this.label&&(this.labelNode.style.display="inline",this.labelNodeLen=this.labelNode.offsetWidth,
this.labelNode.style.display="");b=this.domNode.offsetWidth;d=this.labelNodeLen||0;h[b-2*Math.max(c?b-c.offsetLeft+5:0,a?a.offsetLeft+a.offsetWidth+5:0)>d?"add":"remove"](this.domNode,"mblHeadingCenterTitle")}l.forEach(this.getChildren(),function(a){a.resize&&a.resize()})},_setBackAttr:function(a){this._set("back",a);this.backButton?this.backButton.set("label",a):(this.backButton=new g({arrow:"left",label:a,moveTo:this.moveTo,back:!this.moveTo&&!this.href,href:this.href,transition:this.transition,
transitionDir:-1,dir:this.isLeftToRight()?"ltr":"rtl"}),this.backButton.placeAt(this.domNode,"first"));this.resize()},_setMoveToAttr:function(a){this._set("moveTo",a);this.backButton&&(this.backButton.set("moveTo",a),this.backButton.set("back",!a&&!this.href))},_setHrefAttr:function(a){this._set("href",a);this.backButton&&(this.backButton.set("href",a),this.backButton.set("back",!this.moveTo&&!a))},_setTransitionAttr:function(a){this._set("transition",a);this.backButton&&this.backButton.set("transition",
a)},_setLabelAttr:function(a){this._set("label",a);this.labelNode.innerHTML=this.labelDivNode.innerHTML=this._cv?this._cv(a):a;delete this.labelNodeLen},_setBusyAttr:function(c){var b=this._prog;c?(b||(b=this._prog=new a({size:30,center:!1}),h.add(b.domNode,this.progStyle)),d.place(b.domNode,this.domNode,"first"),b.start()):b&&b.stop();this._set("busy",c)}});return u("dojo-bidi")?k("dojox.mobile.Heading",[m,v]):m})},"dijit/registry":function(){define(["dojo/_base/array","dojo/_base/window","./main"],
function(l,m,k){var e={},b={},h={length:0,add:function(d){if(b[d.id])throw Error("Tried to register widget with id\x3d\x3d"+d.id+" but that id is already registered");b[d.id]=d;this.length++},remove:function(d){b[d]&&(delete b[d],this.length--)},byId:function(d){return"string"==typeof d?b[d]:d},byNode:function(d){return b[d.getAttribute("widgetId")]},toArray:function(){var d=[],e;for(e in b)d.push(b[e]);return d},getUniqueId:function(d){var f;do f=d+"_"+(d in e?++e[d]:e[d]=0);while(b[f]);return"dijit"==
k._scopeName?f:k._scopeName+"_"+f},findWidgets:function(d,e){function h(d){for(d=d.firstChild;d;d=d.nextSibling)if(1==d.nodeType){var k=d.getAttribute("widgetId");k?(k=b[k])&&l.push(k):d!==e&&h(d)}}var l=[];h(d);return l},_destroyAll:function(){k._curFocus=null;k._prevFocus=null;k._activeStack=[];l.forEach(h.findWidgets(m.body()),function(b){b._destroyed||(b.destroyRecursive?b.destroyRecursive():b.destroy&&b.destroy())})},getEnclosingWidget:function(d){for(;d;){var e=1==d.nodeType&&d.getAttribute("widgetId");
if(e)return b[e];d=d.parentNode}return null},_hash:b};return k.registry=h})},"dojox/mobile/ProgressIndicator":function(){define("dojo/_base/config dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dijit/_Contained dijit/_WidgetBase ./_css3 dojo/has!dojo-bidi?dojox/mobile/bidi/ProgressIndicator".split(" "),function(l,m,k,e,b,h,d,f,t,p,n,s){var q=m("dojox.mobile.ProgressIndicator",[p,t],{interval:100,size:40,removeOnStop:!0,startSpinning:!1,
center:!0,colors:null,baseClass:"mblProgressIndicator",constructor:function(){this.colors=[];this._bars=[]},buildRendering:function(){this.inherited(arguments);this.center&&e.add(this.domNode,"mblProgressIndicatorCenter");this.containerNode=b.create("div",{className:"mblProgContainer"},this.domNode);this.spinnerNode=b.create("div",null,this.containerNode);for(var d=0;12>d;d++){var a=b.create("div",{className:"mblProg mblProg"+d},this.spinnerNode);this._bars.push(a)}this.scale(this.size);this.startSpinning&&
this.start()},scale:function(b){var a=b/40;d.set(this.containerNode,n.add({},{transform:"scale("+a+")",transformOrigin:"0 0"}));h.setMarginBox(this.domNode,{w:b,h:b});h.setMarginBox(this.containerNode,{w:b/a,h:b/a})},start:function(){if(this.imageNode){var b=this.imageNode,a=Math.round((this.containerNode.offsetWidth-b.offsetWidth)/2),d=Math.round((this.containerNode.offsetHeight-b.offsetHeight)/2);b.style.margin=d+"px "+a+"px"}else{var c=0,f=this;this.timer=setInterval(function(){c--;c=0>c?11:c;
for(var a=f.colors,b=0;12>b;b++){var d=(c+b)%12;a[d]?f._bars[b].style.backgroundColor=a[d]:e.replace(f._bars[b],"mblProg"+d+"Color","mblProg"+(11===d?0:d+1)+"Color")}},this.interval)}},stop:function(){this.timer&&clearInterval(this.timer);this.timer=null;this.removeOnStop&&(this.domNode&&this.domNode.parentNode)&&this.domNode.parentNode.removeChild(this.domNode)},setImage:function(d){d?(this.imageNode=b.create("img",{src:d},this.containerNode),this.spinnerNode.style.display="none"):(this.imageNode&&
(this.containerNode.removeChild(this.imageNode),this.imageNode=null),this.spinnerNode.style.display="")},destroy:function(){this.inherited(arguments);this===q._instance&&(q._instance=null)}}),q=f("dojo-bidi")?m("dojox.mobile.ProgressIndicator",[q,s]):q;q._instance=null;q.getInstance=function(b){q._instance||(q._instance=new q(b));return q._instance};return q})},"dojox/mobile/Container":function(){define(["dojo/_base/declare","dijit/_Container","./Pane"],function(l,m,k){return l("dojox.mobile.Container",
[k,m],{baseClass:"mblContainer"})})},"dojox/mobile/RoundRectList":function(){define("dojo/_base/array dojo/_base/declare dojo/_base/event dojo/_base/lang dojo/_base/window dojo/dom-construct dojo/dom-attr dijit/_Contained dijit/_Container dijit/_WidgetBase".split(" "),function(l,m,k,e,b,h,d,f,t,p){return m("dojox.mobile.RoundRectList",[p,t,f],{transition:"slide",iconBase:"",iconPos:"",select:"",stateful:!1,syncWithViews:!1,editable:!1,tag:"ul",editableMixinClass:"dojox/mobile/_EditableListMixin",
baseClass:"mblRoundRectList",filterBoxClass:"mblFilteredRoundRectListSearchBox",buildRendering:function(){this.domNode=this.srcNodeRef||h.create(this.tag);this.select&&(d.set(this.domNode,"role","listbox"),"multiple"===this.select&&d.set(this.domNode,"aria-multiselectable","true"));this.inherited(arguments)},postCreate:function(){this.editable&&require([this.editableMixinClass],e.hitch(this,function(b){m.safeMixin(this,new b)}));this.connect(this.domNode,"onselectstart",k.stop);if(this.syncWithViews){var b=
function(b,d,e,a,f,c){(d=l.filter(this.getChildren(),function(a){return a.moveTo==="#"+b.id||a.moveTo===b.id})[0])&&d.set("selected",!0)};this.subscribe("/dojox/mobile/afterTransitionIn",b);this.subscribe("/dojox/mobile/startView",b)}},resize:function(){l.forEach(this.getChildren(),function(b){b.resize&&b.resize()})},onCheckStateChanged:function(){},_setStatefulAttr:function(b){this._set("stateful",b);this.selectOne=b;l.forEach(this.getChildren(),function(b){b.setArrow&&b.setArrow()})},deselectItem:function(b){b.set("selected",
!1)},deselectAll:function(){l.forEach(this.getChildren(),function(b){b.set("selected",!1)})},selectItem:function(b){b.set("selected",!0)}})})},"dijit/_Container":function(){define(["dojo/_base/array","dojo/_base/declare","dojo/dom-construct","dojo/_base/kernel"],function(l,m,k,e){return m("dijit._Container",null,{buildRendering:function(){this.inherited(arguments);this.containerNode||(this.containerNode=this.domNode)},addChild:function(b,e){var d=this.containerNode;if(0<e){for(d=d.firstChild;0<e;)1==
d.nodeType&&e--,d=d.nextSibling;d?e="before":(d=this.containerNode,e="last")}k.place(b.domNode,d,e);this._started&&!b._started&&b.startup()},removeChild:function(b){"number"==typeof b&&(b=this.getChildren()[b]);b&&(b=b.domNode)&&b.parentNode&&b.parentNode.removeChild(b)},hasChildren:function(){return 0<this.getChildren().length},_getSiblingOfChild:function(b,h){e.deprecated(this.declaredClass+"::_getSiblingOfChild() is deprecated. Use _KeyNavMixin::_getNext() instead.","","2.0");var d=this.getChildren(),
f=l.indexOf(d,b);return d[f+h]},getIndexOfChild:function(b){return l.indexOf(this.getChildren(),b)}})})},"dojox/mobile/Switch":function(){define("dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/event dojo/_base/window dojo/dom-class dojo/dom-construct dojo/dom-style dojo/dom-attr dojo/touch dijit/_Contained dijit/_WidgetBase ./sniff ./_maskUtils ./common dojo/has!dojo-bidi?dojox/mobile/bidi/Switch".split(" "),function(l,m,k,e,b,h,d,f,t,p,n,s,q,r,a,g){n=k(q("dojo-bidi")?"dojox.mobile.NonBidiSwitch":
"dojox.mobile.Switch",[s,n],{value:"on",name:"",leftLabel:"ON",rightLabel:"OFF",shape:"mblSwDefaultShape",tabIndex:"0",_setTabIndexAttr:"",baseClass:"mblSwitch",role:"",buildRendering:function(){this.templateString||(this.domNode=this.srcNodeRef&&"SPAN"===this.srcNodeRef.tagName?this.srcNodeRef:d.create("span"));"undefined"!=typeof this.domNode.style.msTouchAction&&(this.domNode.style.msTouchAction="none");this.inherited(arguments);if(!this.templateString){var a=this.srcNodeRef&&this.srcNodeRef.className||
this.className||this["class"];if(a=a.match(/mblSw.*Shape\d*/))this.shape=a;h.add(this.domNode,this.shape);this.domNode.innerHTML='\x3cdiv class\x3d"mblSwitchInner"\x3e\x3cdiv class\x3d"mblSwitchBg mblSwitchBgLeft"\x3e\x3cdiv class\x3d"mblSwitchText mblSwitchTextLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"mblSwitchBg mblSwitchBgRight"\x3e\x3cdiv class\x3d"mblSwitchText mblSwitchTextRight"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"mblSwitchKnob"\x3e\x3c/div\x3e\x3cinput type\x3d"hidden"'+
(this.name?' name\x3d"'+this.name+'"':"")+"\x3e\x3c/div\x3e\x3c/div\x3e";a=this.inner=this.domNode.firstChild;this.left=a.childNodes[0];this.right=a.childNodes[1];this.knob=a.childNodes[2];this.input=a.childNodes[3]}t.set(this.domNode,"role","checkbox");t.set(this.domNode,"aria-checked","on"===this.value?"true":"false");this.switchNode=this.domNode;q("windows-theme")&&(a=d.create("div",{className:"mblSwitchContainer"}),this.labelNode=d.create("label",{"class":"mblSwitchLabel","for":this.id},a),a.appendChild(this.domNode.cloneNode(!0)),
this.domNode=a,this.focusNode=a.childNodes[1],this.labelNode.innerHTML="off"==this.value?this.rightLabel:this.leftLabel,this.switchNode=this.domNode.childNodes[1],a=this.inner=this.domNode.childNodes[1].firstChild,this.left=a.childNodes[0],this.right=a.childNodes[1],this.knob=a.childNodes[2],this.input=a.childNodes[3])},postCreate:function(){this.connect(this.switchNode,"onclick","_onClick");this.connect(this.switchNode,"onkeydown","_onClick");this._startHandle=this.connect(this.switchNode,p.press,
"onTouchStart");this._initialValue=this.value},startup:function(){this._started||this.resize()},resize:function(){if(q("windows-theme"))f.set(this.domNode,"width","100%");else{var a=f.get(this.domNode,"width"),b=a+"px",a=a-f.get(this.knob,"width")+"px";f.set(this.left,"width",b);f.set(this.right,this.isLeftToRight()?{width:b,left:a}:{width:b});f.set(this.left.firstChild,"width",a);f.set(this.right.firstChild,"width",a);f.set(this.knob,"left",a);"off"==this.value&&f.set(this.inner,"left",this.isLeftToRight()?
"-"+a:0);this._hasMaskImage=!1;this._createMaskImage()}},_changeState:function(a,b){var d="on"===a;this.left.style.display="";this.right.style.display="";this.inner.style.left="";b&&h.add(this.switchNode,"mblSwitchAnimation");h.remove(this.switchNode,d?"mblSwitchOff":"mblSwitchOn");h.add(this.switchNode,d?"mblSwitchOn":"mblSwitchOff");t.set(this.switchNode,"aria-checked",d?"true":"false");!d&&!q("windows-theme")&&(this.inner.style.left=(this.isLeftToRight()?-(f.get(this.domNode,"width")-f.get(this.knob,
"width")):0)+"px");var e=this;e.defer(function(){e.left.style.display=d?"":"none";e.right.style.display=!d?"":"none";h.remove(e.switchNode,"mblSwitchAnimation")},b?300:0)},_createMaskImage:function(){this._timer&&(this._timer.remove(),delete this._timer);if(!this._hasMaskImage){var a=f.get(this.domNode,"width"),b=f.get(this.domNode,"height");this._width=a-f.get(this.knob,"width");this._hasMaskImage=!0;if(q("mask-image")){var d=f.get(this.left,"borderTopLeftRadius");if("0px"!=d){var e=d.split(" "),
d=parseFloat(e[0]),e=1==e.length?d:parseFloat(e[1]);(this.shape+"Mask"+a+b+d+e).replace(/\./,"_");r.createRoundMask(this.switchNode,0,0,0,0,a,b,d,e,1)}}}},_onClick:function(a){if((!a||!("keydown"===a.type&&13!==a.keyCode))&&!1!==this.onClick(a)&&!this._moved)this._set("value",this.input.value="on"==this.value?"off":"on"),this._changeState(this.value,!0),this.onStateChanged(this.value)},onClick:function(){},onTouchStart:function(a){this._moved=!1;this.innerStartX=this.inner.offsetLeft;this._conn||
(this._conn=[this.connect(this.inner,p.move,"onTouchMove"),this.connect(b.doc,p.release,"onTouchEnd")],q("windows-theme")&&this._conn.push(this.connect(b.doc,"MSPointerCancel","onTouchEnd")));this.touchStartX=a.touches?a.touches[0].pageX:a.clientX;this.left.style.display="";this.right.style.display="";e.stop(a);this._createMaskImage()},onTouchMove:function(a){a.preventDefault();if(a.targetTouches){if(1!=a.targetTouches.length)return;a=a.targetTouches[0].clientX-this.touchStartX}else a=a.clientX-this.touchStartX;
var b=this.innerStartX+a;b<=-(this._width-10)&&(b=-this._width);-10<=b&&(b=0);this.inner.style.left=b+"px";10<Math.abs(a)&&(this._moved=!0)},onTouchEnd:function(b){l.forEach(this._conn,m.disconnect);this._conn=null;this.innerStartX==this.inner.offsetLeft?q("touch")&&q("clicks-prevented")&&a._sendClick(this.inner,b):(b=this.inner.offsetLeft<-(this._width/2)?"off":"on",b=this._newState(b),this._changeState(b,!0),b!=this.value&&(this._set("value",this.input.value=b),this.onStateChanged(b)))},_newState:function(a){return a},
onStateChanged:function(a){this.labelNode&&(this.labelNode.innerHTML="off"==a?this.rightLabel:this.leftLabel)},_setValueAttr:function(a){this._changeState(a,!1);this.value!=a&&(this._set("value",this.input.value=a),this.onStateChanged(a))},_setLeftLabelAttr:function(a){this.leftLabel=a;this.left.firstChild.innerHTML=this._cv?this._cv(a):a},_setRightLabelAttr:function(a){this.rightLabel=a;this.right.firstChild.innerHTML=this._cv?this._cv(a):a},reset:function(){this.set("value",this._initialValue)}});
return q("dojo-bidi")?k("dojox.mobile.Switch",[n,g]):n})},"dojox/mobile/EdgeToEdgeCategory":function(){define(["dojo/_base/declare","./RoundRectCategory"],function(l,m){return l("dojox.mobile.EdgeToEdgeCategory",m,{buildRendering:function(){this.inherited(arguments);this.domNode.className="mblEdgeToEdgeCategory";this.type&&"long"==this.type&&(this.domNode.className+=" mblEdgeToEdgeCategoryLong")}})})},"dojox/mobile/transition":function(){define(["dojo/_base/Deferred","dojo/_base/config"],function(l,
m){if(m.mblCSS3Transition){var k=new l;require([m.mblCSS3Transition],function(e){k.resolve(e)});return k}return null})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),
function(l,m,k,e,b,h,d,f,t,p,n,s,q,r,a,g,c,u,v,w,y,x,z){function C(a){return function(b){f[b?"set":"remove"](this.domNode,a,b);this._set(a,b)}}q.add("dijit-legacy-requires",!r.isAsync);q.add("dojo-bidi",!1);q("dijit-legacy-requires")&&c(0,function(){l(["dijit/_base/manager"])});var D={};e=h("dijit._WidgetBase",[u,y],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:C("lang"),dir:"",_setDirAttr:C("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",
baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",a)},attributeMap:{},_blankGif:e.blankGif||l.toUrl("dojo/resources/blank.gif"),_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var b=a.prototype,c=a._setterAttrs=[],a=a._onMap={},d;for(d in b.attributeMap)c.push(d);for(d in b)/^on/.test(d)&&(a[d.substring(2).toLowerCase()]=d),/^_set[A-Z](.*)Attr$/.test(d)&&(d=d.charAt(4).toLowerCase()+d.substr(5,
d.length-9),(!b.attributeMap||!(d in b.attributeMap))&&c.push(d))}},postscript:function(a,b){this.create(a,b)},create:function(b,c){this._introspect();this.srcNodeRef=d.byId(c);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);b&&(this.params=b,a.mixin(this,b));this.postMixInProperties();this.id||(this.id=z.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||
(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=w.body(this.ownerDocument);z.add(this);this.buildRendering();var e;if(this.domNode){this._applyAttributes();var f=this.srcNodeRef;f&&(f.parentNode&&this.domNode!==f)&&(f.parentNode.replaceChild(this.domNode,f),e=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();e&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},b;for(b in this.params||{})a[b]=this._get(b);m.forEach(this.constructor._setterAttrs,
function(b){if(!(b in a)){var c=this._get(b);c&&this.set(b,c)}},this);for(b in a)this.set(b,a[b])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(m.map(a,function(a){return a+"Rtl"})));t.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,m.forEach(this.getChildren(),function(b){!b._started&&
(!b._destroyed&&a.isFunction(b.startup))&&(b.startup(),b._started=!0)}))},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(b){function c(a){a.destroyRecursive?a.destroyRecursive(b):a.destroy&&a.destroy(b)}this._beingDestroyed=!0;this.uninitialize();m.forEach(this._connects,a.hitch(this,"disconnect"));m.forEach(this._supportingWidgets,c);this.domNode&&m.forEach(z.findWidgets(this.domNode,this.containerNode),c);this.destroyRendering(b);
z.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?f.remove(this.domNode,"widgetId"):p.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||p.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){m.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(b){var c=this.domNode;a.isObject(b)?
s.set(c,b):c.style.cssText=c.style.cssText?c.style.cssText+("; "+b):b;this._set("style",b)},_attrToDom:function(b,c,d){d=3<=arguments.length?d:this.attributeMap[b];m.forEach(a.isArray(d)?d:[d],function(d){var e=this[d.node||d||"domNode"];switch(d.type||"attribute"){case "attribute":a.isFunction(c)&&(c=a.hitch(this,c));d=d.attribute?d.attribute:/^on[A-Z][a-zA-Z]*$/.test(b)?b.toLowerCase():b;e.tagName?f.set(e,d,c):e.set(d,c);break;case "innerText":e.innerHTML="";e.appendChild(this.ownerDocument.createTextNode(c));
break;case "innerHTML":e.innerHTML=c;break;case "class":t.replace(e,c,this[b])}},this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?this[b.g]():this._get(a)},set:function(b,c){if("object"===typeof b){for(var d in b)this.set(d,b[d]);return this}d=this._getAttrNames(b);var e=this[d.s];if(a.isFunction(e))var f=e.apply(this,Array.prototype.slice.call(arguments,1));else{var e=this.focusNode&&!a.isFunction(this.focusNode)?"focusNode":"domNode",h=this[e]&&this[e].tagName,g;if(g=h)if(!(g=
D[h])){g=this[e];var l={},k;for(k in g)l[k.toLowerCase()]=!0;g=D[h]=l}k=g;d=b in this.attributeMap?this.attributeMap[b]:d.s in this?this[d.s]:k&&d.l in k&&"function"!=typeof c||/^aria-|^data-|^role$/.test(b)?e:null;null!=d&&this._attrToDom(b,c,d);this._set(b,c)}return f||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return b[a]={n:a+"Node",s:"_set"+c+"Attr",
g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;if(this._created&&!(c===b||c!==c&&b!==b))this._watchCallbacks&&this._watchCallbacks(a,c,b),this.emit("attrmodified-"+a,{detail:{prevValue:c,newValue:b}})},_get:function(a){return this[a]},emit:function(a,b,c){b=b||{};void 0===b.bubbles&&(b.bubbles=!0);void 0===b.cancelable&&(b.cancelable=!0);b.detail||(b.detail={});b.detail.widget=this;var d,e=this["on"+a];e&&(d=e.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&
g.emit(this.domNode,a.toLowerCase(),b);return d},on:function(a,b){var c=this._onMap(a);return c?k.after(this,c,b,!0):this.own(g(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;if(!c){var c=b._onMap={},d;for(d in b.prototype)/^on/.test(d)&&(c[d.replace(/^on/,"").toLowerCase()]=d)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?z.findWidgets(this.containerNode):
[]},getParent:function(){return z.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,c,d){return this.own(b.connect(a,c,this,d))[0]},disconnect:function(a){a.remove()},subscribe:function(b,c){return this.own(v.subscribe(b,a.hitch(this,c)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():n.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=s.get(this.domNode,"display")},placeAt:function(a,b){var c=
!a.tagName&&z.byId(a);c&&c.addChild&&(!b||"number"===typeof b)?c.addChild(this,b):(c=c&&"domNode"in c?c.containerNode&&!/after|before|replace/.test(b||"")?c.containerNode:c.domNode:d.byId(a,this.ownerDocument),p.place(this.domNode,c,b),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(b,c){var d=setTimeout(a.hitch(this,function(){d&&(d=null,this._destroyed||a.hitch(this,b)())}),c||0);return{remove:function(){d&&(clearTimeout(d),d=null);return null}}}});q("dojo-bidi")&&
e.extend(x);return e})},"dojox/main":function(){define(["dojo/_base/kernel"],function(l){return l.dojox})},"dojox/mobile/common":function(){define("dojo/_base/array dojo/_base/config dojo/_base/connect dojo/_base/lang dojo/_base/window dojo/_base/kernel dojo/dom dojo/dom-class dojo/dom-construct dojo/domReady dojo/ready dojo/touch dijit/registry ./sniff ./uacss".split(" "),function(l,m,k,e,b,h,d,f,t,p,n,s,q,r){var a=e.getObject("dojox.mobile",!0);b.doc.dojoClick=!0;r("touch")&&(r.add("clicks-prevented",
!(4.1<=r("android")||10===r("ie")||!r("ie")&&6<r("trident"))),r("clicks-prevented")&&(a._sendClick=function(a,d){for(var e=a;e;e=e.parentNode)if(e.dojoClick)return;e=b.doc.createEvent("MouseEvents");e.initMouseEvent("click",!0,!0,b.global,1,d.screenX,d.screenY,d.clientX,d.clientY);a.dispatchEvent(e)}));a.getScreenSize=function(){return{h:b.global.innerHeight||b.doc.documentElement.clientHeight,w:b.global.innerWidth||b.doc.documentElement.clientWidth}};a.updateOrient=function(){var c=a.getScreenSize();
f.replace(b.doc.documentElement,c.h>c.w?"dj_portrait":"dj_landscape",c.h>c.w?"dj_landscape":"dj_portrait")};a.updateOrient();a.tabletSize=500;a.detectScreenSize=function(c){var d=a.getScreenSize(),e=Math.min(d.w,d.h),h,g;if(e>=a.tabletSize&&(c||!this._sz||this._sz<a.tabletSize))h="phone",g="tablet";else if(e<a.tabletSize&&(c||!this._sz||this._sz>=a.tabletSize))h="tablet",g="phone";g&&(f.replace(b.doc.documentElement,"dj_"+g,"dj_"+h),k.publish("/dojox/mobile/screenSize/"+g,[d]));this._sz=e};a.detectScreenSize();
a.hideAddressBarWait="number"===typeof m.mblHideAddressBarWait?m.mblHideAddressBarWait:1500;a.hide_1=function(){scrollTo(0,1);a._hidingTimer=0==a._hidingTimer?200:2*a._hidingTimer;setTimeout(function(){a.isAddressBarHidden()||a._hidingTimer>a.hideAddressBarWait?(a.resizeAll(),a._hiding=!1):setTimeout(a.hide_1,a._hidingTimer)},50)};a.hideAddressBar=function(c){!a.disableHideAddressBar&&!a._hiding&&(a._hiding=!0,a._hidingTimer=r("ios")?200:0,c=screen.availHeight,r("android")&&(c=outerHeight/devicePixelRatio,
0==c&&(a._hiding=!1,setTimeout(function(){a.hideAddressBar()},200)),c<=innerHeight&&(c=outerHeight),3>r("android")&&(b.doc.documentElement.style.overflow=b.body().style.overflow="visible")),b.body().offsetHeight<c&&(b.body().style.minHeight=c+"px",a._resetMinHeight=!0),setTimeout(a.hide_1,a._hidingTimer))};a.isAddressBarHidden=function(){return 1===pageYOffset};a.resizeAll=function(c,d){if(!a.disableResizeAll){k.publish("/dojox/mobile/resizeAll",[c,d]);k.publish("/dojox/mobile/beforeResizeAll",[c,
d]);a._resetMinHeight&&(b.body().style.minHeight=a.getScreenSize().h+"px");a.updateOrient();a.detectScreenSize();var e=function(a){var b=a.getParent&&a.getParent();return!(b&&b.resize||!a.resize)},f=function(a){l.forEach(a.getChildren(),function(a){e(a)&&a.resize();f(a)})};d?(d.resize&&d.resize(),f(d)):l.forEach(l.filter(q.toArray(),e),function(a){a.resize()});k.publish("/dojox/mobile/afterResizeAll",[c,d])}};a.openWindow=function(a,d){b.global.open(a,d||"_blank")};a._detectWindowsTheme=function(){navigator.userAgent.match(/IEMobile\/10\.0/)&&
t.create("style",{innerHTML:"@-ms-viewport {width: auto !important}"},b.doc.head);var a=function(){f.add(b.doc.documentElement,"windows_theme");h.experimental("Dojo Mobile Windows theme","Behavior and appearance of the Windows theme are experimental.")},d=r("windows-theme");if(void 0!==d)d&&a();else{for(var e,g=function(b){return b&&-1!==b.indexOf("/windows/")?(r.add("windows-theme",!0),a(),!0):!1},l=b.doc.styleSheets,d=0;d<l.length;d++)if(!l[d].href){var k=l[d].cssRules||l[d].imports;if(k)for(e=
0;e<k.length;e++)if(g(k[e].href))return}e=b.doc.getElementsByTagName("link");for(d=0;d<e.length&&!g(e[d].href);d++);}};!1!==m.mblApplyPageStyles&&f.add(b.doc.documentElement,"mobile");r("chrome")&&f.add(b.doc.documentElement,"dj_chrome");if(b.global._no_dojo_dm){e=b.global._no_dojo_dm;for(var g in e)a[g]=e[g];a.deviceTheme.setDm(a)}r.add("mblAndroidWorkaround",!1!==m.mblAndroidWorkaround&&3>r("android"),void 0,!0);r.add("mblAndroid3Workaround",!1!==m.mblAndroid3Workaround&&3<=r("android"),void 0,
!0);a._detectWindowsTheme();a.setSelectable=function(a,b){var e,g;a=d.byId(a);if(9>=r("ie"))if(e=a.getElementsByTagName("*"),g=e.length,b)for(a.removeAttribute("unselectable");g--;)e[g].removeAttribute("unselectable");else for(a.setAttribute("unselectable","on");g--;)"INPUT"!==e[g].tagName&&e[g].setAttribute("unselectable","on");else f.toggle(a,"unselectable",!b)};p(function(){f.add(b.body(),"mblBackground")});n(function(){a.detectScreenSize(!0);!1!==m.mblAndroidWorkaroundButtonStyle&&r("android")&&
t.create("style",{innerHTML:"BUTTON,INPUT[type\x3d'button'],INPUT[type\x3d'submit'],INPUT[type\x3d'reset'],INPUT[type\x3d'file']::-webkit-file-upload-button{-webkit-appearance:none;} audio::-webkit-media-controls-play-button,video::-webkit-media-controls-play-button{-webkit-appearance:media-play-button;} video::-webkit-media-controls-fullscreen-button{-webkit-appearance:media-fullscreen-button;}"},b.doc.head,"first");r("mblAndroidWorkaround")&&t.create("style",{innerHTML:".mblView.mblAndroidWorkaround{position:absolute;top:-9999px !important;left:-9999px !important;}"},
b.doc.head,"last");var c=a.resizeAll,d=-1!=navigator.appVersion.indexOf("Mobile")&&!(7<=r("ios"));if(!1!==m.mblHideAddressBar&&d||!0===m.mblForceHideAddressBar)a.hideAddressBar(),!0===m.mblAlwaysHideAddressBar&&(c=a.hideAddressBar);var e=6<=r("ios");if((r("android")||e)&&void 0!==b.global.onorientationchange){var f=c,g,h,l;e?(h=b.doc.documentElement.clientWidth,l=b.doc.documentElement.clientHeight):(c=function(a){var b=k.connect(null,"onresize",null,function(a){k.disconnect(b);f(a)})},g=a.getScreenSize());
k.connect(null,"onresize",null,function(c){if(e){var d=b.doc.documentElement.clientWidth,k=b.doc.documentElement.clientHeight;d==h&&k!=l&&f(c);h=d;l=k}else d=a.getScreenSize(),d.w==g.w&&100<=Math.abs(d.h-g.h)&&f(c),g=d})}k.connect(null,void 0!==b.global.onorientationchange?"onorientationchange":"onresize",null,c);b.body().style.visibility="visible"});return a})},"dojox/mobile/ViewController":function(){define("dojo/_base/kernel dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/_base/window dojo/_base/Deferred dojo/dom dojo/dom-class dojo/dom-construct dojo/on dojo/ready dijit/registry ./ProgressIndicator ./TransitionEvent ./viewRegistry".split(" "),
function(l,m,k,e,b,h,d,f,t,p,n,s,q,r,a,g){var c=e("dojox.mobile.ViewController",null,{dataHandlerClass:"dojox/mobile/dh/DataHandler",dataSourceClass:"dojox/mobile/dh/UrlDataSource",fileTypeMapClass:"dojox/mobile/dh/SuffixFileTypeMap",constructor:function(){this.viewMap={};s(b.hitch(this,function(){n(h.body(),"startTransition",b.hitch(this,"onStartTransition"))}))},findTransitionViews:function(a){if(!a)return[];a.match(/^#?([^&?]+)(.*)/);a=RegExp.$2;var b=q.byId(RegExp.$1);if(!b)return[];for(var c=
b.getParent();c;c=c.getParent())if(c.isVisible&&!c.isVisible()){var d=b.getShowingView();d&&d.id!==b.id&&b.show();b=c}return[b.getShowingView(),b,a]},openExternalView:function(c,e){var f=new d,g=this.viewMap[c.url];if(g)return c.moveTo=g,c.noTransition?q.byId(g).hide():(new a(h.body(),c)).dispatch(),f.resolve(!0),f;for(var l=null,g=e.childNodes.length-1;0<=g;g--){var k=e.childNodes[g];if(1===k.nodeType&&"bottom"===(k.getAttribute("fixed")||k.getAttribute("data-mobile-fixed")||q.byNode(k)&&q.byNode(k).fixed)){l=
k;break}}require([c.dataHandlerClass||this.dataHandlerClass,c.dataSourceClass||this.dataSourceClass,c.fileTypeMapClass||this.fileTypeMapClass],b.hitch(this,function(d,g,k){d=new d(new g(c.data||c.url),e,l);k=c.contentType||k.getContentType(c.url)||"html";d.processData(k,b.hitch(this,function(b){b?(this.viewMap[c.url]=c.moveTo=b,c.noTransition?q.byId(b).hide():(new a(h.body(),c)).dispatch(),f.resolve(!0)):f.reject("Failed to load "+c.url)}))}));return f},onStartTransition:function(a){a.preventDefault();
if(a.detail){var b=a.detail;if(b.moveTo||b.href||b.url||b.scene)if(b.url&&!b.moveTo){var c=b.urlTarget,d=q.byId(c),c=d&&d.containerNode||f.byId(c);c||(c=(d=g.getEnclosingView(a.target))&&d.domNode.parentNode||h.body());if((a=q.getEnclosingWidget(a.target))&&a.callback)b.context=a,b.method=a.callback;this.openExternalView(b,c)}else if(b.href)if(b.hrefTarget&&"_self"!=b.hrefTarget)h.global.open(b.href,b.hrefTarget);else{for(d=g.getEnclosingView(a.target);d;d=g.getParentView(d))c=d;c&&c.performTransition(null,
b.transitionDir,b.transition,a.target,function(){location.href=b.href})}else if(b.scene)k.publish("/dojox/mobile/app/pushScene",[b.scene]);else{var e=this.findTransitionViews(b.moveTo),c=e[0],d=e[1],e=e[2];!location.hash&&!b.hashchange&&(g.initialView=c);b.moveTo&&d&&(b.moveTo=("#"===b.moveTo.charAt(0)?"#"+d.id:d.id)+e);if(c&&!(b.moveTo&&c===q.byId(b.moveTo.replace(/^#?([^&?]+).*/,"$1")))){if((a=q.getEnclosingWidget(a.target))&&a.callback)b.context=a,b.method=a.callback;c.performTransition(b)}}}}});
c._instance=new c;c.getInstance=function(){return c._instance};return c})},"dojo/Stateful":function(){define(["./_base/declare","./_base/lang","./_base/array","./when"],function(l,m,k,e){return l("dojo.Stateful",null,{_attrPairNames:{},_getAttrNames:function(b){var e=this._attrPairNames;return e[b]?e[b]:e[b]={s:"_"+b+"Setter",g:"_"+b+"Getter"}},postscript:function(b){b&&this.set(b)},_get:function(b,e){return"function"===typeof this[e.g]?this[e.g]():this[b]},get:function(b){return this._get(b,this._getAttrNames(b))},
set:function(b,h){if("object"===typeof b){for(var d in b)b.hasOwnProperty(d)&&"_watchCallbacks"!=d&&this.set(d,b[d]);return this}d=this._getAttrNames(b);var f=this._get(b,d);d=this[d.s];var k;"function"===typeof d?k=d.apply(this,Array.prototype.slice.call(arguments,1)):this[b]=h;if(this._watchCallbacks){var l=this;e(k,function(){l._watchCallbacks(b,f,h)})}return this},_changeAttrValue:function(b,e){var d=this.get(b);this[b]=e;this._watchCallbacks&&this._watchCallbacks(b,d,e);return this},watch:function(b,
e){var d=this._watchCallbacks;if(!d)var f=this,d=this._watchCallbacks=function(b,e,h,k){var a=function(a){if(a){a=a.slice();for(var c=0,d=a.length;c<d;c++)a[c].call(f,b,e,h)}};a(d["_"+b]);k||a(d["*"])};!e&&"function"===typeof b?(e=b,b="*"):b="_"+b;var l=d[b];"object"!==typeof l&&(l=d[b]=[]);l.push(e);var m={};m.unwatch=m.remove=function(){var b=k.indexOf(l,e);-1<b&&l.splice(b,1)};return m}})})},"dojox/mobile/RoundRectCategory":function(){define("dojo/_base/declare dojo/_base/window dojo/dom-construct dijit/_Contained dijit/_WidgetBase dojo/has dojo/has!dojo-bidi?dojox/mobile/bidi/RoundRectCategory".split(" "),
function(l,m,k,e,b,h,d){m=l(h("dojo-bidi")?"dojox.mobile.NonBidiRoundRectCategory":"dojox.mobile.RoundRectCategory",[b,e],{label:"",tag:"h2",baseClass:"mblRoundRectCategory",buildRendering:function(){var b=this.domNode=this.containerNode=this.srcNodeRef||k.create(this.tag);this.inherited(arguments);!this.label&&(1===b.childNodes.length&&3===b.firstChild.nodeType)&&(this.label=b.firstChild.nodeValue)},_setLabelAttr:function(b){this.label=b;this.domNode.innerHTML=this._cv?this._cv(b):b}});return h("dojo-bidi")?
l("dojox.mobile.RoundRectCategory",[m,d]):m})},"dojox/mobile/ToolBarButton":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/window dojo/dom-class dojo/dom-construct dojo/dom-style dojo/dom-attr ./sniff ./_ItemBase dojo/has!dojo-bidi?dojox/mobile/bidi/ToolBarButton".split(" "),function(l,m,k,e,b,h,d,f,t,p){k=l(f("dojo-bidi")?"dojox.mobile.NonBidiToolBarButton":"dojox.mobile.ToolBarButton",t,{selected:!1,arrow:"",light:!0,defaultColor:"mblColorDefault",selColor:"mblColorDefaultSel",
baseClass:"mblToolBarButton",_selStartMethod:"touch",_selEndMethod:"touch",buildRendering:function(){!this.label&&this.srcNodeRef&&(this.label=this.srcNodeRef.innerHTML);this.label=m.trim(this.label);this.domNode=this.srcNodeRef&&"SPAN"===this.srcNodeRef.tagName?this.srcNodeRef:b.create("span");d.set(this.domNode,"role","button");this.inherited(arguments);if(this.light&&!this.arrow&&(!this.icon||!this.label))this.labelNode=this.tableNode=this.bodyNode=this.iconParentNode=this.domNode,e.add(this.domNode,
this.defaultColor+" mblToolBarButtonBody"+(this.icon?" mblToolBarButtonLightIcon":" mblToolBarButtonLightText"));else{this.domNode.innerHTML="";if("left"===this.arrow||"right"===this.arrow)this.arrowNode=b.create("span",{className:"mblToolBarButtonArrow mblToolBarButton"+("left"===this.arrow?"Left":"Right")+"Arrow "+(10>f("ie")?"":this.defaultColor+" "+this.defaultColor+"45")},this.domNode),e.add(this.domNode,"mblToolBarButtonHas"+("left"===this.arrow?"Left":"Right")+"Arrow");this.bodyNode=b.create("span",
{className:"mblToolBarButtonBody"},this.domNode);this.tableNode=b.create("table",{cellPadding:"0",cellSpacing:"0",border:"0",role:"presentation"},this.bodyNode);!this.label&&this.arrow&&(this.tableNode.className="mblToolBarButtonText");var h=this.tableNode.insertRow(-1);this.iconParentNode=h.insertCell(-1);this.labelNode=h.insertCell(-1);this.iconParentNode.className="mblToolBarButtonIcon";this.labelNode.className="mblToolBarButtonLabel";this.icon&&("none"!==this.icon&&this.label)&&(e.add(this.domNode,
"mblToolBarButtonHasIcon"),e.add(this.bodyNode,"mblToolBarButtonLabeledIcon"));e.add(this.bodyNode,this.defaultColor)}},startup:function(){this._started||(this.connect(this.domNode,"onkeydown","_onClick"),this.inherited(arguments),this._isOnLine||(this._isOnLine=!0,this.set("icon",void 0!==this._pendingIcon?this._pendingIcon:this.icon),delete this._pendingIcon))},_onClick:function(b){(!b||!("keydown"===b.type&&13!==b.keyCode))&&!1!==this.onClick(b)&&this.defaultClickAction(b)},onClick:function(){},
_setLabelAttr:function(b){this.inherited(arguments);e.toggle(this.tableNode,"mblToolBarButtonText",b||this.arrow)},_setSelectedAttr:function(b){this.inherited(arguments);if(b){if(e.replace(this.bodyNode,this.selColor,this.defaultColor),!(10>f("ie"))&&this.arrowNode){var d=this.selColor,h=this.defaultColor;e.replace(this.arrowNode,d+" "+d+"45",h+" "+h+"45")}}else e.replace(this.bodyNode,this.defaultColor,this.selColor),!(10>f("ie"))&&this.arrowNode&&(d=this.defaultColor,h=this.selColor,e.replace(this.arrowNode,
d+" "+d+"45",h+" "+h+"45"));e.toggle(this.domNode,"mblToolBarButtonSelected",b);e.toggle(this.bodyNode,"mblToolBarButtonBodySelected",b)}});return f("dojo-bidi")?l("dojox.mobile.ToolBarButton",[k,p]):k})},"*noref":1}});define("dojox/mobile",[".","dojo/_base/lang","dojox/mobile/_base"],function(l,m,k){m.getObject("mobile",!0,l);return l.mobile});