define({
  root: ({
    styleText: "Choose a style for the swipe tool.",
    vertical: "Vertical bar",
    horizontal: "Horizontal bar",
    scope: "Spyglass",
    layerText: "Select the layer you want to swipe by default.",
    spyglassText: "Select the layer to appear within the spyglass by default.",
    layerHint: "Note: If the layer is hidded by upper layers, swipe won't have any effect."
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});