define(
   ({
    addDistance: "Lisää pituusyksikkö",
    addArea: "Lisää pinta-alayksikkö",
    label: "Tunnusteksti",
    abbr: "Lyhenne",
    conversion: "Muunto",
    actions: "Toimet",
    areaUnits: "Pinta-alayksiköt",
    distanceUnits: "Pituusyksiköt",
    kilometers: "Kilometriä",
    miles: "Mailia",
    meters: "Metriä",
    feet: "Jalkaa",
    yards: "Jaardia",
    squareKilometers: "Neliökilometriä",
    squareMiles: "Neliömailia",
    acres: "Eekkeriä",
    hectares: "Hehtaaria",
    squareMeters: "Neliömetriä",
    squareFeet: "Neliöjalkaa",
    squareYards: "Neliöjaardia",
    distance: "Etäisyydet",
    area: "Alueet",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "sq km",
    squareMilesAbbreviation: "sq mi",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "sq m",
    squareFeetAbbreviation: "sq ft",
    squareYardsAbbreviation: "sq yd"
  })
);