define(
   ({
    showArcgisBasemaps: "Bao gồm các bản đồ nền của Cổng thông tin",
    settings: "Thiết lập",
    add: "Bấm để Thêm Bản đồ nền Mới",
    edit: "Thuộc tính",
    title: "Tiêu đề",
    titlePH: "Tiêu đề Bản đồ nền",
    thumbnail: "Hình thu nhỏ",
    thumbnailHint: "Bấm vào hình ảnh để cập nhật",
    url: "URL",
    urlPH: "URL của Lớp",
    addlayer: "Thêm Bản đồ nền",
    actions: "Các hành động",
    warning: "Đầu vào không đúng",
    save: "Quay lại và Lưu",
    back: "Quay lại và Hủy",
    addUrl: "Thêm URL",
    autoCheck: "Tự động Kiểm tra",
    checking: "Đang kiểm tra...",
    ok: "OK",
    cancel: "Hủy",
    result: "Đã lưu thành công",
    spError: "Tất cả các bản đồ nền được thêm vào bộ sưu tập phải có cùng một tham chiếu không gian.",
    invalidTitle1:"Bản đồ nền '",
    invalidTitle2:"đã tồn tại. Vui lòng chọn một tiêu đề khác.",
    invalidBasemapUrl1: "Không thể sử dụng loại lớp này làm bản đồ nền.",
    invalidBasemapUrl2: "Tham chiếu không gian khác nhau so với bản đồ hiện tại.",
    addBaselayer: "Thêm Lớp Bản đồ nền"
  })
);