define(
   ({
    _widgetLabel: "Zeichnen",
    selectDrawMode: "Zeichenmodus auswählen",
    clear: "Löschen",
    point: "Punkt",
    line: "Linie",
    polyline: "Polylinie",
    freehandPolyline: "Freihand-Polylinie",
    triangle: "Dreieck",
    extent: "Envelope",
    circle: "Kreis",
    ellipse: "Ellipse",
    polygon: "Polygon",
    freehandPolygon: "Freihand-Polygon",
    text: "Text",
    style: "Style",
    alpha: "Transparenz",
    width: "Breite",
    size: "Größe",
    color: "Farbe",
    markerColor: "Marker-Farbe",
    outlineColor: "Umrissfarbe",
    lineColor: "Linienfarbe",
    fillColor: "Füllfarbe",
    showMeasurements: "Messwerte anzeigen",
    areaUnits: "Flächeneinheiten",
    distanceUnits: "Entfernungseinheiten",
    kilometers: "Kilometer",
    miles: "Meilen",
    meters: "Meter",
    feet: "Fuß",
    yards: "Yards",
    squareKilometers: "Quadratkilometer",
    squareMiles: "Quadratmeilen",
    acres: "Acres",
    hectares: "Hektar",
    squareMeters: "Quadratmeter",
    squareFeet: "Quadratfuß",
    squareYards: "Quadratyard",
    undo: "Rückgängig",
    redo: "Wiederholen"
  })
);