// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/metadata/editor/templates/Editor.html":'\x3cdiv class\x3d"gxeEditor" data-dojo-attach-point\x3d"containerNode"\x3e\r\n\t\x3cdiv data-dojo-type\x3d"esri/dijit/metadata/editor/PrimaryToolbar" data-dojo-attach-point\x3d"primaryToolbar"\x3e\x3c/div\x3e\r\n\t\x3cdiv class\x3d"gxeCanvas" data-dojo-attach-point\x3d"canvasNode"\x3e\r\n\t\t\x3cdiv data-dojo-type\x3d"esri/dijit/metadata/editor/ValidationPane" data-dojo-attach-point\x3d"validationPane" style\x3d"display:none;"\x3e\x3c/div\x3e\r\n\t  \x3cdiv data-dojo-type\x3d"esri/dijit/metadata/editor/ViewDocumentPane" data-dojo-attach-point\x3d"viewDocumentPane" style\x3d"display:none;"\x3e\x3c/div\x3e\r\n\t  \x3cdiv data-dojo-type\x3d"esri/dijit/metadata/editor/XmlPane" data-dojo-attach-point\x3d"xmlPane" style\x3d"display:none;"\x3e\x3c/div\x3e\r\n\t  \x3cdiv data-dojo-type\x3d"esri/dijit/metadata/editor/EditDocumentPane" data-dojo-attach-point\x3d"editDocumentPane" style\x3d"display:none;"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/metadata/editor/Editor","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/on dojo/keys dojo/_base/event dojo/dom-class dojo/dom-construct dojo/dom-style dojo/has dijit/Viewport ../context/GxeAdaptor ../context/GxeContext ../base/etc/viewOnlyUtil ../base/XDocument ../base/xml/XmlImporter ./EditorResizeMixin ../base/Templated dojo/text!./templates/Editor.html esri/kernel ./PrimaryToolbar ./ValidationPane ./EditDocumentPane ./ViewDocumentPane ./XmlPane ../../../dijit/Geocoder".split(" "),
function(c,d,t,k,n,u,v,w,f,x,y,z,A,B,C,D,E,F,G,H){c=c([F,E],{dialogBroker:null,gxeAdaptor:null,gxeContext:null,templateString:G,postCreate:function(){this.inherited(arguments);this.gxeAdaptor||(this.gxeAdaptor=new z);this.gxeContext||(this.gxeContext=new A);this.primaryToolbar.editor=this;this.primaryToolbar.lastSavedXml=this.gxeAdaptor.getOriginalXml();this.validationPane.editor=this;this.xmlPane.setXml(this.gxeAdaptor.getOriginalXml(),"metadata");this.primaryToolbar.initialize();this.dialogBroker||
this.own(y.on("resize",d.hitch(this,"resize")));this.isLeftToRight()||v.add(this.domNode,"gxeRtl");this.own(k(document,"keydown, keypress",d.hitch(this,function(a){a.keyCode===n.BACKSPACE&&void 0===a.target.size&&void 0===a.target.rows&&u.stop(a)})))},destroy:function(){try{this.viewDocumentPane.gxeDocument&&this.viewDocumentPane.gxeDocument.rootDescriptor&&this.viewDocumentPane.gxeDocument.rootDescriptor.destroyRecursive(!1)}catch(a){console.error(a)}try{this.editDocumentPane.gxeDocument&&this.editDocumentPane.gxeDocument.rootDescriptor&&
this.editDocumentPane.gxeDocument.rootDescriptor.destroyRecursive(!1)}catch(l){console.error(l)}this.inherited(arguments)},getEditDocument:function(){return this.editDocumentPane.gxeDocument},getViewDocument:function(){return this.viewDocumentPane.gxeDocument},initializeView:function(){this.primaryToolbar.initializeView()},_loadDocumentPane:function(a,l,e,c,d){var b=null,g=!1,p=!1,m=new t;a===this.editDocumentPane?this.validationPane.clearMessages():g=!0;try{var q,h=a.gxeDocument,r=w.create("div",
{},a.rootContainer),b=new C({gxeContext:this.gxeContext,isViewOnly:g});b.initialize(l,r);e&&(q=new D,q.importDocument(b,e,c));h&&(f.set(h.rootDescriptor.domNode,"display","none"),h.rootDescriptor&&h.rootDescriptor.destroyRecursive(!1));p=!0;a.gxeDocument=b;f.set(r,"display","");f.set(a.domNode,"display","");g&&B.applyViewOnly(b);try{g?this.gxeAdaptor.afterViewDocumentLoad(b,d):this.gxeAdaptor.afterEditDocumentLoad(b,e,c,d)}catch(k){console.error(k)}m.resolve(b);this.primaryToolbar.updateUI()}catch(s){try{b&&
(b.rootDescriptor&&!p)&&(f.set(b.rootDescriptor.domNode,"display","none"),b.rootDescriptor.destroyRecursive(!1))}catch(n){}console.error("Error constructing document");console.error(s);m.reject(s)}return m},loadEditor:function(a,c,e,d){return this._loadDocumentPane(this.editDocumentPane,a,c,e,d)},loadView:function(a,c,d){return this._loadDocumentPane(this.viewDocumentPane,a,c,!1,d)}});x("extend-esri")&&d.setObject("dijit.metadata.editor.Editor",c,H);return c});