// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/HeatmapSlider/templates/HeatmapSlider.html":'\x3cdiv class\x3d"${baseClass}"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_containerNode"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_titleNode"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_sliderNode"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_scaleNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/HeatmapSlider","../kernel dijit/_OnDijitClickMixin dijit/_TemplatedMixin dijit/_WidgetBase ../dijit/RendererSlider dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/dom-style dojo/Evented dojo/has dojox/gfx dojo/i18n!../nls/jsapi dojo/text!./HeatmapSlider/templates/HeatmapSlider.html".split(" "),function(g,c,h,k,l,e,m,b,n,p,q,r,f,s){c=m("esri.dijit.HeatmapSlider",[k,h,c,p],{baseClass:"esriHeatmapSlider",basePath:require.toUrl("esri/dijit/HeatmapSlider/"),templateString:s,
domNode:null,containerNode:null,handles:null,_rampWidthDefault:25,showLabels:null,showTicks:null,showHandles:null,_rampNode:null,_sliderHeight:null,_colorRampSurface:null,_rect:null,_updateTimer:null,constructor:function(a,d){this.inherited(arguments);d&&(this.domNode=d,this.containerNode=this._containerNode,this.rampWidth=a.rampWidth||this._rampWidthDefault,this.handles=a.handles||[3,15],this.showLabels=a.showLabels||!0,this.showTicks=a.showTicks||!0,this.showHandles=a.showHandles||!0,this.colorStops=
a.colorStops,this.minSliderValue=0,this.maxSliderValue=1,this.values=[this.colorStops[3].ratio,this.colorStops[15].ratio])},postCreate:function(){this.inherited(arguments)},startup:function(){this.inherited(arguments);this._slider=new l({type:"HeatmapSlider",values:this.values,minimum:this.minSliderValue,maximum:this.maxSliderValue,precision:2,showLabels:this.showLabels,showTicks:this.showTicks,showHandles:this.showHandles,minLabel:f.widgets.rendererSlider.low,maxLabel:f.widgets.rendererSlider.high},
this._sliderNode);this._slider.startup();this._rampNode=this._slider._sliderAreaRight;this._sliderHeight=n.get(this._rampNode,"height")||155;this._createSVGSurfaces();this._slider.on("slide",b.hitch(this,function(a){this._updateColorStops(a.values[0],a.values[1]);this._fillRamp()}));this._slider.on("change",b.hitch(this,function(a){this.values=[a.values[0],a.values[1]];this.emit("change",b.clone(this.colorStops))}));this._slider.on("handle-value-change",b.hitch(this,function(a){this._updateRendererSlider()}));
this._slider.on("data-value-change",b.hitch(this,function(a){this._updateRendererSlider()}));this._slider.on("stop",b.hitch(this,function(a){this.emit("handle-value-change",b.clone(this.colorStops))}));this.watch("colorStops",this._updateTimeout)},_createSVGSurfaces:function(){this._colorRampSurface=r.createSurface(this._rampNode,this.rampWidth,this._sliderHeight);this._rect=this._colorRampSurface.createRect(this._colorRampSurface.getDimensions()).setStroke("#888");this._fillRamp()},_updateTimeout:function(){var a=
this;clearTimeout(this._updateTimer);this._updateTimer=setTimeout(function(){var d=a;a=null;clearTimeout(d._updateTimer);d._updateRendererSlider()},0)},_updateRendererSlider:function(){this.values=[this.colorStops[3].ratio,this.colorStops[15].ratio];this._slider.set("values",this.values);this._slider._reset();this._slider._updateRoundedLabels();this._slider._generateMoveables();this._clearRect();this._createSVGSurfaces()},_clearRect:function(){this._colorRampSurface.destroy()},destroy:function(){this.inherited(arguments);
this._slider.destroy()},_updateColorStops:function(a,d){e.forEach(this.colorStops,b.hitch(this,function(b,c){2<c&&(b.ratio=a+(d-a)*((c-3)/12),3===c&&b.ratio<this.colorStops[2].ratio&&(b.ratio=this.colorStops[2].ratio))}))},_fillRamp:function(){var a=this.colorStops.slice(0);e.forEach(a,function(a){a.offset=1-a.ratio});a.reverse();this._rect.setFill({type:"linear",x1:0,y1:0,x2:0,y2:200/0.99,colors:a})}});q("extend-esri")&&b.setObject("dijit.HeatmapSlider",c,g);return c});