// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"esri/numberUtils":function(){define(["dojo/has","dojo/number","dojo/i18n!dojo/cldr/nls/number","./kernel"],function(x,I,s,k){var p=function(k,m){return k-m},w={_reNumber:/^-?(\d+)(\.(\d+))?$/i,getDigits:function(k){var m=String(k),h=m.match(w._reNumber);k={integer:0,fractional:0};h&&h[1]?(k.integer=h[1].split("").length,k.fractional=h[3]?h[3].split("").length:0):-1<m.toLowerCase().indexOf("e")&&(h=m.split("e"),m=h[0],h=h[1],m&&h&&(m=Number(m),h=Number(h),(k=0<h)||(h=Math.abs(h)),
m=w.getDigits(m),k?(m.integer+=h,m.fractional=h>m.fractional?0:m.fractional-h):(m.fractional+=h,m.integer=h>m.integer?1:m.integer-h),k=m));return k},getFixedNumbers:function(k,m){var h,p;h=Number(k.toFixed(m));p=h<k?h+1/Math.pow(10,m):h-1/Math.pow(10,m);return[h,p]},getPctChange:function(k,m,h,p){var s={prev:null,next:null},q;null!=h&&(q=k-h,h=m-h-q,s.prev=Math.floor(Math.abs(100*h/q)));null!=p&&(q=p-k,h=p-m-q,s.next=Math.floor(Math.abs(100*h/q)));return s},round:function(k,m){var h=k.slice(0),s,
M,q,g,t,y,D,x,u,I=!m||null==m.tolerance?2:m.tolerance,z=m&&m.indexes;if(z)z.sort(p);else{z=[];for(y=0;y<h.length;y++)z.push(y)}for(y=0;y<z.length;y++)if(u=z[y],s=h[u],M=0===u?null:h[u-1],q=u===h.length-1?null:h[u+1],g=w.getDigits(s),g=g.fractional){D=0;for(x=!1;D<=g&&!x;)t=w.getFixedNumbers(s,D),t=t[0],x=w.hasMinimalChange(s,t,M,q,I),D++;x&&(h[u]=t)}return h},hasMinimalChange:function(k,m,h,p,s){k=w.getPctChange(k,m,h,p);m=null==k.prev||k.prev<=s;h=null==k.next||k.next<=s;return m&&h||k.prev+k.next<=
2*s},_reAllZeros:RegExp("\\"+s.decimal+"0+$","g"),_reSomeZeros:RegExp("(\\d)0*$","g"),format:function(k,m){m=m||{places:20,round:-1};var h=I.format(k,m);h&&(h=h.replace(w._reSomeZeros,"$1").replace(w._reAllZeros,""));return h}};x("extend-esri")&&(k.numberUtils=w);return w})},"*noref":1}});
define("esri/dijit/Legend","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/_base/Color dojo/has dojo/sniff dojo/DeferredList dojo/json dojo/dom dojo/dom-construct dojo/dom-style dijit/_Widget dojox/gfx dojox/gfx/matrix dojox/html/entities ../kernel ../config ../request ../lang ../numberUtils ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/ClassBreaksRenderer ../renderers/ScaleDependentRenderer ../renderers/DotDensityRenderer ../renderers/TemporalRenderer ../renderers/VectorFieldRenderer ../renderers/HeatmapRenderer ../symbols/PictureFillSymbol ../symbols/jsonUtils ./_EventedWidget dojo/i18n!../nls/jsapi".split(" "),function(x,
I,s,k,p,w,L,m,h,T,M,q,g,t,y,D,U,u,V,z,Q,J,B,H,N,K,W,X,Y,P,R,Z,O,$,S){var E=I([$,y],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,dotDensitySwatchSize:26,dotCoverage:75,gradientHeight:30,defaultText:"Aa",gradientWidth:34,colorRampBorder:"1px solid",_specialChars:{lt:"\x3c",gt:"\x3e"},_ieTimer:100,_isRightToLeft:!1,_align:null,_legendAlign:null,constructor:function(a,b){s.mixin(this,S.widgets.legend);this._i18n=S.widgets.legend;a=a||{};a.map?
b?(this.map=a.map,this.layerInfos=a.layerInfos,this._respectCurrentMapScale=!1===a.respectCurrentMapScale?!1:!0,this._respectVisibility=!1===a.respectVisibility?!1:!0,this.arrangement=a.arrangement===E.ALIGN_RIGHT?E.ALIGN_RIGHT:E.ALIGN_LEFT,this.arrangement===E.ALIGN_RIGHT&&(this.alignRight=!0),this.autoUpdate=!1===a.autoUpdate?!1:!0,this._surfaceItems=[]):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},
postMixInProperties:function(){this.inherited(arguments);var a=["ar","he"],b,c;for(b=0;b<a.length;b+=1)c=a[b],x.locale&&-1!==x.locale.indexOf(c)&&(-1!==x.locale.indexOf("-")?-1!==x.locale.indexOf(c+"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);this._isRightToLeft?(this._align=this.alignRight?"left":"right",this._legendAlign=this.alignRight?"esriLegendLeft":"esriLegendRight"):(this._align=this.alignRight?"right":"left",this._legendAlign=this.alignRight?"esriLegendRight":"esriLegendLeft")},
startup:function(){this.inherited(arguments);this._initialize();9>m("ie")&&(this._repaintItems=s.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();this._removeHoverHandlers();this.inherited(arguments)},refresh:function(a){if(this.domNode){a?(this.layerInfos=a,this.layers=[],k.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?
!0:!1,a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this)):this.useAllMapLayers&&(this.layers=this.layerInfos=null);for(a=this.domNode.children.length-1;0<=a;a--)g.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",
_initialize:function(){this.layerInfos&&(this.layers=[],k.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this));this.useAllMapLayers=
!1;if(!this.layers){this.useAllMapLayers=!0;this.layers=[];var a=[],b=[];k.forEach(this.map.layerIds,function(c){c=this.map.getLayer(c);var d;this._isSupportedLayerType(c)&&(c.arcgisProps&&c.arcgisProps.title&&(c._titleForLegend=c.arcgisProps.title),this.layers.push(c));"esri.layers.KMLLayer"==c.declaredClass&&(d=c.getLayers(),k.forEach(d,function(b){a.push(b.id)},this));"esri.layers.GeoRSSLayer"==c.declaredClass&&(d=c.getFeatureLayers(),k.forEach(d,function(a){b.push(a.id)},this))},this);k.forEach(this.map.graphicsLayerIds,
function(c){var d=this.map.getLayer(c);-1==k.indexOf(a,c)&&-1==k.indexOf(b,c)&&(this._isSupportedLayerType(d)&&d._params&&d._params.drawMode)&&(d.arcgisProps&&d.arcgisProps.title&&(d._titleForLegend=d.arcgisProps.title),this.layers.push(d))},this)}this._createLegend()},_activate:function(){this._deactivate();this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=p.connect(this.map,"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=p.connect(this.map,"onLayerAdd",
this,"_updateAllMapLayers"),this._olrConnect=p.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=p.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),k.forEach(this.layers,function(a){a.ovcConnect=p.connect(a,"onVisibilityChange",this,"_refreshLayers");a.oscConnect=p.connect(a,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass&&a.supportsDynamicLayers&&(a.odcConnect=p.connect(a,"_onDynamicLayersChange",
s.hitch(this,"_updateDynamicLayers",a)));"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&(a.oirConnect=p.connect(a,"onRenderingChange",s.partial(this._updateImageServiceLayers,this,a)));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&(a.oivrConnect=p.connect(a,"onRendererChange",s.hitch(this,"_refreshLayers")))},this))},_deactivate:function(){this._ozeConnect&&p.disconnect(this._ozeConnect);this._olaConnect&&p.disconnect(this._olaConnect);this._olroConnect&&p.disconnect(this._olroConnect);
this._olrConnect&&p.disconnect(this._olrConnect);k.forEach(this.layers,function(a){a.ovcConnect&&p.disconnect(a.ovcConnect);a.oscConnect&&p.disconnect(a.oscConnect);a.odcConnect&&p.disconnect(a.odcConnect);a.oirConnect&&p.disconnect(a.oirConnect);a.oivrConnect&&p.disconnect(a.oivrConnect)},this)},_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},_updateImageServiceLayers:function(a,b){delete b.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},
_updateAllMapLayers:function(){this.layers=[];k.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this.layers.push(a)},this);k.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&(a._params&&a._params.drawMode)&&this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=!1;t.set(this.domNode,"position","relative");g.create("div",{id:this.id+"_msg",className:"esriLegendMsg",innerHTML:this.NLS_creatingLegend+
"..."},this.domNode);var b=[];k.forEach(this.layers,function(c){if("esri.layers.KMLLayer"==c.declaredClass||"esri.layers.GeoRSSLayer"==c.declaredClass){var e;c.loaded?("esri.layers.KMLLayer"==c.declaredClass?e=c.getLayers():"esri.layers.GeoRSSLayer"==c.declaredClass&&(e=c.getFeatureLayers(),c._hideLayersInLegend&&(e=k.filter(e,function(a){return-1==k.indexOf(c._hideLayersInLegend,a.id)}))),k.forEach(e,function(a){"esri.layers.FeatureLayer"==a.declaredClass&&c._titleForLegend&&(a._titleForLegend=c._titleForLegend+
" - ","esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==a.geometryType?a._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_polygons),b.push(a))},this)):p.connect(c,"onLoad",s.hitch(this,function(){this.refresh(this.layerInfos)}))}else if("esri.layers.WMSLayer"===c.declaredClass)if(c.loaded){if((!this._respectVisibility||this._respectVisibility&&c.visible)&&0<c.layerInfos.length&&k.some(c.layerInfos,function(a){return a.legendURL})){var f=
!1;k.forEach(c.layerInfos,function(b){b.legendURL&&-1<k.indexOf(c.visibleLayers,b.name)&&(f||(g.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+(c._titleForLegend||c.name||c.id)+"\x3c/span\x3e"},this.domNode),f=!0),g.create("div",{innerHTML:"\x3cimg src\x3d'"+b.legendURL+"'/\x3e"},this.domNode),a=!0)},this)}}else p.connect(c,"onLoad",s.hitch(this,function(){this.refresh(this.layerInfos)}));else b.push(c)},this);var c=[];k.forEach(b,function(a){if(a.loaded){if((!this._respectVisibility||
this._respectVisibility&&a.visible)&&(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var b=g.create("div",{id:this.id+"_"+a.id,style:{display:"none"},"class":"esriLegendService"});g.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},g.create("td",{align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%"},b)))));g.place(b,this.id,"first");a.legendResponse||a.renderer?this._createLegendForLayer(a):c.push(this._legendRequest(a))}}else var f=
p.connect(a,"onLoad",this,function(a){p.disconnect(f);f=null;this.refresh()})},this);0===c.length&&!a?(q.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate()):(new T(c)).addCallback(s.hitch(this,function(b){a?q.byId(this.id+"_msg").innerHTML="":q.byId(this.id+"_msg").innerHTML=this.NLS_noLegend;this._activate()}))},_createLegendForLayer:function(a){if(a.legendResponse||a.renderer){var b=!1;if(a.legendResponse){var c=a.dynamicLayerInfos||a.layerInfos;c&&c.length?k.forEach(c,function(c,
e){if(!a._hideLayersInLegend||-1==k.indexOf(a._hideLayersInLegend,c.id)){var f=this._buildLegendItems(a,c,e);b=b||f}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(b=this._buildLegendItems(a,{id:0,name:null,title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(c=a.url?a.url.substring(a.url.lastIndexOf("/")+1,a.url.length):"fc_"+a.id,b=this._buildLegendItems(a,{id:c,name:null,subLayerIds:null,parentLayerId:-1},0));b&&(t.set(q.byId(this.id+"_"+a.id),"display","block"),
t.set(q.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=a.version?this._legendRequestServer(a):this._legendRequestTools(a);p.connect(a,"onLoad",s.hitch(this,"_legendRequest"))},_legendRequestServer:function(a){var b=a.url,c=b.indexOf("?"),b=-1<c?b.substring(0,c)+"/legend"+b.substring(c):b+"/legend";(c=a._getToken())&&(b+="?token\x3d"+c);var d=s.hitch(this,"_processLegendResponse"),c={f:"json"};a._params.dynamicLayers&&(c.dynamicLayers=M.stringify(this._createDynamicLayers(a)),
"[{}]"===c.dynamicLayers&&(c.dynamicLayers="[]"));a._params.bandIds&&(c.bandIds=a._params.bandIds);a._params.renderingRule&&(c.renderingRule=a._params.renderingRule);return Q({url:b,content:c,callbackParamName:"callback",load:function(b,c){d(a,b,c)},error:z.defaults.io.errorHandler})},_legendRequestTools:function(a){var b=a.url.toLowerCase().indexOf("/rest/"),b=a.url.substring(0,b)+a.url.substring(b+5,a.url.length),b=this._legendUrl+"?soapUrl\x3d"+window.escape(b);if(!m("ie")||8<m("ie"))b+="\x26returnbytes\x3dtrue";
var c=s.hitch(this,"_processLegendResponse");return Q({url:b,content:{f:"json"},callbackParamName:"callback",load:function(b,e){c(a,b,e)},error:z.defaults.io.errorHandler})},_processLegendResponse:function(a,b){b&&b.layers?(a.legendResponse=b,q.byId(this.id+"_"+a.id)&&g.empty(q.byId(this.id+"_"+a.id)),g.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},g.create("td",{align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%"},q.byId(this.id+
"_"+a.id)))))),this._createLegendForLayer(a)):console.log("Legend could not get generated for "+a.url+": "+w.toJson(b))},_buildLegendItems:function(a,b,c){var d=!1,e=q.byId(this.id+"_"+a.id),f=b.parentLayerId;if(b.subLayerIds)a=g.create("div",{id:this.id+"_"+a.id+"_"+b.id+"_group",style:{display:"none"},"class":-1==f?0<c?"esriLegendGroupLayer":"":this._legendAlign},-1==f?e:q.byId(this.id+"_"+a.id+"_"+f+"_group")),g.create("td",{innerHTML:u.encode(b.name),align:this._align},g.create("tr",{},g.create("tbody",
{},g.create("table",{width:"95%","class":"esriLegendLayerLabel"},a))));else{if(a.visibleLayers&&-1==(","+a.visibleLayers+",").indexOf(","+b.id+","))return d;c=g.create("div",{id:this.id+"_"+a.id+"_"+b.id,style:{display:"none"},"class":-1<f?this._legendAlign:""},-1==f?e:q.byId(this.id+"_"+a.id+"_"+f+"_group"));g.create("td",{innerHTML:u.encode(b.name)||"",align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%","class":"esriLegendLayerLabel"},c))));a.legendResponse?d=d||
this._buildLegendItems_Tools(a,b,c):a.renderer&&(d=d||this._buildLegendItems_Renderer(a,b,c))}return d},_buildLegendItems_Tools:function(a,b,c){var d=b.parentLayerId,e=this.map.getScale(),f=!1,r=function(a,b){var c,d;for(c=0;c<a.length;c++)if(b.dynamicLayerInfos)for(d=0;d<b.dynamicLayerInfos[d].length;d++){if(b.dynamicLayerInfos[d].mapLayerId==a[c].layerId)return a[c]}else if(b.id==a[c].layerId)return a[c];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(a,
b,e)){var v=!0;if("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISMapServiceLayer"===a.declaredClass){var n=this._getEffectiveScale(a,b);if(n.minScale&&n.minScale<e||n.maxScale&&n.maxScale>e)v=!1}if(v){var e=r(a.legendResponse.layers,b),l=e.legendType,m=e.legend;if(m){c=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);var h=g.create("tbody",{},c);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(c,a,b);k.forEach(m,function(c){if(!(10.1<=
a.version&&!c.values&&1<m.length&&(a._hideDefaultSymbol||"\x3call other values\x3e"===c.label||!c.label&&!("esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.3<=a.version))))if(c.url&&0===c.url.indexOf("http")||c.imageData&&0<c.imageData.length)f=!0,this._buildRow_Tools(c,h,a,b.id,l)},this)}}}f&&(t.set(q.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<d&&(t.set(q.byId(this.id+"_"+a.id+"_"+d+"_group"),"display","block"),this._findParentGroup(a.id,a,d)));return f},_buildRow_Tools:function(a,
b,c,d,e){var f=g.create("tr",{},b),r;this.alignRight?(b=g.create("td",{align:this._isRightToLeft?"left":"right"},f),r=g.create("td",{align:this._isRightToLeft?"left":"right",width:35},f)):(r=g.create("td",{width:35},f),b=g.create("td",{},f));f=a.url;(!m("ie")||9<=m("ie")||9>m("ie")&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass)&&a.imageData&&0<a.imageData.length?f="data:image/png;base64,"+a.imageData:0!==a.url.indexOf("http")&&(f=c.url+"/"+d+"/images/"+a.url,(d=c._getToken())&&(f+="?token\x3d"+
d));d=g.create("img",{src:f,border:0,style:"opacity:"+c.opacity},r);a=g.create("td",{innerHTML:u.encode(a.label),align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%",dir:"ltr"},b))));e&&("Stretched"===e&&10.3<=c.version&&"esri.layers.ArcGISImageServiceLayer"===c.declaredClass)&&(a.style.verticalAlign="top",a.style.lineHeight="1",d.style.marginBottom="-1px",d.style.display="block",b.style.verticalAlign="top");9>m("ie")&&(d.style.filter="alpha(opacity\x3d"+100*c.opacity+
")")},_getVariable:function(a,b){var c;a&&(c=(c=a.getVisualVariablesForType(b))&&c[0]);return c},_getFieldAlias:function(a,b){var c=b.infoTemplate,c=c&&c.getFieldInfo&&c.getFieldInfo(a),d=b.getField(a),e=c||d,f="";e&&(f=c&&c.label||d&&d.alias||e.name||e.fieldName);return f},_getDefaultHoverLabel:function(a,b){var c;if(a){var d=this._getVariable(a,"colorInfo"),e=this._getVariable(a,"opacityInfo"),f=this._getVariable(a,"sizeInfo"),d=d||f||e,r,g,n,l,k;a instanceof R?r=a.field:a instanceof N&&!a.attributeField2&&
!a.attributeField3?(r=a.attributeField,d&&(n=d.field,l=d.normalizationField)):a instanceof K?d?(r=d.field,g=d.normalizationField):(r=a.attributeField,g=a.normalizationField,k="percent-of-total"===a.normalizationType):a instanceof H&&d&&(r=d.field,g=d.normalizationField);(k=l&&"showOpNormField"||n&&"showOpField"||g&&"showNormField"||(k?"showNormPct":null)||r&&"showField"||null)&&(c=J.substitute({field:r&&this._getFieldAlias(r,b),normField:g&&this._getFieldAlias(g,b),opField:n&&this._getFieldAlias(n,
b),opNormField:l&&this._getFieldAlias(l,b)},this._i18n[k]))}return c},_buildLegendItems_Renderer:function(a,b,c){var d=b.parentLayerId,e=this.map,f=e.getScale(),r=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,b,f)){var v,n,l="esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass?a.renderer.renderer:a.renderer,m,h,C,p,F;if(l instanceof W&&(l=(e="zoom"===l.rangeType?l.getRendererInfoByZoom(e.getZoom()):l.getRendererInfoByScale(f))&&e.renderer,!l))return!1;var e=this._getVariable(l,
"colorInfo"),f=this._getVariable(l,"opacityInfo"),G=this._getVariable(l,"sizeInfo"),A=this._getDefaultHoverLabel(l,a);e?(m=this._getMedianColor(l,e),e.field&&(C=s.isFunction(e.field)?null:a.getField(e.field))):f&&(F=s.isFunction(f.field)?null:a.getField(f.field));G&&G.field&&(p=s.isFunction(G.field)?null:a.getField(G.field));if(l instanceof R)r=!0,this._showHeatRamp(a,b,l,c,A);else if(l instanceof X)r=!0,this._showDotDensityLegend(a,b,l,c);else if(l instanceof Y)r=!0,n=g.create("table",{cellpadding:0,
cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=g.create("tbody",{},n),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(n,a,b),l.latestObservationRenderer&&l.latestObservationRenderer instanceof H&&this._buildRow_Renderer(a,l.latestObservationRenderer.symbol,m,u.encode(l.latestObservationRenderer.label)||this.NLS_currentObservations,null,v),l.observationRenderer&&l.observationRenderer instanceof H&&this._buildRow_Renderer(a,l.observationRenderer.symbol,m,u.encode(l.observationRenderer.label)||
this.NLS_previousObservations,null,v);else if(l instanceof N){if(l.infos&&0<l.infos.length){r=!0;n=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);v=g.create("tbody",{},n);(a._hoverLabel||a._hoverLabels||A)&&this._createHoverAction(n,a,b,A);var w=[];k.forEach(l.infos,function(b){var c=null;a._editable&&a.types&&(c=this._getTemplateFromTypes(a.types,b.value));var d=b.label;null==d&&(d=b.value);-1===k.indexOf(w,d)&&(w.push(d),this._buildRow_Renderer(a,b.symbol,
m,u.encode(d),c,v))},this)}}else if(l instanceof K){if(l.infos&&0<l.infos.length||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass)r=!0,n=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=g.create("tbody",{},n),(a._hoverLabel||a._hoverLabels||A)&&this._createHoverAction(n,a,b,A),n=l.infos.slice(0).reverse(),k.forEach(n,function(b){var c=b.label;null==c&&(c=(c=C||p||F)&&this._isSmartRenderer(l,c.name)?this._getFieldAlias(c.name,a):b.minValue+" - "+
b.maxValue);this._buildRow_Renderer(a,b.symbol,m,u.encode(c),null,v)},this),"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&(a.rendererStyle===P.STYLE_SCALAR||a.rendererStyle===P.STYLE_SINGLE_ARROW)&&this._buildRow_Renderer(a,l.defaultSymbol,null,"",null,v)}else l instanceof H&&(r=!0,n=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=g.create("tbody",{},n),(a._hoverLabel||a._hoverLabels||A)&&this._createHoverAction(n,a,b,A),h=null,a._editable&&
(a.templates&&0<a.templates.length)&&(h=a.templates[0]),n=(C||F)&&p?null:C||F||p,this._buildRow_Renderer(a,l.symbol,m,u.encode(n?this._getFieldAlias(n.name,a):l.label),h,v),h=l.symbol&&l.symbol.color,n&&(C=F=p=null));r&&(e&&e.field?(C&&this._isSmartRenderer(l,C.name)&&(C=null),this._showColorRamp(a,b,l,null,c,e,C,A)):f&&h&&this._showColorRamp(a,b,l,h,c,f,F,A),G&&G.field&&(p&&this._isSmartRenderer(l,p.name)&&(p=null),this._showSizeLegend(a,b,l,G,m,c,p,A)));!a._hideDefaultSymbol&&l.defaultSymbol&&(r=
!0,n=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c),v=g.create("tbody",{},n),this._buildRow_Renderer(a,l.defaultSymbol,null,u.encode(l.defaultLabel)||"others",null,v))}r&&(t.set(q.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<d&&(t.set(q.byId(this.id+"_"+a.id+"_"+d+"_group"),"display","block"),this._findParentGroup(a.id,d)));return r},_isSmartRenderer:function(a,b){return a instanceof K&&a.infos&&1===a.infos.length&&a.attributeField===b},_showColorRamp:function(a,
b,c,d,e,f,r,k){var n;n=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},e);e=g.create("tbody",{},n);(a._hoverLabel||a._hoverLabels||k)&&this._createHoverAction(n,a,b,k);r&&this._addSubHeader(e,this._getFieldAlias(r.name,a));b=this._getRampStops(c,f,d);b.length&&this._drawColorRamp(e,b,!0,a,this._getRampBorderColor(c))},_getMedianColor:function(a,b){var c,d;b.colors?(c=b.minDataValue,d=b.maxDataValue):b.stops&&(c=b.stops[0].value,d=b.stops[b.stops.length-1].value);
return a.getColor(c+(d-c)/2,{colorInfo:b})},_getRampStops:function(a,b,c){var d,e,f,r,g=!1;b.colors||b.opacityValues?(e=b.maxDataValue-b.minDataValue,d=k.map([0,0.25,0.5,0.75,1],function(a){f=b.minDataValue+a*e;return Number(f.toFixed(6))}),this._checkPrecision(0,4,d)):b.stops&&(d=k.map(b.stops,function(a){return a.value}),(g=k.some(b.stops,function(a){return!!a.label}))&&(r=k.map(b.stops,function(a){return a.label})));var n=d[0],l,m,h;e=d[d.length-1]-n;return k.map(d,function(f,k){c?(l=new L(c.toRgba()),
m=a.getOpacity(f,{opacityInfo:b}),null!=m&&(l.a=m)):l=a.getColor(f,{colorInfo:b});h="";0===k?h=this._specialChars.lt+" ":k===d.length-1&&(h=this._specialChars.gt+" ");return{value:f,color:l,offset:1-(f-n)/e,label:g?r[k]:h+B.format(f)}},this).reverse()},_checkPrecision:function(a,b,c){var d=a+(b-a)/2,e=c[a],f=c[d],r=c[b],g=Math.floor(e),n=Math.floor(f),l=Math.floor(r);g===e&&(l===r&&n!==f&&g!==n&&l!==n)&&(c[d]=n);a+1!==d&&this._checkPrecision(a,d,c);d+1!==b&&this._checkPrecision(d,b,c)},_getRampBorderColor:function(a){var b;
if(a instanceof H)b=a.symbol;else if(a instanceof N||a instanceof K)b=a.infos[0].symbol;return(a=b&&-1===b.type.indexOf("linesymbol")?b.getStroke():null)&&a.color},_drawColorRamp:function(a,b,c,d,e){var f=g.create("tr",{},a),r,v,n,l,h,p=b.length-1,s;l=0;this.alignRight?(a=g.create("td",{align:this._isRightToLeft?"left":"right"},f),r=g.create("td",{align:this._isRightToLeft?"left":"right",width:this.gradientWidth},f)):(r=g.create("td",{width:this.gradientWidth,align:"center"},f),a=g.create("td",{},
f));var q=e&&0<e.a&&!(240<=e.r&&240<=e.g&&240<=e.b);v=g.create("div",{"class":q?"":"esriLegendBorderLessColorRamp",style:"position: relative; width:"+this.gradientWidth+"px;"},r);f=g.create("div",{"class":"esriLegendColorRamp"},v);r=t.get(f,"width");q&&(e=9>m("ie")?e.toHex():"rgba("+e.toRgba().join(",")+")",t.set(f,"border",this.colorRampBorder+" "+e));c?(e=this.gradientHeight*p,t.set(f,"height",e+"px")):e=t.get(f,"height");t.set(v,"height",e+"px");f=D.createSurface(f,r,e);9>m("ie")&&(l=f.getEventSource(),
t.set(l,"position","relative"),t.set(l.parentNode,"position","relative"),l=1);try{c&&k.forEach(b,function(a,b){a.offset=b/p}),h=f.createRect({x:-l,y:-l,width:r+l,height:e+l}),h.setFill({type:"linear",x1:0,y1:0,x2:0,y2:e,colors:b}).setStroke(null),f.createRect({width:r,height:e}).setFill(new L([255,255,255,1-d.opacity])).setStroke(null),this._surfaceItems.push(f)}catch(F){f.clear(),f.destroy()}k.forEach(b,function(a,c){if(a.label){s="top:"+100*a.offset+"%;";var d="";0===c&&(d+=" esriLegendColorRampTickFirst");
c===b.length-1&&(d+=" esriLegendColorRampTickLast");g.create("div",{"class":"esriLegendColorRampTick"+d,innerHTML:"\x26nbsp;",style:s},v)}});n=g.create("div",{"class":"esriLegendColorRampLabels",style:{height:e+this.gradientHeight+"px"}},a);c?k.forEach(b,function(a){g.create("div",{"class":"esriLegendColorRampLabel",innerHTML:u.encode(a.label)||"\x26nbsp;"},n)}):(g.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.high},n),g.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.low,
style:"top: "+(e+this.gradientHeight-2*this.gradientHeight)+"px;"},n))},_showHeatRamp:function(a,b,c,d,e){var f,r=c.field;f=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);d=g.create("tbody",{},f);(a._hoverLabel||a._hoverLabels||e)&&this._createHoverAction(f,a,b,e);(r=r&&a.getField(r))&&this._addSubHeader(d,this._getFieldAlias(r.name,a));b=this._getHeatmapStops(c);b.length&&this._drawColorRamp(d,b,!1,a)},_getHeatmapStops:function(a){var b=a.colorStops;a=a.colors;
var c,d,e,f;if(b&&b[0])if(c=b.length-1,a=b[0]&&null!=b[0].ratio){if((a=b[c])&&1!==a.ratio)b=b.slice(0),b.push({ratio:1,color:a.color}),c++}else d=b[0].value,e=b[c].value-d,b=k.map(b,function(a){return{color:a.color,ratio:(a.value-d)/e}});else a&&a[0]&&(c=a.length-1,f=1/(a.length-1),b=k.map(a,function(a,b){return{color:a,ratio:b*f}}));b=k.map(b,function(a,b){var d="";0===b?d="Low":b===c&&(d="High");return{color:a.color,label:d,offset:1-a.ratio}});return b.reverse()},_showDotDensityLegend:function(a,
b,c,d){var e=c.legendOptions,f,r,m,n,l,h,p,q=this.dotDensitySwatchSize,t=Math.round(q/2);e&&(r=e.backgroundColor,m=e.outline,n=e.valueUnit,l=e.dotCoverage);l=(l||this.dotCoverage)/100;p=Math.round(q*q/Math.pow(c.dotSize,2)*l);d=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);h=g.create("tbody",{},d);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(d,a,b);this._addSubHeader(h,J.substitute({value:c.dotValue,unit:n||""},this.NLS_dotValue));k.forEach(c.fields,
function(b){b=s.mixin({},b);b.numPoints=p;f=new Z(c._generateImageSrc(q,q,[b],{x:0,y:0},{x:q,y:q},r),m||c.outline,q,q);b=a.getField(b.name)||b;this._buildRow_Renderer(a,f,null,u.encode(this._getFieldAlias(b.name,a)),null,h,{type:"path",path:"M "+-t+","+-t+" L "+t+","+-t+" L "+t+","+t+" L "+-t+","+t+" L "+-t+","+-t+" E"})},this)},_showSizeLegend:function(a,b,c,d,e,f,r,m){var n=d.legendOptions,n=n&&n.customValues,l,h,p=this._getSizeSymbol(c,e);"unknown"!==d.valueUnit||(!p||!n&&(null==d.minSize||null==
d.maxSize))||(e=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},f),l=g.create("tbody",{},e),(a._hoverLabel||a._hoverLabels||m)&&this._createHoverAction(e,a,b,m),r&&this._addSubHeader(l,this._getFieldAlias(r.name,a)),h=n||this._getDataValues(c,p,d),h.reverse(),k.forEach(h,function(b,e){p=O.fromJson(p.toJson());this._applySize(p,c,d,b);b=B.format(b);var f="";0===e?f=this._specialChars.gt+" ":e===h.length-1&&(f=this._specialChars.lt+" ");f="\x3cspan class\x3d'esriLegendSizeRampLabel'\x3e"+
u.encode(f+b)+"\x3c/span\x3e";this._buildRow_Renderer(a,p,null,f,null,l)},this))},_getSizeSymbol:function(a,b){var c;if(a instanceof H)c=a.symbol;else if(a instanceof P)c=a.defaultSymbol;else if(a instanceof N||a instanceof K)c=a.infos[0].symbol;if(c=-1!==c.type.indexOf("fillsymbol")?null:c)c=O.fromJson(c.toJson()),b&&c.setColor(new L(b.toRgba()));return c},_getDataValues:function(a,b,c,d,e){e=null==e?20:e;d=this._interpolateSizeRange(c.minSize,c.maxSize,null==d?5:d);var f=k.map(d,function(a){return this._getDataValueFromSize(a,
c)},this),g,h,f=B.round(f);for(g=1;g<f.length-1;g++)if(h=this._roundDataValue(a,b,c,f[g],f[g-1],e))f[g]=h[0],d[g]=h[1];return f},_interpolateSizeRange:function(a,b,c){b=(b-a)/(c-1);var d,e=[];for(d=0;d<c;d++)e.push(a+b*d);return e},_getDataValueFromSize:function(a,b){var c=b.minSize,d=b.maxSize,e=b.minDataValue,f=b.maxDataValue;return c=a<=c?e:a>=d?f:(a-c)/(d-c)*(f-e)+e},_roundDataValue:function(a,b,c,d,e,f){var g=this._getSize(b,a,c,d);e=this._getSize(b,a,c,e);var k,n=B.getDigits(d),l=n.integer,
n=n.fractional,h,m,p,q,s,t,u,w,x,y,z;0<d&&1>d&&(k=Math.pow(10,n),d*=k,l=B.getDigits(d).integer);for(l-=1;0<=l&&!(h=Math.pow(10,l),n=Math.floor(d/h)*h,h*=Math.ceil(d/h),null!=k&&(n/=k,h/=k),m=(n+h)/2,m=B.round([n,m,h],{indexes:[1]})[1],p=this._getSize(b,a,c,n),q=this._getSize(b,a,c,h),s=this._getSize(b,a,c,m),t=B.getPctChange(g,p,e,null),u=B.getPctChange(g,q,e,null),w=B.getPctChange(g,s,e,null),x=t.prev<=f,y=u.prev<=f,x&&y&&(t.prev<=u.prev?(x=!0,y=!1):(y=!0,x=!1)),x?z=[n,p]:y?z=[h,q]:w.prev<=f&&(z=
[m,s]),z);l--);return z},_applySize:function(a,b,c,d){var e=a.type;b=this._getSize(a,b,c,d);switch(e){case "simplemarkersymbol":a.setSize(b);break;case "picturemarkersymbol":e=a.width;c=a.height;a.setHeight(b);a.setWidth(b*(e/c));break;case "simplelinesymbol":case "cartographiclinesymbol":a.setWidth(b);break;case "textsymbol":a.font&&a.font.setSize(b)}},_getSize:function(a,b,c,d){return b.getSize(d,{sizeInfo:c,shape:-1!==a.type.indexOf("markersymbol")?a.style:null})},_buildRow_Renderer:function(a,
b,c,d,e,f,k){var h=g.create("tr",{},f),n;this.alignRight?(f=g.create("td",{align:this._isRightToLeft?"left":"right"},h),n=g.create("td",{align:this._isRightToLeft?"left":"right",width:35},h)):(n=g.create("td",{width:35,align:"center"},h),f=g.create("td",{},h));var l=h=30;if("simplemarkersymbol"==b.type)h=Math.min(Math.max(h,b.size+12),125),l=Math.min(Math.max(l,b.size+12),125);else if("picturemarkersymbol"==b.type)h=Math.min(Math.max(h,b.width),125),l=Math.min(b.height||l,125);else if("textsymbol"==
b.type){var m,p;b.text||(m=b.text,p=!0,b.setText(this.defaultText));h=Math.min(Math.max(h,b.getWidth()+12),125);l=Math.min(Math.max(l,b.getHeight()+12),125);p&&b.setText(m)}m=g.create("div",{style:"width:"+h+"px;height:"+l+"px;"},n);J.isDefined(d)&&"number"===typeof d&&(d=""+d);g.create("td",{innerHTML:d||"",align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%"},f))));a=this._drawSymbol(m,b,c,h,l,e,a,k);this._surfaceItems.push(a)},_addSubHeader:function(a,b){var c=
g.create("tr",{},a),c=g.create("td",{align:this._align,colspan:2},c);g.create("td",{innerHTML:u.encode(b)||"",align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%"},c))))},_drawSymbol:function(a,b,c,d,e,f,g,h){b=O.fromJson(b.toJson());var k=g.opacity;c&&b.setColor(new L(c.toRgba()));if("simplelinesymbol"===b.type||"cartographiclinesymbol"===b.type||"textsymbol"===b.type){if(!b.color)return;c=b.color.toRgba();c[3]*=k;b.color.setColor(c)}else if("simplemarkersymbol"===
b.type||"simplefillsymbol"===b.type){if(!b.color)return;c=b.color.toRgba();c[3]*=k;b.color.setColor(c);b.outline&&b.outline.color&&(c=b.outline.color.toRgba(),c[3]*=k,b.outline.color.setColor(c))}else"picturemarkersymbol"===b.type&&(a.style.opacity=k,a.style.filter="alpha(opacity\x3d("+100*k+"))");a=D.createSurface(a,d,e);9>m("ie")&&(c=a.getEventSource(),t.set(c,"position","relative"),t.set(c.parentNode,"position","relative"));f=this._getDrawingToolShape(b,f)||O.getShapeDescriptors(b);var l,k=(c=
f.defaultShape)&&"text"===c.type;try{k&&!c.text&&(c.text=this.defaultText),l=a.createShape(h||c).setFill(f.fill).setStroke(f.stroke),k&&l.setFont(f.font)}catch(p){a.clear();a.destroy();return}var q=l.getBoundingBox();h=q.width;f=q.height;var k=-(q.x+h/2),u=-(q.y+f/2);c=a.getDimensions();k={dx:k+c.width/2,dy:u+c.height/2};if("simplemarkersymbol"===b.type&&"path"===b.style)d=g._getScaleMatrix(q,b.size),l.applyTransform(U.scaleAt(d.xx,d.yy,{x:c.width/2,y:c.height/2}));else if(h>d||f>e)g=h/d>f/e,d=((g?
d:e)-5)/(g?h:f),s.mixin(k,{xx:d,yy:d});l.applyTransform(k);return a},_getDrawingToolShape:function(a,b){var c;switch(b?b.drawingTool||null:null){case "esriFeatureEditToolArrow":c={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 E"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 E"};break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 E"};break;case "esriFeatureEditToolCircle":c=
{type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":c={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:a.getFill(),stroke:a.getStroke()}},_repaintItems:function(){k.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(b){}a.children&&s.isArray(a.children)&&k.forEach(a.children,this._repaint,this)}},
_createHoverAction:function(a,b,c,d){if(d=b._hoverLabel||b._hoverLabels&&b._hoverLabels[c.id]||d)d=u.encode(d),b.mouseMoveHandler=b.mouseMoveHandler||{},b.mouseMoveHandler[c.id]=p.connect(a,"onmousemove",s.hitch(this,function(a,b){this.mouseX=b.clientX;this.mouseY=b.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,t.set(q.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(s.hitch(this,function(a,b,c){if(a==this.mouseX&&b==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=
!0,q.byId(this.id+"_hoverLabel")){var d=q.byId(this.id+"_hoverLabel");d.innerHTML="\x3cspan\x3e"+c+"\x3c/span\x3e";t.set(d,"top",b+"px");t.set(d,"left",a+15+"px");t.set(d,"display","")}else g.create("div",{innerHTML:"\x3cspan\x3e"+c+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:b+"px",left:a+15+"px"}},document.body)},b.clientX,b.clientY,a),500)},d)),b.mouseOutHandler=b.mouseOutHandler||{},b.mouseOutHandler[c.id]=p.connect(a,"onmouseout",s.hitch(this,function(a){this.mouseY=
this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,t.set(q.byId(this.id+"_hoverLabel"),"display","none"))}))},_removeHoverHandlers:function(){var a;k.forEach(this.layers,function(b){if(b.mouseMoveHandler)for(a in b.mouseMoveHandler)p.disconnect(b.mouseMoveHandler[a]);if(b.mouseOutHandler)for(a in b.mouseOutHandler)p.disconnect(b.mouseOutHandler[a])})},_createDynamicLayers:function(a){var b=[],c;k.forEach(a.dynamicLayerInfos||a.layerInfos,function(d){c={id:d.id};c.source=d.source&&d.source.toJson();
var e;a.layerDefinitions&&a.layerDefinitions[d.id]&&(e=a.layerDefinitions[d.id]);e&&(c.definitionExpression=e);var f;a.layerDrawingOptions&&a.layerDrawingOptions[d.id]&&(f=a.layerDrawingOptions[d.id]);f&&(c.drawingInfo=f.toJson());c.minScale=d.minScale||0;c.maxScale=d.maxScale||0;b.push(c)});return b},_getTemplateFromTypes:function(a,b){var c;for(c=0;c<a.length;c++)if(a[c].id==b&&a[c].templates&&0<a[c].templates.length)return a[c].templates[0];return null},_findParentGroup:function(a,b,c){var d,e=
b.dynamicLayerInfos||b.layerInfos;for(d=0;d<e.length;d++)if(c==e[d].id){-1<e[d].parentLayerId&&(t.set(q.byId(this.id+"_"+a+"_"+e[d].parentLayerId+"_group"),"display","block"),this._findParentGroup(a,b,e[d].parentLayerId));break}},_addSubLayersToHide:function(a){function b(c,d){var e=a.layer.dynamicLayerInfos||a.layer.layerInfos,f,g;for(f=0;f<e.length;f++)if(e[f].id===c&&e[f].subLayerIds)for(g=0;g<e[f].subLayerIds.length;g++){var h=e[f].subLayerIds[g];-1===k.indexOf(d,h)&&(d.push(h),b(h,d))}}a.layer.layerInfos&&
k.forEach(a.layer._hideLayersInLegend,function(c){b(c,a.layer._hideLayersInLegend)})},_isLayerInScale:function(a,b,c){var d,e=!0;if(a.legendResponse&&a.legendResponse.layers)for(d=0;d<a.legendResponse.layers.length;d++){var f=a.legendResponse.layers[d];if(b.id==f.layerId){var g,h;!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale?(0==f.minScale&&a.tileInfo&&(g=a.tileInfo.lods[0].scale),0==f.maxScale&&a.tileInfo&&(h=a.tileInfo.lods[a.tileInfo.lods.length-1].scale)):(g=Math.min(a.minScale,f.minScale)||
a.minScale||f.minScale,h=Math.max(a.maxScale,f.maxScale));if(0<g&&g<c||h>c)e=!1;break}}else if(a.minScale||a.maxScale)if(a.minScale&&a.minScale<c||a.maxScale&&a.maxScale>c)e=!1;return e},_getServiceTitle:function(a){var b=a._titleForLegend;b||((b=a.url)?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+1,
b.length)):-1<a.url.indexOf("/FeatureServer")&&(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&a.vectorFieldPixelFilter&&(a=a.vectorFieldPixelFilter.outputUnit?this["NLS_"+a.vectorFieldPixelFilter.outputUnit]:this["NLS_"+a.vectorFieldPixelFilter.inputUnit],J.isDefined(a)&&(b+=" ("+a+")"));return u.encode(b)},_getEffectiveScale:function(a,
b){var c=b.minScale,d=b.maxScale;if(J.isDefined(b.parentLayerId)){var e=a.layerInfos,f=b.parentLayerId,g;for(g=e.length-1;0<=g;g--)if(e[g].id==f)if(0==c&&0<e[g].minScale?c=e[g].minScale:0<c&&0==e[g].minScale||0<c&&0<e[g].minScale&&(c=Math.min(c,e[g].minScale)),d=Math.max(d||0,e[g].maxScale||0),-1<e[g].parentLayerId)f=e[g].parentLayerId;else break}return{minScale:c,maxScale:d}},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===
a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)?!0:!1}});s.mixin(E,{ALIGN_LEFT:0,ALIGN_RIGHT:1});m("extend-esri")&&s.setObject("dijit.Legend",
E,V);return E});