// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/VisibleScaleRangeSlider/templates/ScaleMenu.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"${css.section}"\x3e\r\n    \x3cdiv class\x3d"${css.header}"\x3e${labels.current}\x3c/div\x3e\r\n    \x3cdiv class\x3d"${css.content}"\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"dap_currentScaleLabel" class\x3d"${css.item} ${css.current}"\x3e\x3c/div\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"dap_scaleInput" data-dojo-type\x3d"dijit/form/TextBox" class\x3d"${css.input}"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"${css.section}"\x3e\r\n    \x3cdiv class\x3d"${css.header}" data-dojo-attach-point\x3d"dap_scaleListHeader"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"${css.content}"\x3e\r\n      \x3col data-dojo-attach-point\x3d"dap_recommendedScales" class\x3d"${css.list}"\x3e\r\n        \x3cli data-dojo-attach-point\x3d"dap_currentScaleItem" class\x3d"${css.item} ${css.selectable}"\x3e\x3c/li\x3e\r\n        \x3c!--additional list items added dynamically--\x3e\r\n      \x3c/ol\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/dijit/VisibleScaleRangeSlider/ScaleMenu","../../domUtils ../../kernel ../_EventedWidget ../_Tooltip dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/dom-construct dojo/dom-prop dojo/has dojo/keys dojo/number dojo/on dojo/query dojo/string dojox/html/entities dojox/lang/functional/object dojo/i18n!../../nls/jsapi dojo/text!./templates/ScaleMenu.html dijit/form/TextBox".split(" "),function(e,n,b,p,q,r,s,t,d,f,g,u,v,k,l,w,h,x,y,
z,A){b=s([b,q,r,p],{declaredClass:"esri.dijit.VisibleScaleRangeSlider.ScaleMenu",templateString:A,baseClass:"esriScaleMenu",labels:z.visibleScaleRangeSlider,_recommendedScales:{world:1E8,continent:5E7,countriesBig:25E6,countriesSmall:12E6,statesProvinces:6E6,stateProvince:3E6,counties:15E5,county:75E4,metropolitanArea:32E4,cities:16E4,city:8E4,town:4E4,neighborhood:2E4,streets:1E4,street:5E3,buildings:2500,building:1250},_elementValueMap:null,_elements:null,_scaleRangeCategories:null,_scaleRanges:null,
_originalScaleInputValue:null,constructor:function(){d.extend(this.constructor,{css:{header:"esriHeader",section:"esriSection",content:"esriContent",current:"esriCurrent",input:"esriInput",list:"esriList",item:"esriItem",inline:"esriInline",selectable:"esriSelectable"}})},buildRendering:function(){this.inherited(arguments);var a=this.labels,c=a.featuredScaleLabels,m=this._recommendedScales,B=this.css.item+" "+this.css.selectable,b;t.forEach(y.keys(m),function(a){b=c[a];a=h.substitute(b,{scaleLabel:this._formatScale(m[a])});
f.create("li",{innerHTML:a,className:B},this.dap_recommendedScales)},this);var d=f.create("span",{innerHTML:a.setTo,className:this.css.inline}),e=f.create("span",{innerHTML:a.selectOne,className:this.css.inline});g.set(this.dap_scaleListHeader,"innerHTML",h.substitute(a.setToSelectOne,{setTo:d.outerHTML,selectOne:e.outerHTML}))},_formatScale:function(a){return"1:"+k.format(a)},postCreate:function(){this.inherited(arguments);this.own(l(this.domNode,l.selector("."+this.css.item+"."+this.css.selectable,
"click"),d.hitch(this,function(a){this._emitScaleSelected(this._parseScale(a.target.innerHTML))})));this.dap_scaleInput.on("keyDown",d.hitch(this,function(a){a.keyCode===v.ENTER&&this._handleCustomScaleInput()}));this.createTooltip(this.dap_scaleInput,this.labels.customScaleInputTooltip)},_emitScaleSelected:function(a){this.emit("scale-selected",{scale:a})},_handleCustomScaleInput:function(){var a=this._parseScale(this.dap_scaleInput.get("value"));isNaN(a)||this._emitScaleSelected(a)},_parseScale:function(a){a=
x.decode(a).replace(/.*\(/,"").replace(/\).*$/,"").replace(/.*1:/,"").replace(/[^0-9.\s]/g,"");return k.parse(a)},_setCurrentScaleAttr:function(a){var c=this._formatScale(a.scale);g.set(this.dap_currentScaleLabel,"innerHTML",a.label);this.dap_scaleInput.set("value",c,!1);this._originalScaleInputValue=c;c=h.substitute(this.labels.featuredScaleLabels.current,{scaleLabel:this._formatScale(a.mapScale)});g.set(this.dap_currentScaleItem,"innerHTML",c);this._scaleRanges=a.ranges;this._hideOutOfScaleRanges()},
_hideOutOfScaleRanges:function(){var a=w("."+this.css.item+"."+this.css.selectable,this.dap_recommendedScales),c=this._scaleRanges,b;a.forEach(function(a){a!==this.dap_currentScaleItem&&(b=this._parseScale(a.innerHTML),c.contains(b)?e.show(a):e.hide(a))},this)}});u("extend-esri")&&d.setObject("dijit.ScaleMenu",b,n);return b});