define(
   ({
    _widgetLabel: "Zīmēt",
    selectDrawMode: "Izvēlēties zīmēšanas režīmu",
    clear: "Notīrīt",
    point: "Virsotne",
    line: "Līnija",
    polyline: "Līnija",
    freehandPolyline: "Brīvrokas līnija",
    triangle: "Trīsstūris",
    extent: "Pārklājuma taisnstūris",
    circle: "Aplis",
    ellipse: "Elipse",
    polygon: "Laukums",
    freehandPolygon: "Brīvrokas laukums",
    text: "Teksts",
    style: "Stils",
    alpha: "Caurspīdīgums",
    width: "Platums",
    size: "Lielums",
    color: "Krāsa",
    markerColor: "Marķiera krāsa",
    outlineColor: "Kontūras krāsa",
    lineColor: "Līnijas krāsa",
    fillColor: "Aizpildījuma krāsa",
    showMeasurements: "Rādīt mērījumus",
    areaUnits: "Laukuma vienības",
    distanceUnits: "Garuma vienības",
    kilometers: "Kilometri",
    miles: "Jūdzes",
    meters: "Metri",
    feet: "Pēdas",
    yards: "Jardi",
    squareKilometers: "Kvadrātkilometri",
    squareMiles: "Kvadrātjūdzes",
    acres: "Akri",
    hectares: "Hektāri",
    squareMeters: "Kvadrātmetri",
    squareFeet: "Kvadrātpēdas",
    squareYards: "Kvadrātjardi",
    undo: "Atsaukt",
    redo: "Atcelt atsaukšanu"
  })
);