define(
   ({
    _widgetLabel: "Σχεδίαση",
    selectDrawMode: "Επιλογή τρόπου σχεδίασης",
    clear: "Απαλοιφή",
    point: "Σημείο",
    line: "Γραμμή",
    polyline: "Γραμμή",
    freehandPolyline: "Γραμμή ελεύθερης σχεδίασης",
    triangle: "Τρίγωνο",
    extent: "Έκταση",
    circle: "Κύκλος",
    ellipse: "Έλλειψη",
    polygon: "Πολύγωνο",
    freehandPolygon: "Πολύγωνο ελεύθερης σχεδίασης",
    text: "Κείμενο",
    style: "Στυλ",
    alpha: "Διαφάνεια",
    width: "Πλάτος",
    size: "Μέγεθος",
    color: "Χρώμα",
    markerColor: "Χρώμα συμβόλου",
    outlineColor: "Χρώμα περιγράμματος",
    lineColor: "Χρώμα γραμμής",
    fillColor: "Χρώμα γεμίσματος",
    showMeasurements: "Εμφάνιση μετρήσεων",
    areaUnits: "Μονάδες εμβαδού",
    distanceUnits: "Μονάδες απόστασης",
    kilometers: "Χιλιόμετρα",
    miles: "Μίλια",
    meters: "Μέτρα",
    feet: "Πόδια",
    yards: "Γιάρδες",
    squareKilometers: "Τετραγωνικά χιλιόμετρα",
    squareMiles: "Τετραγωνικά μίλια",
    acres: "Έικρ",
    hectares: "Εκτάρια",
    squareMeters: "Τετραγωνικά μέτρα",
    squareFeet: "Τετραγωνικά πόδια",
    squareYards: "Τετραγωνικές γιάρδες",
    undo: "Αναίρεση",
    redo: "Επανάληψη"
  })
);