define(
   ({
    placeholder: "プレースホルダー テキスト",
    url: "ジオコーダーの URL",
    name: "ジオコーダー名",
    example: "例",
    singleLineFieldName: "フィールド名",
    portalConnectionError: 'ジオコーダーの構成をポータルから取得できません',
    actions: "アクション",
    warning: "このジオコード サービスのバージョンはサポートされていません。このウィジェットは 10.1 以上のジオコード サービスをサポートしています。",
    instruction: "このウィジェットにジオコーダーを設定します。[ジオコーダーの追加] をクリックして URL を参照し、わかりやすい名前を指定して、その他のプロパティを設定します。以下よりジオコーダーの並べ替え、構成、または削除を行うことができます。",
    layerInstruction1: "以下の場所で検索条件を構成できます。 ",
    layerInstruction2: "Web マップの詳細ページ",
    searchAddress: "住所で検索",
    searchLayer: "レイヤーで検索",
    layer: "レイヤー",
    field: "フィールド",
    condition: "条件",
    contains: "含む",
    deleteLastGeocoderError: "最後のジオコーダーを削除できません。",
    noSearchFactorError: "少なくとも 1 つの機能 ([住所で検索] または [レイヤーで検索]) を選択する必要があります。",
    equals: "等しい",
    add: "ジオコーダの追加",
    edit: "ジオコーダの編集",
    ok: "OK",
    cancel: "キャンセル",
    geocoderNamePlaceHolder: "マイ ジオコーダー",
    geocodePlaceHolder: "住所または場所を検索",
    REPEATING_ERROR: "次のフィールドを繰り返します: "
  })
);