define(
   ({
    _widgetLabel: "Attributtabell",
    ok: "OK",
    cancel: "Avbryt",
    unsupportQueryWarning: "Laget må støtte spørringsoperasjoner for å kunne vises i miniprogrammet Attributtabell. Sørg for at spørringsfunksjonen i tjenesten er slått på.",
    exportMessage: "Eksportere data til CSV-fil?",
    exportFiles: "Eksporter til CSV",
    options: "Alternativer",
    zoomto: "Zoom til",
    highlight: "Uthev grafikk",
    selectAll: "Velg oppføringer på alle sider",
    selectPage: "Velg oppføringer på gjeldende side",
    clearSelection: "Fjern utvalg",
    filterByExtent: "Filtrer etter kartutstrekning",
    showSelectedRecords: "Vis valgte poster",
    showRelatedRecords: "Vis relaterte oppføringer",
    noRelatedRecords: "Ingen relaterte poster",
    refresh: "Oppdater",
    features: "geoobjekter",
    selected: "valgte",
    transparent: "Gjennomsiktig modus",
    indicate: "Finn utvalg",
    columns: "Vis/skjul kolonner",
    selectionSymbol: "Utvalgsymbol",
    closeMessage: "Skjul tabellen (utvid den igjen nederst)",
    dataNotAvailable: "Data ikke tilgjengelig!<br>Klikk på [Oppdater] for å prøve på nytt.",
    openTableTip: "Åpne attributtabell",
    closeTableTip: "Skjul attributt-tabell"
  })
);