/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
require({cache:{"dojox/gfx/decompose":function(){define(["./_base","dojo/_base/lang","./matrix"],function(k,s,m){function t(c,b){return Math.abs(c-b)<=1E-6*(Math.abs(c)+Math.abs(b))}function u(c,b,d,a){if(isFinite(c)){if(!isFinite(d))return c}else return d;b=Math.abs(b);a=Math.abs(a);return(b*c+a*d)/(b+a)}function h(c){c=m.normalize(c);var b=-c.xx-c.yy,d=c.xx*c.yy-c.xy*c.yx,a=Math.sqrt(b*b-4*d),b=-(b+(0>b?-a:a))/2,d=d/b,a=c.xy/(b-c.xx),q=1,f=c.xy/(d-c.xx),h=1;t(b,d)&&(a=1,f=q=0,h=1);isFinite(a)||
(a=1,q=(b-c.xx)/c.xy,isFinite(q)||(a=(b-c.yy)/c.yx,q=1,isFinite(a)||(a=1,q=c.yx/(b-c.yy))));isFinite(f)||(f=1,h=(d-c.xx)/c.xy,isFinite(h)||(f=(d-c.yy)/c.yx,h=1,isFinite(f)||(f=1,h=c.yx/(d-c.yy))));c=Math.sqrt(a*a+q*q);var k=Math.sqrt(f*f+h*h);if(!isFinite(a/=c))a=0;if(!isFinite(q/=c))q=0;if(!isFinite(f/=k))f=0;if(!isFinite(h/=k))h=0;return{value1:b,value2:d,vector1:{x:a,y:q},vector2:{x:f,y:h}}}function f(c,b){var d=0>c.xx*c.yy||0<c.xy*c.yx?-1:1,a=b.angle1=(Math.atan2(c.yx,c.yy)+Math.atan2(-d*c.xy,
d*c.xx))/2,d=Math.cos(a),a=Math.sin(a);b.sx=u(c.xx/d,d,-c.xy/a,a);b.sy=u(c.yy/d,d,c.yx/a,a);return b}function d(c,b){var d=0>c.xx*c.yy||0<c.xy*c.yx?-1:1,a=b.angle2=(Math.atan2(d*c.yx,d*c.xx)+Math.atan2(-c.xy,c.yy))/2,d=Math.cos(a),a=Math.sin(a);b.sx=u(c.xx/d,d,c.yx/a,a);b.sy=u(c.yy/d,d,-c.xy/a,a);return b}return k.decompose=function(c){var b=m.normalize(c);c={dx:b.dx,dy:b.dy,sx:1,sy:1,angle1:0,angle2:0};if(t(b.xy,0)&&t(b.yx,0))return s.mixin(c,{sx:b.xx,sy:b.yy});if(t(b.xx*b.yx,-b.xy*b.yy))return f(b,
c);if(t(b.xx*b.xy,-b.yx*b.yy))return d(b,c);var n,a=new m.Matrix2D(b);n=s.mixin(a,{dx:0,dy:0,xy:a.yx,yx:a.xy});a=h([b,n]);n=h([n,b]);a=new m.Matrix2D({xx:a.vector1.x,xy:a.vector2.x,yx:a.vector1.y,yy:a.vector2.y});n=new m.Matrix2D({xx:n.vector1.x,xy:n.vector1.y,yx:n.vector2.x,yy:n.vector2.y});b=new m.Matrix2D([m.invert(a),b,m.invert(n)]);f(n,c);b.xx*=c.sx;b.yy*=c.sy;d(a,c);b.xx*=c.sx;b.yy*=c.sy;return s.mixin(c,{sx:b.xx,sy:b.yy})}})},"dojox/gfx/bezierutils":function(){define(["./_base"],function(k){k=
k.bezierutils={};k.tAtLength=function(f,d){var c=0,b=6==f.length,n=0,a=0,q=b?t:h,y=function(h,k){for(var r=0,l=0;l<h.length-2;l+=2)r+=m(h[l],h[l+1],h[l+2],h[l+3]);l=b?m(f[0],f[1],f[4],f[5]):m(f[0],f[1],f[6],f[7]);r-l>k||n+r>d+k?(++a,r=q(h,0.5),y(r[0],k),Math.abs(n-d)<=k||y(r[1],k)):(n+=r,c+=1/(1<<a))};d&&y(f,0.5);return c};var s=k.computeLength=function(f){for(var d=6==f.length,c=0,b=0;b<f.length-2;b+=2)c+=m(f[b],f[b+1],f[b+2],f[b+3]);b=d?m(f[0],f[1],f[4],f[5]):m(f[0],f[1],f[6],f[7]);0.1<c-b&&(f=
d?t(f,0.5):u(f,0.5),c=s(f[0],d),c+=s(f[1],d));return c},m=k.distance=function(f,d,c,b){return Math.sqrt((c-f)*(c-f)+(b-d)*(b-d))},t=function(f,d){var c=1-d,b=c*c,h=d*d,a=f[0],q=f[1],y=f[2],k=f[3],m=f[4],r=f[5],l=b*a+2*c*d*y+h*m,b=b*q+2*c*d*k+h*r;return[[a,q,c*a+d*y,c*q+d*k,l,b],[l,b,c*y+d*m,c*k+d*r,m,r]]},u=function(f,d){var c=1-d,b=c*c,h=b*c,a=d*d,q=a*d,k=f[0],m=f[1],w=f[2],r=f[3],l=f[4],t=f[5],v=f[6],u=f[7],s=h*k+3*b*d*w+3*c*a*l+q*v,h=h*m+3*b*d*r+3*c*a*t+q*u;return[[k,m,c*k+d*w,c*m+d*r,b*k+2*c*
d*w+a*l,b*m+2*c*d*r+a*t,s,h],[s,h,b*w+2*c*d*l+a*v,b*r+2*c*d*t+a*u,c*l+d*v,c*t+d*u,v,u]]},h=k.splitBezierAtT=function(f,d){return 6==f.length?t(f,d):u(f,d)};return k})},"dojox/gfx/shape":function(){define("./_base dojo/_base/lang dojo/_base/declare dojo/_base/kernel dojo/_base/sniff dojo/on dojo/_base/array dojo/dom-construct dojo/_base/Color ./matrix".split(" "),function(k,s,m,t,u,h,f,d,c,b){var n=k.shape={};n.Shape=m("dojox.gfx.shape.Shape",null,{constructor:function(){this.parentMatrix=this.parent=
this.bbox=this.strokeStyle=this.fillStyle=this.matrix=this.shape=this.rawNode=null;if(u("gfxRegistry")){var a=n.register(this);this.getUID=function(){return a}}},destroy:function(){u("gfxRegistry")&&n.dispose(this);this.rawNode&&"__gfxObject__"in this.rawNode&&(this.rawNode.__gfxObject__=null);this.rawNode=null},getNode:function(){return this.rawNode},getShape:function(){return this.shape},getTransform:function(){return this.matrix},getFill:function(){return this.fillStyle},getStroke:function(){return this.strokeStyle},
getParent:function(){return this.parent},getBoundingBox:function(){return this.bbox},getTransformedBoundingBox:function(){var a=this.getBoundingBox();if(!a)return null;var c=this._getRealMatrix();return[b.multiplyPoint(c,a.x,a.y),b.multiplyPoint(c,a.x+a.width,a.y),b.multiplyPoint(c,a.x+a.width,a.y+a.height),b.multiplyPoint(c,a.x,a.y+a.height)]},getEventSource:function(){return this.rawNode},setClip:function(a){this.clip=a},getClip:function(){return this.clip},setShape:function(a){this.shape=k.makeParameters(this.shape,
a);this.bbox=null;return this},setFill:function(a){if(!a)return this.fillStyle=null,this;var b=null;if("object"==typeof a&&"type"in a)switch(a.type){case "linear":b=k.makeParameters(k.defaultLinearGradient,a);break;case "radial":b=k.makeParameters(k.defaultRadialGradient,a);break;case "pattern":b=k.makeParameters(k.defaultPattern,a)}else b=k.normalizeColor(a);this.fillStyle=b;return this},setStroke:function(a){if(!a)return this.strokeStyle=null,this;if("string"==typeof a||s.isArray(a)||a instanceof
c)a={color:a};a=this.strokeStyle=k.makeParameters(k.defaultStroke,a);a.color=k.normalizeColor(a.color);return this},setTransform:function(a){this.matrix=b.clone(a?b.normalize(a):b.identity);return this._applyTransform()},_applyTransform:function(){return this},moveToFront:function(){var a=this.getParent();a&&(a._moveChildToFront(this),this._moveToFront());return this},moveToBack:function(){var a=this.getParent();a&&(a._moveChildToBack(this),this._moveToBack());return this},_moveToFront:function(){},
_moveToBack:function(){},applyRightTransform:function(a){return a?this.setTransform([this.matrix,a]):this},applyLeftTransform:function(a){return a?this.setTransform([a,this.matrix]):this},applyTransform:function(a){return a?this.setTransform([this.matrix,a]):this},removeShape:function(a){this.parent&&this.parent.remove(this,a);return this},_setParent:function(a,b){this.parent=a;return this._updateParentMatrix(b)},_updateParentMatrix:function(a){this.parentMatrix=a?b.clone(a):null;return this._applyTransform()},
_getRealMatrix:function(){for(var a=this.matrix,c=this.parent;c;)c.matrix&&(a=b.multiply(c.matrix,a)),c=c.parent;return a}});n._eventsProcessing={on:function(a,b){return h(this.getEventSource(),a,n.fixCallback(this,k.fixTarget,b))},connect:function(a,b,c){"on"==a.substring(0,2)&&(a=a.substring(2));return this.on(a,c?s.hitch(b,c):b)},disconnect:function(a){return a.remove()}};n.fixCallback=function(a,b,c,d){d||(d=c,c=null);if(s.isString(d)){c=c||t.global;if(!c[d])throw['dojox.gfx.shape.fixCallback: scope["',
d,'"] is null (scope\x3d"',c,'")'].join("");return function(f){return b(f,a)?c[d].apply(c,arguments||[]):void 0}}return!c?function(f){return b(f,a)?d.apply(c,arguments):void 0}:function(f){return b(f,a)?d.apply(c,arguments||[]):void 0}};s.extend(n.Shape,n._eventsProcessing);n.Container={_init:function(){this.children=[];this._batch=0},openBatch:function(){return this},closeBatch:function(){return this},add:function(a){var b=a.getParent();b&&b.remove(a,!0);this.children.push(a);return a._setParent(this,
this._getRealMatrix())},remove:function(a,b){for(var c=0;c<this.children.length;++c)if(this.children[c]==a){b||(a.parent=null,a.parentMatrix=null);this.children.splice(c,1);break}return this},clear:function(a){for(var b,c=0;c<this.children.length;++c)b=this.children[c],b.parent=null,b.parentMatrix=null,a&&b.destroy();this.children=[];return this},getBoundingBox:function(){if(this.children){var a=null;f.forEach(this.children,function(c){var d=c.getBoundingBox();d&&((c=c.getTransform())&&(d=b.multiplyRectangle(c,
d)),a?(a.x=Math.min(a.x,d.x),a.y=Math.min(a.y,d.y),a.endX=Math.max(a.endX,d.x+d.width),a.endY=Math.max(a.endY,d.y+d.height)):a={x:d.x,y:d.y,endX:d.x+d.width,endY:d.y+d.height})});a&&(a.width=a.endX-a.x,a.height=a.endY-a.y);return a}return null},_moveChildToFront:function(a){for(var b=0;b<this.children.length;++b)if(this.children[b]==a){this.children.splice(b,1);this.children.push(a);break}return this},_moveChildToBack:function(a){for(var b=0;b<this.children.length;++b)if(this.children[b]==a){this.children.splice(b,
1);this.children.unshift(a);break}return this}};n.Surface=m("dojox.gfx.shape.Surface",null,{constructor:function(){this._parent=this.rawNode=null;this._nodes=[];this._events=[]},destroy:function(){f.forEach(this._nodes,d.destroy);this._nodes=[];f.forEach(this._events,function(a){a&&a.remove()});this._events=[];this.rawNode=null;if(u("ie"))for(;this._parent.lastChild;)d.destroy(this._parent.lastChild);else this._parent.innerHTML="";this._parent=null},getEventSource:function(){return this.rawNode},
_getRealMatrix:function(){return null},isLoaded:!0,onLoad:function(a){},whenLoaded:function(a,b){var c=s.hitch(a,b);if(this.isLoaded)c(this);else h.once(this,"load",function(a){c(a)})}});s.extend(n.Surface,n._eventsProcessing);n.Rect=m("dojox.gfx.shape.Rect",n.Shape,{constructor:function(a){this.shape=k.getDefault("Rect");this.rawNode=a},getBoundingBox:function(){return this.shape}});n.Ellipse=m("dojox.gfx.shape.Ellipse",n.Shape,{constructor:function(a){this.shape=k.getDefault("Ellipse");this.rawNode=
a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:a.cx-a.rx,y:a.cy-a.ry,width:2*a.rx,height:2*a.ry}}return this.bbox}});n.Circle=m("dojox.gfx.shape.Circle",n.Shape,{constructor:function(a){this.shape=k.getDefault("Circle");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r}}return this.bbox}});n.Line=m("dojox.gfx.shape.Line",n.Shape,{constructor:function(a){this.shape=k.getDefault("Line");this.rawNode=
a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:Math.min(a.x1,a.x2),y:Math.min(a.y1,a.y2),width:Math.abs(a.x2-a.x1),height:Math.abs(a.y2-a.y1)}}return this.bbox}});n.Polyline=m("dojox.gfx.shape.Polyline",n.Shape,{constructor:function(a){this.shape=k.getDefault("Polyline");this.rawNode=a},setShape:function(a,b){a&&a instanceof Array?(this.inherited(arguments,[{points:a}]),b&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):this.inherited(arguments,[a]);
return this},_normalizePoints:function(){var a=this.shape.points,b=a&&a.length;if(b&&"number"==typeof a[0]){for(var c=[],d=0;d<b;d+=2)c.push({x:a[d],y:a[d+1]});this.shape.points=c}},getBoundingBox:function(){if(!this.bbox&&this.shape.points.length){for(var a=this.shape.points,b=a.length,c=a[0],d=c.x,f=c.y,h=c.x,k=c.y,n=1;n<b;++n)c=a[n],d>c.x&&(d=c.x),h<c.x&&(h=c.x),f>c.y&&(f=c.y),k<c.y&&(k=c.y);this.bbox={x:d,y:f,width:h-d,height:k-f}}return this.bbox}});n.Image=m("dojox.gfx.shape.Image",n.Shape,
{constructor:function(a){this.shape=k.getDefault("Image");this.rawNode=a},getBoundingBox:function(){return this.shape},setStroke:function(){return this},setFill:function(){return this}});n.Text=m(n.Shape,{constructor:function(a){this.fontStyle=null;this.shape=k.getDefault("Text");this.rawNode=a},getFont:function(){return this.fontStyle},setFont:function(a){this.fontStyle="string"==typeof a?k.splitFontString(a):k.makeParameters(k.defaultFont,a);this._setFont();return this},getBoundingBox:function(){var a=
null;this.getShape().text&&(a=k._base._computeTextBoundingBox(this));return a}});n.Creator={createShape:function(a){switch(a.type){case k.defaultPath.type:return this.createPath(a);case k.defaultRect.type:return this.createRect(a);case k.defaultCircle.type:return this.createCircle(a);case k.defaultEllipse.type:return this.createEllipse(a);case k.defaultLine.type:return this.createLine(a);case k.defaultPolyline.type:return this.createPolyline(a);case k.defaultImage.type:return this.createImage(a);
case k.defaultText.type:return this.createText(a);case k.defaultTextPath.type:return this.createTextPath(a)}return null},createGroup:function(){return this.createObject(k.Group)},createRect:function(a){return this.createObject(k.Rect,a)},createEllipse:function(a){return this.createObject(k.Ellipse,a)},createCircle:function(a){return this.createObject(k.Circle,a)},createLine:function(a){return this.createObject(k.Line,a)},createPolyline:function(a){return this.createObject(k.Polyline,a)},createImage:function(a){return this.createObject(k.Image,
a)},createText:function(a){return this.createObject(k.Text,a)},createPath:function(a){return this.createObject(k.Path,a)},createTextPath:function(a){return this.createObject(k.TextPath,{}).setText(a)},createObject:function(a,b){return null}};return n})},"dojox/gfx/arc":function(){define(["./_base","dojo/_base/lang","./matrix"],function(k,s,m){function t(b){var c=Math.cos(b);b=Math.sin(b);var a={x:c+4/3*(1-c),y:b-4/3*c*(1-c)/b};return{s:{x:c,y:-b},c1:{x:a.x,y:-a.y},c2:a,e:{x:c,y:b}}}var u=2*Math.PI,
h=Math.PI/4,f=Math.PI/8,d=h+f,c=t(f);return k.arc={unitArcAsBezier:t,curvePI4:c,arcAsBezier:function(b,k,a,q,s,A,w,r){s=Boolean(s);A=Boolean(A);var l=m._degToRad(q);q=k*k;var B=a*a,v=m.multiplyPoint(m.rotate(-l),{x:(b.x-w)/2,y:(b.y-r)/2}),z=v.x*v.x,G=v.y*v.y;q=Math.sqrt((q*B-q*G-B*z)/(q*G+B*z));isNaN(q)&&(q=0);q={x:q*k*v.y/a,y:-q*a*v.x/k};s==A&&(q={x:-q.x,y:-q.y});q=m.multiplyPoint([m.translate((b.x+w)/2,(b.y+r)/2),m.rotate(l)],q);k=m.normalize([m.translate(q.x,q.y),m.rotate(l),m.scale(k,a)]);q=m.invert(k);
b=m.multiplyPoint(q,b);r=m.multiplyPoint(q,w,r);w=Math.atan2(b.y,b.x);r=Math.atan2(r.y,r.x);q=w-r;A&&(q=-q);0>q?q+=u:q>u&&(q-=u);a=f;r=c;a=A?a:-a;b=[];for(s=q;0<s;s-=h)s<d&&(a=s/2,r=t(a),a=A?a:-a,s=0),v=m.normalize([k,m.rotate(w+a)]),A?(q=m.multiplyPoint(v,r.c1),l=m.multiplyPoint(v,r.c2),v=m.multiplyPoint(v,r.e)):(q=m.multiplyPoint(v,r.c2),l=m.multiplyPoint(v,r.c1),v=m.multiplyPoint(v,r.s)),b.push([q.x,q.y,l.x,l.y,v.x,v.y]),w+=2*a;return b}}})},"dojox/gfx/path":function(){define(["./_base","dojo/_base/lang",
"dojo/_base/declare","./matrix","./shape"],function(k,s,m,t,u){u=m("dojox.gfx.path.Path",u.Shape,{constructor:function(h){this.shape=s.clone(k.defaultPath);this.segments=[];this.tbbox=null;this.absolute=!0;this.last={};this.rawNode=h;this.segmented=!1},setAbsoluteMode:function(h){this._confirmSegmented();this.absolute="string"==typeof h?"absolute"==h:h;return this},getAbsoluteMode:function(){this._confirmSegmented();return this.absolute},getBoundingBox:function(){this._confirmSegmented();return this.bbox&&
"l"in this.bbox?{x:this.bbox.l,y:this.bbox.t,width:this.bbox.r-this.bbox.l,height:this.bbox.b-this.bbox.t}:null},_getRealBBox:function(){this._confirmSegmented();if(this.tbbox)return this.tbbox;var h=this.bbox,f=this._getRealMatrix();this.bbox=null;for(var d=0,c=this.segments.length;d<c;++d)this._updateWithSegment(this.segments[d],f);f=this.bbox;this.bbox=h;return this.tbbox=f?[{x:f.l,y:f.t},{x:f.r,y:f.t},{x:f.r,y:f.b},{x:f.l,y:f.b}]:null},getLastPosition:function(){this._confirmSegmented();return"x"in
this.last?this.last:null},_applyTransform:function(){this.tbbox=null;return this.inherited(arguments)},_updateBBox:function(h,f,d){d&&(f=t.multiplyPoint(d,h,f),h=f.x,f=f.y);this.bbox&&"l"in this.bbox?(this.bbox.l>h&&(this.bbox.l=h),this.bbox.r<h&&(this.bbox.r=h),this.bbox.t>f&&(this.bbox.t=f),this.bbox.b<f&&(this.bbox.b=f)):this.bbox={l:h,b:f,r:h,t:f}},_updateWithSegment:function(h,f){var d=h.args,c=d.length,b;switch(h.action){case "M":case "L":case "C":case "S":case "Q":case "T":for(b=0;b<c;b+=2)this._updateBBox(d[b],
d[b+1],f);this.last.x=d[c-2];this.last.y=d[c-1];this.absolute=!0;break;case "H":for(b=0;b<c;++b)this._updateBBox(d[b],this.last.y,f);this.last.x=d[c-1];this.absolute=!0;break;case "V":for(b=0;b<c;++b)this._updateBBox(this.last.x,d[b],f);this.last.y=d[c-1];this.absolute=!0;break;case "m":b=0;"x"in this.last||(this._updateBBox(this.last.x=d[0],this.last.y=d[1],f),b=2);for(;b<c;b+=2)this._updateBBox(this.last.x+=d[b],this.last.y+=d[b+1],f);this.absolute=!1;break;case "l":case "t":for(b=0;b<c;b+=2)this._updateBBox(this.last.x+=
d[b],this.last.y+=d[b+1],f);this.absolute=!1;break;case "h":for(b=0;b<c;++b)this._updateBBox(this.last.x+=d[b],this.last.y,f);this.absolute=!1;break;case "v":for(b=0;b<c;++b)this._updateBBox(this.last.x,this.last.y+=d[b],f);this.absolute=!1;break;case "c":for(b=0;b<c;b+=6)this._updateBBox(this.last.x+d[b],this.last.y+d[b+1],f),this._updateBBox(this.last.x+d[b+2],this.last.y+d[b+3],f),this._updateBBox(this.last.x+=d[b+4],this.last.y+=d[b+5],f);this.absolute=!1;break;case "s":case "q":for(b=0;b<c;b+=
4)this._updateBBox(this.last.x+d[b],this.last.y+d[b+1],f),this._updateBBox(this.last.x+=d[b+2],this.last.y+=d[b+3],f);this.absolute=!1;break;case "A":for(b=0;b<c;b+=7)this._updateBBox(d[b+5],d[b+6],f);this.last.x=d[c-2];this.last.y=d[c-1];this.absolute=!0;break;case "a":for(b=0;b<c;b+=7)this._updateBBox(this.last.x+=d[b+5],this.last.y+=d[b+6],f);this.absolute=!1}var m=[h.action];for(b=0;b<c;++b)m.push(k.formatNumber(d[b],!0));if("string"==typeof this.shape.path)this.shape.path+=m.join("");else{b=
0;for(c=m.length;b<c;++b)this.shape.path.push(m[b])}},_validSegments:{m:2,l:2,h:1,v:1,c:6,s:4,q:4,t:2,a:7,z:0},_pushSegment:function(h,f){this.tbbox=null;var d=this._validSegments[h.toLowerCase()];"number"==typeof d&&(d?f.length>=d&&(d={action:h,args:f.slice(0,f.length-f.length%d)},this.segments.push(d),this._updateWithSegment(d)):(d={action:h,args:[]},this.segments.push(d),this._updateWithSegment(d)))},_collectArgs:function(h,f){for(var d=0;d<f.length;++d){var c=f[d];"boolean"==typeof c?h.push(c?
1:0):"number"==typeof c?h.push(c):c instanceof Array?this._collectArgs(h,c):"x"in c&&"y"in c&&h.push(c.x,c.y)}},moveTo:function(){this._confirmSegmented();var h=[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?"M":"m",h);return this},lineTo:function(){this._confirmSegmented();var h=[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?"L":"l",h);return this},hLineTo:function(){this._confirmSegmented();var h=[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?
"H":"h",h);return this},vLineTo:function(){this._confirmSegmented();var h=[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?"V":"v",h);return this},curveTo:function(){this._confirmSegmented();var h=[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?"C":"c",h);return this},smoothCurveTo:function(){this._confirmSegmented();var h=[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?"S":"s",h);return this},qCurveTo:function(){this._confirmSegmented();var h=
[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?"Q":"q",h);return this},qSmoothCurveTo:function(){this._confirmSegmented();var h=[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?"T":"t",h);return this},arcTo:function(){this._confirmSegmented();var h=[];this._collectArgs(h,arguments);this._pushSegment(this.absolute?"A":"a",h);return this},closePath:function(){this._confirmSegmented();this._pushSegment("Z",[]);return this},_confirmSegmented:function(){if(!this.segmented){var h=
this.shape.path;this.shape.path=[];this._setPath(h);this.shape.path=this.shape.path.join("");this.segmented=!0}},_setPath:function(h){h=s.isArray(h)?h:h.match(k.pathSvgRegExp);this.segments=[];this.absolute=!0;this.bbox={};this.last={};if(h){for(var f="",d=[],c=h.length,b=0;b<c;++b){var m=h[b],a=parseFloat(m);isNaN(a)?(f&&this._pushSegment(f,d),d=[],f=m):d.push(a)}this._pushSegment(f,d)}},setShape:function(h){this.inherited(arguments,["string"==typeof h?{path:h}:h]);this.segmented=!1;this.segments=
[];k.lazyPathSegmentation||this._confirmSegmented();return this},_2PI:2*Math.PI});m=m("dojox.gfx.path.TextPath",u,{constructor:function(h){"text"in this||(this.text=s.clone(k.defaultTextPath));"fontStyle"in this||(this.fontStyle=s.clone(k.defaultFont))},getText:function(){return this.text},setText:function(h){this.text=k.makeParameters(this.text,"string"==typeof h?{text:h}:h);this._setText();return this},getFont:function(){return this.fontStyle},setFont:function(h){this.fontStyle="string"==typeof h?
k.splitFontString(h):k.makeParameters(k.defaultFont,h);this._setFont();return this}});return k.path={Path:u,TextPath:m}})},"*noref":1}});
define("dojox/gfx/canvas","./_base dojo/_base/lang dojo/_base/array dojo/_base/declare dojo/_base/window dojo/dom-geometry dojo/dom ./shape ./path ./arc ./matrix ./decompose ./bezierutils".split(" "),function(k,s,m,t,u,h,f,d,c,b,n,a,q){function y(x,g,e,a,b,c,d,f,h,k){var m,l,q=g.length,n=0;k?(l=k.l/b,n=k.i):l=g[0]/b;for(;c<d;)c+l>d&&(m={l:(c+l-d)*b,i:n},l=d-c),n%2||(x.beginPath(),x.arc(e,a,b,c,c+l,f),h&&x.stroke()),c+=l,++n,l=g[n%q]/b;return m}function A(x,g,e,a){var b=0,c=0,d,f=0;a?(d=a.l,f=a.i):
d=g[0];for(;1>c;)c=q.tAtLength(x,d),1==c&&(b=q.computeLength(x),b={l:d-b,i:f}),x=q.splitBezierAtT(x,c),f%2||e.push(x[0]),x=x[1],++f,d=g[f%g.length];return b}function w(x,g,e,a){var b=[g.last.x,g.last.y].concat(e),c=!(x instanceof Array);e=4===e.length?"quadraticCurveTo":"bezierCurveTo";var d=[];g=A(b,g.canvasDash,d,a);for(a=0;a<d.length;++a)b=d[a],c?(x.moveTo(b[0],b[1]),x[e].apply(x,b.slice(2))):(x.push("moveTo",[b[0],b[1]]),x.push(e,b.slice(2)));return g}function r(a,g,e,b,c,d,f){var h=0,k=0,l=0,
m=q.distance(e,b,c,d),n=0;g=g.canvasDash;var r=e,s=b,t,u=!(a instanceof Array);f?(l=f.l,n=f.i):l+=g[0];for(;0.01<Math.abs(1-k);)l>m&&(h={l:l-m,i:n},l=m),k=l/m,f=e+(c-e)*k,t=b+(d-b)*k,n++%2||(u?(a.moveTo(r,s),a.lineTo(f,t)):(a.push("moveTo",[r,s]),a.push("lineTo",[f,t]))),r=f,s=t,l+=g[n%g.length];return h}var l=k.canvas={},B=null,v=n.multiplyPoint,z=Math.PI,G=2*z,C=z/2;a=s.extend;if(u.global.CanvasRenderingContext2D){u=u.doc.createElement("canvas").getContext("2d");var H="function"==typeof u.setLineDash,
K="function"==typeof u.fillText}var J={solid:"none",shortdash:[4,1],shortdot:[1,1],shortdashdot:[4,1,1,1],shortdashdotdot:[4,1,1,1,1,1],dot:[1,3],dash:[4,3],longdash:[8,3],dashdot:[4,3,1,3],longdashdot:[8,3,1,3],longdashdotdot:[8,3,1,3,1,3]};l.Shape=t("dojox.gfx.canvas.Shape",d.Shape,{_render:function(a){a.save();this._renderTransform(a);this._renderClip(a);this._renderShape(a);this._renderFill(a,!0);this._renderStroke(a,!0);a.restore()},_renderClip:function(a){this.canvasClip&&(this.canvasClip.render(a),
a.clip())},_renderTransform:function(a){if("canvasTransform"in this){var g=this.canvasTransform;a.translate(g.dx,g.dy);a.rotate(g.angle2);a.scale(g.sx,g.sy);a.rotate(g.angle1)}},_renderShape:function(a){},_renderFill:function(a,g){if("canvasFill"in this){var e=this.fillStyle;if("canvasFillImage"in this){var b=e.width,c=e.height,d=this.canvasFillImage.width,f=this.canvasFillImage.height,h=Math.min(b==d?1:b/d,c==f?1:c/f),k=(b-h*d)/2,l=(c-h*f)/2;B.width=b;B.height=c;var m=B.getContext("2d");m.clearRect(0,
0,b,c);m.drawImage(this.canvasFillImage,0,0,d,f,k,l,h*d,h*f);this.canvasFill=a.createPattern(B,"repeat");delete this.canvasFillImage}a.fillStyle=this.canvasFill;g&&("pattern"===e.type&&(0!==e.x||0!==e.y)&&a.translate(e.x,e.y),a.fill())}else a.fillStyle="rgba(0,0,0,0.0)"},_renderStroke:function(a,g){var e=this.strokeStyle;e?(a.strokeStyle=e.color.toString(),a.lineWidth=e.width,a.lineCap=e.cap,"number"==typeof e.join?(a.lineJoin="miter",a.miterLimit=e.join):a.lineJoin=e.join,this.canvasDash?H?(a.setLineDash(this.canvasDash),
g&&a.stroke()):this._renderDashedStroke(a,g):g&&a.stroke()):g||(a.strokeStyle="rgba(0,0,0,0.0)")},_renderDashedStroke:function(a,g){},getEventSource:function(){return null},on:function(){},connect:function(){},disconnect:function(){},canvasClip:null,setClip:function(a){this.inherited(arguments);var g=a?"width"in a?"rect":"cx"in a?"ellipse":"points"in a?"polyline":"d"in a?"path":null:null;if(a&&!g)return this;this.canvasClip=a?L(g,a):null;this.parent&&this.parent._makeDirty();return this}});var L=
function(a,g){switch(a){case "ellipse":return{canvasEllipse:I({shape:g}),render:function(a){return l.Ellipse.prototype._renderShape.call(this,a)}};case "rect":return{shape:s.delegate(g,{r:0}),render:function(a){return l.Rect.prototype._renderShape.call(this,a)}};case "path":return{canvasPath:M(g),render:function(a){this.canvasPath._renderShape(a)}};case "polyline":return{canvasPolyline:g.points,render:function(a){return l.Polyline.prototype._renderShape.call(this,a)}}}return null},M=function(a){var g=
new dojox.gfx.canvas.Path;g.canvasPath=[];g._setPath(a.d);return g},E=function(a,g,e){var b=a.prototype[g];a.prototype[g]=e?function(){this.parent&&this.parent._makeDirty();b.apply(this,arguments);e.call(this);return this}:function(){this.parent&&this.parent._makeDirty();return b.apply(this,arguments)}};E(l.Shape,"setTransform",function(){this.matrix?this.canvasTransform=k.decompose(this.matrix):delete this.canvasTransform});E(l.Shape,"setFill",function(){var a=this.fillStyle,g;if(a){if("object"==
typeof a&&"type"in a){var e=this.surface.rawNode.getContext("2d");switch(a.type){case "linear":case "radial":g="linear"==a.type?e.createLinearGradient(a.x1,a.y1,a.x2,a.y2):e.createRadialGradient(a.cx,a.cy,0,a.cx,a.cy,a.r);m.forEach(a.colors,function(a){g.addColorStop(a.offset,k.normalizeColor(a.color).toString())});break;case "pattern":B||(B=document.createElement("canvas")),e=new Image,this.surface.downloadImage(e,a.src),this.canvasFillImage=e}}else g=a.toString();this.canvasFill=g}else delete this.canvasFill});
E(l.Shape,"setStroke",function(){var a=this.strokeStyle;if(a){var g=this.strokeStyle.style.toLowerCase();g in J&&(g=J[g]);if(g instanceof Array){this.canvasDash=g=g.slice();var e;for(e=0;e<g.length;++e)g[e]*=a.width;if("butt"!=a.cap){for(e=0;e<g.length;e+=2)g[e]-=a.width,1>g[e]&&(g[e]=1);for(e=1;e<g.length;e+=2)g[e]+=a.width}}else delete this.canvasDash}else delete this.canvasDash;this._needsDash=!H&&!!this.canvasDash});E(l.Shape,"setShape");l.Group=t("dojox.gfx.canvas.Group",l.Shape,{constructor:function(){d.Container._init.call(this)},
_render:function(a){a.save();this._renderTransform(a);this._renderClip(a);for(var g=0;g<this.children.length;++g)this.children[g]._render(a);a.restore()},destroy:function(){d.Container.clear.call(this,!0);l.Shape.prototype.destroy.apply(this,arguments)}});l.Rect=t("dojox.gfx.canvas.Rect",[l.Shape,d.Rect],{_renderShape:function(a){var g=this.shape,e=Math.min(g.r,g.height/2,g.width/2),b=g.x,c=b+g.width,d=g.y,g=d+g.height,f=b+e,h=c-e,k=d+e,l=g-e;a.beginPath();a.moveTo(f,d);e?(a.arc(h,k,e,-C,0,!1),a.arc(h,
l,e,0,C,!1),a.arc(f,l,e,C,z,!1),a.arc(f,k,e,z,z+C,!1)):(a.lineTo(h,d),a.lineTo(c,l),a.lineTo(f,g),a.lineTo(b,k));a.closePath()},_renderDashedStroke:function(a,g){var e=this.shape,b=Math.min(e.r,e.height/2,e.width/2),c=e.x,d=c+e.width,f=e.y,h=f+e.height,k=c+b,l=d-b,m=f+b,n=h-b;b?(a.beginPath(),e=r(a,this,k,f,l,f),g&&a.stroke(),e=y(a,this.canvasDash,l,m,b,-C,0,!1,g,e),a.beginPath(),e=r(a,this,d,m,d,n,e),g&&a.stroke(),e=y(a,this.canvasDash,l,n,b,0,C,!1,g,e),a.beginPath(),e=r(a,this,l,h,k,h,e),g&&a.stroke(),
e=y(a,this.canvasDash,k,n,b,C,z,!1,g,e),a.beginPath(),e=r(a,this,c,n,c,m,e),g&&a.stroke(),y(a,this.canvasDash,k,m,b,z,z+C,!1,g,e)):(a.beginPath(),e=r(a,this,k,f,l,f),e=r(a,this,l,f,d,n,e),e=r(a,this,d,n,k,h,e),r(a,this,k,h,c,m,e),g&&a.stroke())}});var D=[];(function(){var a=b.curvePI4;D.push(a.s,a.c1,a.c2,a.e);for(var g=45;360>g;g+=45){var e=n.rotateg(g);D.push(v(e,a.c1),v(e,a.c2),v(e,a.e))}})();var I=function(a){var g,e,b,c=[],d=a.shape,f=n.normalize([n.translate(d.cx,d.cy),n.scale(d.rx,d.ry)]);
g=v(f,D[0]);c.push([g.x,g.y]);for(d=1;d<D.length;d+=3)e=v(f,D[d]),b=v(f,D[d+1]),g=v(f,D[d+2]),c.push([e.x,e.y,b.x,b.y,g.x,g.y]);if(a._needsDash){g=[];e=c[0];for(d=1;d<c.length;++d)b=[],A(e.concat(c[d]),a.canvasDash,b),e=[c[d][4],c[d][5]],g.push(b);a._dashedPoints=g}return c};l.Ellipse=t("dojox.gfx.canvas.Ellipse",[l.Shape,d.Ellipse],{setShape:function(){this.inherited(arguments);this.canvasEllipse=I(this);return this},setStroke:function(){this.inherited(arguments);H||(this.canvasEllipse=I(this));
return this},_renderShape:function(a){var g=this.canvasEllipse,e;a.beginPath();a.moveTo.apply(a,g[0]);for(e=1;e<g.length;++e)a.bezierCurveTo.apply(a,g[e]);a.closePath()},_renderDashedStroke:function(a,g){var e=this._dashedPoints;a.beginPath();for(var b=0;b<e.length;++b)for(var c=e[b],d=0;d<c.length;++d){var f=c[d];a.moveTo(f[0],f[1]);a.bezierCurveTo(f[2],f[3],f[4],f[5],f[6],f[7])}g&&a.stroke()}});l.Circle=t("dojox.gfx.canvas.Circle",[l.Shape,d.Circle],{_renderShape:function(a){var g=this.shape;a.beginPath();
a.arc(g.cx,g.cy,g.r,0,G,1)},_renderDashedStroke:function(a,g){var e=this.shape,b=0,c,d=this.canvasDash.length;for(i=0;b<G;)c=this.canvasDash[i%d]/e.r,i%2||(a.beginPath(),a.arc(e.cx,e.cy,e.r,b,b+c,0),g&&a.stroke()),b+=c,++i}});l.Line=t("dojox.gfx.canvas.Line",[l.Shape,d.Line],{_renderShape:function(a){var g=this.shape;a.beginPath();a.moveTo(g.x1,g.y1);a.lineTo(g.x2,g.y2)},_renderDashedStroke:function(a,g){var e=this.shape;a.beginPath();r(a,this,e.x1,e.y1,e.x2,e.y2);g&&a.stroke()}});l.Polyline=t("dojox.gfx.canvas.Polyline",
[l.Shape,d.Polyline],{setShape:function(){this.inherited(arguments);var a=this.shape.points,g=a[0],e,b;this.bbox=null;this._normalizePoints();if(a.length)if("number"==typeof g)g=a;else{g=[];for(b=0;b<a.length;++b)e=a[b],g.push(e.x,e.y)}else g=[];this.canvasPolyline=g;return this},_renderShape:function(a){var g=this.canvasPolyline;if(g.length){a.beginPath();a.moveTo(g[0],g[1]);for(var e=2;e<g.length;e+=2)a.lineTo(g[e],g[e+1])}},_renderDashedStroke:function(a,g){var e=this.canvasPolyline,b=0;a.beginPath();
for(var c=0;c<e.length;c+=2)b=r(a,this,e[c],e[c+1],e[c+2],e[c+3],b);g&&a.stroke()}});l.Image=t("dojox.gfx.canvas.Image",[l.Shape,d.Image],{setShape:function(){this.inherited(arguments);var a=new Image;this.surface.downloadImage(a,this.shape.src);this.canvasImage=a;return this},_renderShape:function(a){var g=this.shape;a.drawImage(this.canvasImage,g.x,g.y,g.width,g.height)}});l.Text=t("dojox.gfx.canvas.Text",[l.Shape,d.Text],{_setFont:function(){this.fontStyle?this.canvasFont=k.makeFontString(this.fontStyle):
delete this.canvasFont},getTextWidth:function(){var a=this.shape,g=0,e;a.text&&(e=this.surface.rawNode.getContext("2d"),e.save(),this._renderTransform(e),this._renderFill(e,!1),this._renderStroke(e,!1),this.canvasFont&&(e.font=this.canvasFont),g=e.measureText(a.text).width,e.restore());return g},_render:function(a){a.save();this._renderTransform(a);this._renderFill(a,!1);this._renderStroke(a,!1);this._renderShape(a);a.restore()},_renderShape:function(a){var g,e=this.shape;e.text&&(g="middle"===e.align?
"center":e.align,a.textAlign=g,this.canvasFont&&(a.font=this.canvasFont),this.canvasFill&&a.fillText(e.text,e.x,e.y),this.strokeStyle&&(a.beginPath(),a.strokeText(e.text,e.x,e.y),a.closePath()))}});E(l.Text,"setFont");K||l.Text.extend({getTextWidth:function(){return 0},getBoundingBox:function(){return null},_renderShape:function(){}});var N={M:"_moveToA",m:"_moveToR",L:"_lineToA",l:"_lineToR",H:"_hLineToA",h:"_hLineToR",V:"_vLineToA",v:"_vLineToR",C:"_curveToA",c:"_curveToR",S:"_smoothCurveToA",s:"_smoothCurveToR",
Q:"_qCurveToA",q:"_qCurveToR",T:"_qSmoothCurveToA",t:"_qSmoothCurveToR",A:"_arcTo",a:"_arcTo",Z:"_closePath",z:"_closePath"};l.Path=t("dojox.gfx.canvas.Path",[l.Shape,c.Path],{constructor:function(){this.lastControl={}},setShape:function(){this.canvasPath=[];this._dashedPath=[];return this.inherited(arguments)},setStroke:function(){this.inherited(arguments);H||(this.segmented=!1,this._confirmSegmented());return this},_setPath:function(){this._dashResidue=null;this.inherited(arguments)},_updateWithSegment:function(a){var g=
s.clone(this.last);this[N[a.action]](this.canvasPath,a.action,a.args,this._needsDash?this._dashedPath:null);this.last=g;this.inherited(arguments)},_renderShape:function(a){var g=this.canvasPath;a.beginPath();for(var e=0;e<g.length;e+=2)a[g[e]].apply(a,g[e+1])},_renderDashedStroke:H?function(){}:function(a,g){var e=this._dashedPath;a.beginPath();for(var b=0;b<e.length;b+=2)a[e[b]].apply(a,e[b+1]);g&&a.stroke()},_moveToA:function(a,b,e,c){a.push("moveTo",[e[0],e[1]]);c&&c.push("moveTo",[e[0],e[1]]);
for(b=2;b<e.length;b+=2)a.push("lineTo",[e[b],e[b+1]]),c&&(this._dashResidue=r(c,this,e[b-2],e[b-1],e[b],e[b+1],this._dashResidue));this.last.x=e[e.length-2];this.last.y=e[e.length-1];this.lastControl={}},_moveToR:function(a,b,e,c){b="x"in this.last?[this.last.x+=e[0],this.last.y+=e[1]]:[this.last.x=e[0],this.last.y=e[1]];a.push("moveTo",b);c&&c.push("moveTo",b);for(b=2;b<e.length;b+=2)a.push("lineTo",[this.last.x+=e[b],this.last.y+=e[b+1]]),c&&(this._dashResidue=r(c,this,c[c.length-1][0],c[c.length-
1][1],this.last.x,this.last.y,this._dashResidue));this.lastControl={}},_lineToA:function(a,b,e,c){for(b=0;b<e.length;b+=2)c&&(this._dashResidue=r(c,this,this.last.x,this.last.y,e[b],e[b+1],this._dashResidue)),a.push("lineTo",[e[b],e[b+1]]);this.last.x=e[e.length-2];this.last.y=e[e.length-1];this.lastControl={}},_lineToR:function(a,b,e,c){for(b=0;b<e.length;b+=2)a.push("lineTo",[this.last.x+=e[b],this.last.y+=e[b+1]]),c&&(this._dashResidue=r(c,this,c[c.length-1][0],c[c.length-1][1],this.last.x,this.last.y,
this._dashResidue));this.lastControl={}},_hLineToA:function(a,b,e,c){for(b=0;b<e.length;++b)a.push("lineTo",[e[b],this.last.y]),c&&(this._dashResidue=r(c,this,c[c.length-1][0],c[c.length-1][1],e[b],this.last.y,this._dashResidue));this.last.x=e[e.length-1];this.lastControl={}},_hLineToR:function(a,b,e,c){for(b=0;b<e.length;++b)a.push("lineTo",[this.last.x+=e[b],this.last.y]),c&&(this._dashResidue=r(c,this,c[c.length-1][0],c[c.length-1][1],this.last.x,this.last.y,this._dashResidue));this.lastControl=
{}},_vLineToA:function(a,b,e,c){for(b=0;b<e.length;++b)a.push("lineTo",[this.last.x,e[b]]),c&&(this._dashResidue=r(c,this,c[c.length-1][0],c[c.length-1][1],this.last.x,e[b],this._dashResidue));this.last.y=e[e.length-1];this.lastControl={}},_vLineToR:function(a,b,e,c){for(b=0;b<e.length;++b)a.push("lineTo",[this.last.x,this.last.y+=e[b]]),c&&(this._dashResidue=r(c,this,c[c.length-1][0],c[c.length-1][1],this.last.x,this.last.y,this._dashResidue));this.lastControl={}},_curveToA:function(a,b,c,d){for(b=
0;b<c.length;b+=6)a.push("bezierCurveTo",c.slice(b,b+6)),d&&(this._dashResidue=w(d,this,a[a.length-1],this._dashResidue));this.last.x=c[c.length-2];this.last.y=c[c.length-1];this.lastControl.x=c[c.length-4];this.lastControl.y=c[c.length-3];this.lastControl.type="C"},_curveToR:function(a,b,c,d){for(b=0;b<c.length;b+=6)a.push("bezierCurveTo",[this.last.x+c[b],this.last.y+c[b+1],this.lastControl.x=this.last.x+c[b+2],this.lastControl.y=this.last.y+c[b+3],this.last.x+c[b+4],this.last.y+c[b+5]]),d&&(this._dashResidue=
w(d,this,a[a.length-1],this._dashResidue)),this.last.x+=c[b+4],this.last.y+=c[b+5];this.lastControl.type="C"},_smoothCurveToA:function(a,b,c,d){for(b=0;b<c.length;b+=4){var f="C"==this.lastControl.type;a.push("bezierCurveTo",[f?2*this.last.x-this.lastControl.x:this.last.x,f?2*this.last.y-this.lastControl.y:this.last.y,c[b],c[b+1],c[b+2],c[b+3]]);d&&(this._dashResidue=w(d,this,a[a.length-1],this._dashResidue));this.lastControl.x=c[b];this.lastControl.y=c[b+1];this.lastControl.type="C"}this.last.x=
c[c.length-2];this.last.y=c[c.length-1]},_smoothCurveToR:function(a,b,c,d){for(b=0;b<c.length;b+=4){var f="C"==this.lastControl.type;a.push("bezierCurveTo",[f?2*this.last.x-this.lastControl.x:this.last.x,f?2*this.last.y-this.lastControl.y:this.last.y,this.last.x+c[b],this.last.y+c[b+1],this.last.x+c[b+2],this.last.y+c[b+3]]);d&&(this._dashResidue=w(d,this,a[a.length-1],this._dashResidue));this.lastControl.x=this.last.x+c[b];this.lastControl.y=this.last.y+c[b+1];this.lastControl.type="C";this.last.x+=
c[b+2];this.last.y+=c[b+3]}},_qCurveToA:function(a,b,c,d){for(b=0;b<c.length;b+=4)a.push("quadraticCurveTo",c.slice(b,b+4));d&&(this._dashResidue=w(d,this,a[a.length-1],this._dashResidue));this.last.x=c[c.length-2];this.last.y=c[c.length-1];this.lastControl.x=c[c.length-4];this.lastControl.y=c[c.length-3];this.lastControl.type="Q"},_qCurveToR:function(a,b,c,d){for(b=0;b<c.length;b+=4)a.push("quadraticCurveTo",[this.lastControl.x=this.last.x+c[b],this.lastControl.y=this.last.y+c[b+1],this.last.x+c[b+
2],this.last.y+c[b+3]]),d&&(this._dashResidue=w(d,this,a[a.length-1],this._dashResidue)),this.last.x+=c[b+2],this.last.y+=c[b+3];this.lastControl.type="Q"},_qSmoothCurveToA:function(a,b,c,d){for(b=0;b<c.length;b+=2){var f="Q"==this.lastControl.type;a.push("quadraticCurveTo",[this.lastControl.x=f?2*this.last.x-this.lastControl.x:this.last.x,this.lastControl.y=f?2*this.last.y-this.lastControl.y:this.last.y,c[b],c[b+1]]);d&&(this._dashResidue=w(d,this,a[a.length-1],this._dashResidue));this.lastControl.type=
"Q"}this.last.x=c[c.length-2];this.last.y=c[c.length-1]},_qSmoothCurveToR:function(a,b,c,d){for(b=0;b<c.length;b+=2){var f="Q"==this.lastControl.type;a.push("quadraticCurveTo",[this.lastControl.x=f?2*this.last.x-this.lastControl.x:this.last.x,this.lastControl.y=f?2*this.last.y-this.lastControl.y:this.last.y,this.last.x+c[b],this.last.y+c[b+1]]);d&&(this._dashResidue=w(d,this,a[a.length-1],this._dashResidue));this.lastControl.type="Q";this.last.x+=c[b];this.last.y+=c[b+1]}},_arcTo:function(a,c,d,f){c=
"a"==c;for(var h=0;h<d.length;h+=7){var k=d[h+5],l=d[h+6];c&&(k+=this.last.x,l+=this.last.y);var n=b.arcAsBezier(this.last,d[h],d[h+1],d[h+2],d[h+3]?1:0,d[h+4]?1:0,k,l);m.forEach(n,function(b){a.push("bezierCurveTo",b)});f&&(this._dashResidue=w(f,this,p,this._dashResidue));this.last.x=k;this.last.y=l}this.lastControl={}},_closePath:function(a,b,c,d){a.push("closePath",[]);d&&(this._dashResidue=r(d,this,this.last.x,this.last.y,d[1][0],d[1][1],this._dashResidue));this.lastControl={}}});m.forEach("moveTo lineTo hLineTo vLineTo curveTo smoothCurveTo qCurveTo qSmoothCurveTo arcTo closePath".split(" "),
function(a){E(l.Path,a)});l.TextPath=t("dojox.gfx.canvas.TextPath",[l.Shape,c.TextPath],{_renderShape:function(a){},_setText:function(){},_setFont:function(){}});l.Surface=t("dojox.gfx.canvas.Surface",d.Surface,{constructor:function(){d.Container._init.call(this);this.pendingImageCount=0;this.makeDirty()},destroy:function(){d.Container.clear.call(this,!0);this.inherited(arguments)},setDimensions:function(a,b){this.width=k.normalizedLength(a);this.height=k.normalizedLength(b);if(!this.rawNode)return this;
var c=!1;this.rawNode.width!=this.width&&(this.rawNode.width=this.width,c=!0);this.rawNode.height!=this.height&&(this.rawNode.height=this.height,c=!0);c&&this.makeDirty();return this},getDimensions:function(){return this.rawNode?{width:this.rawNode.width,height:this.rawNode.height}:null},_render:function(a){if(this.rawNode&&(a||!this.pendingImageCount))a=this.rawNode.getContext("2d"),a.clearRect(0,0,this.rawNode.width,this.rawNode.height),this.render(a),"pendingRender"in this&&(clearTimeout(this.pendingRender),
delete this.pendingRender)},render:function(a){a.save();for(var b=0;b<this.children.length;++b)this.children[b]._render(a);a.restore()},makeDirty:function(){!this.pendingImagesCount&&(!("pendingRender"in this)&&!this._batch)&&(this.pendingRender=setTimeout(s.hitch(this,this._render),0))},downloadImage:function(a,b){var c=s.hitch(this,this.onImageLoad);!this.pendingImageCount++&&"pendingRender"in this&&(clearTimeout(this.pendingRender),delete this.pendingRender);a.onload=c;a.onerror=c;a.onabort=c;
a.src=b},onImageLoad:function(){--this.pendingImageCount||(this.onImagesLoaded(),this._render())},onImagesLoaded:function(){},getEventSource:function(){return null},connect:function(){},disconnect:function(){},on:function(){}});l.createSurface=function(a,b,c){if(!b&&!c){var d=h.position(a);b=b||d.w;c=c||d.h}"number"==typeof b&&(b+="px");"number"==typeof c&&(c+="px");d=new l.Surface;a=f.byId(a);var m=a.ownerDocument.createElement("canvas");m.width=k.normalizedLength(b);m.height=k.normalizedLength(c);
a.appendChild(m);d.rawNode=m;d._parent=a;return d.surface=d};var F=d.Container;t={openBatch:function(){++this._batch;return this},closeBatch:function(){this._batch=0<this._batch?--this._batch:0;this._makeDirty();return this},_makeDirty:function(){this._batch||this.surface.makeDirty()},add:function(a){this._makeDirty();return F.add.apply(this,arguments)},remove:function(a,b){this._makeDirty();return F.remove.apply(this,arguments)},clear:function(){this._makeDirty();return F.clear.apply(this,arguments)},
getBoundingBox:F.getBoundingBox,_moveChildToFront:function(a){this._makeDirty();return F._moveChildToFront.apply(this,arguments)},_moveChildToBack:function(a){this._makeDirty();return F._moveChildToBack.apply(this,arguments)}};c={createObject:function(a,b){var c=new a;c.surface=this.surface;c.setShape(b);this.add(c);return c}};a(l.Group,t);a(l.Group,d.Creator);a(l.Group,c);a(l.Surface,t);a(l.Surface,d.Creator);a(l.Surface,c);l.fixTarget=function(a,b){return!0};return l});