define(
   ({
    _widgetLabel: "Tekenen",
    selectDrawMode: "Tekenmodus selecteren",
    clear: "Wissen",
    point: "Punt",
    line: "Lijn",
    polyline: "Polylijn",
    freehandPolyline: "Polylijn in vrije stijl",
    triangle: "Driehoek",
    extent: "Omhulsel",
    circle: "Cirkel",
    ellipse: "Ellips",
    polygon: "Veelhoek",
    freehandPolygon: "Veelhoek in vrije stijl",
    text: "Tekst",
    style: "Stijl",
    alpha: "Transparant",
    width: "Breedte",
    size: "Grootte",
    color: "Kleur",
    markerColor: "Kleur van markering",
    outlineColor: "Kleur omtreklijn",
    lineColor: "Lijnkleur",
    fillColor: "Opvulkleur",
    showMeasurements: "Metingen weergeven",
    areaUnits: "Oppervlakte-eenheden",
    distanceUnits: "Afstandseenheden",
    kilometers: "Kilometer",
    miles: "Mijl",
    meters: "Meter",
    feet: "Voet",
    yards: "Yard",
    squareKilometers: "Vierkante kilometer",
    squareMiles: "Vierkante mijl",
    acres: "Acres",
    hectares: "Hectare",
    squareMeters: "Vierkante meter",
    squareFeet: "Vierkante voet",
    squareYards: "Vierkante yard",
    undo: "Ongedaan maken",
    redo: "Opnieuw uitvoeren"
  })
);