define(
   ({
    addDistance: "Přidat jednotku délky",
    addArea: "Přidat jednotku plochy",
    label: "Štítek",
    abbr: "Zkratka",
    conversion: "Konverze",
    actions: "Akce",
    areaUnits: "Plošné jednotky",
    distanceUnits: "Jednotky délky",
    kilometers: "Kilometry",
    miles: "Míle",
    meters: "Metry",
    feet: "Stopy",
    yards: "Yardy",
    squareKilometers: "Čtvereční kilometry",
    squareMiles: "Čtvereční míle",
    acres: "Akry",
    hectares: "Hektary",
    squareMeters: "Čtvereční metry",
    squareFeet: "Čtvereční stopy",
    squareYards: "Čtvereční yardy",
    distance: "Vzdálenosti",
    area: "Plochy",
    kilometersAbbreviation: "km",
    milesAbbreviation: "míle",
    metersAbbreviation: "m",
    feetAbbreviation: "stopy",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "čtver. km",
    squareMilesAbbreviation: "čtver. míl.",
    acresAbbreviation: "akr",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "čtver. m",
    squareFeetAbbreviation: "čtver. stopy",
    squareYardsAbbreviation: "čtver. yd."
  })
);