define(
   ({
    placeholder: "플레이스홀더 텍스트",
    url: "지오코더 URL",
    name: "지오코더 이름",
    example: "예",
    singleLineFieldName: "한 줄 필드 이름",
    portalConnectionError: '포털에서 지오코더 구성을 가져올 수 없음',
    actions: "작업",
    warning: "지원되는 지오코드 서비스 버전이 아닙니다. 이 위젯은 지오코딩 서비스 10.1 이상을 지원합니다.",
    instruction: "이 위젯에서 지오코더를 설정합니다. 지오코더 추가를 클릭하여 URL을 참조하고, 사용자에게 친숙한 이름을 지정하고, 기타 등록정보를 설정하세요. 또한 아래의 지오코더를 재정렬, 구성하거나 삭제할 수 있습니다.",
    layerInstruction1: "다음에서 검색 조건을 구성할 수 있습니다. ",
    layerInstruction2: "웹 맵의 세부정보 페이지",
    searchAddress: "주소 기준 검색",
    searchLayer: "레이어 기준 검색",
    layer: "레이어",
    field: "필드",
    condition: "조건",
    contains: "포함",
    deleteLastGeocoderError: "마지막 지오코더를 삭제할 수 없습니다.",
    noSearchFactorError: "최소 하나의 기능(주소 기준 검색 또는 레이어 기준 검색)을 선택해야 합니다.",
    equals: "같음",
    add: "지오코더 추가",
    edit: "지오코더 편집",
    ok: "확인",
    cancel: "취소",
    geocoderNamePlaceHolder: "내 지오코더",
    geocodePlaceHolder: "주소 또는 위치 찾기",
    REPEATING_ERROR: "다음 필드가 반복됨: "
  })
);