// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/_coremap","require module dojo/_base/kernel dojo/_base/declare dojo/_base/connect dojo/_base/Deferred dojo/_base/lang dojo/_base/array dojo/_base/event dojo/_base/unload dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/sniff dijit/registry dojox/gfx/matrix ./kernel ./config ./basemaps ./lang ./Evented ./fx ./deferredUtils ./tileUtils ./PluginTarget ./geometry/Point ./geometry/ScreenPoint ./geometry/Extent ./geometry/Rect ./geometry/mathUtils ./geometry/scaleUtils ./geometry/screenUtils ./geometry/webMercatorUtils ./layers/GraphicsLayer ./layers/TileInfo ./layers/LOD ./layers/ArcGISTiledMapServiceLayer ./layers/MapImageLayer ./layers/OpenStreetMapLayer ./dijit/Popup ./plugins/popupManager dojo/uacss".split(" "),
function(R,la,ma,U,z,ca,G,m,Ga,na,oa,pa,Z,H,V,W,M,qa,ra,sa,ta,D,s,ua,da,va,ea,wa,N,C,A,O,xa,I,fa,$,x,ya,za,Aa,Ba,ga,Ca){function ha(a,b){var c=a.lods;c.sort(function(a,b){return a.scale>b.scale?-1:a.scale<b.scale?1:0});var d=[],c=m.filter(c,function(a){if(-1===P(d,a.scale))return d.push(a.scale),!0}),e=b.lods=[],f;m.forEach(c,function(a,b){f=e[b]=new za(a);f.level=b});b.tileInfo=new ya(S(a,{lods:e}))}var aa,T=fa.toMapPoint,ba=fa.toScreenPoint,X=z.connect,Q=z.disconnect,B=G.hitch,F=W.set,P=m.indexOf,
S=G.mixin,Y=0,J=ta.defaults.map,ia=J.layerNamePrefix,ja=J.graphicsLayerNamePrefix,Da=RegExp("^"+ia+"(\\d+)$"),Ea=RegExp("^"+ja+"(\\d+)$"),Fa=function(){};U=U([ua,wa],{declaredClass:"esri._CoreMap",resizeDelay:300,invalidExtent:"Map does not have a valid extent.",invalidGeometry:"Geometry (wkid: ${geometry}) cannot be converted to spatial reference of the map (wkid: ${map})",unknownBasemap:'Unable to find basemap definition for: "${basemapName}". Try one of these: ${list}',invalidBasemap:'Unable to add basemap: "${basemapName}".',
unknownLayerType:'Unknown basemap layer type: "${type}" found in basemap definition for: "${basemapName}".',visible:!0,_eventMap:{"basemap-change":!0,"extent-change":["extent","delta","levelChange","lod"],"layer-add":["layer"],"layer-add-result":["layer","error"],"layer-remove":["layer"],"layer-reorder":["layer","index"],"layer-resume":["layer"],"layer-suspend":["layer"],"layers-add-result":["layers"],"layers-removed":!0,"layers-reordered":["layerIds"],load:["map"],pan:["extent","delta"],"pan-end":["extent",
"delta"],"pan-start":["extent","screenPoint"],reposition:["x","y"],resize:["extent","width","height"],scale:["matrix","immediate"],"time-extent-change":["timeExtent"],"before-unload":["map"],unload:["map"],"update-end":["error"],"update-start":!0,zoom:["extent","zoomFactor","anchor"],"zoom-end":["extent","zoomFactor","anchor","level"],"zoom-start":["extent","zoomFactor","anchor","level"],click:!0,"dbl-click":!0,"key-down":!0,"key-up":!0,"mouse-down":!0,"mouse-drag":!0,"mouse-drag-end":!0,"mouse-drag-start":!0,
"mouse-move":!0,"mouse-out":!0,"mouse-over":!0,"mouse-up":!0,"mouse-wheel":!0,"basic-tap":!0,"double-tap":!0,"pinch-end":!0,"pinch-move":!0,"pinch-start":!0,"processed-double-tap":!0,"processed-tap":!0,"swipe-end":!0,"swipe-move":!0,"swipe-start":!0,tap:!0,"two-finger-tap":!0},constructor:function(a,b){var c=this;this.registerConnectEvents();S(this,{_internalLayerIds:[],_layers:[],_layerDivs:[],_layerSize:0,_connects:[],_zoomAnimDiv:null,_zoomAnim:null,_layersDiv:null,_firstLayerId:null,_delta:null,
_cursor:null,_ratioW:1,_ratioH:1,_params:null,cursor:null,layerIds:[],graphicsLayerIds:[],graphics:null,_labels:null,loaded:!1,__panning:!1,__zooming:!1,__container:null,root:null,__LOD:null,__tileInfo:null,__visibleRect:null,__visibleDelta:null,_rids:[]});var d=this.container=oa.byId(a),e=this.id=pa.get(d,"id")||qa.getUniqueId(this.declaredClass);Z.add(d,"map");var f=V.getContentBox(d),g=Z.add,k=H.create;this.position=new C(0,0);this._reposition();var h=this.width=f.w||J.width,l=this.height=f.h||
J.height;0===f.w&&F(d,"width",h+"px");0===f.h&&F(d,"height",l+"px");var t=this.root=k("div",{id:e+"_root",style:{width:h+"px",height:l+"px",direction:"ltr"}});g(t,"container");f=this.__container=k("div",{id:e+"_container"},t);F(f,"position","absolute");g(f,"container");d.appendChild(t);d=this._params=S({slider:!0,nav:!1,zoom:-1,minZoom:-1,maxZoom:-1,scale:-1,minScale:0,maxScale:0,showInfoWindowOnClick:!0,displayGraphicsOnPan:!0,wrapAround180:!0,fitExtent:!1,optimizePanAnimation:!0},b||{});this.wrapAround180=
d.wrapAround180;this.optimizePanAnimation=d.optimizePanAnimation;s.isDefined(d.resizeDelay)&&(this.resizeDelay=d.resizeDelay);d.lods&&(ha({rows:512,cols:512,dpi:96,format:"JPEG",compressionQuality:75,origin:{x:-180,y:90},spatialReference:{wkid:4326},lods:d.lods},d),this.__tileInfo=d.tileInfo);this.extent=d.extent;this._extentUtil({mapCenter:d.center,targetLevel:d.zoom,targetScale:d.scale});this.__visibleRect=new O(0,0,h,l);this.__visibleDelta=new O(0,0,h,l);e=this._layersDiv=k("div",{id:e+"_layers"});
g(e,"layersDiv");f.appendChild(e);this._zoomAnimDiv=k("div",{style:{position:"absolute"}});d.infoWindow?this.infoWindow=d.infoWindow:(g=this.infoWindow=new Ca(d.popupOptions,k("div")),g.startup(),g._ootb=!0,F(g.domNode,"zIndex",40));d.showLabels&&(R(["./layers/LabelLayer"],function(a){aa=a;c._createLabelLayer()}),this.on("load",function(){c._createLabelLayer()}));this.addPlugin(this._getAbsMid("./plugins/popupManager"),{enabled:d.showInfoWindowOnClick});this._zoomStartHandler=B(this,this._zoomStartHandler);
this._zoomingHandler=B(this,this._zoomingHandler);this._zoomEndHandler=B(this,this._zoomEndHandler);this._panningHandler=B(this,this._panningHandler);this._panEndHandler=B(this,this._panEndHandler);this._endTranslate=B(this,this._endTranslate);na.addOnWindowUnload(this,this.destroy)},_getAbsMid:function(a){return R.toAbsMid?R.toAbsMid(a):la.id.replace(/\/[^\/]*$/ig,"/")+a},_cleanUp:function(){var a=this.infoWindow;a&&(a._ootb&&a.destroy?a.destroy():a.unsetMap(this),delete this.infoWindow);Q(this._tsTimeExtentChange_connect);
this.removePlugin("./plugins/popupManager");H.destroy(this.root);this.root=null},_addLayer:function(a,b,c){if(a.id){var d=a.id.match(a instanceof x?Ea:Da);d&&d[1]&&(d=Number(d[1]),Y<=d&&(Y=d+1))}var e=a.id||(a instanceof x?ja:ia)+Y++;a.id=e;this._layers[e]=a;var f,g;if(b===this.layerIds||b===this.graphicsLayerIds)f=this._layerSize,this._layerSize++;a._isRefLayer="top"===c;c=!s.isDefined(c)||0>c||c>b.length||"top"===c?b.length:c;0===f&&(this._firstLayerId=e);if(!a._isRefLayer)for(;(g=this.getLayer(b[c-
1]))&&g._isRefLayer;)c--;b.splice(c,0,e);var k=B(this,this._addLayerHandler),h=this;c=this._connects;d=function(){a.loaded?h._onLoadFix?(h._onLoadFix=!1,setTimeout(function(){k(a)},0)):k(a):(h["_"+e+"_addtoken_load"]=X(a,"onLoad",h,"_addLayerHandler"),h["_"+e+"_addtoken_err"]=X(a,"onError",h,function(c){k(a,c,b)}))};this.loaded||0===f||a.loaded&&-1===P(this.graphicsLayerIds,e)?d():c.push(X(this,"onLoad",d));return a},_addLayerHandler:function(a,b,c){var d=this.id,e=a.id,f=P(a instanceof x?this.graphicsLayerIds:
this.layerIds,e),g=f,k=!1,h=this._params;Q(this["_"+e+"_addtoken_load"]);Q(this["_"+e+"_addtoken_err"]);if(b)delete this._layers[e],-1!==f&&(c.splice(f,1),this.onLayerAddResult(a,b));else{-1===f&&(f=P(this._internalLayerIds,e),g=20+f,k=!0);if(e===this._firstLayerId){b=a.spatialReference;if((c=this.extent&&this.extent.spatialReference)&&!c.equals(b)&&(a.tileInfo||!a.url))c=null;c=this.spatialReference=c||b;this.wrapAround180=this.wrapAround180&&c&&c._isWrappable()?!0:!1;a.tileInfo&&(this.__tileInfo?
(b=this.__tileInfo.lods,this.__tileInfo=S({},a.tileInfo),this.__tileInfo.lods=b):(ha(S({},a.tileInfo),h),this.__tileInfo=h.tileInfo));if(this.wrapAround180){b=this.__tileInfo;c=c._getInfo();if(!b||Math.abs(c.origin[0]-b.origin.x)>c.dx)this.wrapAround180=!1;this.wrapAround180&&b&&ea._addFrameInfo(b,c)}h.units=a.units;if((b=this.__tileInfo&&this.__tileInfo.lods)&&b.length){c=h.minScale;var f=h.maxScale,l=-1,t=-1,n=!1,ka=!1,q;for(q=0;q<b.length;q++)0<c&&(!n&&c>=b[q].scale)&&(l=b[q].level,n=!0),0<f&&
(!ka&&f>=b[q].scale)&&(t=0<q?b[q-1].level:-1,ka=!0);-1===h.minZoom&&(h.minZoom=0===c?b[0].level:l);-1===h.maxZoom&&(h.maxZoom=0===f?b[b.length-1].level:t);for(q=0;q<b.length;q++)h.minZoom===b[q].level&&(h.minScale=b[q].scale),h.maxZoom===b[q].level&&(h.maxScale=b[q].scale)}else h.minZoom=h.maxZoom=h.zoom=-1}a instanceof x?(this._gc||(this._gc=new x._GraphicsContainer,this._gc._setMap(this,this._layersDiv).id=d+"_gc"),g=a._setMap(this,this._gc._surface),g.id=d+"_"+e,this._layerDivs[e]=g,this._reorderLayers(this.graphicsLayerIds)):
(g=a._setMap(this,this._layersDiv,g,this.__LOD),g.id=d+"_"+e,this._layerDivs[e]=g,this._reorderLayers(this.layerIds),!k&&-1!==a.declaredClass.indexOf("VETiledLayer")&&this._onBingLayerAdd(a));e===this._firstLayerId&&(this.graphics=new x({id:d+"_graphics",displayOnPan:h.displayGraphicsOnPan}),this._addLayer(this.graphics,this._internalLayerIds,20));if(a===this.graphics){c=this._layers[this._firstLayerId];d=h.zoom;g=h.scale;b=h.center;c=c.initialExtent||c.fullExtent;this._firstLayerId=null;this.extent&&
(this.extent=this._convertGeometry(this,this.extent));!this.extent&&c&&(b&&(b=this._convertGeometry(c,b)),b&&(c=c.centerAt(b)));if(b=this.extent||c&&new A(c.toJson()))-1<d?b=this.__getExtentForLevel(d,null,b).extent:0<g&&(b=I.getExtentForScale(this,g,b));if(!b){console.log("Map: "+this.invalidExtent);return}d=this._fixExtent(b,h.fitExtent);this.extent=d.extent;this.__LOD=d.lod;this.__setExtent(this.extent,null,null,h.fitExtent);this.loaded=!0;this.attr("data-loaded","");this.infoWindow.setMap(this);
this.onLoad(this)}k||(this.onLayerAdd(a),this.onLayerAddResult(a));Q(this[e+"_addLayerHandler_connect"])}},_convertGeometry:function(a,b){var c=a&&a.spatialReference,d=b&&b.spatialReference;c&&(d&&!c.equals(d))&&(c._canProject(d)?c.isWebMercator()?b=$.geographicToWebMercator(b):4326===c.wkid&&(b=$.webMercatorToGeographic(b,!0)):(console.log("Map: "+s.substitute({geometry:d.wkid||d.wkt,map:c.wkid||c.wkt},this.invalidGeometry)),b=null));return b},_reorderLayers:function(a){var b=this.onLayerReorder,
c=H.place,d=this._layerDivs,e=this._layers,f=this._gc?this._gc._surface.getEventSource():null;if(a===this.graphicsLayerIds)m.forEach(a,function(a,g){var h=d[a];h&&(c(h.getEventSource(),f,g),b(e[a],g))});else{var g=this.graphics,k=g?g.id:null,h=this._layersDiv,l;m.forEach(a,function(a,f){l=d[a];a!==k&&l&&(c(l,h,f),b(e[a],f))});this._mapImageLyr&&this._placeMapImageLyr();f&&(f=9>M("ie")?f.parentNode:f,c(f,f.parentNode,a.length))}this.onLayersReordered([].concat(a))},_zoomStartHandler:function(){this.__zoomStart(this._zoomAnimDiv.startingExtent,
this._zoomAnimDiv.anchor)},_zoomingHandler:function(a){var b=parseFloat(a.left),c=parseFloat(a.top);a=new A(b,c-parseFloat(a.height),b+parseFloat(a.width),c,this.spatialReference);b=this.extent.getWidth()/a.getWidth();this.__zoom(a,b,this._zoomAnimDiv.anchor)},_zoomEndHandler:function(){var a=this._zoomAnimDiv,b=a.extent,c=this.extent.getWidth()/b.getWidth(),d=a.anchor,e=a.newLod,f=a.levelChange;a.extent=a.anchor=a.levelChange=a.startingExtent=a.newLod=this._delta=this._zoomAnim=null;this.__zoomEnd(b,
c,d,e,f)},_panningHandler:function(a){if(isNaN(parseFloat(a.left))||isNaN(parseFloat(a.top))){var b=Math.round,c=this._panAnim.node;a.left=-1*(this._delta.x-b(this.width/2))+"px";a.top=-1*(this._delta.y-b(this.height/2))+"px";W.set(c,"left",a.left);W.set(c,"top",a.top)}a=new C(parseFloat(a.left),parseFloat(a.top));b=this.toMap(a);this.onPan(this.extent.offset(this.extent.xmin-b.x,this.extent.ymax-b.y),a)},_panEndHandler:function(a){this.__panning=!1;var b=Math.round;a=new C(-b(parseFloat(a.style.left)),
-b(parseFloat(a.style.top)));var b=a.x,c=a.y,d=this.__visibleRect,e=this.__visibleDelta;d.x+=-b;d.y+=-c;e.x+=-b;e.y+=-c;F(this._zoomAnimDiv,{left:"0px",top:"0px"});var d=this.extent,e=this._ratioW,f=this._ratioH,d=new A(d.xmin+b/e,d.ymin-c/f,d.xmax+b/e,d.ymax-c/f,this.spatialReference);a.setX(-a.x);a.setY(-a.y);this._delta=this._panAnim=null;this._updateExtent(d);this.onPanEnd(d,a);this._fireExtChg([d,a,!1,this.__LOD])},_fixExtent:function(a,b){for(var c=this._reshapeExtent(a),d=1.25;!0===b&&(c.extent.getWidth()<
a.getWidth()||c.extent.getHeight()<a.getHeight())&&0<c.lod.level&&3>=d;)c=this._reshapeExtent(a.expand(d)),d+=0.25;return c},_getFrameWidth:function(){var a=-1,b=this.spatialReference._getInfo();this.__LOD?(b=this.__LOD._frameInfo)&&(a=b[3]):b&&(a=Math.round(2*b.valid[1]/(this.extent.getWidth()/this.width)));return a},_fixAspectRatio:function(a){var b=a.getWidth(),c=a.getHeight(),d=b/c,e=this.width/this.height,f=0,g=0;this.width>this.height?b>c?e>d?f=c*e-b:g=b/e-c:f=c*e-b:this.width<this.height?b<
c?e>d?f=c*e-b:g=b/e-c:g=b/e-c:b<c?f=c-b:b>c&&(g=b/e-c);f&&(a.xmin-=f/2,a.xmax+=f/2);g&&(a.ymin-=g/2,a.ymax+=g/2);return a},_reshapeExtent:function(a){a=this._fixAspectRatio(a);return this._getAdjustedExtent(a)},_getAdjustedExtent:function(a){if(this.__tileInfo)return ea.getCandidateTileInfo(this,this.__tileInfo,a);var b=I.getScale(this,a),c=this.getMinScale(),d=this.getMaxScale(),e=!d||b>=d;c&&!(b<=c)?a=I.getExtentForScale(this,c,a):e||(a=I.getExtentForScale(this,d,a));return{extent:a}},_onBingLayerAdd:function(a){this["__"+
a.id+"_vis_connect"]=z.connect(a,"onVisibilityChange",this,"_toggleBingLogo");this._toggleBingLogo(a.visible)},_onBingLayerRemove:function(a){z.disconnect(this["__"+a.id+"_vis_connect"]);delete this["__"+a.id+"_vis_connect"];var b=m.some(this.layerIds,function(b){return(a=this._layers[b])&&a.visible&&-1!==a.declaredClass.indexOf("VETiledLayer")},this);this._toggleBingLogo(b)},_toggleBingLogo:function(a){a&&!this._bingLogo?(a={left:this._mapParams&&this._mapParams.nav?"25px":""},6===M("ie")&&(a.filter=
"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled\x3d'true', sizingMethod\x3d'crop', src\x3d'"+R.toUrl("./images/map/bing-logo-lg.png")+"')"),a=this._bingLogo=H.create("div",{style:a},this.root),Z.add(a,"bingLogo-lg")):!a&&this._bingLogo&&(H.destroy(this._bingLogo),delete this._bingLogo)},__panStart:function(a,b){var c=this._zoomAnim,d=this._panAnim;if(c&&c._active)c.stop(),c._fire("onEnd",[c.node]);else if(d&&d._active){d.stop();this._panAnim=null;var d=d.curve.getValue(d._getStep()),c=
Math.round(parseFloat(d.left)),d=Math.round(parseFloat(d.top)),e=this.navigationManager._dragOrigin;this.__pan(c,d);e&&(e.x-=c,e.y-=d);return}this.__panning=!0;this.onPanStart(this.extent,new C(a,b))},__pan:function(a,b){var c=this.extent,d=this._ratioW,e=this._ratioH;this.onPan(new A(c.xmin-a/d,c.ymin+b/e,c.xmax-a/d,c.ymax+b/e,this.spatialReference),new C(a,b))},__panEnd:function(a,b){var c=this.__visibleRect,d=this.__visibleDelta;c.x+=a;c.y+=b;d.x+=a;d.y+=b;var c=new C(a,b),d=this.extent,e=this._ratioW,
f=this._ratioH,d=new A(d.xmin-a/e,d.ymin+b/f,d.xmax-a/e,d.ymax+b/f,this.spatialReference);this.__panning=!1;this._updateExtent(d);this.onPanEnd(d,c);this._fireExtChg([d,c,!1,this.__LOD])},__zoomStart:function(a,b){this.__zooming=!0;this.onZoomStart(a,1,b,this.__LOD?this.__LOD.level:null)},__zoom:function(a,b,c){this.onZoom(a,b,c)},__zoomEnd:function(a,b,c,d,e){F(this._layersDiv,{left:"0px",top:"0px"});this._delta=new C(0,0);this.__visibleRect.x=this.__visibleRect.y=0;a=new A(a);this.__LOD=d;this._ratioW=
this.width/a.getWidth();this._ratioH=this.height/a.getHeight();var f=this._delta;this._delta=null;this.__zooming=!1;this._updateExtent(a,e);this.onZoomEnd(a,b,c,d?d.level:null);this._fireExtChg([a,f,e,d])},_extentUtil:function(a,b,c,d,e){var f=new ca,g,k,h,l,t,n,m,q,u,y,r=this.width,p=this.height,L,v,w;a&&(g=a.numLevels,k=a.targetLevel,L=s.isDefined(k),h=a.factor,l=a.mapAnchor,t=a.screenAnchor,n=a.mapCenter,v=a.levelOrFactor,m=a.targetScale,q=s.isDefined(m)&&0<m);b&&(u=b.dx,y=b.dy,n=b.mapCenter);
G.isArray(n)&&(n=new N(n));var z=this._panAnim;b=(a=this._stopAnim())?a.divExtent:this.extent;var x=this.__tileInfo,E=this._params;if(!this.loaded){if(c)b&&(c=this._convertGeometry(b,c)),c&&(this.extent=c,E.zoom=E.scale=-1,E.center=null);else if(n||L||q){if(n)if(b){if(n=this._convertGeometry(b,n))this.extent=b.centerAt(n),E.center=null}else E.center=n;L&&-1<k?(E.zoom=k,E.scale=-1):q&&(E.scale=m,E.zoom=-1)}f.resolve();return f}if(n&&(n=this._convertGeometry(this,n),!n)||l&&(l=this._convertGeometry(this,
l),!l)||c&&(c=this._convertGeometry(this,c),!c))return f.reject(),f;z&&(l&&t)&&(l=T(this.extent,r,p,t));a&&(l&&t)&&(l=T(a.divExtent,r,p,t));L&&(x?(g=this.getMinZoom(),L=this.getMaxZoom(),k<g?k=g:k>L&&(k=L),g=k-(a?a.level:this.getLevel())):(g=0<k?-1:1,w=v?k:null));if(!c)if(s.isDefined(g))x?(r=a?a.level:this.getLevel(),p=this.__getExtentForLevel(r+g,n,b).extent):(p=(a?a.end:this.extent).expand(w||(0<g?0.5*g:2*-g)),w&&n&&(p=p.centerAt(n))),p&&(n?c=p:(r=l||b.getCenter(),u=b.ymax-(p.getHeight()-b.getHeight())*
(r.y-b.ymax)/b.getHeight(),r=b.xmin-(p.getWidth()-b.getWidth())*(r.x-b.xmin)/b.getWidth(),c=new A(r,u-p.getHeight(),r+p.getWidth(),u,this.spatialReference)));else if(q)c=I.getExtentForScale(this,m,b);else if(s.isDefined(h))c=b.expand(h);else if(u||y)a?(c=a.end,l=c.getCenter(),w=ba(c,r,p,l),w.x+=u,w.y+=y,w=T(c,r,p,w),c=c.offset(w.x-l.x,w.y-l.y)):(u=new C(r/2+u,p/2+y),y=T(b,r,p,u),p=b.getWidth(),u=b.getHeight(),r=y.x-p/2,y=y.y-u/2,c=new A(r,y,r+p,y+u,this.spatialReference));c||(n?(b=a?a.end:b,p=b.getWidth(),
u=b.getHeight(),r=n.x-p/2,y=n.y-u/2,c=new A(r,y,r+p,y+u,this.spatialReference)):a&&(c=a.end));c?(this._extentDfd&&-1===this._extentDfd.fired&&(this._extentDfd.then(null,Fa),this._extentDfd.reject()),this._extentDfd=f,this.__setExtent(c,null,t,d,a,e)):f.reject();return f},__setExtent:function(a,b,c,d,e,f){try{if(this._firstLayerId)this.extent=a;else{var g=!0,k=this.spatialReference,h=e?e.divExtent:this.extent,l=this._fixExtent(a,d||!1);a=l.extent;var t=a.getWidth(),n=a.getHeight(),m=Math.round;if(h)var q=
m(1E6*h.getWidth()),u=m(1E6*t),y=m(1E6*h.getHeight()),r=m(1E6*n),g=q!==u||y!==r;var p,s,v=e&&e.rect,w=e&&e.divExtent;if(J.zoomDuration&&g&&h){w=w||new A(h);v=v||{left:h.xmin,top:h.ymax,width:h.getWidth(),height:h.getHeight()};s={left:a.xmin,top:a.ymax,width:t,height:n};var x=new N(a.xmin,a.ymax,k),z=new N(a.xmin,a.ymin,k),E=new N(this.extent.xmin,this.extent.ymax,k),D=new N(this.extent.xmin,this.extent.ymin,k);p=xa.getLineIntersection(E,x,D,z,k);!p&&!e&&(g=!1)}this._ratioW=this.width/t;this._ratioH=
this.height/n;var K=this._zoomAnimDiv;if(g)F(this._layersDiv,{left:"0px",top:"0px"}),b=new C(0,0),this.__visibleRect.x=this.__visibleRect.y=0,v&&s?(this._delta=b,K.id="_zAD",K.startingExtent=w,K.extent=a,K.levelChange=g,K.newLod=l.lod,K.anchor=c?c:!p&&e?e.anchor:ba(this.extent,this.width,this.height,p),this._zoomAnim=da.resize({node:K,start:v,end:s,duration:J.zoomDuration,rate:J.zoomRate,beforeBegin:!e?this._zoomStartHandler:null,onAnimate:this._zoomingHandler,onEnd:this._zoomEndHandler}).play(),
this._fireOnScale(this.extent.getWidth()/a.getWidth(),K.anchor)):(this._updateExtent(a,g),this._fireExtChg([this.extent,b,g,this.__LOD=l.lod]));else if(!this.__panning)if(!1===this.loaded||f)this._updateExtent(a,g),this._fireExtChg([this.extent,b,g,this.__LOD=l.lod]);else{this.__panning=!0;v=(new O(0,0,this.width,this.height,this.spatialReference)).getCenter();v.x=m(v.x);v.y=m(v.y);var B=this._delta=this.toScreen(a.getCenter()),H=Math.abs(v.x-B.x),I=Math.abs(v.y-B.y);this.optimizePanAnimation&&(H>
2*this.width||I>2*this.height)?(this.__panStart(0,0),this.__pan(0,0),this.__visibleRect.x=this.__visibleRect.y=this.__visibleDelta.x=this.__visibleDelta.y=0,this.__panning=!1,this._delta=null,this._updateExtent(a,!1),this.onPanEnd(this.extent,new C(0,0)),this._fireExtChg([this.extent,new C(0,0),!0,this.__LOD])):(this.onPanStart(this.extent,new C(0,0)),this._panAnim=da.slideTo({node:K,left:v.x-B.x,top:v.y-B.y,duration:J.panDuration,rate:J.panRate,onAnimate:this._panningHandler,onEnd:this._panEndHandler}),
this._panAnim.play())}}}catch(G){console.log(G.stack),console.error(G)}},_fireOnScale:function(a,b,c){if("css-transforms"===this.navigationMode){var d=this.__visibleDelta;this.onScale(ra.scaleAt(a,{x:-1*(this.width/2-(b.x-d.x)),y:-1*(this.height/2-(b.y-d.y))}),c)}},_stopAnim:function(){var a=this._zoomAnim,b=this._panAnim;if(a&&a._active){a.stop();var b=a.curve.getValue(a._getStep()),c=parseFloat(b.left),d=parseFloat(b.top),a=a.node;return{anchor:a.anchor,start:a.startingExtent,end:a.extent,level:a.newLod&&
a.newLod.level,rect:b,divExtent:new A(c,d-parseFloat(b.height),c+parseFloat(b.width),d,this.spatialReference)}}b&&b._active&&(b.stop(),b._fire("onEnd",[b.node]))},__getExtentForLevel:function(a,b,c){var d=this.__tileInfo,d=d&&d.lods;a=s.isDefined(a)?a:0;c=c||this.extent;b=b||c&&c.getCenter();if(d){if(b){c=this.getMinZoom();var e=this.getMaxZoom();a>e&&(a=e);a<c&&(a=c);a=d[a];d=this.width*a.resolution/2;c=this.height*a.resolution/2;return{extent:new A(b.x-d,b.y-c,b.x+d,b.y+c,b.spatialReference),lod:a}}}else if(c)return{extent:c.expand(!a||
1>a?1:a).centerAt(b)};console.log("Map: "+this.invalidExtent)},_jobs:0,_incr:function(){1===++this._jobs&&(this.updating=!0,this.attr("data-updating",""),this.onUpdateStart())},_decr:function(){var a=--this._jobs;a?0>a&&(this._jobs=0):(this.updating=!1,this.attr("data-updating"),this.onUpdateEnd())},_fireEvent:function(a,b){this[a]&&this[a].apply(this,b)},_updateExtent:function(a,b){this.extent=a;b&&this._setClipRect();var c=this.spatialReference;c&&(c.isWebMercator()?this.geographicExtent=$.webMercatorToGeographic(this._getAvailExtent(),
!0):4326===c.wkid&&(this.geographicExtent=new A(this._getAvailExtent().toJson())))},_fireExtChg:function(a){this.attr("data-zoom",this.getZoom());this.attr("data-scale",this.getScale());this._fireEvent("onExtentChange",a);if(a=this._extentDfd)delete this._extentDfd,a.resolve()},attr:function(a,b){var c=this.container;c&&(null==b?c.removeAttribute(a):c.setAttribute(a,b));return this},onUpdateStart:function(){},onUpdateEnd:function(){},onLoad:function(){this._setClipRect()},onBeforeUnload:function(){},
onUnload:function(){},onExtentChange:function(a,b,c){},onTimeExtentChange:function(){},onLayerAdd:function(){},onLayerAddResult:function(){},onLayersAddResult:function(){},onLayerRemove:function(){},onLayersRemoved:function(){},onLayerReorder:function(){},onLayersReordered:function(){},onLayerSuspend:function(){},onLayerResume:function(){},onPanStart:function(){},onPan:function(){},onPanEnd:function(){},onScale:function(){},onZoomStart:function(){},onZoom:function(){},onZoomEnd:function(){},onResize:function(){this._setClipRect()},
onReposition:function(){},destroy:function(){this._destroyed||(this.onBeforeUnload(this),this.removeAllLayers(),this._cleanUp(),this._gc&&this._gc._cleanUp(),this._destroyed=!0,this.onUnload(this))},setCursor:function(a){F(this.__container,"cursor",this.cursor=a)},setMapCursor:function(a){this.setCursor(this._cursor=a)},resetMapCursor:function(){this.setCursor(this._cursor)},setInfoWindow:function(a){var b=this.infoWindow;b&&b.unsetMap(this);this.infoWindow=a;this.loaded&&a&&a.setMap(this)},setInfoWindowOnClick:function(a){this._params.showInfoWindowOnClick=
a;this.popupManager&&this.popupManager.set("enabled",a)},getInfoWindowAnchor:function(a){return this.infoWindow&&this.infoWindow._getAnchor&&this.infoWindow._getAnchor(a)||"upperright"},toScreen:function(a,b){return ba(this.extent,this.width,this.height,a,b)},toMap:function(a){return T(this.extent,this.width,this.height,a)},addLayer:function(a,b){a&&!this.getLayer(a.id)&&this._addLayer(a,a instanceof x?this.graphicsLayerIds:this.layerIds,b);return a},addLayers:function(a){var b=[],c=a.length,d,e,
f=a.length;d=z.connect(this,"onLayerAddResult",function(e,f){-1!==m.indexOf(a,e)&&(c--,b.push({layer:e,success:!f,error:f}),c||(z.disconnect(d),this.onLayersAddResult(b)))});for(e=0;e<f;e++)this.addLayer(a[e]);return this},removeLayer:function(a,b){var c=a.id,d=a instanceof x?this.graphicsLayerIds:this.layerIds,e=P(d,c);0<=e&&(d.splice(e,1),a instanceof x?(Q(this["_gl_"+a.id+"_click_connect"]),a.loaded&&a._unsetMap(this,this._gc._surface)):a.loaded&&(a._unsetMap(this,this._layersDiv),-1!==a.declaredClass.indexOf("VETiledLayer")&&
this._onBingLayerRemove(a)),delete this._layers[c],delete this._layerDivs[c],b||this._reorderLayers(d),this.onLayerRemove(a))},removeAllLayers:function(){var a=this.layerIds,b;for(b=a.length-1;0<=b;b--)this.removeLayer(this._layers[a[b]],1);a=this.graphicsLayerIds;for(b=a.length-1;0<=b;b--)this.removeLayer(this._layers[a[b]],1);this.onLayersRemoved()},reorderLayer:function(a,b){G.isString(a)&&(ma.deprecated(this.declaredClass+": Map.reorderLayer(/*String*/ id, /*Number*/ index) deprecated. Use Map.reorderLayer(/*Layer*/ layer, /*Number*/ index).",
null,"v2.0"),a=this.getLayer(a));var c=a.id,d,e=a instanceof x?this.graphicsLayerIds:this.layerIds;0>b?b=0:b>=e.length&&(b=e.length-1);d=P(e,c);-1===d||d===b||(e.splice(d,1),e.splice(b,0,c),this._reorderLayers(e))},getLayer:function(a){return this._layers[a]},setExtent:function(a,b){a=new A(a.toJson());var c=a.getWidth(),d=a.getHeight();return 0===c&&0===d?this.centerAt(new N({x:a.xmin,y:a.ymin,spatialReference:a.spatialReference&&a.spatialReference.toJson()})):this._extentUtil(null,null,a,b)},centerAt:function(a){return this._extentUtil(null,
{mapCenter:a})},centerAndZoom:function(a,b){return this._extentUtil({targetLevel:b,mapCenter:a,levelOrFactor:!0})},getScale:function(){return this.__LOD?this.__LOD.scale:I.getScale(this)},getResolution:function(){return this.__LOD?this.__LOD.resolution:this.extent?this.extent.getWidth()/this.width:0},getResolutionInMeters:function(){return this.getResolution()*I.getUnitValueForSR(this.spatialReference)},getMinScale:function(){return this._params.minScale},getMaxScale:function(){return this._params.maxScale},
setScale:function(a){return this._extentUtil({targetScale:a})},getLayersVisibleAtScale:function(a){var b=[];(a=a||this.getScale())&&m.forEach(this.layerIds.concat(this.graphicsLayerIds),function(c){c=this.getLayer(c);c.isVisibleAtScale(a)&&b.push(c)},this);return b},getNumLevels:function(){var a=this.getMinZoom(),b=this.getMaxZoom();return a===b&&0>a?0:b-a+1},getLevel:function(){return this.__LOD?this.__LOD.level:-1},setLevel:function(a){if(-1<a)return this._extentUtil({targetLevel:a})},getZoom:function(){return this.getLevel()},
setZoom:function(a){return this.setLevel(a)},getMinZoom:function(){return this._params.minZoom},getMaxZoom:function(){return this._params.maxZoom},setBasemap:function(a){var b;G.isObject(a)?(b=a,a=b.title):b=D&&D[a];if(b){this._basemapDfd&&-1===this._basemapDfd.fired&&this._basemapDfd.cancel();var c=[],d=[],e=0;m.forEach(b.baseMapLayers||b.layers,function(b){var f,g={id:b.id,displayLevels:b.displayLevels,opacity:s.isDefined(b.opacity)?b.opacity:null,visible:s.isDefined(b.visibility)?b.visibility:
null};if(b.type)switch(b.type){case "OpenStreetMap":f=new ga(g);break;default:console.log("Map.setBasemap: "+s.substitute({basemapName:a,type:b.type},this.unknownLayerType))}else{f=b.url;if("https:"===window.location.protocol&&(-1!==f.search(/^http\:\/\/server\.arcgisonline\.com/i)||-1!==f.search(/^http\:\/\/services\.arcgisonline\.com/i)||-1!==f.search(/^http\:\/\/.+\.arcgis\.com/i)))f=f.replace(/http:/i,"https:");f=new Aa(f,g)}f&&(c.push(f),d.push(b),b.isReference||e++)},this);if(!c.length||!e)console.log("Map.setBasemap: "+
s.substitute({basemapName:a},this.invalidBasemap));else{var f={basemapName:a,infos:d,layers:c};if(this.loaded){var g=this,k=new ca(va._dfdCanceller),h=function(a){k._pendingLayers--;a=m.indexOf(f.layers,this);if(-1<a&&(a=k._layerEvents[a]))z.disconnect(a[0]),z.disconnect(a[1]);0>=k._pendingLayers&&(delete k._layerEvents,delete g._basemapDfd,0>k.fired&&k.callback(f))};this._basemapDfd=k;k._pendingLayers=0;k._layerEvents={};m.forEach(c,function(a,b){a&&(k._pendingLayers++,a.loaded?h(a):k._layerEvents[b]=
[z.connect(a,"onLoad",a,h),z.connect(a,"onError",a,h)])});k.addCallback(B(this,this._basemapLoaded))}else this._basemapLoaded(f)}}else{b=[];for(var l in D)b.push(l);console.log("Map.setBasemap: "+s.substitute({basemapName:a,list:b.join(",")},this.unknownBasemap))}},_basemapLoaded:function(a){var b=a.layers,c=a.infos,d=0,e=!0,f;this.loaded&&(m.forEach(b,function(a,b){a.loaded&&(c[b].isReference||d++)}),e=d);e&&(this.basemapLayerIds&&(f={basemapName:this._basemap,infos:D&&D[this._basemap]&&D[this._basemap].baseMapLayers},
f.basemapName||(m.forEach(this.basemapLayerIds,function(a){if(this.getLayer(a)instanceof ga)return f.basemapName="osm",f.infos=D&&D.osm&&D.osm.baseMapLayers,!1},this),f.basemapName||(f=null))),this._removeBasemap(),this._basemap=a.basemapName,this.basemapLayerIds=this._addBasemap(b,c),this.attr("data-basemap",this.getBasemap()),this.emit("basemap-change",{current:a,previous:f}))},_addBasemap:function(a,b){var c=[],d=[],e=0;m.forEach(a,function(a,g){b[g].isReference?c.push(a):(this.addLayer(a,e++),
d.push(a.id))},this);c.length&&m.forEach(c,function(a){this.addLayer(a,"top");d.push(a.id)},this);return d},_removeBasemap:function(){var a=this.basemapLayerIds,b;a&&a.length&&m.forEach(a,function(a){(b=this.getLayer(a))&&this.removeLayer(b)},this)},getBasemap:function(){return this._basemap||""},translate:function(a,b){a=a||0;b=b||0;if(!this._txTimer){this._tx=this._ty=0;var c=this.toScreen(this.extent.getCenter());this.__panStart(c.x,c.y)}this._tx+=a;this._ty+=b;this.__pan(this._tx,this._ty);clearTimeout(this._txTimer);
this._txTimer=setTimeout(this._endTranslate,150)},_endTranslate:function(){clearTimeout(this._txTimer);this._txTimer=null;var a=this._tx,b=this._ty;this._tx=this._ty=0;this.__panEnd(a,b)},setTimeExtent:function(a){a=(this.timeExtent=a)?new a.constructor(a.toJson()):null;this.onTimeExtentChange(a)},setTimeSlider:function(a){this.timeSlider&&(Q(this._tsTimeExtentChange_connect),this.timeSlider=this._tsTimeExtentChange_connect=null);a&&(this.timeSlider=a,this.setTimeExtent(a.getCurrentTimeExtent()),
this._tsTimeExtentChange_connect=X(a,"onTimeExtentChange",this,"setTimeExtent"))},setVisibility:function(a){if(this.visible!==a){this.visible=a;a||(this._display=this.container.style.display);this.container.style.display=a?this._display:"none";if(this.autoResize){var b=a?"resume":"pause";this._rszSignal[b]();this._oriSignal[b]()}a&&this.resize()}return this},resize:function(a){var b=this,c=function(){clearTimeout(b._resizeT);b.reposition();b._resize()};clearTimeout(b._resizeT);!0===a?c():b._resizeT=
setTimeout(c,b.resizeDelay)},_resize:function(){var a=this.width,b=this.height,c=V.getContentBox(this.container);if(!(a===c.w&&b===c.h)){var d=this._zoomAnim||this._panAnim;d&&(d.stop(),d._fire("onEnd",[d.node]));F(this.root,{width:(this.width=c.w)+"px",height:(this.height=c.h)+"px"});c=this.width;d=this.height;this.attribution&&this.attribution.domNode&&W.set(this.attribution.domNode,"maxWidth",Math.floor(c*this._mapParams.attributionWidth)+"px");this.__visibleRect.update(this.__visibleRect.x,this.__visibleRect.y,
c,d);this.__visibleDelta.update(this.__visibleDelta.x,this.__visibleDelta.y,c,d);var e=new O(this.extent),a=(new O(e.x,e.y,e.width*(c/a),e.height*(d/b),this.spatialReference)).getExtent();this.onResize(a,c,d);this._extentUtil(null,null,a,null,!0)}},reposition:function(){this._reposition();this.onReposition(this.position.x,this.position.y)},_reposition:function(){var a=V.position(this.container,!0),b=V.getPadBorderExtents(this.container);this.position.update(a.x+b.l,a.y+b.t)},_setClipRect:function(){delete this._clip;
var a=7>=M("ie")||void 0===M("ie")&&7<=M("trident")?"rect(auto,auto,auto,auto)":"auto";if(this.wrapAround180){var b=this.width,c=this.height,d=this._getFrameWidth(),e=b-d;0<e&&(a=e/2,a="rect(0px,"+(a+d)+"px,"+c+"px,"+a+"px)",c=this.extent.getWidth(),b=c*(d/b),this._clip=[(c-b)/2,b])}F(this.__container,"clip",a)},_getAvailExtent:function(){var a=this.extent,b=this._clip;if(b){if(!a._clip){var c=new O(a);c.width=b[1];c.x+=b[0];a._clip=c.getExtent()}return a._clip}return a},_fixedPan:function(a,b){return this._extentUtil(null,
{dx:a,dy:b})},panUp:function(){return this._fixedPan(0,-0.75*this.height)},panUpperRight:function(){return this._fixedPan(0.75*this.width,-0.75*this.height)},panRight:function(){return this._fixedPan(0.75*this.width,0)},panLowerRight:function(){return this._fixedPan(0.75*this.width,0.75*this.height)},panDown:function(){return this._fixedPan(0,0.75*this.height)},panLowerLeft:function(){return this._fixedPan(-0.75*this.width,0.75*this.height)},panLeft:function(){return this._fixedPan(-0.75*this.width,
0)},panUpperLeft:function(){return this._fixedPan(-0.75*this.width,-0.75*this.height)},enableSnapping:function(a){a=a||{};if("esri.SnappingManager"===a.declaredClass)this.snappingManager=a;else{var b=Y++,c=this;this._rids&&this._rids.push(b);R(["./SnappingManager"],function(d){var e=c._rids?m.indexOf(c._rids,b):-1;-1!==e&&(c._rids.splice(e,1),c.snappingManager=new d(G.mixin({map:c},a)))})}return this.snappingManager},disableSnapping:function(){this.snappingManager&&this.snappingManager.destroy();
this.snappingManager=null},_createLabelLayer:function(){function a(){b._labels.removeAllFeatureLayers();m.forEach(b.graphicsLayerIds,function(a){a=b.getLayer(a);"function"===typeof a.applyEdits&&b._labels.addFeatureLayer(a)})}var b=this;!this._labels&&(aa&&this.loaded)&&(this._labels=new aa({id:"_internal_LabelLayer"}),this._labels._setMap(this,this._gc._surface),a(),this.on("layers-reordered",a))},_getMapImageLyr:function(){this.loaded&&!this._mapImageLyr&&(this._mapImageLyr=new Ba,this._mapImageLyr._setMap(this,
this._layersDiv),this._placeMapImageLyr());return this._mapImageLyr},_placeMapImageLyr:function(){for(var a=this.layerIds,b=this._layerDivs,c=!1,d,e,f=a.length-1;0<=f;f--)if(d=a[f],e=this.getLayer(d),d=b[d],e&&d&&!e._isReference){H.place(this._mapImageLyr._div,d,"after");c=!0;break}c||H.place(this._mapImageLyr._div,this._layersDiv,"first")}});M("extend-esri")&&(sa._CoreMap=U);return U});