// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/request","require dojo/_base/array dojo/_base/config dojo/_base/Deferred dojo/_base/lang dojo/_base/url dojo/_base/xhr dojo/io/script dojo/io/iframe dojo/dom-construct dojo/io-query ./kernel ./config ./sniff ./lang ./urlUtils ./deferredUtils".split(" "),function(Q,w,L,R,q,W,A,X,Y,S,T,h,Z,n,x,r,$){function M(a){a=new W(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function B(a,d,e,f){var l=!1,m=!1,t;x.isDefined(d)&&(q.isObject(d)?(l=!!d.useProxy,m=!!d.usePost,t=d.crossOrigin):
l=!!d);a=q.mixin({},a);a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));d=a.content;var k=a.url,g=e&&a.form,s=p;t=x.isDefined(t)?t:s.useCors;a.load=function(a){var b;a&&(a.error?(b=q.mixin(Error(),a.error),b.log=L.isDebug):"error"===a.status&&(b=q.mixin(Error(),a),b.log=L.isDebug),b&&!x.isDefined(b.httpCode)&&(b.httpCode=b.code));return b||a};a.error=function(a,b){b&&b.xhr&&b.xhr.abort();a instanceof Error||(a=q.mixin(Error(),a));a.log=L.isDebug;s.errorHandler(a,b);return a};a._token&&(a.content=
a.content||{},a.content.token=a._token);var y=0,C;d&&k&&(C=T.objectToQuery(d),y=C.length+k.length+1,n("esri-url-encodes-apostrophe")&&(y=C.replace(/'/g,"%27").length+k.length+1));a.timeout=x.isDefined(a.timeout)?a.timeout:s.timeout;a.handleAs=a.handleAs||"json";try{var u,v,b=t&&r.canUseXhr(a.url)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),c=r.hasSameOrigin(a.url,window.location.href)||b,D=m||e||y>s.postLength?!0:!1,U=!c&&-1!==a.handleAs.indexOf("json")&&a.callbackParamName&&!e?!0:
!1,E=r.getProxyRule(a.url)||s.alwaysUseProxy||l||(!U||D)&&!c?!0:!1;e&&(!n("esri-file-upload")&&!E&&b)&&(E=!0);if(E)if(u=r.getProxyUrl(k,t),v=u.path,u._xo&&(b=!0),!D&&v.length+1+y>s.postLength&&(D=!0),a.url=v+"?"+k,D)a.content=q.mixin(u.query||{},d);else{var V=T.objectToQuery(q.mixin(u.query||{},d));V&&(a.url+="?"+V);a.content=null}if(U&&!D)return!x.isDefined(a.isAsync)&&4>n("ff")&&(a.isAsync=!0),X.get(F?F(a):a);var G=a.headers;if(b&&(!G||!G.hasOwnProperty("X-Requested-With")))G=a.headers=G||{},G["X-Requested-With"]=
null;if(e){var N=a.callbackParamName||"callback.html",B=a.callbackElementName||"textarea",H,O,I,P,J=g.elements?g.elements.length:0,z;if(d=a.content)for(H in d)if(I=d[H],x.isDefined(I)){O=null;for(P=0;P<J;P++)if(z=g.elements[P],z.name===H){O=z;break}O?O.value=I:f?g.append(H,I):g.appendChild(S.create("input",{type:"hidden",name:H,value:I}))}if(n("esri-file-upload"))w.forEach(g.elements,function(a){a.name===N&&g.removeChild(a)}),a.contentType=!1,a.postData=f?g:new FormData(g),delete a.form;else{g.enctype=
"multipart/form-data";9>n("ie")&&(g.encoding="multipart/form-data");g.method="post";w.some(g.elements,function(a){return a.name===N})||g.appendChild(S.create("input",{type:"hidden",name:N,value:B}));if(-1!==k.toLowerCase().indexOf("addattachment")||-1!==k.toLowerCase().indexOf("updateattachment"))a.url=k+(-1===k.indexOf("?")?"?":"\x26")+N+"\x3d"+B,E&&(a.url=v+"?"+a.url);delete a.content}}if(b&&!a.hasOwnProperty("withCredentials"))if(f=E?v:k,-1!==w.indexOf(p.webTierAuthServers,M(f)))a.withCredentials=
!0;else if(h.id){var K=h.id.findServerInfo(f);K&&K.webTierAuth&&(a.withCredentials=!0)}a=F?F(a):a;if(D){if(e&&!n("esri-file-upload"))return Y.send(a);!E&&n("safari")&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+aa++);return A.post(a)}return A.get(a)}catch(Q){return e=new R,e.errback(a.error(Q)),e}}function J(a){var d=p.corsStatus,e=r.canUseXhr(a,!0);-1<e&&p.corsEnabledServers.splice(e,1);d[M(a)]=1;return e}function z(a){var d=p.corsStatus;if(p.corsDetection&&p.useCors)try{var e=
M(a);n("esri-cors")&&(a&&-1!==a.toLowerCase().indexOf("/rest/services")&&!r.hasSameOrigin(a,window.location.href)&&!r.canUseXhr(a)&&!d[e])&&(d[e]=-1,A.get({url:a.substring(0,a.toLowerCase().indexOf("/rest/")+6)+"info",content:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null}}).then(function(f){f?(d[e]=2,r.canUseXhr(a)||p.corsEnabledServers.push(e)):d[e]=1},function(a){d[e]=1}))}catch(f){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}}function K(a){F=
a}function m(a,d){function e(b){b._pendingDfd=B(a,d,y,s);if(!b._pendingDfd){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;var c=Error("Deferred object is missing");c.log=L.isDebug;a._usrDfd=null;b.errback(c);b._pendingDfd=null;return b}b._pendingDfd.addCallback(function(d){b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;a._usrDfd=null;b.callback(d);b._pendingDfd=null}).addErrback(function(c){var e,f,g;c&&(e=c.code,f=c.subcode,g=(g=c.messageCode)&&g.toUpperCase());if(c&&403==e&&(4==f||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&
-1===c.message.toLowerCase().indexOf("permission"))){if(!a._ssl){a._ssl=a._sslFromServer=!0;a._usrDfd=b;m(a,d);return}}else if(c&&415==c.status){if(J(a.url),!a._err415){a._err415=1;a._usrDfd=b;m(a,d);return}}else if(h.id&&-1!==w.indexOf(h.id._errorCodes,e)&&!h.id._isPublic(a.url)&&!q&&(403!=e||-1===w.indexOf(ba,g)&&(!x.isDefined(f)||2==f))){b._pendingDfd=h.id.getCredential(a.url,{token:a._token,error:c});b._pendingDfd.addCallback(function(c){a._token=c.token;a._usrDfd=b;a._credential=c;a._ssl=a._sslFromServer||
c.ssl;m(a,d)}).addErrback(function(c){a._usrDfd=null;b.errback(c);b._pendingDfd=null});return}b.ioArgs=b._pendingDfd&&b._pendingDfd.ioArgs;a._usrDfd=null;b.errback(c);b._pendingDfd=null})}a.url=r.fixUrl(a.url);"file:"!==window.location.protocol&&(a.url=r.getAbsoluteUrl(a.url));d=d||{};var f,l=a.form,q=d.disableIdentityLookup,t=d._preLookup,k=!1;if(n("esri-workers")&&!1!==p.useWorkers)if(!0===d.useWorkers||!0===p.useWorkers)k=!0;else if(d.workerOptions){var g=d.workerOptions;if(g.callback||g.worker&&
g.worker.worker instanceof Worker)k=!0}var s=l&&l.append,y=l&&(l.elements?w.some(l.elements,function(a){return"file"===a.type}):s),C=-1!==a.url.toLowerCase().indexOf("token\x3d")||a.content&&a.content.token||y&&w.some(l.elements,function(a){return"token"===a.name})?1:0;z(a.url);if(a._usrDfd)f=a._usrDfd;else{f=new R($._dfdCanceller);f.addCallback(function(b){/\/sharing\/rest\/accounts\/self/i.test(a.url)&&(!C&&!a._token&&b.user&&b.user.username)&&p.webTierAuthServers.push(M(a.url));if(b=a._credential){var c=
h.id.findServerInfo(b.server);if(c=c&&c.owningSystemUrl)c=c.replace(/\/?$/,"/sharing"),(b=h.id.findCredential(c,b.userId))&&-1===h.id._getIdenticalSvcIdx(c,b)&&b.resources.splice(0,0,c)}});f.addBoth(function(b){delete a._credential;if(b&&(!n("ie")||!b.nodeType))b._ssl=a._ssl});var u=a.load,v=a.error;u&&f.addCallback(function(a){var c=f._pendingDfd,c=c&&c.ioArgs;return u.call(c&&c.args,a,c)});v&&f.addErrback(function(a){var c=f._pendingDfd,c=c&&c.ioArgs;return v.call(c&&c.args,a,c)})}if(h.id&&!C&&
!a._token&&!h.id._isPublic(a.url)&&(!q||t))if(l=h.id.findCredential(a.url))a._token=l.token,a._ssl=l.ssl;k?d.workerOptions&&d.workerOptions.worker?(A=d.workerOptions.worker,e(f)):Q(["./workers/RequestClient"],function(a){if(d.workerOptions){var c=d.workerOptions;A=a.getClient(c.callback,c.cbFunction)}else A=a.getClient();e(f)}):e(f);return f}var F,p=Z.defaults.io,ba=["COM_0056","COM_0057"],aa=0;m._request=B;m._disableCors=J;m._detectCors=z;m.setRequestPreCallback=K;n("extend-esri")&&(h.request=m,
h._request=B,h._disableCors=J,h._detectCors=z,h.setRequestPreCallback=K);return m});