define({
  root: ({
    addDistance: "Add Length Unit",
    addArea: "Add Area Unit",
    label: "Label",
    abbr: "Abbreviation",
    conversion: "Conversion",
    actions: "Actions",
    areaUnits: "Area Units",
    distanceUnits: "Length Units",
    kilometers: "Kilometers",
    miles: "Miles",
    meters: "Meters",
    feet: "Feet",
    yards: "Yards",
    squareKilometers: "Square kilometers",
    squareMiles: "Square miles",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Square meters",
    squareFeet: "Square feet",
    squareYards: "Square yards",
    distance: "Distances",
    area: "Areas",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "sq km",
    squareMilesAbbreviation: "sq mi",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "sq m",
    squareFeetAbbreviation: "sq ft",
    squareYardsAbbreviation: "sq yd"
  }),
  "ar": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1
});