define(
   ({
    placeholder: "טקסט מציין מיקום (Placeholder)",
    url: "URL של מעגן הכתובות",
    name: "שם מעגן הכתובות",
    example: "דוגמה",
    singleLineFieldName: "SingleLineFieldName",
    portalConnectionError: 'לא ניתן לקבל הגדרת מעגל הכתובות מהפורטל',
    actions: "פעולות",
    warning: "זו אינה גרסה נתמכת של שירות עיגון כתובות‏. וידג'ט זה תומך בשירות עיגון כתובות בגרסה 10.1 ואילך.",
    instruction: "קבע את מעגני הכתובות בוידג'ט זה. לחץ על \'הוסף מעגן כתובות\' כדי להפנות לכתובת URL, לציין שם ידידותי למשתמש ולהגדיר תכונות נוספות. ניתן גם לשנות את הסדר, להגדיר או למחוק את מעגני הכתובות למטה.",
    layerInstruction1: "ניתן להגדיר את תנאי החיפוש תחת ",
    layerInstruction2: "דף הפרטים של מפת Web",
    searchAddress: "חפש לפי כתובת",
    searchLayer: "חפש לפי שכבה",
    layer: "שכבה",
    field: "שדה",
    condition: "תנאי",
    contains: "כולל",
    deleteLastGeocoderError: "לא ניתן למחוק את מעגן הכתובות האחרון.",
    noSearchFactorError: "יש לבחור לפחות יכולת אחת (\'חפש לפי כתובת\' או \'חפש לפי שכבה\').",
    equals: "שווה",
    add: "הוסף מעגן כתובות",
    edit: "ערוך מעגן כתובות",
    ok: "אישור",
    cancel: "ביטול",
    geocoderNamePlaceHolder: "מעגן הכתובות שלי",
    geocodePlaceHolder: "מצא כתובת או מקום",
    REPEATING_ERROR: "השדות הבאים חוזרים על עצמם: "
  })
);