define(
   ({
    addDistance: "Aggiungi unità di lunghezza",
    addArea: "Aggiungi unità di superficie",
    label: "Etichetta",
    abbr: "Abbreviazione",
    conversion: "Conversione",
    actions: "Azioni",
    areaUnits: "Unità di superficie",
    distanceUnits: "Unità lunghezza",
    kilometers: "Chilometri",
    miles: "Miglia",
    meters: "Metri",
    feet: "Piedi",
    yards: "Iarde",
    squareKilometers: "Chilometri quadrati",
    squareMiles: "Miglia quadrate",
    acres: "Acri",
    hectares: "Ettari",
    squareMeters: "Metri quadrati",
    squareFeet: "Piedi quadrati",
    squareYards: "Iarde quadrate",
    distance: "Distanze",
    area: "Aree",
    kilometersAbbreviation: "km",
    milesAbbreviation: "miglio",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "km²",
    squareMilesAbbreviation: "miglio²",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m²",
    squareFeetAbbreviation: "ft²",
    squareYardsAbbreviation: "yd²"
  })
);