define(
   ({
    _widgetLabel: "Tabla de atributos",
    ok: "Aceptar",
    cancel: "Cancelar",
    unsupportQueryWarning: "La capa debe ser compatible con la operación de consulta para mostrar el widget Tabla de atributos. Asegúrate de que la función de consulta en el servicio está activada.",
    exportMessage: "¿Exportar datos a archivo CSV?",
    exportFiles: "Exportar a CSV",
    options: "Opciones",
    zoomto: "Acercar a",
    highlight: "Resaltar gráficos",
    selectAll: "Seleccionar registros en todas las páginas",
    selectPage: "Seleccionar registros en la página actual",
    clearSelection: "Borrar selección",
    filterByExtent: "Filtrar por extensión de mapa",
    showSelectedRecords: "Mostrar los registros seleccionados",
    showRelatedRecords: "Mostrar los registros relacionados",
    noRelatedRecords: "No hay registros relacionados",
    refresh: "Actualizar",
    features: "entidades",
    selected: "seleccionado",
    transparent: "Modo transparente",
    indicate: "Localizar selección",
    columns: "Mostrar/Ocultar columnas",
    selectionSymbol: "Símbolo de selección",
    closeMessage: "Ocultar tabla (volver a expandirla desde la parte inferior)",
    dataNotAvailable: "¡Datos no disponibles!<br>Haz clic en el botón [Actualizar] para intentarlo de nuevo.",
    openTableTip: "Abrir tabla de atributos",
    closeTableTip: "Ocultar tabla de atributos"
  })
);