define(
   ({
    addDistance: "長さ単位の追加",
    addArea: "面積単位の追加",
    label: "ラベル",
    abbr: "略語",
    conversion: "変換",
    actions: "アクション",
    areaUnits: "面積単位",
    distanceUnits: "長さ単位",
    kilometers: "キロメートル",
    miles: "マイル",
    meters: "メートル",
    feet: "フィート",
    yards: "ヤード",
    squareKilometers: "平方キロメートル",
    squareMiles: "平方マイル",
    acres: "エーカー",
    hectares: "ヘクタール",
    squareMeters: "平方メートル",
    squareFeet: "平方フィート",
    squareYards: "平方ヤード",
    distance: "距離",
    area: "面積",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "sq km",
    squareMilesAbbreviation: "sq mi",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "sq m",
    squareFeetAbbreviation: "sq ft",
    squareYardsAbbreviation: "sq yd"
  })
);