define(
   ({
    _widgetLabel: "Rita",
    selectDrawMode: "Välj ritläge",
    clear: "Rensa",
    point: "Punkt",
    line: "Linje",
    polyline: "Polylinje",
    freehandPolyline: "Frihandspolylinje",
    triangle: "Triangel",
    extent: "Utbredningsområde",
    circle: "Cirkel",
    ellipse: "Ellips",
    polygon: "Polygon",
    freehandPolygon: "Frihandspolygon",
    text: "Text",
    style: "Format",
    alpha: "Transparens",
    width: "Bredd",
    size: "Storlek",
    color: "Färg",
    markerColor: "Markeringsfärg",
    outlineColor: "Konturfärg",
    lineColor: "Linjefärg",
    fillColor: "Fyllningsfärg",
    showMeasurements: "Visa mått",
    areaUnits: "Areaenheter",
    distanceUnits: "Distansenheter",
    kilometers: "Kilometer",
    miles: "Engelska mil",
    meters: "Meter",
    feet: "Fot",
    yards: "Yard",
    squareKilometers: "Kvadratkilometer",
    squareMiles: "Square miles",
    acres: "Tunnland",
    hectares: "Hektar",
    squareMeters: "Kvadratmeter",
    squareFeet: "Square feet",
    squareYards: "Square yards",
    undo: "Ångra",
    redo: "Upprepa"
  })
);