define(
   ({
    addDistance: "Lengte-eenheid toevoegen",
    addArea: "Oppervlakte-eenheid toevoegen",
    label: "Label",
    abbr: "Afkorting",
    conversion: "Conversie",
    actions: "Acties",
    areaUnits: "Oppervlakte-eenheden",
    distanceUnits: "Lengte-eenheden",
    kilometers: "Kilometer",
    miles: "Mijl",
    meters: "Meter",
    feet: "Voet",
    yards: "Yard",
    squareKilometers: "Vierkante kilometer",
    squareMiles: "Vierkante mijl",
    acres: "Hectare",
    hectares: "Hectare",
    squareMeters: "Vierkante meter",
    squareFeet: "Vierkante voet",
    squareYards: "Vierkante yard",
    distance: "Afstanden",
    area: "Gebieden",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "ft",
    yardsAbbreviation: "yd",
    squareKilometersAbbreviation: "sq km",
    squareMilesAbbreviation: "sq mi",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "sq m",
    squareFeetAbbreviation: "sq ft",
    squareYardsAbbreviation: "yd²"
  })
);