define(
   ({
    _widgetLabel: "วาด",
    selectDrawMode: "เลือกโหมดการวาด",
    clear: "ลบ",
    point: "จุด",
    line: "เส้น",
    polyline: "เส้น",
    freehandPolyline: "การวาดเส้นหลายเส้นด้วยมือเปล่า",
    triangle: "สามเหลี่ยม",
    extent: "ส่วนขยาย",
    circle: "วงกลม",
    ellipse: "วงรี",
    polygon: "รูปปิด",
    freehandPolygon: "การวาดรูปหลายเหลี่ยมด้วยมือเปล่า",
    text: "ข้อความ",
    style: "สไตล์",
    alpha: "โปร่งแสง",
    width: "ความกว้าง",
    size: "ขนาด",
    color: "สี",
    markerColor: "สีของเครื่องหมาย",
    outlineColor: "สีของโครงร่าง",
    lineColor: "สีของเส้น",
    fillColor: "ใส่สี",
    showMeasurements: "แสดงการวัด",
    areaUnits: "หน่วยพื้นที่",
    distanceUnits: "หน่วยระยะทาง",
    kilometers: "กิโลเมตร",
    miles: "ไมล์",
    meters: "เมตร",
    feet: "ฟุต",
    yards: "หลา",
    squareKilometers: "ตารางกิโลเมตร",
    squareMiles: "ตารางไมล์",
    acres: "เอเคอร์",
    hectares: "เฮกตาร์",
    squareMeters: "ตารางเมตร",
    squareFeet: "ตารางนิ้ว",
    squareYards: "ตารางหลา",
    undo: "ยกเลิก",
    redo: "ทำอีกครั้ง"
  })
);