define(
   ({
    _widgetLabel: "그리기",
    selectDrawMode: "그리기 모드 선택",
    clear: "지우기",
    point: "포인트",
    line: "라인",
    polyline: "폴리라인",
    freehandPolyline: "자유곡선 폴리라인",
    triangle: "삼각형",
    extent: "엔빌롭",
    circle: "원",
    ellipse: "타원",
    polygon: "폴리곤",
    freehandPolygon: "자유곡선 폴리곤",
    text: "텍스트",
    style: "스타일",
    alpha: "투명도",
    width: "너비",
    size: "크기",
    color: "색상",
    markerColor: "표식 색상",
    outlineColor: "윤곽선 색상",
    lineColor: "라인 색상",
    fillColor: "채우기 색상",
    showMeasurements: "측정치 표시",
    areaUnits: "면적 단위",
    distanceUnits: "거리 단위",
    kilometers: "킬로미터",
    miles: "마일",
    meters: "미터",
    feet: "피트",
    yards: "야드",
    squareKilometers: "제곱킬로미터",
    squareMiles: "제곱마일",
    acres: "에이커",
    hectares: "헥타르",
    squareMeters: "제곱미터",
    squareFeet: "제곱피트",
    squareYards: "제곱야드",
    undo: "실행 취소",
    redo: "다시 실행"
  })
);