define(
   ({
    addDistance: "إضافة وحدة الطول",
    addArea: "إضافة وحدة المنطقة",
    label: "لافتة التسمية",
    abbr: "اختصار",
    conversion: "تحويل",
    actions: "الأفعال",
    areaUnits: "وحدات المنطقة",
    distanceUnits: "وحدات الطول",
    kilometers: "كيلومترات",
    miles: "أميال",
    meters: "مترات",
    feet: "قدم",
    yards: "ياردات",
    squareKilometers: "كيلو مترات مربعة",
    squareMiles: "أميال مربعة",
    acres: "فدان",
    hectares: "هكتار",
    squareMeters: "أمتار مربعة",
    squareFeet: "قدم مربع",
    squareYards: "ياردات مربعة",
    distance: "مسافات",
    area: "مناطق",
    kilometersAbbreviation: "كم",
    milesAbbreviation: "ميل",
    metersAbbreviation: "متر",
    feetAbbreviation: "قدم",
    yardsAbbreviation: "ياردة",
    squareKilometersAbbreviation: "كم مربع",
    squareMilesAbbreviation: "ميل مربع",
    acresAbbreviation: "ac",
    hectaresAbbreviation: "هكتار",
    squareMetersAbbreviation: "متر مربع",
    squareFeetAbbreviation: "قدم مربع",
    squareYardsAbbreviation: "ياردة مربعة"
  })
);