define(
   ({
    showArcgisBasemaps: "Uwzględnij mapy bazowe z portalu",
    settings: "Ustawienia",
    add: "Kliknij, aby dodać nową mapę bazową",
    edit: "Właściwości",
    title: "Tytuł",
    titlePH: "Tytuł mapy bazowej",
    thumbnail: "Miniatura",
    thumbnailHint: "Kliknij obraz do zaktualizowania",
    url: "URL",
    urlPH: "Adres URL warstwy",
    addlayer: "Dodaj mapę bazową",
    actions: "Operacje",
    warning: "Nieprawidłowe dane wejściowe",
    save: "Wróć i zapisz",
    back: "Wróć i anuluj",
    addUrl: "Dodaj adres URL",
    autoCheck: "Automatyczne sprawdzanie",
    checking: "Trwa sprawdzanie...",
    ok: "OK",
    cancel: "Anuluj",
    result: "Zapisano pomyślnie",
    spError: "Wszystkie mapy bazowe dodane do galerii muszą mieć to samo odniesienie przestrzenne.",
    invalidTitle1:"Mapa bazowa '",
    invalidTitle2:"' już istnieje. Wybierz inny tytuł.",
    invalidBasemapUrl1: "Warstwy tego typu nie można użyć jako mapy bazowej.",
    invalidBasemapUrl2: "Bieżąca mapa używa innego odniesienia przestrzennego.",
    addBaselayer: "Dodaj warstwę mapy bazowej"
  })
);