// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/nls/widgets_cs",{"dijit/_editor/nls/commands":{removeFormat:"Odebrat form\u00e1t",copy:"Kop\u00edrovat",paste:"Vlo\u017eit",selectAll:"Vybrat v\u0161e",insertOrderedList:"\u010c\u00edslovan\u00fd seznam",insertTable:"Vlo\u017eit/upravit tabulku",print:"Tisk",underline:"Podtr\u017een\u00ed",foreColor:"Barva pop\u0159ed\u00ed",htmlToggle:"Zdroj HTML",formatBlock:"Styl odstavce",newPage:"Nov\u00e1 str\u00e1nka",insertHorizontalRule:"Vodorovn\u00e1 \u010d\u00e1ra","delete":"Odstranit",appleKey:"\u2318${0}",
insertUnorderedList:"Seznam s odr\u00e1\u017ekami",tableProp:"Vlastnost tabulky",insertImage:"Vlo\u017eit obr\u00e1zek",superscript:"Horn\u00ed index",subscript:"Doln\u00ed index",createLink:"Vytvo\u0159it odkaz",undo:"Zp\u011bt",fullScreen:"P\u0159epnout re\u017eim cel\u00e9 obrazovky",italic:"Kurz\u00edva",fontName:"N\u00e1zev p\u00edsma",justifyLeft:"Zarovnat vlevo",unlink:"Odebrat odkaz",toggleTableBorder:"P\u0159epnout ohrani\u010den\u00ed tabulky",viewSource:"Zobrazit zdroj ve form\u00e1tu HTML",
ctrlKey:"ctrl+${0}",fontSize:"Velikost p\u00edsma",systemShortcut:'Akce "${0}" je v prohl\u00ed\u017ee\u010di dostupn\u00e1 pouze prost\u0159ednictv\u00edm kl\u00e1vesov\u00e9 zkratky. Pou\u017eijte kl\u00e1vesovou zkratku ${1}.',indent:"Odsadit",redo:"Opakovat",strikethrough:"P\u0159e\u0161krtnut\u00ed",justifyFull:"Do bloku",justifyCenter:"Zarovnat na st\u0159ed",hiliteColor:"Barva pozad\u00ed",deleteTable:"Odstranit tabulku",outdent:"P\u0159edsadit",cut:"Vyjmout",_localized:{},plainFormatBlock:"Styl odstavce",
toggleDir:"P\u0159epnout sm\u011br",bold:"Tu\u010dn\u00e9",tabIndent:"Odsazen\u00ed tabul\u00e1toru",justifyRight:"Zarovnat vpravo"},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"ne po \u00fat st \u010dt p\u00e1 so".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"nyn\u00ed","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Den v t\u00fddnu","field-wed-relative+0":"tuto st\u0159edu","field-wed-relative+1":"p\u0159\u00ed\u0161t\u00ed st\u0159edu",
"dateFormatItem-GyMMMEd":"E d. M. y G","dateFormatItem-MMMEd":"E d. M.",eraNarrow:["AH"],"field-tue-relative+-1":"minul\u00e9 \u00fater\u00fd","days-format-short":"ne po \u00fat st \u010dt p\u00e1 so".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d. MMMM y G","field-fri-relative+-1":"minul\u00fd p\u00e1tek","field-wed-relative+-1":"minulou st\u0159edu","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE d. MMMM y G","dateFormatItem-yyyyMEd":"E d. M. y GGGGG","field-thu-relative+-1":"minul\u00fd \u010dtvrtek","dateFormatItem-Md":"d. M.",_localized:{},"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Letopo\u010det","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"timeFormat-short":"H:mm","quarters-format-wide":["1. \u010dtvrtlet\u00ed","2. \u010dtvrtlet\u00ed","3. \u010dtvrtlet\u00ed","4. \u010dtvrtlet\u00ed"],"timeFormat-long":"H:mm:ss z","field-year":"Rok","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hodina","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"tuto sobotu","field-sat-relative+1":"p\u0159\u00ed\u0161t\u00ed sobotu","timeFormat-full":"H:mm:ss zzzz",
"dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"dnes","field-thu-relative+0":"tento \u010dtvrtek","field-day-relative+1":"z\u00edtra","field-thu-relative+1":"p\u0159\u00ed\u0161t\u00ed \u010dtvrtek","dateFormatItem-GyMMMd":"d. M. y G","field-day-relative+2":"poz\u00edt\u0159\u00ed","dateFormatItem-H":"H","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],
"quarters-standAlone-wide":["1. \u010dtvrtlet\u00ed","2. \u010dtvrtlet\u00ed","3. \u010dtvrtlet\u00ed","4. \u010dtvrtlet\u00ed"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d. M. y G","dateFormatItem-M":"L","days-standAlone-wide":"ned\u011ble pond\u011bl\u00ed \u00fater\u00fd st\u0159eda \u010dtvrtek p\u00e1tek sobota".split(" "),"dateFormatItem-yyyyMMM":"LLLL y G","dateFormatItem-yyyyMMMd":"d. M. y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"H:mm:ss","field-sun-relative+0":"tuto ned\u011bli",
"dateFormatItem-Hm":"H:mm","field-sun-relative+1":"p\u0159\u00ed\u0161t\u00ed ned\u011bli","quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minuta","field-dayperiod":"AM/PM","days-standAlone-abbr":"ne po \u00fat st \u010dt p\u00e1 so".split(" "),"dateFormatItem-d":"d.","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"v\u010dera","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"AM","dateFormatItem-h":"h a",
"field-day-relative+-2":"p\u0159edev\u010d\u00edrem","dateFormatItem-MMMd":"d. M.","dateFormatItem-MEd":"E d. M.","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"tento p\u00e1tek","field-fri-relative+1":"p\u0159\u00ed\u0161t\u00ed p\u00e1tek","field-day":"Den","days-format-wide":"ned\u011ble pond\u011bl\u00ed \u00fater\u00fd st\u0159eda \u010dtvrtek p\u00e1tek sobota".split(" "),"field-zone":"\u010casov\u00e9 p\u00e1smo","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G",
"dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"minul\u00fd rok","field-month-relative+-1":"minul\u00fd m\u011bs\u00edc","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"ne po \u00fat st \u010dt p\u00e1 so".split(" "),eraNames:["AH"],"days-format-narrow":"NP\u00daS\u010cPS".split(""),"dateFormatItem-yyyyMd":"d. M. y GGGGG","field-month":"M\u011bs\u00edc",
"days-standAlone-narrow":"NP\u00daS\u010cPS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"toto \u00fater\u00fd","field-tue-relative+1":"p\u0159\u00ed\u0161t\u00ed \u00fater\u00fd","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"toto pond\u011bl\u00ed","field-mon-relative+1":"p\u0159\u00ed\u0161t\u00ed pond\u011bl\u00ed",
"dateFormat-short":"dd.MM.yy GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Sekunda","field-sat-relative+-1":"minulou sobotu","field-sun-relative+-1":"minulou ned\u011bli","field-month-relative+0":"tento m\u011bs\u00edc","field-month-relative+1":"p\u0159\u00ed\u0161t\u00ed m\u011bs\u00edc","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d.","field-week":"T\u00fdden","dateFormat-medium":"d. M. y G",
"field-week-relative+-1":"minul\u00fd t\u00fdden","field-year-relative+0":"tento rok","dateFormatItem-yyyyM":"M/y GGGGG","field-year-relative+1":"p\u0159\u00ed\u0161t\u00ed rok","dayPeriods-format-narrow-pm":"PM","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"H:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"LLLL y G","field-mon-relative+-1":"minul\u00e9 pond\u011bl\u00ed","dateFormatItem-yyyy":"y G","field-week-relative+0":"tento t\u00fdden",
"field-week-relative+1":"p\u0159\u00ed\u0161t\u00ed t\u00fdden"},"dijit/form/nls/ComboBox":{previousMessage:"P\u0159edchoz\u00ed volby",_localized:{},nextMessage:"Dal\u0161\u00ed volby"}});