// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/nls/widgets_pt-br",{"dijit/_editor/nls/commands":{removeFormat:"Remover Formato",copy:"Copiar",paste:"Colar",selectAll:"Selecionar Todos",insertOrderedList:"Lista Numerada",insertTable:"Inserir/Editar Tabela",print:"Impress\u00e3o",underline:"Sublinhado",foreColor:"Cor do Primeiro Plano",htmlToggle:"Origem HTML",formatBlock:"Estilo de Par\u00e1grafo",newPage:"Nova P\u00e1gina",insertHorizontalRule:"R\u00e9gua Horizontal","delete":"Excluir",appleKey:"\u2318${0}",insertUnorderedList:"Lista com Marcadores",
tableProp:"Propriedade da Tabela",insertImage:"Inserir Imagem",superscript:"Sobrescrito",subscript:"Subscrito",createLink:"Criar Link",undo:"Desfazer",fullScreen:"Comutar Tela Cheia",italic:"It\u00e1lico",fontName:"Nome da Fonte",justifyLeft:"Alinhar pela Esquerda",unlink:"Remover Link",toggleTableBorder:"Alternar Moldura da Tabela",viewSource:"Visualizar Origem HTML",ctrlKey:"ctrl+${0}",fontSize:"Tamanho da Fonte",systemShortcut:'A a\u00e7\u00e3o "${0}" est\u00e1 dispon\u00edvel em seu navegador apenas usando um atalho do teclado. Use ${1}.',
indent:"Recuar",redo:"Refazer",strikethrough:"Tachado",justifyFull:"Justificar",justifyCenter:"Alinhar pelo Centro",hiliteColor:"Cor de segundo plano",deleteTable:"Excluir Tabela",outdent:"N\u00e3o-chanfrado",cut:"Recortar",_localized:{},plainFormatBlock:"Estilo de Par\u00e1grafo",toggleDir:"Comutar Dire\u00e7\u00e3o",bold:"Negrito",tabIndent:"Recuo de Guia",justifyRight:"Alinhar pela Direita"},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"dom seg ter qua qui sex s\u00e1b".split(" "),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"agora","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Dia da semana","field-wed-relative+0":"esta quarta-feira","field-wed-relative+1":"pr\u00f3xima quarta-feira","dateFormatItem-GyMMMEd":"E, d 'de' MMM 'de' y G","dateFormatItem-MMMEd":"E, d 'de' MMM",eraNarrow:["AH"],"field-tue-relative+-1":"ter\u00e7a-feira passada","days-format-short":"dom seg ter qua qui sex s\u00e1b".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"d 'de' MMMM 'de' y G","field-fri-relative+-1":"sexta-feira passada","field-wed-relative+-1":"quarta-feira passada","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, d 'de' MMMM 'de' y G","dateFormatItem-yyyyMEd":"E, dd/MM/y GGGGG","field-thu-relative+-1":"quinta-feira passada",
"dateFormatItem-Md":"d/M",_localized:{},"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"meio-dia","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"timeFormat-long":"HH:mm:ss z",
"field-year":"Ano","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hora","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"este s\u00e1bado","field-sat-relative+1":"pr\u00f3ximo s\u00e1bado","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"hoje","field-thu-relative+0":"esta quinta-feira","field-day-relative+1":"amanh\u00e3","field-thu-relative+1":"pr\u00f3xima quinta-feira",
"dateFormatItem-GyMMMd":"d 'de' MMM 'de' y G","field-day-relative+2":"depois de amanh\u00e3","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, d 'de' MMM 'de' y G","dateFormatItem-M":"L","days-standAlone-wide":"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),
"dateFormatItem-yyyyMMM":"MMM 'de' y G","dateFormatItem-yyyyMMMd":"d 'de' MMM 'de' y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"este domingo","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"pr\u00f3ximo domingo","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["AH"],"field-minute":"Minuto","field-dayperiod":"Per\u00edodo do dia","days-standAlone-abbr":"dom seg ter qua qui sex s\u00e1b".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss",
"quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"ontem","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","field-day-relative+-2":"anteontem","dateFormatItem-MMMd":"d 'de' MMM","dateFormatItem-MEd":"E, dd/MM","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"esta sexta-feira","field-fri-relative+1":"pr\u00f3xima sexta-feira","field-day":"Dia","days-format-wide":"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),
"field-zone":"Fuso","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"ano passado","field-month-relative+-1":"m\u00eas passado","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dom seg ter qua qui sex s\u00e1b".split(" "),eraNames:["AH"],"days-format-narrow":"DSTQQSS".split(""),
"dateFormatItem-yyyyMd":"dd/MM/y GGGGG","field-month":"M\u00eas","days-standAlone-narrow":"DSTQQSS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"esta ter\u00e7a-feira","field-tue-relative+1":"pr\u00f3xima ter\u00e7a-feira","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"esta segunda-feira",
"field-mon-relative+1":"pr\u00f3xima segunda-feira","dateFormat-short":"dd/MM/yy GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Segundo","field-sat-relative+-1":"s\u00e1bado passado","field-sun-relative+-1":"domingo passado","field-month-relative+0":"este m\u00eas","field-month-relative+1":"pr\u00f3ximo m\u00eas","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d","field-week":"Semana","dateFormat-medium":"dd/MM/y G",
"field-week-relative+-1":"semana passada","field-year-relative+0":"este ano","dateFormatItem-yyyyM":"MM/y GGGGG","field-year-relative+1":"pr\u00f3ximo ano","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM 'de' y G","field-mon-relative+-1":"segunda-feira passada","dateFormatItem-yyyy":"y G","field-week-relative+0":"esta semana","field-week-relative+1":"pr\u00f3xima semana"},
"dijit/form/nls/ComboBox":{previousMessage:"Op\u00e7\u00f5es anteriores",_localized:{},nextMessage:"Mais op\u00e7\u00f5es"}});