// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
define("esri/nls/widgets_nl-nl",{"dijit/_editor/nls/commands":{removeFormat:"Opmaak verwijderen",copy:"Kopi\u00ebren",paste:"Plakken",selectAll:"Alles selecteren",insertOrderedList:"Genummerde lijst",insertTable:"Tabel invoegen/bewerken",print:"Afdrukken",underline:"Onderstrepen",foreColor:"Voorgrondkleur",htmlToggle:"HTML-bron",formatBlock:"Alineastijl",newPage:"Nieuwe pagina",insertHorizontalRule:"Horizontale liniaal","delete":"Wissen",appleKey:"\u2318${0}",insertUnorderedList:"Lijst met opsommingstekens",
tableProp:"Tabeleigenschap",insertImage:"Afbeelding invoegen",superscript:"Superscript",subscript:"Subscript",createLink:"Link maken",undo:"Ongedaan maken",fullScreen:"Volledig scherm in-/uitschakelen",italic:"Cursief",fontName:"Lettertype",justifyLeft:"Links uitlijnen",unlink:"Link verwijderen",toggleTableBorder:"Tabelkader wijzigen",viewSource:"HTML-bron bekijken",ctrlKey:"ctrl+${0}",fontSize:"Lettergrootte",systemShortcut:'De actie "${0}" is alleen beschikbaar in uw browser via een sneltoetscombinatie. Gebruik ${1}.',
indent:"Inspringen",redo:"Opnieuw",strikethrough:"Doorhalen",justifyFull:"Uitvullen",justifyCenter:"Centreren",hiliteColor:"Achtergrondkleur",deleteTable:"Tabel wissen",outdent:"Uitspringen",cut:"Knippen",_localized:{},plainFormatBlock:"Alineastijl",toggleDir:"Schrijfrichting wijzigen",bold:"Vet",tabIndent:"Inspringen",justifyRight:"Rechts uitlijnen"},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"zo ma di wo do vr za".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),
"field-second-relative+0":"nu","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Dag van de week","field-wed-relative+0":"deze woensdag","field-wed-relative+1":"volgende week woensdag","dateFormatItem-GyMMMEd":"E d MMM y G","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["Sa\u02bbna Hizjria"],"field-tue-relative+-1":"afgelopen dinsdag","days-format-short":"zo ma di wo do vr za".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM y G","field-fri-relative+-1":"afgelopen vrijdag",
"field-wed-relative+-1":"afgelopen woensdag","months-format-wide":"Moeharram;Safar;Rabi\u02bba al awal;Rabi\u02bba al thani;Joemad\u02bbal awal;Joemad\u02bbal thani;Rajab;Sja\u02bbaban;Ramadan;Sjawal;Doe al ka\u02bbaba;Doe al hizja".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE d MMMM y G","dateFormatItem-yyyyMEd":"E d-M-y GGGGG","field-thu-relative+-1":"afgelopen donderdag","dateFormatItem-Md":"d-M",_localized:{},
"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"12 uur 's middags","field-era":"Tijdperk","months-standAlone-wide":"Moeharram;Safar;Rabi\u02bba al awal;Rabi\u02bba al thani;Joemad\u02bbal awal;Joemad\u02bbal thani;Rajab;Sja\u02bbaban;Ramadan;Sjawal;Doe al ka\u02bbaba;Doe al hizja".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["1e kwartaal","2e kwartaal","3e kwartaal","4e kwartaal"],"timeFormat-long":"HH:mm:ss z",
"field-year":"Jaar","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Uur","dateFormatItem-yyyyMMMM":"MMMM y G","months-format-abbr":"Moeh.;Saf.;Rab. I;Rab. II;Joem. I;Joem. II;Raj.;Sja.;Ram.;Sjaw.;Doe al k.;Doe al h.".split(";"),"field-sat-relative+0":"deze zaterdag","field-sat-relative+1":"volgende week zaterdag","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"vandaag","field-thu-relative+0":"deze donderdag","field-day-relative+1":"morgen",
"field-thu-relative+1":"volgende week donderdag","dateFormatItem-GyMMMd":"d MMM y G","field-day-relative+2":"overmorgen","dateFormatItem-H":"HH","months-standAlone-abbr":"Moeh.;Saf.;Rab. I;Rab. II;Joem. I;Joem. II;Raj.;Sja.;Ram.;Sjaw.;Doe al k.;Doe al h.".split(";"),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["1e kwartaal","2e kwartaal","3e kwartaal","4e kwartaal"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"zondag maandag dinsdag woensdag donderdag vrijdag zaterdag".split(" "),
"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d MMM y G","dateFormatItem-MMMMd":"d MMMM","dayPeriods-format-abbr-noon":"12 uur 's middags","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"deze zondag","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"volgende week zondag","quarters-standAlone-abbr":["K1","K2","K3","K4"],eraAbbr:["Sa\u02bbna Hizjria"],"field-minute":"Minuut","field-dayperiod":"AM/PM","days-standAlone-abbr":"zo ma di wo do vr za".split(" "),"dateFormatItem-d":"d",
"dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"gisteren","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"AM","dateFormatItem-h":"h a","field-day-relative+-2":"eergisteren","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E d-M","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"deze vrijdag","field-fri-relative+1":"volgende week vrijdag","field-day":"Dag","days-format-wide":"zondag maandag dinsdag woensdag donderdag vrijdag zaterdag".split(" "),
"field-zone":"Zone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"vorig jaar","field-month-relative+-1":"vorige maand","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"zo ma di wo do vr za".split(" "),eraNames:["Sa\u02bbna Hizjria"],"days-format-narrow":"ZMDWDVZ".split(""),
"dateFormatItem-yyyyMd":"d-M-y GGGGG","field-month":"Maand","days-standAlone-narrow":"ZMDWDVZ".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"deze dinsdag","field-tue-relative+1":"volgende week dinsdag","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"deze maandag","field-mon-relative+1":"volgende week maandag",
"dateFormat-short":"dd-MM-yy GGGGG","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Seconde","field-sat-relative+-1":"afgelopen zaterdag","field-sun-relative+-1":"afgelopen zondag","field-month-relative+0":"deze maand","field-month-relative+1":"volgende maand","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d","field-week":"Week","dateFormat-medium":"d MMM y G","field-week-relative+-1":"vorige week",
"field-year-relative+0":"dit jaar","dateFormatItem-yyyyM":"M-y GGGGG","field-year-relative+1":"volgend jaar","dayPeriods-format-narrow-pm":"PM","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"afgelopen maandag","dateFormatItem-yyyy":"y G","field-week-relative+0":"deze week","field-week-relative+1":"volgende week"},"dijit/form/nls/ComboBox":{previousMessage:"Eerdere opties",
_localized:{},nextMessage:"Meer opties"}});