/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
require({cache:{"dijit/popup":function(){define("dojo/_base/array dojo/aspect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/keys dojo/_base/lang dojo/on ./place ./BackgroundIframe ./Viewport ./main".split(" "),function(m,k,h,l,e,a,d,f,c,g,b,t,B,u,r,n){function v(){this._popupWrapper&&(a.destroy(this._popupWrapper),delete this._popupWrapper)}h=h(null,{_stack:[],_beginZIndex:1E3,_idGen:1,_repositionAll:function(){if(this._firstAroundNode){var c=
this._firstAroundPosition,a=d.position(this._firstAroundNode,!0),g=a.x-c.x,c=a.y-c.y;if(g||c){this._firstAroundPosition=a;for(a=0;a<this._stack.length;a++){var f=this._stack[a].wrapper.style;f.top=parseFloat(f.top)+c+"px";"auto"==f.right?f.left=parseFloat(f.left)+g+"px":f.right=parseFloat(f.right)-g+"px"}}this._aroundMoveListener=setTimeout(b.hitch(this,"_repositionAll"),g||c?10:50)}},_createWrapper:function(b){var c=b._popupWrapper,g=b.domNode;c||(c=a.create("div",{"class":"dijitPopup",style:{display:"none"},
role:"region","aria-label":b["aria-label"]||b.label||b.name||b.id},b.ownerDocumentBody),c.appendChild(g),g=g.style,g.display="",g.visibility="",g.position="",g.top="0px",b._popupWrapper=c,k.after(b,"destroy",v,!0),"ontouchend"in document&&t(c,"touchend",function(b){/^(input|button|textarea)$/i.test(b.target.tagName)||b.preventDefault()}));return c},moveOffScreen:function(b){var c=this._createWrapper(b);b=d.isBodyLtr(b.ownerDocument);var a={visibility:"hidden",top:"-9999px",display:""};a[b?"left":
"right"]="-9999px";a[b?"right":"left"]="auto";f.set(c,a);return c},hide:function(b){var c=this._createWrapper(b);f.set(c,{display:"none",height:"auto",overflow:"visible",border:""});b=b.domNode;"_originalStyle"in b&&(b.style.cssText=b._originalStyle)},getTopPopup:function(){for(var b=this._stack,c=b.length-1;0<c&&b[c].parent===b[c-1].widget;c--);return b[c]},open:function(a){for(var h=this._stack,n=a.popup,k=n.domNode,m=a.orient||["below","below-alt","above","above-alt"],q=a.parent?a.parent.isLeftToRight():
d.isBodyLtr(n.ownerDocument),F=a.around,v=a.around&&a.around.id?a.around.id+"_dropdown":"popup_"+this._idGen++;h.length&&(!a.parent||!l.isDescendant(a.parent.domNode,h[h.length-1].widget.domNode));)this.close(h[h.length-1].widget);var y=this.moveOffScreen(n);n.startup&&!n._started&&n.startup();var H,I=d.position(k);if("maxHeight"in a&&-1!=a.maxHeight)H=a.maxHeight||Infinity;else{H=r.getEffectiveBox(this.ownerDocument);var M=F?d.position(F,!1):{y:a.y-(a.padding||0),h:2*(a.padding||0)};H=Math.floor(Math.max(M.y,
H.h-(M.y+M.h)))}I.h>H&&(I=f.getComputedStyle(k),f.set(y,{overflowY:"scroll",height:H+"px",border:I.borderLeftWidth+" "+I.borderLeftStyle+" "+I.borderLeftColor}),k._originalStyle=k.style.cssText,k.style.border="none");e.set(y,{id:v,style:{zIndex:this._beginZIndex+h.length},"class":"dijitPopup "+(n.baseClass||n["class"]||"").split(" ")[0]+"Popup",dijitPopupParent:a.parent?a.parent.id:""});0==h.length&&F&&(this._firstAroundNode=F,this._firstAroundPosition=d.position(F,!0),this._aroundMoveListener=setTimeout(b.hitch(this,
"_repositionAll"),50));c("config-bgIframe")&&!n.bgIframe&&(n.bgIframe=new u(y));v=n.orient?b.hitch(n,"orient"):null;m=F?B.around(y,F,m,q,v):B.at(y,a,"R"==m?["TR","BR","TL","BL"]:["TL","BL","TR","BR"],a.padding,v);y.style.visibility="visible";k.style.visibility="visible";k=[];k.push(t(y,"keydown",b.hitch(this,function(b){if(b.keyCode==g.ESCAPE&&a.onCancel)b.stopPropagation(),b.preventDefault(),a.onCancel();else if(b.keyCode==g.TAB&&(b.stopPropagation(),b.preventDefault(),(b=this.getTopPopup())&&b.onCancel))b.onCancel()})));
n.onCancel&&a.onCancel&&k.push(n.on("cancel",a.onCancel));k.push(n.on(n.onExecute?"execute":"change",b.hitch(this,function(){var b=this.getTopPopup();if(b&&b.onExecute)b.onExecute()})));h.push({widget:n,wrapper:y,parent:a.parent,onExecute:a.onExecute,onCancel:a.onCancel,onClose:a.onClose,handlers:k});if(n.onOpen)n.onOpen(m);return m},close:function(b){for(var a=this._stack;b&&m.some(a,function(a){return a.widget==b})||!b&&a.length;){var c=a.pop(),g=c.widget,f=c.onClose;g.bgIframe&&(g.bgIframe.destroy(),
delete g.bgIframe);if(g.onClose)g.onClose();for(var d;d=c.handlers.pop();)d.remove();g&&g.domNode&&this.hide(g);f&&f()}0==a.length&&this._aroundMoveListener&&(clearTimeout(this._aroundMoveListener),this._firstAroundNode=this._firstAroundPosition=this._aroundMoveListener=null)}});return n.popup=new h})},"dojo/string":function(){define(["./_base/kernel","./_base/lang"],function(m,k){var h=/[&<>'"\/]/g,l={"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;","/":"\x26#x2F;"},
e={};k.setObject("dojo.string",e);e.escape=function(a){return!a?"":a.replace(h,function(a){return l[a]})};e.rep=function(a,d){if(0>=d||!a)return"";for(var f=[];;){d&1&&f.push(a);if(!(d>>=1))break;a+=a}return f.join("")};e.pad=function(a,d,f,c){f||(f="0");a=String(a);d=e.rep(f,Math.ceil((d-a.length)/f.length));return c?a+d:d+a};e.substitute=function(a,d,f,c){c=c||m.global;f=f?k.hitch(c,f):function(a){return a};return a.replace(/\$\{([^\s\:\}]+)(?:\:([^\s\:\}]+))?\}/g,function(a,b,e){a=k.getObject(b,
!1,d);e&&(a=k.getObject(e,!1,c).call(c,a,b));return f(a,b).toString()})};e.trim=String.prototype.trim?k.trim:function(a){a=a.replace(/^\s+/,"");for(var d=a.length-1;0<=d;d--)if(/\S/.test(a.charAt(d))){a=a.substring(0,d+1);break}return a};return e})},"dijit/a11y":function(){define("dojo/_base/array dojo/dom dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/sniff ./main".split(" "),function(m,k,h,l,e,a,d){var f={_isElementShown:function(a){var g=l.get(a);return"hidden"!=g.visibility&&"collapsed"!=g.visibility&&
"none"!=g.display&&"hidden"!=h.get(a,"type")},hasDefaultTabStop:function(a){switch(a.nodeName.toLowerCase()){case "a":return h.has(a,"href");case "area":case "button":case "input":case "object":case "select":case "textarea":return!0;case "iframe":var g;try{var b=a.contentDocument;if("designMode"in b&&"on"==b.designMode)return!0;g=b.body}catch(f){try{g=a.contentWindow.document.body}catch(d){return!1}}return g&&("true"==g.contentEditable||g.firstChild&&"true"==g.firstChild.contentEditable);default:return"true"==
a.contentEditable}},effectiveTabIndex:function(a){return h.get(a,"disabled")?void 0:h.has(a,"tabIndex")?+h.get(a,"tabIndex"):f.hasDefaultTabStop(a)?0:void 0},isTabNavigable:function(a){return 0<=f.effectiveTabIndex(a)},isFocusable:function(a){return-1<=f.effectiveTabIndex(a)},_getTabNavigable:function(c){function g(b){return b&&"input"==b.tagName.toLowerCase()&&b.type&&"radio"==b.type.toLowerCase()&&b.name&&b.name.toLowerCase()}var b,d,e,u,l,n,k={},m=f._isElementShown,s=f.effectiveTabIndex,p=function(c){for(c=
c.firstChild;c;c=c.nextSibling)if(!(1!=c.nodeType||9>=a("ie")&&"HTML"!==c.scopeName||!m(c))){var f=s(c);if(0<=f){if(0==f)b||(b=c),d=c;else if(0<f){if(!e||f<u)u=f,e=c;if(!l||f>=n)n=f,l=c}f=g(c);h.get(c,"checked")&&f&&(k[f]=c)}"SELECT"!=c.nodeName.toUpperCase()&&p(c)}};m(c)&&p(c);return{first:k[g(b)]||b,last:k[g(d)]||d,lowest:k[g(e)]||e,highest:k[g(l)]||l}},getFirstInTabbingOrder:function(a,g){var b=f._getTabNavigable(k.byId(a,g));return b.lowest?b.lowest:b.first},getLastInTabbingOrder:function(a,g){var b=
f._getTabNavigable(k.byId(a,g));return b.last?b.last:b.highest}};e.mixin(d,f);return f})},"dijit/WidgetSet":function(){define(["dojo/_base/array","dojo/_base/declare","dojo/_base/kernel","./registry"],function(m,k,h,l){var e=k("dijit.WidgetSet",null,{constructor:function(){this._hash={};this.length=0},add:function(a){if(this._hash[a.id])throw Error("Tried to register widget with id\x3d\x3d"+a.id+" but that id is already registered");this._hash[a.id]=a;this.length++},remove:function(a){this._hash[a]&&
(delete this._hash[a],this.length--)},forEach:function(a,d){d=d||h.global;var f=0,c;for(c in this._hash)a.call(d,this._hash[c],f++,this._hash);return this},filter:function(a,d){d=d||h.global;var f=new e,c=0,g;for(g in this._hash){var b=this._hash[g];a.call(d,b,c++,this._hash)&&f.add(b)}return f},byId:function(a){return this._hash[a]},byClass:function(a){var d=new e,f,c;for(f in this._hash)c=this._hash[f],c.declaredClass==a&&d.add(c);return d},toArray:function(){var a=[],d;for(d in this._hash)a.push(this._hash[d]);
return a},map:function(a,d){return m.map(this.toArray(),a,d)},every:function(a,d){d=d||h.global;var f=0,c;for(c in this._hash)if(!a.call(d,this._hash[c],f++,this._hash))return!1;return!0},some:function(a,d){d=d||h.global;var f=0,c;for(c in this._hash)if(a.call(d,this._hash[c],f++,this._hash))return!0;return!1}});m.forEach("forEach filter byClass map every some".split(" "),function(a){l[a]=e.prototype[a]});return e})},"dijit/_base/wai":function(){define(["dojo/dom-attr","dojo/_base/lang","../main",
"../hccss"],function(m,k,h){k.mixin(h,{hasWaiRole:function(h,e){var a=this.getWaiRole(h);return e?-1<a.indexOf(e):0<a.length},getWaiRole:function(h){return k.trim((m.get(h,"role")||"").replace("wairole:",""))},setWaiRole:function(h,e){m.set(h,"role",e)},removeWaiRole:function(h,e){var a=m.get(h,"role");a&&(e?(a=k.trim((" "+a+" ").replace(" "+e+" "," ")),m.set(h,"role",a)):h.removeAttribute("role"))},hasWaiState:function(h,e){return h.hasAttribute?h.hasAttribute("aria-"+e):!!h.getAttribute("aria-"+
e)},getWaiState:function(h,e){return h.getAttribute("aria-"+e)||""},setWaiState:function(h,e,a){h.setAttribute("aria-"+e,a)},removeWaiState:function(h,e){h.removeAttribute("aria-"+e)}});return h})},"dijit/Viewport":function(){define(["dojo/Evented","dojo/on","dojo/domReady","dojo/sniff","dojo/window"],function(m,k,h,l,e){var a=new m,d;h(function(){var f=e.getBox();a._rlh=k(window,"resize",function(){var c=e.getBox();f.h==c.h&&f.w==c.w||(f=c,a.emit("resize"))});if(8==l("ie")){var c=screen.deviceXDPI;
setInterval(function(){screen.deviceXDPI!=c&&(c=screen.deviceXDPI,a.emit("resize"))},500)}l("ios")&&(k(document,"focusin",function(a){d=a.target}),k(document,"focusout",function(a){d=null}))});a.getEffectiveBox=function(a){a=e.getBox(a);var c=d&&d.tagName&&d.tagName.toLowerCase();if(l("ios")&&d&&!d.readOnly&&("textarea"==c||"input"==c&&/^(color|email|number|password|search|tel|text|url)$/.test(d.type)))a.h*=0==orientation||180==orientation?0.66:0.4,c=d.getBoundingClientRect(),a.h=Math.max(a.h,c.top+
c.height);return a};return a})},"dojo/hccss":function(){define("require ./_base/config ./dom-class ./dom-style ./has ./domReady ./_base/window".split(" "),function(m,k,h,l,e,a,d){e.add("highcontrast",function(){var a=d.doc.createElement("div");a.style.cssText='border: 1px solid; border-color:red green; position: absolute; height: 5px; top: -999px;background-image: url("'+(k.blankGif||m.toUrl("./resources/blank.gif"))+'");';d.body().appendChild(a);var c=l.getComputedStyle(a),g=c.backgroundImage,c=
c.borderTopColor==c.borderRightColor||g&&("none"==g||"url(invalid-url:)"==g);8>=e("ie")?a.outerHTML="":d.body().removeChild(a);return c});a(function(){e("highcontrast")&&h.add(d.body(),"dj_a11y")});return e})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),
function(m,k,h,l,e,a,d,f,c,g,b,t,B,u,r,n,v,x,s,p,w,D,q){function F(b){return function(a){f[a?"set":"remove"](this.domNode,b,a);this._set(b,a)}}B.add("dijit-legacy-requires",!u.isAsync);B.add("dojo-bidi",!1);B("dijit-legacy-requires")&&v(0,function(){m(["dijit/_base/manager"])});var E={};l=a("dijit._WidgetBase",[x,w],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:F("lang"),dir:"",_setDirAttr:F("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",
baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(b){this._set("ownerDocument",b)},attributeMap:{},_blankGif:l.blankGif||m.toUrl("dojo/resources/blank.gif"),_introspect:function(){var b=this.constructor;if(!b._setterAttrs){var a=b.prototype,c=b._setterAttrs=[],b=b._onMap={},g;for(g in a.attributeMap)c.push(g);for(g in a)/^on/.test(g)&&(b[g.substring(2).toLowerCase()]=g),/^_set[A-Z](.*)Attr$/.test(g)&&(g=g.charAt(4).toLowerCase()+g.substr(5,
g.length-9),(!a.attributeMap||!(g in a.attributeMap))&&c.push(g))}},postscript:function(b,a){this.create(b,a)},create:function(b,a){this._introspect();this.srcNodeRef=d.byId(a);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);b&&(this.params=b,r.mixin(this,b));this.postMixInProperties();this.id||(this.id=q.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||
(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=p.body(this.ownerDocument);q.add(this);this.buildRendering();var c;if(this.domNode){this._applyAttributes();var g=this.srcNodeRef;g&&(g.parentNode&&this.domNode!==g)&&(g.parentNode.replaceChild(this.domNode,g),c=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var b={},a;for(a in this.params||{})b[a]=this._get(a);k.forEach(this.constructor._setterAttrs,
function(a){if(!(a in b)){var c=this._get(a);c&&this.set(a,c)}},this);for(a in b)this.set(a,b[a])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var b=this.baseClass.split(" ");this.isLeftToRight()||(b=b.concat(k.map(b,function(b){return b+"Rtl"})));c.add(this.domNode,b)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,k.forEach(this.getChildren(),function(b){!b._started&&
(!b._destroyed&&r.isFunction(b.startup))&&(b.startup(),b._started=!0)}))},destroyRecursive:function(b){this._beingDestroyed=!0;this.destroyDescendants(b);this.destroy(b)},destroy:function(b){function a(c){c.destroyRecursive?c.destroyRecursive(b):c.destroy&&c.destroy(b)}this._beingDestroyed=!0;this.uninitialize();k.forEach(this._connects,r.hitch(this,"disconnect"));k.forEach(this._supportingWidgets,a);this.domNode&&k.forEach(q.findWidgets(this.domNode,this.containerNode),a);this.destroyRendering(b);
q.remove(this.id);this._destroyed=!0},destroyRendering:function(b){this.bgIframe&&(this.bgIframe.destroy(b),delete this.bgIframe);this.domNode&&(b?f.remove(this.domNode,"widgetId"):g.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(b||g.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(b){k.forEach(this.getChildren(),function(a){a.destroyRecursive&&a.destroyRecursive(b)})},uninitialize:function(){return!1},_setStyleAttr:function(b){var a=this.domNode;r.isObject(b)?
t.set(a,b):a.style.cssText=a.style.cssText?a.style.cssText+("; "+b):b;this._set("style",b)},_attrToDom:function(b,a,g){g=3<=arguments.length?g:this.attributeMap[b];k.forEach(r.isArray(g)?g:[g],function(g){var d=this[g.node||g||"domNode"];switch(g.type||"attribute"){case "attribute":r.isFunction(a)&&(a=r.hitch(this,a));g=g.attribute?g.attribute:/^on[A-Z][a-zA-Z]*$/.test(b)?b.toLowerCase():b;d.tagName?f.set(d,g,a):d.set(g,a);break;case "innerText":d.innerHTML="";d.appendChild(this.ownerDocument.createTextNode(a));
break;case "innerHTML":d.innerHTML=a;break;case "class":c.replace(d,a,this[b])}},this)},get:function(b){var a=this._getAttrNames(b);return this[a.g]?this[a.g]():this._get(b)},set:function(b,a){if("object"===typeof b){for(var c in b)this.set(c,b[c]);return this}c=this._getAttrNames(b);var g=this[c.s];if(r.isFunction(g))var d=g.apply(this,Array.prototype.slice.call(arguments,1));else{var g=this.focusNode&&!r.isFunction(this.focusNode)?"focusNode":"domNode",f=this[g]&&this[g].tagName,e;if(e=f)if(!(e=
E[f])){e=this[g];var B={},t;for(t in e)B[t.toLowerCase()]=!0;e=E[f]=B}t=e;c=b in this.attributeMap?this.attributeMap[b]:c.s in this?this[c.s]:t&&c.l in t&&"function"!=typeof a||/^aria-|^data-|^role$/.test(b)?g:null;null!=c&&this._attrToDom(b,a,c);this._set(b,a)}return d||this},_attrPairNames:{},_getAttrNames:function(b){var a=this._attrPairNames;if(a[b])return a[b];var c=b.replace(/^[a-z]|-[a-zA-Z]/g,function(b){return b.charAt(b.length-1).toUpperCase()});return a[b]={n:b+"Node",s:"_set"+c+"Attr",
g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(b,a){var c=this[b];this[b]=a;if(this._created&&!(c===a||c!==c&&a!==a))this._watchCallbacks&&this._watchCallbacks(b,c,a),this.emit("attrmodified-"+b,{detail:{prevValue:c,newValue:a}})},_get:function(b){return this[b]},emit:function(b,a,c){a=a||{};void 0===a.bubbles&&(a.bubbles=!0);void 0===a.cancelable&&(a.cancelable=!0);a.detail||(a.detail={});a.detail.widget=this;var g,d=this["on"+b];d&&(g=d.apply(this,c?c:[a]));this._started&&!this._beingDestroyed&&
n.emit(this.domNode,b.toLowerCase(),a);return g},on:function(b,a){var c=this._onMap(b);return c?h.after(this,c,a,!0):this.own(n(this.domNode,b,a))[0]},_onMap:function(b){var a=this.constructor,c=a._onMap;if(!c){var c=a._onMap={},g;for(g in a.prototype)/^on/.test(g)&&(c[g.replace(/^on/,"").toLowerCase()]=g)}return c["string"==typeof b&&b.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?q.findWidgets(this.containerNode):
[]},getParent:function(){return q.getEnclosingWidget(this.domNode.parentNode)},connect:function(b,a,c){return this.own(e.connect(b,a,this,c))[0]},disconnect:function(b){b.remove()},subscribe:function(b,a){return this.own(s.subscribe(b,r.hitch(this,a)))[0]},unsubscribe:function(b){b.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():b.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=t.get(this.domNode,"display")},placeAt:function(b,a){var c=
!b.tagName&&q.byId(b);c&&c.addChild&&(!a||"number"===typeof a)?c.addChild(this,a):(c=c&&"domNode"in c?c.containerNode&&!/after|before|replace/.test(a||"")?c.containerNode:c.domNode:d.byId(b,this.ownerDocument),g.place(this.domNode,c,a),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(b,a){var c=setTimeout(r.hitch(this,function(){c&&(c=null,this._destroyed||r.hitch(this,b)())}),a||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}});B("dojo-bidi")&&
l.extend(D);return l})},"dijit/_base":function(){define("./main ./a11y ./WidgetSet ./_base/focus ./_base/manager ./_base/place ./_base/popup ./_base/scroll ./_base/sniff ./_base/typematic ./_base/wai ./_base/window".split(" "),function(m){return m._base})},"dojo/touch":function(){define("./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(m,k,h,l,e,a,d,f,c,g){function b(b,c,g){return r&&g?function(b,c){return a(b,g,c)}:v?function(g,
d){var f=a(g,c,function(b){d.call(this,b);H=(new Date).getTime()}),e=a(g,b,function(b){(!H||(new Date).getTime()>H+1E3)&&d.call(this,b)});return{remove:function(){f.remove();e.remove()}}}:function(c,g){return a(c,b,g)}}function t(b){do if(void 0!==b.dojoClick)return b;while(b=b.parentNode)}function B(b,c,d){var f=t(b.target);if(s=!b.target.disabled&&f&&f.dojoClick)if(w=(p="useTarget"==s)?f:b.target,p&&b.preventDefault(),D=b.changedTouches?b.changedTouches[0].pageX-g.global.pageXOffset:b.clientX,q=
b.changedTouches?b.changedTouches[0].pageY-g.global.pageYOffset:b.clientY,F=("object"==typeof s?s.x:"number"==typeof s?s:0)||4,E=("object"==typeof s?s.y:"number"==typeof s?s:0)||4,!x){x=!0;var e=function(b){s=p?h.isDescendant(g.doc.elementFromPoint(b.changedTouches?b.changedTouches[0].pageX-g.global.pageXOffset:b.clientX,b.changedTouches?b.changedTouches[0].pageY-g.global.pageYOffset:b.clientY),w):s&&(b.changedTouches?b.changedTouches[0].target:b.target)==w&&Math.abs((b.changedTouches?b.changedTouches[0].pageX-
g.global.pageXOffset:b.clientX)-D)<=F&&Math.abs((b.changedTouches?b.changedTouches[0].pageY-g.global.pageYOffset:b.clientY)-q)<=E};g.doc.addEventListener(c,function(b){e(b);p&&b.preventDefault()},!0);g.doc.addEventListener(d,function(b){e(b);if(s){y=(new Date).getTime();var c=p?w:b.target;"LABEL"===c.tagName&&(c=h.byId(c.getAttribute("for"))||c);var g=b.changedTouches?b.changedTouches[0]:b,d=document.createEvent("MouseEvents");d._dojo_click=!0;d.initMouseEvent("click",!0,!0,b.view,b.detail,g.screenX,
g.screenY,g.clientX,g.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,null);setTimeout(function(){a.emit(c,"click",d);y=(new Date).getTime()},0)}},!0);b=function(b){g.doc.addEventListener(b,function(a){!a._dojo_click&&((new Date).getTime()<=y+1E3&&!("INPUT"==a.target.tagName&&l.contains(a.target,"dijitOffScreen")))&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),"click"==b&&(("INPUT"!=a.target.tagName||"radio"==a.target.type||"checkbox"==a.target.type)&&"TEXTAREA"!=
a.target.tagName&&"AUDIO"!=a.target.tagName&&"VIDEO"!=a.target.tagName)&&a.preventDefault())},!0)};b("click");b("mousedown");b("mouseup")}}var u=5>d("ios"),r=d("pointer-events")||d("MSPointer"),n=function(){var b={},a;for(a in{down:1,move:1,up:1,cancel:1,over:1,out:1})b[a]=d("MSPointer")?"MSPointer"+a.charAt(0).toUpperCase()+a.slice(1):"pointer"+a;return b}(),v=d("touch-events"),x,s,p=!1,w,D,q,F,E,y,H,I;r?c(function(){g.doc.addEventListener(n.down,function(b){B(b,n.move,n.up)},!0)}):v&&c(function(){function b(a){var c=
e.delegate(a,{bubbles:!0});6<=d("ios")&&(c.touches=a.touches,c.altKey=a.altKey,c.changedTouches=a.changedTouches,c.ctrlKey=a.ctrlKey,c.metaKey=a.metaKey,c.shiftKey=a.shiftKey,c.targetTouches=a.targetTouches);return c}I=g.body();g.doc.addEventListener("touchstart",function(b){H=(new Date).getTime();var c=I;I=b.target;a.emit(c,"dojotouchout",{relatedTarget:I,bubbles:!0});a.emit(I,"dojotouchover",{relatedTarget:c,bubbles:!0});B(b,"touchmove","touchend")},!0);a(g.doc,"touchmove",function(c){H=(new Date).getTime();
var d=g.doc.elementFromPoint(c.pageX-(u?0:g.global.pageXOffset),c.pageY-(u?0:g.global.pageYOffset));d&&(I!==d&&(a.emit(I,"dojotouchout",{relatedTarget:d,bubbles:!0}),a.emit(d,"dojotouchover",{relatedTarget:I,bubbles:!0}),I=d),a.emit(d,"dojotouchmove",b(c))||c.preventDefault())});a(g.doc,"touchend",function(c){H=(new Date).getTime();var d=g.doc.elementFromPoint(c.pageX-(u?0:g.global.pageXOffset),c.pageY-(u?0:g.global.pageYOffset))||g.body();a.emit(d,"dojotouchend",b(c))})});k={press:b("mousedown",
"touchstart",n.down),move:b("mousemove","dojotouchmove",n.move),release:b("mouseup","dojotouchend",n.up),cancel:b(f.leave,"touchcancel",r?n.cancel:null),over:b("mouseover","dojotouchover",n.over),out:b("mouseout","dojotouchout",n.out),enter:f._eventHandler(b("mouseover","dojotouchover",n.over)),leave:f._eventHandler(b("mouseout","dojotouchout",n.out))};return m.touch=k})},"dijit/form/_FormValueMixin":function(){define("dojo/_base/declare dojo/dom-attr dojo/keys dojo/_base/lang dojo/on ./_FormWidgetMixin".split(" "),
function(m,k,h,l,e,a){return m("dijit.form._FormValueMixin",a,{readOnly:!1,_setReadOnlyAttr:function(a){k.set(this.focusNode,"readOnly",a);this._set("readOnly",a)},postCreate:function(){this.inherited(arguments);void 0===this._resetValue&&(this._lastValueReported=this._resetValue=this.value)},_setValueAttr:function(a,f){this._handleOnChange(a,f)},_handleOnChange:function(a,f){this._set("value",a);this.inherited(arguments)},undo:function(){this._setValueAttr(this._lastValueReported,!1)},reset:function(){this._hasBeenBlurred=
!1;this._setValueAttr(this._resetValue,!0)}})})},"dojo/Stateful":function(){define(["./_base/declare","./_base/lang","./_base/array","./when"],function(m,k,h,l){return m("dojo.Stateful",null,{_attrPairNames:{},_getAttrNames:function(e){var a=this._attrPairNames;return a[e]?a[e]:a[e]={s:"_"+e+"Setter",g:"_"+e+"Getter"}},postscript:function(e){e&&this.set(e)},_get:function(e,a){return"function"===typeof this[a.g]?this[a.g]():this[e]},get:function(e){return this._get(e,this._getAttrNames(e))},set:function(e,
a){if("object"===typeof e){for(var d in e)e.hasOwnProperty(d)&&"_watchCallbacks"!=d&&this.set(d,e[d]);return this}d=this._getAttrNames(e);var f=this._get(e,d);d=this[d.s];var c;"function"===typeof d?c=d.apply(this,Array.prototype.slice.call(arguments,1)):this[e]=a;if(this._watchCallbacks){var g=this;l(c,function(){g._watchCallbacks(e,f,a)})}return this},_changeAttrValue:function(e,a){var d=this.get(e);this[e]=a;this._watchCallbacks&&this._watchCallbacks(e,d,a);return this},watch:function(e,a){var d=
this._watchCallbacks;if(!d)var f=this,d=this._watchCallbacks=function(b,a,c,g){var e=function(g){if(g){g=g.slice();for(var d=0,e=g.length;d<e;d++)g[d].call(f,b,a,c)}};e(d["_"+b]);g||e(d["*"])};!a&&"function"===typeof e?(a=e,e="*"):e="_"+e;var c=d[e];"object"!==typeof c&&(c=d[e]=[]);c.push(a);var g={};g.unwatch=g.remove=function(){var b=h.indexOf(c,a);-1<b&&c.splice(b,1)};return g}})})},"dijit/_CssStateMixin":function(){define("dojo/_base/array dojo/_base/declare dojo/dom dojo/dom-class dojo/has dojo/_base/lang dojo/on dojo/domReady dojo/touch dojo/_base/window ./a11yclick ./registry".split(" "),
function(m,k,h,l,e,a,d,f,c,g,b,t){k=k("dijit._CssStateMixin",[],{hovering:!1,active:!1,_applyAttributes:function(){this.inherited(arguments);m.forEach("disabled readOnly checked selected focused state hovering active _opened".split(" "),function(b){this.watch(b,a.hitch(this,"_setStateClass"))},this);for(var b in this.cssStateNodes||{})this._trackMouseState(this[b],this.cssStateNodes[b]);this._trackMouseState(this.domNode,this.baseClass);this._setStateClass()},_cssMouseEvent:function(b){if(!this.disabled)switch(b.type){case "mouseover":case "MSPointerOver":case "pointerover":this._set("hovering",
!0);this._set("active",this._mouseDown);break;case "mouseout":case "MSPointerOut":case "pointerout":this._set("hovering",!1);this._set("active",!1);break;case "mousedown":case "touchstart":case "MSPointerDown":case "pointerdown":case "keydown":this._set("active",!0);break;case "mouseup":case "dojotouchend":case "MSPointerUp":case "pointerup":case "keyup":this._set("active",!1)}},_setStateClass:function(){function b(c){a=a.concat(m.map(a,function(b){return b+c}),"dijit"+c)}var a=this.baseClass.split(" ");
this.isLeftToRight()||b("Rtl");var c="mixed"==this.checked?"Mixed":this.checked?"Checked":"";this.checked&&b(c);this.state&&b(this.state);this.selected&&b("Selected");this._opened&&b("Opened");this.disabled?b("Disabled"):this.readOnly?b("ReadOnly"):this.active?b("Active"):this.hovering&&b("Hover");this.focused&&b("Focused");var c=this.stateNode||this.domNode,g={};m.forEach(c.className.split(" "),function(b){g[b]=!0});"_stateClasses"in this&&m.forEach(this._stateClasses,function(b){delete g[b]});m.forEach(a,
function(b){g[b]=!0});var d=[],f;for(f in g)d.push(f);c.className=d.join(" ");this._stateClasses=a},_subnodeCssMouseEvent:function(b,a,c){function g(c){l.toggle(b,a+"Active",c)}if(!this.disabled&&!this.readOnly)switch(c.type){case "mouseover":case "MSPointerOver":case "pointerover":l.toggle(b,a+"Hover",!0);break;case "mouseout":case "MSPointerOut":case "pointerout":l.toggle(b,a+"Hover",!1);g(!1);break;case "mousedown":case "touchstart":case "MSPointerDown":case "pointerdown":case "keydown":g(!0);
break;case "mouseup":case "MSPointerUp":case "pointerup":case "dojotouchend":case "keyup":g(!1);break;case "focus":case "focusin":l.toggle(b,a+"Focused",!0);break;case "blur":case "focusout":l.toggle(b,a+"Focused",!1)}},_trackMouseState:function(b,a){b._cssState=a}});f(function(){function a(b,c,g){if(!g||!h.isDescendant(g,c))for(;c&&c!=g;c=c.parentNode)if(c._cssState){var d=t.getEnclosingWidget(c);d&&(c==d.domNode?d._cssMouseEvent(b):d._subnodeCssMouseEvent(c,c._cssState,b))}}var f=g.body(),e;d(f,
c.over,function(b){a(b,b.target,b.relatedTarget)});d(f,c.out,function(b){a(b,b.target,b.relatedTarget)});d(f,b.press,function(b){e=b.target;a(b,e)});d(f,b.release,function(b){a(b,e);e=null});d(f,"focusin, focusout",function(b){var a=b.target;if(a._cssState&&!a.getAttribute("widgetId")){var c=t.getEnclosingWidget(a);c&&c._subnodeCssMouseEvent(a,a._cssState,b)}})});return k})},"dijit/_base/manager":function(){define(["dojo/_base/array","dojo/_base/config","dojo/_base/lang","../registry","../main"],
function(m,k,h,l,e){var a={};m.forEach("byId getUniqueId findWidgets _destroyAll byNode getEnclosingWidget".split(" "),function(d){a[d]=l[d]});h.mixin(a,{defaultDuration:k.defaultDuration||200});h.mixin(e,a);return e})},"dijit/_base/sniff":function(){define(["dojo/uacss"],function(){})},"dijit/BackgroundIframe":function(){define("require ./main dojo/_base/config dojo/dom-construct dojo/dom-style dojo/_base/lang dojo/on dojo/sniff".split(" "),function(m,k,h,l,e,a,d,f){f.add("config-bgIframe",f("ie")&&
!/IEMobile\/10\.0/.test(navigator.userAgent)||f("trident")&&/Windows NT 6.[01]/.test(navigator.userAgent));var c=new function(){var a=[];this.pop=function(){var b;a.length?(b=a.pop(),b.style.display=""):(9>f("ie")?(b="\x3ciframe src\x3d'"+(h.dojoBlankHtmlUrl||m.toUrl("dojo/resources/blank.html")||'javascript:""')+"' role\x3d'presentation' style\x3d'position: absolute; left: 0px; top: 0px;z-index: -1; filter:Alpha(Opacity\x3d\"0\");'\x3e",b=document.createElement(b)):(b=l.create("iframe"),b.src='javascript:""',
b.className="dijitBackgroundIframe",b.setAttribute("role","presentation"),e.set(b,"opacity",0.1)),b.tabIndex=-1);return b};this.push=function(b){b.style.display="none";a.push(b)}};k.BackgroundIframe=function(g){if(!g.id)throw Error("no id");if(f("config-bgIframe")){var b=this.iframe=c.pop();g.appendChild(b);7>f("ie")||f("quirks")?(this.resize(g),this._conn=d(g,"resize",a.hitch(this,"resize",g))):e.set(b,{width:"100%",height:"100%"})}};a.extend(k.BackgroundIframe,{resize:function(a){this.iframe&&e.set(this.iframe,
{width:a.offsetWidth+"px",height:a.offsetHeight+"px"})},destroy:function(){this._conn&&(this._conn.remove(),this._conn=null);this.iframe&&(this.iframe.parentNode.removeChild(this.iframe),c.push(this.iframe),delete this.iframe)}});return k.BackgroundIframe})},"dijit/typematic":function(){define("dojo/_base/array dojo/_base/connect dojo/_base/lang dojo/on dojo/sniff ./main".split(" "),function(m,k,h,l,e,a){var d=a.typematic={_fireEventAndReload:function(){this._timer=null;this._callback(++this._count,
this._node,this._evt);this._currentTimeout=Math.max(0>this._currentTimeout?this._initialDelay:1<this._subsequentDelay?this._subsequentDelay:Math.round(this._currentTimeout*this._subsequentDelay),this._minDelay);this._timer=setTimeout(h.hitch(this,"_fireEventAndReload"),this._currentTimeout)},trigger:function(a,c,g,b,d,e,k,l){if(d!=this._obj){this.stop();this._initialDelay=k||500;this._subsequentDelay=e||0.9;this._minDelay=l||10;this._obj=d;this._node=g;this._count=this._currentTimeout=-1;this._callback=
h.hitch(c,b);this._evt={faux:!0};for(var m in a)"layerX"!=m&&"layerY"!=m&&(c=a[m],"function"!=typeof c&&"undefined"!=typeof c&&(this._evt[m]=c));this._fireEventAndReload()}},stop:function(){this._timer&&(clearTimeout(this._timer),this._timer=null);this._obj&&(this._callback(-1,this._node,this._evt),this._obj=null)},addKeyListener:function(a,c,g,b,e,B,u){var r="keyCode"in c?"keyCode":"charCode"in c?"charCode":"charOrCode",n=[l(a,"keyCode"in c?"keydown":"charCode"in c?"keypress":k._keypress,h.hitch(this,
function(h){h[r]==c[r]&&(void 0===c.ctrlKey||c.ctrlKey==h.ctrlKey)&&(void 0===c.altKey||c.altKey==h.altKey)&&(void 0===c.metaKey||c.metaKey==(h.metaKey||!1))&&(void 0===c.shiftKey||c.shiftKey==h.shiftKey)?(h.stopPropagation(),h.preventDefault(),d.trigger(h,g,a,b,c,e,B,u)):d._obj==c&&d.stop()})),l(a,"keyup",h.hitch(this,function(){d._obj==c&&d.stop()}))];return{remove:function(){m.forEach(n,function(b){b.remove()})}}},addMouseListener:function(a,c,g,b,t,B){var k=[l(a,"mousedown",h.hitch(this,function(e){e.preventDefault();
d.trigger(e,c,a,g,a,b,t,B)})),l(a,"mouseup",h.hitch(this,function(b){this._obj&&b.preventDefault();d.stop()})),l(a,"mouseout",h.hitch(this,function(b){this._obj&&b.preventDefault();d.stop()})),l(a,"dblclick",h.hitch(this,function(k){k.preventDefault();9>e("ie")&&(d.trigger(k,c,a,g,a,b,t,B),setTimeout(h.hitch(this,d.stop),50))}))];return{remove:function(){m.forEach(k,function(b){b.remove()})}}},addListener:function(a,c,g,b,d,e,h,k){var l=[this.addKeyListener(c,g,b,d,e,h,k),this.addMouseListener(a,
b,d,e,h,k)];return{remove:function(){m.forEach(l,function(b){b.remove()})}}}};return d})},"dojo/_base/url":function(){define(["./kernel"],function(m){var k=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,h=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,l=function(){for(var e=arguments,a=[e[0]],d=1;d<e.length;d++)if(e[d]){var f=new l(e[d]+""),a=new l(a[0]+"");if(""==f.path&&!f.scheme&&!f.authority&&!f.query)null!=f.fragment&&(a.fragment=f.fragment),f=a;else if(!f.scheme&&
(f.scheme=a.scheme,!f.authority&&(f.authority=a.authority,"/"!=f.path.charAt(0)))){for(var a=(a.path.substring(0,a.path.lastIndexOf("/")+1)+f.path).split("/"),c=0;c<a.length;c++)"."==a[c]?c==a.length-1?a[c]="":(a.splice(c,1),c--):0<c&&(!(1==c&&""==a[0])&&".."==a[c]&&".."!=a[c-1])&&(c==a.length-1?(a.splice(c,1),a[c-1]=""):(a.splice(c-1,2),c-=2));f.path=a.join("/")}a=[];f.scheme&&a.push(f.scheme,":");f.authority&&a.push("//",f.authority);a.push(f.path);f.query&&a.push("?",f.query);f.fragment&&a.push("#",
f.fragment)}this.uri=a.join("");e=this.uri.match(k);this.scheme=e[2]||(e[1]?"":null);this.authority=e[4]||(e[3]?"":null);this.path=e[5];this.query=e[7]||(e[6]?"":null);this.fragment=e[9]||(e[8]?"":null);null!=this.authority&&(e=this.authority.match(h),this.user=e[3]||null,this.password=e[4]||null,this.host=e[6]||e[7],this.port=e[9]||null)};l.prototype.toString=function(){return this.uri};return m._Url=l})},"dojo/date/stamp":function(){define(["../_base/lang","../_base/array"],function(m,k){var h=
{};m.setObject("dojo.date.stamp",h);h.fromISOString=function(l,e){h._isoRegExp||(h._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/);var a=h._isoRegExp.exec(l),d=null;if(a){a.shift();a[1]&&a[1]--;a[6]&&(a[6]*=1E3);e&&(e=new Date(e),k.forEach(k.map("FullYear Month Date Hours Minutes Seconds Milliseconds".split(" "),function(a){return e["get"+a]()}),function(c,b){a[b]=a[b]||c}));d=new Date(a[0]||1970,a[1]||0,a[2]||1,a[3]||0,a[4]||
0,a[5]||0,a[6]||0);100>a[0]&&d.setFullYear(a[0]||1970);var f=0,c=a[7]&&a[7].charAt(0);"Z"!=c&&(f=60*(a[8]||0)+(Number(a[9])||0),"-"!=c&&(f*=-1));c&&(f-=d.getTimezoneOffset());f&&d.setTime(d.getTime()+6E4*f)}return d};h.toISOString=function(h,e){var a=function(b){return 10>b?"0"+b:b};e=e||{};var d=[],f=e.zulu?"getUTC":"get",c="";"time"!=e.selector&&(c=h[f+"FullYear"](),c=["0000".substr((c+"").length)+c,a(h[f+"Month"]()+1),a(h[f+"Date"]())].join("-"));d.push(c);if("date"!=e.selector){c=[a(h[f+"Hours"]()),
a(h[f+"Minutes"]()),a(h[f+"Seconds"]())].join(":");f=h[f+"Milliseconds"]();e.milliseconds&&(c+="."+(100>f?"0":"")+a(f));if(e.zulu)c+="Z";else if("time"!=e.selector)var f=h.getTimezoneOffset(),g=Math.abs(f),c=c+((0<f?"-":"+")+a(Math.floor(g/60))+":"+a(g%60));d.push(c)}return d.join("T")};return h})},"dijit/_base/place":function(){define(["dojo/_base/array","dojo/_base/lang","dojo/window","../place","../main"],function(m,k,h,l,e){var a={getViewport:function(){return h.getBox()}};a.placeOnScreen=l.at;
a.placeOnScreenAroundElement=function(a,f,c,g){var b;if(k.isArray(c))b=c;else{b=[];for(var e in c)b.push({aroundCorner:e,corner:c[e]})}return l.around(a,f,b,!0,g)};a.placeOnScreenAroundNode=a.placeOnScreenAroundElement;a.placeOnScreenAroundRectangle=a.placeOnScreenAroundElement;a.getPopupAroundAlignment=function(a,f){var c={};m.forEach(a,function(a){var b=f;switch(a){case "after":c[f?"BR":"BL"]=f?"BL":"BR";break;case "before":c[f?"BL":"BR"]=f?"BR":"BL";break;case "below-alt":b=!b;case "below":c[b?
"BL":"BR"]=b?"TL":"TR";c[b?"BR":"BL"]=b?"TR":"TL";break;case "above-alt":b=!b;default:c[b?"TL":"TR"]=b?"BL":"BR",c[b?"TR":"TL"]=b?"BR":"BL"}});return c};k.mixin(e,a);return e})},"dijit/registry":function(){define(["dojo/_base/array","dojo/_base/window","./main"],function(m,k,h){var l={},e={},a={length:0,add:function(a){if(e[a.id])throw Error("Tried to register widget with id\x3d\x3d"+a.id+" but that id is already registered");e[a.id]=a;this.length++},remove:function(a){e[a]&&(delete e[a],this.length--)},
byId:function(a){return"string"==typeof a?e[a]:a},byNode:function(a){return e[a.getAttribute("widgetId")]},toArray:function(){var a=[],f;for(f in e)a.push(e[f]);return a},getUniqueId:function(a){var f;do f=a+"_"+(a in l?++l[a]:l[a]=0);while(e[f]);return"dijit"==h._scopeName?f:h._scopeName+"_"+f},findWidgets:function(a,f){function c(b){for(b=b.firstChild;b;b=b.nextSibling)if(1==b.nodeType){var a=b.getAttribute("widgetId");a?(a=e[a])&&g.push(a):b!==f&&c(b)}}var g=[];c(a);return g},_destroyAll:function(){h._curFocus=
null;h._prevFocus=null;h._activeStack=[];m.forEach(a.findWidgets(k.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(a){for(;a;){var f=1==a.nodeType&&a.getAttribute("widgetId");if(f)return e[f];a=a.parentNode}return null},_hash:e};return h.registry=a})},"dijit/form/_FormWidgetMixin":function(){define("dojo/_base/array dojo/_base/declare dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/mouse dojo/on dojo/sniff dojo/window ../a11y".split(" "),
function(m,k,h,l,e,a,d,f,c,g){return k("dijit.form._FormWidgetMixin",null,{name:"",alt:"",value:"",type:"text","aria-label":"focusNode",tabIndex:"0",_setTabIndexAttr:"focusNode",disabled:!1,intermediateChanges:!1,scrollOnFocus:!0,_setIdAttr:"focusNode",_setDisabledAttr:function(b){this._set("disabled",b);h.set(this.focusNode,"disabled",b);this.valueNode&&h.set(this.valueNode,"disabled",b);this.focusNode.setAttribute("aria-disabled",b?"true":"false");b?(this._set("hovering",!1),this._set("active",
!1),b="tabIndex"in this.attributeMap?this.attributeMap.tabIndex:"_setTabIndexAttr"in this?this._setTabIndexAttr:"focusNode",m.forEach(e.isArray(b)?b:[b],function(b){b=this[b];f("webkit")||g.hasDefaultTabStop(b)?b.setAttribute("tabIndex","-1"):b.removeAttribute("tabIndex")},this)):""!=this.tabIndex&&this.set("tabIndex",this.tabIndex)},_onFocus:function(b){if("mouse"==b&&this.isFocusable())var a=this.own(d(this.focusNode,"focus",function(){h.remove();a.remove()}))[0],g=f("pointer-events")?"pointerup":
f("MSPointer")?"MSPointerUp":f("touch-events")?"touchend, mouseup":"mouseup",h=this.own(d(this.ownerDocumentBody,g,e.hitch(this,function(b){h.remove();a.remove();this.focused&&("touchend"==b.type?this.defer("focus"):this.focus())})))[0];this.scrollOnFocus&&this.defer(function(){c.scrollIntoView(this.domNode)});this.inherited(arguments)},isFocusable:function(){return!this.disabled&&this.focusNode&&"none"!=l.get(this.domNode,"display")},focus:function(){if(!this.disabled&&this.focusNode.focus)try{this.focusNode.focus()}catch(b){}},
compare:function(b,a){return"number"==typeof b&&"number"==typeof a?isNaN(b)&&isNaN(a)?0:b-a:b>a?1:b<a?-1:0},onChange:function(){},_onChangeActive:!1,_handleOnChange:function(b,a){if(void 0==this._lastValueReported&&(null===a||!this._onChangeActive))this._resetValue=this._lastValueReported=b;this._pendingOnChange=this._pendingOnChange||typeof b!=typeof this._lastValueReported||0!=this.compare(b,this._lastValueReported);if((this.intermediateChanges||a||void 0===a)&&this._pendingOnChange)this._lastValueReported=
b,this._pendingOnChange=!1,this._onChangeActive&&(this._onChangeHandle&&this._onChangeHandle.remove(),this._onChangeHandle=this.defer(function(){this._onChangeHandle=null;this.onChange(b)}))},create:function(){this.inherited(arguments);this._onChangeActive=!0},destroy:function(){this._onChangeHandle&&(this._onChangeHandle.remove(),this.onChange(this._lastValueReported));this.inherited(arguments)}})})},"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),
function(m,k,h,l,e,a,d,f,c){var g=e.delegate(f,{mouseenter:a.enter,mouseleave:a.leave,keypress:h._keypress}),b;h=l("dijit._AttachMixin",null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},_beforeFillContent:function(){},_attachTemplateNodes:function(b){for(var a=b;;)if(1==a.nodeType&&(this._processTemplateNode(a,function(b,a){return b.getAttribute(a)},this._attach)||
this.searchContainerNode)&&a.firstChild)a=a.firstChild;else{if(a==b)break;for(;!a.nextSibling;)if(a=a.parentNode,a==b)return;a=a.nextSibling}},_processTemplateNode:function(b,a,c){var g=!0,f=this.attachScope||this,d=a(b,"dojoAttachPoint")||a(b,"data-dojo-attach-point");if(d)for(var h=d.split(/\s*,\s*/);d=h.shift();)e.isArray(f[d])?f[d].push(b):f[d]=b,g="containerNode"!=d,this._attachPoints.push(d);if(a=a(b,"dojoAttachEvent")||a(b,"data-dojo-attach-event")){d=a.split(/\s*,\s*/);for(h=e.trim;a=d.shift();)if(a){var k=
null;-1!=a.indexOf(":")?(k=a.split(":"),a=h(k[0]),k=h(k[1])):a=h(a);k||(k=a);this._attachEvents.push(c(b,a,e.hitch(f,k)))}}return g},_attach:function(a,c,f){c=c.replace(/^on/,"").toLowerCase();c="dijitclick"==c?b||(b=m("./a11yclick")):g[c]||c;return d(a,c,f)},_detachTemplateNodes:function(){var b=this.attachScope||this;k.forEach(this._attachPoints,function(a){delete b[a]});this._attachPoints=[];k.forEach(this._attachEvents,function(b){b.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();
this.inherited(arguments)}});e.extend(c,{dojoAttachEvent:"",dojoAttachPoint:""});return h})},"dojo/uacss":function(){define(["./dom-geometry","./_base/lang","./domReady","./sniff","./_base/window"],function(m,k,h,l,e){var a=e.doc.documentElement;e=l("ie");var d=l("opera"),f=Math.floor,c=l("ff"),g=m.boxModel.replace(/-/,""),d={dj_quirks:l("quirks"),dj_opera:d,dj_khtml:l("khtml"),dj_webkit:l("webkit"),dj_safari:l("safari"),dj_chrome:l("chrome"),dj_gecko:l("mozilla"),dj_ios:l("ios"),dj_android:l("android")};
e&&(d.dj_ie=!0,d["dj_ie"+f(e)]=!0,d.dj_iequirks=l("quirks"));c&&(d["dj_ff"+f(c)]=!0);d["dj_"+g]=!0;var b="",t;for(t in d)d[t]&&(b+=t+" ");a.className=k.trim(a.className+" "+b);h(function(){if(!m.isBodyLtr()){var c="dj_rtl dijitRtl "+b.replace(/ /g,"-rtl ");a.className=k.trim(a.className+" "+c+"dj_rtl dijitRtl "+b.replace(/ /g,"-rtl "))}});return l})},"dijit/place":function(){define("dojo/_base/array dojo/dom-geometry dojo/dom-style dojo/_base/kernel dojo/_base/window ./Viewport ./main".split(" "),
function(m,k,h,l,e,a,d){function f(c,b,d,f){var l=a.getEffectiveBox(c.ownerDocument);(!c.parentNode||"body"!=String(c.parentNode.tagName).toLowerCase())&&e.body(c.ownerDocument).appendChild(c);var r=null;m.some(b,function(b){var a=b.corner,e=b.pos,h=0,m={w:{L:l.l+l.w-e.x,R:e.x-l.l,M:l.w}[a.charAt(1)],h:{T:l.t+l.h-e.y,B:e.y-l.t,M:l.h}[a.charAt(0)]},q=c.style;q.left=q.right="auto";d&&(h=d(c,b.aroundCorner,a,m,f),h="undefined"==typeof h?0:h);var n=c.style,E=n.display,y=n.visibility;"none"==n.display&&
(n.visibility="hidden",n.display="");q=k.position(c);n.display=E;n.visibility=y;E={L:e.x,R:e.x-q.w,M:Math.max(l.l,Math.min(l.l+l.w,e.x+(q.w>>1))-q.w)}[a.charAt(1)];y={T:e.y,B:e.y-q.h,M:Math.max(l.t,Math.min(l.t+l.h,e.y+(q.h>>1))-q.h)}[a.charAt(0)];e=Math.max(l.l,E);n=Math.max(l.t,y);E=Math.min(l.l+l.w,E+q.w);y=Math.min(l.t+l.h,y+q.h);E-=e;y-=n;h+=q.w-E+(q.h-y);if(null==r||h<r.overflow)r={corner:a,aroundCorner:b.aroundCorner,x:e,y:n,w:E,h:y,overflow:h,spaceAvailable:m};return!h});r.overflow&&d&&d(c,
r.aroundCorner,r.corner,r.spaceAvailable,f);b=r.y;var n=r.x,v=e.body(c.ownerDocument);/relative|absolute/.test(h.get(v,"position"))&&(b-=h.get(v,"marginTop"),n-=h.get(v,"marginLeft"));v=c.style;v.top=b+"px";v.left=n+"px";v.right="auto";return r}var c={TL:"BR",TR:"BL",BL:"TR",BR:"TL"};return d.place={at:function(a,b,d,e,h){d=m.map(d,function(a){var g={corner:a,aroundCorner:c[a],pos:{x:b.x,y:b.y}};e&&(g.pos.x+="L"==a.charAt(1)?e.x:-e.x,g.pos.y+="T"==a.charAt(0)?e.y:-e.y);return g});return f(a,d,h)},
around:function(a,b,c,e,d){function r(b,a){y.push({aroundCorner:b,corner:a,pos:{x:{L:D,R:D+F,M:D+(F>>1)}[b.charAt(1)],y:{T:q,B:q+E,M:q+(E>>1)}[b.charAt(0)]}})}var n;if("string"==typeof b||"offsetWidth"in b||"ownerSVGElement"in b){if(n=k.position(b,!0),/^(above|below)/.test(c[0])){var v=k.getBorderExtents(b),x=b.firstChild?k.getBorderExtents(b.firstChild):{t:0,l:0,b:0,r:0},s=k.getBorderExtents(a),p=a.firstChild?k.getBorderExtents(a.firstChild):{t:0,l:0,b:0,r:0};n.y+=Math.min(v.t+x.t,s.t+p.t);n.h-=
Math.min(v.t+x.t,s.t+p.t)+Math.min(v.b+x.b,s.b+p.b)}}else n=b;if(b.parentNode){v="absolute"==h.getComputedStyle(b).position;for(b=b.parentNode;b&&1==b.nodeType&&"BODY"!=b.nodeName;){x=k.position(b,!0);s=h.getComputedStyle(b);/relative|absolute/.test(s.position)&&(v=!1);if(!v&&/hidden|auto|scroll/.test(s.overflow)){var p=Math.min(n.y+n.h,x.y+x.h),w=Math.min(n.x+n.w,x.x+x.w);n.x=Math.max(n.x,x.x);n.y=Math.max(n.y,x.y);n.h=p-n.y;n.w=w-n.x}"absolute"==s.position&&(v=!0);b=b.parentNode}}var D=n.x,q=n.y,
F="w"in n?n.w:n.w=n.width,E="h"in n?n.h:(l.deprecated("place.around: dijit/place.__Rectangle: { x:"+D+", y:"+q+", height:"+n.height+", width:"+F+" } has been deprecated.  Please use { x:"+D+", y:"+q+", h:"+n.height+", w:"+F+" }","","2.0"),n.h=n.height),y=[];m.forEach(c,function(b){var a=e;switch(b){case "above-centered":r("TM","BM");break;case "below-centered":r("BM","TM");break;case "after-centered":a=!a;case "before-centered":r(a?"ML":"MR",a?"MR":"ML");break;case "after":a=!a;case "before":r(a?
"TL":"TR",a?"TR":"TL");r(a?"BL":"BR",a?"BR":"BL");break;case "below-alt":a=!a;case "below":r(a?"BL":"BR",a?"TL":"TR");r(a?"BR":"BL",a?"TR":"TL");break;case "above-alt":a=!a;case "above":r(a?"TL":"TR",a?"BL":"BR");r(a?"TR":"TL",a?"BR":"BL");break;default:r(b.aroundCorner,b.corner)}});a=f(a,y,d,{w:F,h:E});a.aroundNodePos=n;return a}}})},"dojo/promise/all":function(){define(["../_base/array","../Deferred","../when"],function(m,k,h){var l=m.some;return function(e){var a,d;e instanceof Array?d=e:e&&"object"===
typeof e&&(a=e);var f,c=[];if(a){d=[];for(var g in a)Object.hasOwnProperty.call(a,g)&&(c.push(g),d.push(a[g]));f={}}else d&&(f=[]);if(!d||!d.length)return(new k).resolve(f);var b=new k;b.promise.always(function(){f=c=null});var t=d.length;l(d,function(g,e){a||c.push(e);h(g,function(a){b.isFulfilled()||(f[c[e]]=a,0===--t&&b.resolve(f))},b.reject);return b.isFulfilled()});return b.promise}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),
function(m,k,h,l,e,a,d){k.add("rtl-adjust-position-for-verticalScrollBar",function(a,g){var b=h.body(g),f=d.create("div",{style:{overflow:"scroll",overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},b,"last"),k=d.create("div",{style:{overflow:"hidden",direction:"ltr"}},f,"last"),l=0!=e.position(k).x;f.removeChild(k);b.removeChild(f);return l});k.add("position-fixed-support",function(a,g){var b=h.body(g),f=d.create("span",{style:{visibility:"hidden",
position:"fixed",left:"1px",top:"1px"}},b,"last"),k=d.create("span",{style:{position:"fixed",left:"0",top:"0"}},f,"last"),l=e.position(k).x!=e.position(f).x;f.removeChild(k);b.removeChild(f);return l});var f={getBox:function(a){a=a||h.doc;var g="BackCompat"==a.compatMode?h.body(a):a.documentElement,b=e.docScroll(a);if(k("touch")){var d=f.get(a);a=d.innerWidth||g.clientWidth;g=d.innerHeight||g.clientHeight}else a=g.clientWidth,g=g.clientHeight;return{l:b.x,t:b.y,w:a,h:g}},get:function(a){if(k("ie")&&
f!==document.parentWindow){a.parentWindow.execScript("document._parentWindow \x3d window;","Javascript");var g=a._parentWindow;a._parentWindow=null;return g}return a.parentWindow||a.defaultView},scrollIntoView:function(c,g){try{c=l.byId(c);var b=c.ownerDocument||h.doc,d=h.body(b),f=b.documentElement||d.parentNode,m=k("ie"),r=k("webkit");if(!(c==d||c==f))if(!k("mozilla")&&(!m&&!r&&!k("opera")&&!k("trident"))&&"scrollIntoView"in c)c.scrollIntoView(!1);else{var n="BackCompat"==b.compatMode,v=Math.min(d.clientWidth||
f.clientWidth,f.clientWidth||d.clientWidth),x=Math.min(d.clientHeight||f.clientHeight,f.clientHeight||d.clientHeight),b=r||n?d:f,s=g||e.position(c),p=c.parentNode,r=function(b){return 6>=m||7==m&&n?!1:k("position-fixed-support")&&"fixed"==a.get(b,"position").toLowerCase()},w=this,D=function(a,b,c){"BODY"==a.tagName||"HTML"==a.tagName?w.get(a.ownerDocument).scrollBy(b,c):(b&&(a.scrollLeft+=b),c&&(a.scrollTop+=c))};if(!r(c))for(;p;){p==d&&(p=b);var q=e.position(p),F=r(p),E="rtl"==a.getComputedStyle(p).direction.toLowerCase();
if(p==b){q.w=v;q.h=x;if(b==f&&(m||k("trident"))&&E)q.x+=b.offsetWidth-q.w;if(0>q.x||!m||9<=m||k("trident"))q.x=0;if(0>q.y||!m||9<=m||k("trident"))q.y=0}else{var y=e.getPadBorderExtents(p);q.w-=y.w;q.h-=y.h;q.x+=y.l;q.y+=y.t;var H=p.clientWidth,I=q.w-H;0<H&&0<I&&(E&&k("rtl-adjust-position-for-verticalScrollBar")&&(q.x+=I),q.w=H);H=p.clientHeight;I=q.h-H;0<H&&0<I&&(q.h=H)}F&&(0>q.y&&(q.h+=q.y,q.y=0),0>q.x&&(q.w+=q.x,q.x=0),q.y+q.h>x&&(q.h=x-q.y),q.x+q.w>v&&(q.w=v-q.x));var M=s.x-q.x,O=s.y-q.y,S=M+s.w-
q.w,T=O+s.h-q.h,J,z;if(0<S*M&&(p.scrollLeft||p==b||p.scrollWidth>p.offsetHeight)){J=Math[0>M?"max":"min"](M,S);if(E&&(8==m&&!n||9<=m||k("trident")))J=-J;z=p.scrollLeft;D(p,J,0);J=p.scrollLeft-z;s.x-=J}if(0<T*O&&(p.scrollTop||p==b||p.scrollHeight>p.offsetHeight))J=Math.ceil(Math[0>O?"max":"min"](O,T)),z=p.scrollTop,D(p,0,J),J=p.scrollTop-z,s.y-=J;p=p!=b&&!F&&p.parentNode}}}catch(A){console.error("scrollIntoView: "+A),c.scrollIntoView(!1)}}};m.setObject("dojo.window",f);return f})},"dijit/form/_FormValueWidget":function(){define(["dojo/_base/declare",
"dojo/sniff","./_FormWidget","./_FormValueMixin"],function(m,k,h,l){return m("dijit.form._FormValueWidget",[h,l],{_layoutHackIE7:function(){if(7==k("ie"))for(var e=this.domNode,a=e.parentNode,d=e.firstChild||e,f=d.style.filter,c=this;a&&0==a.clientHeight;)(function(){var g=c.connect(a,"onscroll",function(){c.disconnect(g);d.style.filter=(new Date).getMilliseconds();c.defer(function(){d.style.filter=f})})})(),a=a.parentNode}})})},"dijit/_OnDijitClickMixin":function(){define("dojo/on dojo/_base/array dojo/keys dojo/_base/declare dojo/has ./a11yclick".split(" "),
function(m,k,h,l,e,a){m=l("dijit._OnDijitClickMixin",null,{connect:function(d,f,c){return this.inherited(arguments,[d,"ondijitclick"==f?a:f,c])}});m.a11yclick=a;return m})},"dijit/a11yclick":function(){define(["dojo/keys","dojo/mouse","dojo/on","dojo/touch"],function(m,k,h,l){function e(a){if((a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&!/input|button|textarea/i.test(a.target.nodeName))for(a=a.target;a;a=a.parentNode)if(a.dojoClick)return!0}var a;h(document,"keydown",function(d){e(d)?(a=d.target,d.preventDefault()):
a=null});h(document,"keyup",function(d){e(d)&&d.target==a&&(a=null,h.emit(d.target,"click",{cancelable:!0,bubbles:!0,ctrlKey:d.ctrlKey,shiftKey:d.shiftKey,metaKey:d.metaKey,altKey:d.altKey,_origType:d.type}))});var d=function(a,c){a.dojoClick=!0;return h(a,"click",c)};d.click=d;d.press=function(a,c){var g=h(a,l.press,function(a){("mousedown"!=a.type||k.isLeft(a))&&c(a)}),b=h(a,"keydown",function(a){(a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&c(a)});return{remove:function(){g.remove();b.remove()}}};
d.release=function(a,c){var g=h(a,l.release,function(a){("mouseup"!=a.type||k.isLeft(a))&&c(a)}),b=h(a,"keyup",function(a){(a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&c(a)});return{remove:function(){g.remove();b.remove()}}};d.move=l.move;return d})},"dijit/hccss":function(){define(["dojo/dom-class","dojo/hccss","dojo/domReady","dojo/_base/window"],function(m,k,h,l){h(function(){k("highcontrast")&&m.add(l.body(),"dijit_a11y")});return k})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),
function(m,k,h,l,e,a,d,f){var c=k("dijit._TemplatedMixin",f,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(a){var b=this.declaredClass,c=this;return d.substitute(a,this,function(a,g){"!"==g.charAt(0)&&(a=l.getObject(g.substr(1),!1,c));if("undefined"==typeof a)throw Error(b+" template:"+g);return null==a?"":"!"==g.charAt(0)?a:this._escapeValue(""+a)},this)},_escapeValue:function(a){return a.replace(/["'<>&]/g,function(a){return{"\x26":"\x26amp;",
"\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[a]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=m(this.templatePath,{sanitize:!0}));var a=c.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),b;if(l.isString(a)){if(b=h.toDom(this._stringRepl(a),this.ownerDocument),1!=b.nodeType)throw Error("Invalid template: "+a);}else b=a.cloneNode(!0);this.domNode=b}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);
this._rendered=!0},_fillContent:function(a){var b=this.containerNode;if(a&&b)for(;a.hasChildNodes();)b.appendChild(a.firstChild)}});c._templateCache={};c.getCachedTemplate=function(a,b,e){var f=c._templateCache,k=a,l=f[k];if(l){try{if(!l.ownerDocument||l.ownerDocument==(e||document))return l}catch(m){}h.destroy(l)}a=d.trim(a);if(b||a.match(/\$\{([^\}]+)\}/g))return f[k]=a;b=h.toDom(a,e);if(1!=b.nodeType)throw Error("Invalid template: "+a);return f[k]=b};a("ie")&&e(window,"unload",function(){var a=
c._templateCache,b;for(b in a){var d=a[b];"object"==typeof d&&h.destroy(d);delete a[b]}});return c})},"dijit/selection":function(){define("dojo/_base/array dojo/dom dojo/_base/lang dojo/sniff dojo/_base/window dijit/focus".split(" "),function(m,k,h,l,e,a){var d=function(c){var g=c.document;this.getType=function(){if(g.getSelection){var a="text",d;try{d=c.getSelection()}catch(e){}d&&1==d.rangeCount&&(d=d.getRangeAt(0),d.startContainer==d.endContainer&&(1==d.endOffset-d.startOffset&&3!=d.startContainer.nodeType)&&
(a="control"));return a}return g.selection.type.toLowerCase()};this.getSelectedText=function(){if(g.getSelection){var a=c.getSelection();return a?a.toString():""}return"control"==this.getType()?null:g.selection.createRange().text};this.getSelectedHtml=function(){if(g.getSelection){var a=c.getSelection();if(a&&a.rangeCount){var d,e="";for(d=0;d<a.rangeCount;d++){var f=a.getRangeAt(d).cloneContents(),h=g.createElement("div");h.appendChild(f);e+=h.innerHTML}return e}return null}return"control"==this.getType()?
null:g.selection.createRange().htmlText};this.getSelectedElement=function(){if("control"==this.getType()){if(g.getSelection){var a=c.getSelection();return a.anchorNode.childNodes[a.anchorOffset]}if((a=g.selection.createRange())&&a.item)return g.selection.createRange().item(0)}return null};this.getParentElement=function(){if("control"==this.getType()){var a=this.getSelectedElement();if(a)return a.parentNode}else if(g.getSelection){if(a=g.getSelection()){for(a=a.anchorNode;a&&1!=a.nodeType;)a=a.parentNode;
return a}}else return a=g.selection.createRange(),a.collapse(!0),a.parentElement();return null};this.hasAncestorElement=function(a){return null!=this.getAncestorElement.apply(this,arguments)};this.getAncestorElement=function(a){var c=this.getSelectedElement()||this.getParentElement();return this.getParentOfType(c,arguments)};this.isTag=function(a,c){if(a&&a.tagName)for(var d=a.tagName.toLowerCase(),g=0;g<c.length;g++){var e=String(c[g]).toLowerCase();if(d==e)return e}return""};this.getParentOfType=
function(a,c){for(;a;){if(this.isTag(a,c).length)return a;a=a.parentNode}return null};this.collapse=function(a){if(g.getSelection){var d=c.getSelection();d.removeAllRanges?a?d.collapseToStart():d.collapseToEnd():d.collapse(a)}else d=g.selection.createRange(),d.collapse(a),d.select()};this.remove=function(){var a=g.selection;g.getSelection?(a=c.getSelection(),a.deleteFromDocument()):"none"!=a.type.toLowerCase()&&a.clear();return a};this.selectElementChildren=function(a,d){var e;a=k.byId(a);if(g.getSelection){var f=
c.getSelection();l("opera")?(e=f.rangeCount?f.getRangeAt(0):g.createRange(),e.setStart(a,0),e.setEnd(a,3==a.nodeType?a.length:a.childNodes.length),f.addRange(e)):f.selectAllChildren(a)}else if(e=a.ownerDocument.body.createTextRange(),e.moveToElementText(a),!d)try{e.select()}catch(h){}};this.selectElement=function(a,c){var d;a=k.byId(a);if(g.getSelection){var f=g.getSelection();d=g.createRange();f.removeAllRanges&&(l("opera")&&f.getRangeAt(0)&&(d=f.getRangeAt(0)),d.selectNode(a),f.removeAllRanges(),
f.addRange(d))}else try{f=a.tagName?a.tagName.toLowerCase():"",d="img"===f||"table"===f?e.body(g).createControlRange():e.body(g).createRange(),d.addElement(a),c||d.select()}catch(h){this.selectElementChildren(a,c)}};this.inSelection=function(a){if(a){var d,e;if(g.getSelection){var f=c.getSelection();f&&0<f.rangeCount&&(e=f.getRangeAt(0));if(e&&e.compareBoundaryPoints&&g.createRange)try{if(d=g.createRange(),d.setStart(a,0),1===e.compareBoundaryPoints(e.START_TO_END,d))return!0}catch(h){}}else{e=g.selection.createRange();
try{d=a.ownerDocument.body.createTextRange(),d.moveToElementText(a)}catch(k){}if(e&&d&&1===e.compareEndPoints("EndToStart",d))return!0}}return!1};this.getBookmark=function(){var b,d,e=g.selection,f=a.curNode;if(g.getSelection){if(e=c.getSelection())if(e.isCollapsed){if(b=f?f.tagName:"")if(b=b.toLowerCase(),"textarea"==b||"input"==b&&(!f.type||"text"==f.type.toLowerCase()))return e={start:f.selectionStart,end:f.selectionEnd,node:f,pRange:!0},{isCollapsed:e.end<=e.start,mark:e};b={isCollapsed:!0};e.rangeCount&&
(b.mark=e.getRangeAt(0).cloneRange())}else d=e.getRangeAt(0),b={isCollapsed:!1,mark:d.cloneRange()}}else if(e){b=f?f.tagName:"";b=b.toLowerCase();if(f&&b&&("button"==b||"textarea"==b||"input"==b)){if(e.type&&"none"==e.type.toLowerCase())return{isCollapsed:!0,mark:null};d=e.createRange();return{isCollapsed:d.text&&d.text.length?!1:!0,mark:{range:d,pRange:!0}}}b={};try{d=e.createRange(),b.isCollapsed=!("Text"==e.type?d.htmlText.length:d.length)}catch(h){return b.isCollapsed=!0,b}if("CONTROL"==e.type.toUpperCase())if(d.length){b.mark=
[];e=0;for(f=d.length;e<f;)b.mark.push(d.item(e++))}else b.isCollapsed=!0,b.mark=null;else b.mark=d.getBookmark()}else console.warn("No idea how to store the current selection for this browser!");return b};this.moveToBookmark=function(a){if(a=a.mark)if(g.getSelection){var d=c.getSelection();d&&d.removeAllRanges?a.pRange?(d=a.node,d.selectionStart=a.start,d.selectionEnd=a.end):(d.removeAllRanges(),d.addRange(a)):console.warn("No idea how to restore selection for this browser!")}else if(g.selection&&
a){var e;a.pRange?e=a.range:h.isArray(a)?(e=g.body.createControlRange(),m.forEach(a,function(a){e.addElement(a)})):(e=g.body.createTextRange(),e.moveToBookmark(a));e.select()}};this.isCollapsed=function(){return this.getBookmark().isCollapsed}},f=new d(window);f.SelectionManager=d;return f})},"dijit/form/_FormWidget":function(){define("dojo/_base/declare dojo/sniff dojo/_base/kernel dojo/ready ../_Widget ../_CssStateMixin ../_TemplatedMixin ./_FormWidgetMixin".split(" "),function(m,k,h,l,e,a,d,f){k("dijit-legacy-requires")&&
l(0,function(){require(["dijit/form/_FormValueWidget"])});return m("dijit.form._FormWidget",[e,d,a,f],{setDisabled:function(a){h.deprecated("setDisabled("+a+") is deprecated. Use set('disabled',"+a+") instead.","","2.0");this.set("disabled",a)},setValue:function(a){h.deprecated("dijit.form._FormWidget:setValue("+a+") is deprecated.  Use set('value',"+a+") instead.","","2.0");this.set("value",a)},getValue:function(){h.deprecated(this.declaredClass+"::getValue() is deprecated. Use get('value') instead.",
"","2.0");return this.get("value")},postMixInProperties:function(){this.nameAttrSetting=this.name&&!k("msapp")?'name\x3d"'+this.name.replace(/"/g,"\x26quot;")+'"':"";this.inherited(arguments)}})})},"dijit/_base/focus":function(){define("dojo/_base/array dojo/dom dojo/_base/lang dojo/topic dojo/_base/window ../focus ../selection ../main".split(" "),function(m,k,h,l,e,a,d,f){a.focus=function(c){if(c){var d="node"in c?c.node:c,b=c.bookmark;c=c.openedForWindow;var h=b?b.isCollapsed:!1;if(d){var k="iframe"==
d.tagName.toLowerCase()?d.contentWindow:d;if(k&&k.focus)try{k.focus()}catch(l){}a._onFocusNode(d)}if(b&&e.withGlobal(c||e.global,f.isCollapsed)&&!h){c&&c.focus();try{e.withGlobal(c||e.global,f.moveToBookmark,null,[b])}catch(m){}}}};a.watch("curNode",function(a,d,b){f._curFocus=b;f._prevFocus=d;b&&l.publish("focusNode",b)});a.watch("activeStack",function(a,d,b){f._activeStack=b});a.on("widget-blur",function(a,d){l.publish("widgetBlur",a,d)});a.on("widget-focus",function(a,d){l.publish("widgetFocus",
a,d)});h.mixin(f,{_curFocus:null,_prevFocus:null,isCollapsed:function(){return f.getBookmark().isCollapsed},getBookmark:function(){return(e.global==window?d:new d.SelectionManager(e.global)).getBookmark()},moveToBookmark:function(a){return(e.global==window?d:new d.SelectionManager(e.global)).moveToBookmark(a)},getFocus:function(c,d){var b=!a.curNode||c&&k.isDescendant(a.curNode,c.domNode)?f._prevFocus:a.curNode;return{node:b,bookmark:b&&b==a.curNode&&e.withGlobal(d||e.global,f.getBookmark),openedForWindow:d}},
_activeStack:[],registerIframe:function(c){return a.registerIframe(c)},unregisterIframe:function(a){a&&a.remove()},registerWin:function(c,d){return a.registerWin(c,d)},unregisterWin:function(a){a&&a.remove()}});return f})},"dojo/parser":function(){define("require ./_base/kernel ./_base/lang ./_base/array ./_base/config ./dom ./_base/window ./_base/url ./aspect ./promise/all ./date/stamp ./Deferred ./has ./query ./on ./ready".split(" "),function(m,k,h,l,e,a,d,f,c,g,b,t,B,u,r,n){function v(a){return eval("("+
a+")")}function x(a){var b=a._nameCaseMap,c=a.prototype;if(!b||b._extendCnt<p){var b=a._nameCaseMap={},d;for(d in c)"_"!==d.charAt(0)&&(b[d.toLowerCase()]=d);b._extendCnt=p}return b}function s(a,b){var c=a.join();if(!w[c]){for(var d=[],e=0,g=a.length;e<g;e++){var f=a[e];d[d.length]=w[f]=w[f]||h.getObject(f)||~f.indexOf("/")&&(b?b(f):m(f))}e=d.shift();w[c]=d.length?e.createSubclass?e.createSubclass(d):e.extend.apply(e,d):e}return w[c]}new Date("X");var p=0;c.after(h,"extend",function(){p++},!0);var w=
{},D={_clearCache:function(){p++;w={}},_functionFromScript:function(a,b){var c="",d="",e=a.getAttribute(b+"args")||a.getAttribute("args"),f=a.getAttribute("with"),e=(e||"").split(/\s*,\s*/);f&&f.length&&l.forEach(f.split(/\s*,\s*/),function(a){c+="with("+a+"){";d+="}"});return new Function(e,c+a.innerHTML+d)},instantiate:function(a,b,c){b=b||{};c=c||{};var d=(c.scope||k._scopeName)+"Type",e="data-"+(c.scope||k._scopeName)+"-",f=e+"type",g=e+"mixins",h=[];l.forEach(a,function(a){var c=d in b?b[d]:
a.getAttribute(f)||a.getAttribute(d);if(c){var e=a.getAttribute(g),c=e?[c].concat(e.split(/\s*,\s*/)):[c];h.push({node:a,types:c})}});return this._instantiate(h,b,c)},_instantiate:function(a,b,c,d){function e(a){!b._started&&!c.noStart&&l.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a}a=l.map(a,function(a){var d=a.ctor||s(a.types,c.contextRequire);if(!d)throw Error("Unable to resolve constructor for: '"+a.types.join()+"'");return this.construct(d,a.node,b,
c,a.scripts,a.inherited)},this);return d?g(a).then(e):e(a)},construct:function(a,d,e,g,m,n){function D(a){w&&h.setObject(w,a);for(A=0;A<L.length;A++)c[L[A].advice||"after"](a,L[A].method,h.hitch(a,L[A].func),!0);for(A=0;A<R.length;A++)R[A].call(a);for(A=0;A<P.length;A++)a.watch(P[A].prop,P[A].func);for(A=0;A<Q.length;A++)r(a,Q[A].event,Q[A].func);return a}var p=a&&a.prototype;g=g||{};var s={};g.defaults&&h.mixin(s,g.defaults);n&&h.mixin(s,n);var t;B("dom-attributes-explicit")?t=d.attributes:B("dom-attributes-specified-flag")?
t=l.filter(d.attributes,function(a){return a.specified}):(n=(/^input$|^img$/i.test(d.nodeName)?d:d.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),t=l.map(n.split(/\s+/),function(a){var b=a.toLowerCase();return{name:a,value:"LI"==d.nodeName&&"value"==a||"enctype"==b?d.getAttribute(b):d.getAttributeNode(b).value}}));var J=g.scope||k._scopeName;n="data-"+J+"-";var z={};"dojo"!==J&&(z[n+"props"]="data-dojo-props",z[n+"type"]=
"data-dojo-type",z[n+"mixins"]="data-dojo-mixins",z[J+"type"]="dojoType",z[n+"id"]="data-dojo-id");for(var A=0,C,J=[],w,N;C=t[A++];){var G=C.name,K=G.toLowerCase();C=C.value;switch(z[K]||K){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":N=C;break;case "data-dojo-id":case "jsid":w=C;break;case "data-dojo-attach-point":case "dojoattachpoint":s.dojoAttachPoint=C;break;case "data-dojo-attach-event":case "dojoattachevent":s.dojoAttachEvent=C;break;case "class":s["class"]=
d.className;break;case "style":s.style=d.style&&d.style.cssText;break;default:if(G in p||(G=x(a)[K]||G),G in p)switch(typeof p[G]){case "string":s[G]=C;break;case "number":s[G]=C.length?Number(C):NaN;break;case "boolean":s[G]="false"!=C.toLowerCase();break;case "function":""===C||-1!=C.search(/[^\w\.]+/i)?s[G]=new Function(C):s[G]=h.getObject(C,!1)||new Function(C);J.push(G);break;default:K=p[G],s[G]=K&&"length"in K?C?C.split(/\s*,\s*/):[]:K instanceof Date?""==C?new Date(""):"now"==C?new Date:b.fromISOString(C):
K instanceof f?k.baseUrl+C:v(C)}else s[G]=C}}for(t=0;t<J.length;t++)z=J[t].toLowerCase(),d.removeAttribute(z),d[z]=null;if(N)try{N=v.call(g.propsThis,"{"+N+"}"),h.mixin(s,N)}catch(U){throw Error(U.toString()+" in data-dojo-props\x3d'"+N+"'");}h.mixin(s,e);m||(m=a&&(a._noScript||p._noScript)?[]:u("\x3e script[type^\x3d'dojo/']",d));var L=[],R=[],P=[],Q=[];if(m)for(A=0;A<m.length;A++)z=m[A],d.removeChild(z),e=z.getAttribute(n+"event")||z.getAttribute("event"),g=z.getAttribute(n+"prop"),N=z.getAttribute(n+
"method"),J=z.getAttribute(n+"advice"),t=z.getAttribute("type"),z=this._functionFromScript(z,n),e?"dojo/connect"==t?L.push({method:e,func:z}):"dojo/on"==t?Q.push({event:e,func:z}):s[e]=z:"dojo/aspect"==t?L.push({method:N,advice:J,func:z}):"dojo/watch"==t?P.push({prop:g,func:z}):R.push(z);a=(m=a.markupFactory||p.markupFactory)?m(s,d,a):new a(s,d);return a.then?a.then(D):D(a)},scan:function(a,b){function c(a){if(!a.inherited){a.inherited={};var b=a.node,d=c(a.parent),b={dir:b.getAttribute("dir")||d.dir,
lang:b.getAttribute("lang")||d.lang,textDir:b.getAttribute(D)||d.textDir},e;for(e in b)b[e]&&(a.inherited[e]=b[e])}return a.inherited}var d=[],e=[],g={},f=(b.scope||k._scopeName)+"Type",h="data-"+(b.scope||k._scopeName)+"-",n=h+"type",D=h+"textdir",h=h+"mixins",p=a.firstChild,r=b.inherited;if(!r){var v=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&v(a.parentNode,b)},r={dir:v(a,"dir"),lang:v(a,"lang"),textDir:v(a,D)},u;for(u in r)r[u]||delete r[u]}for(var r={inherited:r},x,
w;;)if(p)if(1!=p.nodeType)p=p.nextSibling;else if(x&&"script"==p.nodeName.toLowerCase())(G=p.getAttribute("type"))&&/^dojo\/\w/i.test(G)&&x.push(p),p=p.nextSibling;else if(w)p=p.nextSibling;else{var G=p.getAttribute(n)||p.getAttribute(f);u=p.firstChild;if(!G&&(!u||3==u.nodeType&&!u.nextSibling))p=p.nextSibling;else{w=null;if(G){var K=p.getAttribute(h);x=K?[G].concat(K.split(/\s*,\s*/)):[G];try{w=s(x,b.contextRequire)}catch(U){}w||l.forEach(x,function(a){~a.indexOf("/")&&!g[a]&&(g[a]=!0,e[e.length]=
a)});K=w&&!w.prototype._noScript?[]:null;r={types:x,ctor:w,parent:r,node:p,scripts:K};r.inherited=c(r);d.push(r)}else r={node:p,scripts:x,parent:r};x=K;w=p.stopParser||w&&w.prototype.stopParser&&!b.template;p=u}}else{if(!r||!r.node)break;p=r.node.nextSibling;w=!1;r=r.parent;x=r.scripts}var L=new t;e.length?(B("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+e.join(", ")),(b.contextRequire||m)(e,function(){L.resolve(l.filter(d,function(a){if(!a.ctor)try{a.ctor=s(a.types,
b.contextRequire)}catch(c){}for(var d=a.parent;d&&!d.types;)d=d.parent;var e=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(e&&e.stopParser&&!b.template);a.instantiate=!d||d.instantiate&&d.instantiateChildren;return a.instantiate}))})):L.resolve(d);return L.promise},_require:function(a,b){var c=v("{"+a.innerHTML+"}"),d=[],e=[],g=new t,f=b&&b.contextRequire||m,k;for(k in c)d.push(k),e.push(c[k]);f(e,function(){for(var a=0;a<d.length;a++)h.setObject(d[a],arguments[a]);g.resolve(arguments)});return g.promise},
_scanAmd:function(a,b){var c=new t,d=c.promise;c.resolve(!0);var e=this;u("script[type\x3d'dojo/require']",a).forEach(function(a){d=d.then(function(){return e._require(a,b)});a.parentNode.removeChild(a)});return d},parse:function(b,c){var e;!c&&b&&b.rootNode?(c=b,e=c.rootNode):b&&h.isObject(b)&&!("nodeType"in b)?c=b:e=b;e=e?a.byId(e):d.body();c=c||{};var g=c.template?{template:!0}:{},f=[],k=this,l=this._scanAmd(e,c).then(function(){return k.scan(e,c)}).then(function(a){return k._instantiate(a,g,c,
!0)}).then(function(a){return f=f.concat(a)}).otherwise(function(a){console.error("dojo/parser::parse() error",a);throw a;});h.mixin(f,l);return f}};k.parser=D;e.parseOnLoad&&n(100,D,"parse");return D})},"dijit/layout/_LayoutWidget":function(){define("dojo/_base/lang ../_Widget ../_Container ../_Contained ../Viewport dojo/_base/declare dojo/dom-class dojo/dom-geometry dojo/dom-style".split(" "),function(m,k,h,l,e,a,d,f,c){return a("dijit.layout._LayoutWidget",[k,h,l],{baseClass:"dijitLayoutContainer",
isLayoutContainer:!0,_setTitleAttr:null,buildRendering:function(){this.inherited(arguments);d.add(this.domNode,"dijitContainer")},startup:function(){if(!this._started){this.inherited(arguments);var a=this.getParent&&this.getParent();if(!a||!a.isLayoutContainer)this.resize(),this.own(e.on("resize",m.hitch(this,"resize")))}},resize:function(a,b){var d=this.domNode;a&&f.setMarginBox(d,a);var e=b||{};m.mixin(e,a||{});if(!("h"in e)||!("w"in e))e=m.mixin(f.getMarginBox(d),e);var h=c.getComputedStyle(d),
k=f.getMarginExtents(d,h),l=f.getBorderExtents(d,h),e=this._borderBox={w:e.w-(k.w+l.w),h:e.h-(k.h+l.h)},k=f.getPadExtents(d,h);this._contentBox={l:c.toPixelValue(d,h.paddingLeft),t:c.toPixelValue(d,h.paddingTop),w:e.w-k.w,h:e.h-k.h};this.layout()},layout:function(){},_setupChild:function(a){d.add(a.domNode,this.baseClass+"-child "+(a.baseClass?this.baseClass+"-"+a.baseClass:""))},addChild:function(a,b){this.inherited(arguments);this._started&&this._setupChild(a)},removeChild:function(a){d.remove(a.domNode,
this.baseClass+"-child"+(a.baseClass?" "+this.baseClass+"-"+a.baseClass:""));this.inherited(arguments)}})})},"dijit/_Widget":function(){define("dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/has dojo/_base/kernel dojo/_base/lang dojo/query dojo/ready ./registry ./_WidgetBase ./_OnDijitClickMixin ./_FocusMixin dojo/uacss ./hccss".split(" "),function(m,k,h,l,e,a,d,f,c,g,b,t,B){function u(){}function r(a){return function(b,c,e,f){return b&&"string"==typeof c&&b[c]==u?b.on(c.substring(2).toLowerCase(),
d.hitch(e,f)):a.apply(h,arguments)}}m.around(h,"connect",r);a.connect&&m.around(a,"connect",r);m=l("dijit._Widget",[b,t,B],{onClick:u,onDblClick:u,onKeyDown:u,onKeyPress:u,onKeyUp:u,onMouseDown:u,onMouseMove:u,onMouseOut:u,onMouseOver:u,onMouseLeave:u,onMouseEnter:u,onMouseUp:u,constructor:function(a){this._toConnect={};for(var b in a)this[b]===u&&(this._toConnect[b.replace(/^on/,"").toLowerCase()]=a[b],delete a[b])},postCreate:function(){this.inherited(arguments);for(var a in this._toConnect)this.on(a,
this._toConnect[a]);delete this._toConnect},on:function(a,b){return this[this._onMap(a)]===u?h.connect(this.domNode,a.toLowerCase(),this,b):this.inherited(arguments)},_setFocusedAttr:function(a){this._focused=a;this._set("focused",a)},setAttribute:function(b,c){a.deprecated(this.declaredClass+"::setAttribute(attr, value) is deprecated. Use set() instead.","","2.0");this.set(b,c)},attr:function(a,b){return 2<=arguments.length||"object"===typeof a?this.set.apply(this,arguments):this.get(a)},getDescendants:function(){a.deprecated(this.declaredClass+
"::getDescendants() is deprecated. Use getChildren() instead.","","2.0");return this.containerNode?f("[widgetId]",this.containerNode).map(g.byNode):[]},_onShow:function(){this.onShow()},onShow:function(){},onHide:function(){},onClose:function(){return!0}});e("dijit-legacy-requires")&&c(0,function(){require(["dijit/_base"])});return m})},"dijit/_FocusMixin":function(){define(["./focus","./_WidgetBase","dojo/_base/declare","dojo/_base/lang"],function(m,k,h,l){l.extend(k,{focused:!1,onFocus:function(){},
onBlur:function(){},_onFocus:function(){this.onFocus()},_onBlur:function(){this.onBlur()}});return h("dijit._FocusMixin",null,{_focusManager:m})})},"dijit/focus":function(){define("dojo/aspect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/Evented dojo/_base/lang dojo/on dojo/domReady dojo/sniff dojo/Stateful dojo/_base/window dojo/window ./a11y ./registry ./main".split(" "),function(m,k,h,l,e,a,d,f,c,g,b,t,B,u,r,n,v){var x,s,p=new (k([t,d],{curNode:null,activeStack:[],
constructor:function(){var b=f.hitch(this,function(a){h.isDescendant(this.curNode,a)&&this.set("curNode",null);h.isDescendant(this.prevNode,a)&&this.set("prevNode",null)});m.before(a,"empty",b);m.before(a,"destroy",b)},registerIframe:function(a){return this.registerWin(a.contentWindow,a)},registerWin:function(a,d){var e=this,f=a.document&&a.document.body;if(f){var g=b("pointer-events")?"pointerdown":b("MSPointer")?"MSPointerDown":b("touch-events")?"mousedown, touchstart":"mousedown",h=c(a.document,
g,function(a){if(!a||!(a.target&&null==a.target.parentNode))e._onTouchNode(d||a.target,"mouse")}),k=c(f,"focusin",function(a){if(a.target.tagName){var b=a.target.tagName.toLowerCase();"#document"==b||"body"==b||(r.isFocusable(a.target)?e._onFocusNode(d||a.target):e._onTouchNode(d||a.target))}}),l=c(f,"focusout",function(a){e._onBlurNode(d||a.target)});return{remove:function(){h.remove();k.remove();l.remove();f=h=k=l=null}}}},_onBlurNode:function(a){a=(new Date).getTime();a<x+100||(this._clearFocusTimer&&
clearTimeout(this._clearFocusTimer),this._clearFocusTimer=setTimeout(f.hitch(this,function(){this.set("prevNode",this.curNode);this.set("curNode",null)}),0),this._clearActiveWidgetsTimer&&clearTimeout(this._clearActiveWidgetsTimer),a<s+100||(this._clearActiveWidgetsTimer=setTimeout(f.hitch(this,function(){delete this._clearActiveWidgetsTimer;this._setStack([])}),0)))},_onTouchNode:function(a,b){s=(new Date).getTime();this._clearActiveWidgetsTimer&&(clearTimeout(this._clearActiveWidgetsTimer),delete this._clearActiveWidgetsTimer);
e.contains(a,"dijitPopup")&&(a=a.firstChild);var c=[];try{for(;a;){var d=l.get(a,"dijitPopupParent");if(d)a=n.byId(d).domNode;else if(a.tagName&&"body"==a.tagName.toLowerCase()){if(a===B.body())break;a=u.get(a.ownerDocument).frameElement}else{var f=a.getAttribute&&a.getAttribute("widgetId"),g=f&&n.byId(f);g&&!("mouse"==b&&g.get("disabled"))&&c.unshift(f);a=a.parentNode}}}catch(h){}this._setStack(c,b)},_onFocusNode:function(a){a&&9!=a.nodeType&&(x=(new Date).getTime(),this._clearFocusTimer&&(clearTimeout(this._clearFocusTimer),
delete this._clearFocusTimer),this._onTouchNode(a),a!=this.curNode&&(this.set("prevNode",this.curNode),this.set("curNode",a)))},_setStack:function(a,b){var c=this.activeStack,d=c.length-1,e=a.length-1;if(a[e]!=c[d]){this.set("activeStack",a);var f;for(f=d;0<=f&&c[f]!=a[f];f--)if(d=n.byId(c[f]))d._hasBeenBlurred=!0,d.set("focused",!1),d._focusManager==this&&d._onBlur(b),this.emit("widget-blur",d,b);for(f++;f<=e;f++)if(d=n.byId(a[f]))d.set("focused",!0),d._focusManager==this&&d._onFocus(b),this.emit("widget-focus",
d,b)}},focus:function(a){if(a)try{a.focus()}catch(b){}}}));g(function(){var a=p.registerWin(u.get(document));b("ie")&&c(window,"unload",function(){a&&(a.remove(),a=null)})});v.focus=function(a){p.focus(a)};for(var w in p)/^_/.test(w)||(v.focus[w]="function"==typeof p[w]?f.hitch(p,w):p[w]);p.watch(function(a,b,c){v.focus[a]=c});return p})},"dijit/_Contained":function(){define(["dojo/_base/declare","./registry"],function(m,k){return m("dijit._Contained",null,{_getSibling:function(h){var l=this.domNode;
do l=l[h+"Sibling"];while(l&&1!=l.nodeType);return l&&k.byNode(l)},getPreviousSibling:function(){return this._getSibling("previous")},getNextSibling:function(){return this._getSibling("next")},getIndexInParent:function(){var h=this.getParent();return!h||!h.getIndexOfChild?-1:h.getIndexOfChild(this)}})})},"dijit/_base/scroll":function(){define(["dojo/window","../main"],function(m,k){k.scrollIntoView=function(h,k){m.scrollIntoView(h,k)}})},"dijit/main":function(){define(["dojo/_base/kernel"],function(m){return m.dijit})},
"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(m,k,h){return h("dijit.Destroyable",null,{destroy:function(h){this._destroyed=!0},own:function(){var h=["destroyRecursive","destroy","remove"];m.forEach(arguments,function(e){function a(){f.remove();m.forEach(c,function(a){a.remove()})}var d,f=k.before(this,"destroy",function(a){e[d](a)}),c=[];e.then?(d="cancel",e.then(a,a)):m.forEach(h,function(f){"function"===typeof e[f]&&(d||(d=f),c.push(k.after(e,
f,a,!0)))})},this);return arguments}})})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(m){return m.cache})},"dijit/_base/window":function(){define(["dojo/window","../main"],function(m,k){k.getDocumentWindow=function(h){return m.get(h)}})},"dijit/_base/typematic":function(){define(["../typematic"],function(){})},"dijit/_base/popup":function(){define(["dojo/dom-class","dojo/_base/window","../popup","../BackgroundIframe"],function(m,k,h){var l=h._createWrapper;h._createWrapper=
function(a){a.declaredClass||(a={_popupWrapper:a.parentNode&&m.contains(a.parentNode,"dijitPopup")?a.parentNode:null,domNode:a,destroy:function(){},ownerDocument:a.ownerDocument,ownerDocumentBody:k.body(a.ownerDocument)});return l.call(this,a)};var e=h.open;h.open=function(a){if(a.orient&&"string"!=typeof a.orient&&!("length"in a.orient)){var d=[],f;for(f in a.orient)d.push({aroundCorner:f,corner:a.orient[f]});a.orient=d}return e.call(this,a)};return h})},"dijit/_Container":function(){define(["dojo/_base/array",
"dojo/_base/declare","dojo/dom-construct","dojo/_base/kernel"],function(m,k,h,l){return k("dijit._Container",null,{buildRendering:function(){this.inherited(arguments);this.containerNode||(this.containerNode=this.domNode)},addChild:function(e,a){var d=this.containerNode;if(0<a){for(d=d.firstChild;0<a;)1==d.nodeType&&a--,d=d.nextSibling;d?a="before":(d=this.containerNode,a="last")}h.place(e.domNode,d,a);this._started&&!e._started&&e.startup()},removeChild:function(e){"number"==typeof e&&(e=this.getChildren()[e]);
e&&(e=e.domNode)&&e.parentNode&&e.parentNode.removeChild(e)},hasChildren:function(){return 0<this.getChildren().length},_getSiblingOfChild:function(e,a){l.deprecated(this.declaredClass+"::_getSiblingOfChild() is deprecated. Use _KeyNavMixin::_getNext() instead.","","2.0");var d=this.getChildren(),f=m.indexOf(d,e);return d[f+a]},getIndexOfChild:function(e){return m.indexOf(this.getChildren(),e)}})})},"*noref":1}});
define("dijit/dijit","./main ./_base dojo/parser ./_Widget ./_TemplatedMixin ./_Container ./layout/_LayoutWidget ./form/_FormWidget ./form/_FormValueWidget".split(" "),function(m){return m});