define(
   ({
    _widgetLabel: "Vẽ",
    selectDrawMode: "Chọn chế độ vẽ",
    clear: "Xóa",
    point: "Điểm",
    line: "Đường",
    polyline: "Đa tuyến",
    freehandPolyline: "Đa tuyến vẽ tự do",
    triangle: "Hình tam giác",
    extent: "Đường bao",
    circle: "Hình tròn",
    ellipse: "Hình Elip",
    polygon: "Vùng",
    freehandPolygon: "Vùng vẽ bằng tay",
    text: "Văn bản",
    style: "Kiểu",
    alpha: "Độ trong suốt",
    width: "Chiều rộng",
    size: "Kích cỡ",
    color: "Màu sắc",
    markerColor: "Màu Điểm đánh dấu",
    outlineColor: "Màu Đường viền",
    lineColor: "Màu Đường",
    fillColor: "Tô Màu",
    showMeasurements: "Hiển thị Các phép đo",
    areaUnits: "Đơn vị Diện tích",
    distanceUnits: "Đơn vị Khoảng cách",
    kilometers: "Kilômét",
    miles: "Dặm",
    meters: "Mét",
    feet: "Feet",
    yards: "Thước",
    squareKilometers: "Kilômét vuông",
    squareMiles: "Dặm vuông",
    acres: "Mẫu Anh",
    hectares: "Hecta",
    squareMeters: "Mét vuông",
    squareFeet: "Feet vuông",
    squareYards: "Thước vuông",
    undo: "Hoàn tác",
    redo: "Làm lại"
  })
);