define(
   ({
    _widgetLabel: "Desenhar",
    selectDrawMode: "Selecionar modo de desenho",
    clear: "Limpar",
    point: "Ponto",
    line: "Linha",
    polyline: "Polilinha",
    freehandPolyline: "Polilinha À Mão Livre",
    triangle: "Triângulo",
    extent: "Envelope",
    circle: "Círculo",
    ellipse: "Elipse",
    polygon: "Polígono",
    freehandPolygon: "Polígono À Mão Livre",
    text: "Texto",
    style: "Estilo",
    alpha: "Transparência",
    width: "Largura",
    size: "Tamanho",
    color: "Cor",
    markerColor: "Cor do Marcador",
    outlineColor: "Cor de Contorno",
    lineColor: "Cor de Linha",
    fillColor: "Cor do Preenchimento",
    showMeasurements: "Exibir Medidas",
    areaUnits: "Unidades de Área",
    distanceUnits: "Unidades de Distância",
    kilometers: "Quilômetros",
    miles: "Milhas",
    meters: "Metros",
    feet: "Pés",
    yards: "Jardas",
    squareKilometers: "Quilómetros quadrados",
    squareMiles: "Milhas quadradas",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Metros quadrados",
    squareFeet: "Pés quadrados",
    squareYards: "Jardas quadradas",
    undo: "Desfazer",
    redo: "Refazer"
  })
);