define(
   ({
    _widgetLabel: "Table attributaire",
    ok: "OK",
    cancel: "Annuler",
    unsupportQueryWarning: "La couche doit prendre en charge l’opération de requête pour s’afficher dans le widget Table attributaire. Vérifiez que la fonction de requête dans le service est activée.",
    exportMessage: "Voulez-vous exporter les données au format CSV ?",
    exportFiles: "Exporter au format CSV",
    options: "Options",
    zoomto: "Zoom",
    highlight: "Mettre en surbrillance les graphiques",
    selectAll: "Sélectionner les enregistrements sur toutes les pages",
    selectPage: "Sélectionner les enregistrements sur la page en cours",
    clearSelection: "Effacer la sélection",
    filterByExtent: "Filtrer selon l’étendue de la carte",
    showSelectedRecords: "Afficher les enregistrements sélectionnés",
    showRelatedRecords: "Afficher les enregistrements associés",
    noRelatedRecords: "Aucun enregistrement associé",
    refresh: "Actualiser",
    features: "entités",
    selected: "sélectionné",
    transparent: "Mode transparent",
    indicate: "Localiser la sélection",
    columns: "Afficher/Masquer les colonnes",
    selectionSymbol: "Symbole de la sélection",
    closeMessage: "Masquer la table (redéveloppement à partir du bas)",
    dataNotAvailable: "Données non disponibles !<br>Cliquez sur le bouton [Actualiser] pour réessayer.",
    openTableTip: "Ouvrir la table attributaire",
    closeTableTip: "Masquer la table attributaire"
  })
);