// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"esri/tasks/ImageServiceIdentifyResult":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../geometry/jsonUtils ./FeatureSet".split(" "),function(k,e,h,p,d,c){k=k(null,{declaredClass:"esri.tasks.ImageServiceIdentifyResult",constructor:function(b){b.catalogItems&&(this.catalogItems=new c(b.catalogItems));b.location&&(this.location=d.fromJson(b.location));this.catalogItemVisibilities=b.catalogItemVisibilities;this.name=b.name;this.objectId=b.objectId;this.value=
b.value;this.properties=b.properties}});h("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyResult",k,p);return k})},"esri/layers/PixelBlock":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(k,e,h,p){k=k([],{declaredClass:"esri.layers.PixelBlock",planes:null,width:null,height:null,pixelType:null,pixels:[],statistics:[],constructor:function(d){if(d){if(!d.width||Math.floor(d.width)!==d.width)throw"PixelBlock: incorrect width";if(!d.height||Math.floor(d.height)!==
d.height)throw"PixelBlock: incorrect height";if(!d.pixels||!d.statistics)throw"PixelBlock: pixel data or statistics not present";this.width=d.width;this.height=d.height;this.pixels=d.pixels;this.pixelType=d.pixelType||null;this.statistics=d.statistics;this.mask=d.mask||null}},getPlaneCount:function(){return this.pixels.length!==this.statistics.length?console.error("Inconsistent pixel data and statistics"):this.statistics.length},addData:function(d){if(!d.pixels||!d.statistics)throw"Pixel data or statistics are not present";
if(d.pixels.length!==this.width*this.height)throw"Inconsistent pixel data size";this.statistics.push(d.statistics);this.pixels.push(d.pixels)},getAsRGBA:function(){var d=new ArrayBuffer(4*this.width*this.height);switch(this.pixelType){case "S8":case "S16":case "U16":case "S32":case "U32":case "F32":case "F64":this._fillFromNon8Bit(d);break;default:this._fillFrom8Bit(d)}return new Uint8ClampedArray(d)},getAsRGBAFloat:function(){var d=new Float32Array(4*this.width*this.height);this._fillFrom32Bit(d);
return d},clone:function(){var d=new this.constructor;d.width=this.width;d.height=this.height;d.pixelType=this.pixelType;this.mask&&(d.mask=new Uint8Array(this.mask));var c,b;if(this.pixels){d.pixels=[];b=this.pixels.length;for(c=0;c<b;c++)d.pixels[c]=new Float32Array(this.pixels[c])}if(this.statistics){d.statistics=[];b=this.statistics.length;for(c=0;c<b;c++)d.statistics[c]=e.clone(this.statistics[c])}return d},_fillFrom8Bit:function(d){var c=this.pixels,b=this.mask;if(!d||!c||!c.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");
var a,g,f;a=g=f=c[0];3<=c.length&&(g=c[1],f=c[2]);var c=new Uint32Array(d),e=this.width*this.height;if(a.length!==e)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");if(b&&b.length===e)for(d=0;d<e;d++)b[d]&&(c[d]=-16777216|f[d]<<16|g[d]<<8|a[d]);else for(d=0;d<e;d++)c[d]=-16777216|f[d]<<16|g[d]<<8|a[d]},_fillFromNon8Bit:function(d){var c=this.pixels,b=this.mask,a=this.statistics;if(!d||!c||!c.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");
var g=1,f=0;a&&0<a.length?(f=a[0].minValue,g=255/(a[0].maxValue-a[0].minValue)):(g=255,"S8"===this.pixelType?(f=-128,g=127):"U16"===this.pixelType?g=65535:"S16"===this.pixelType?(f=-32768,g=32767):"U32"===this.pixelType?g=4294967295:"S32"===this.pixelType?(f=-2147483648,g=2147483647):"F32"===this.pixelType?(f=-3.4*1E39,g=3.4*1E39):"F64"===this.pixelType&&(f=-Number.MAX_VALUE,g=Number.MAX_VALUE),g=255/(g-f));d=new Uint32Array(d);var a=this.width*this.height,e,h,k;e=c[0];if(e.length!==a)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");
if(3<=c.length)if(h=c[1],k=c[2],b&&b.length===a)for(c=0;c<a;c++)b[c]&&(d[c]=-16777216|(k[c]-f)*g<<16|(h[c]-f)*g<<8|(e[c]-f)*g);else for(c=0;c<a;c++)d[c]=-16777216|(k[c]-f)*g<<16|(h[c]-f)*g<<8|(e[c]-f)*g;else if(b&&b.length===a)for(c=0;c<a;c++)h=(e[c]-f)*g,b[c]&&(d[c]=-16777216|h<<16|h<<8|h);else for(c=0;c<a;c++)h=(e[c]-f)*g,d[c]=-16777216|h<<16|h<<8|h},_fillFrom32Bit:function(d){var c=this.pixels,b=this.mask;if(!d||!c||!c.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");
var a,g,f;a=g=f=c[0];3<=c.length&&(g=c[1],f=c[2]);var e=this.width*this.height;if(a.length!==e)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");var h=0;if(b&&b.length===e)for(c=0;c<e;c++)d[h++]=a[c],d[h++]=g[c],d[h++]=f[c],d[h++]=b[c];else for(c=0;c<e;c++)d[h++]=a[c],d[h++]=g[c],d[h++]=f[c],d[h++]=255}});h("extend-esri")&&e.setObject("layers.PixelBlock",k,p);return k})},"esri/layers/RasterFunction":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel",
"../lang"],function(k,e,h,p,d){var c=k(null,{declaredClass:"esri.layers.RasterFunction",functionName:null,arguments:null,functionArguments:null,variableName:null,outputPixelType:null,constructor:function(b){if(e.isObject(b)){var a=0;this.functionName=b.rasterFunction;this.functionArguments=e.clone(b.rasterFunctionArguments||b.arguments);e.mixin(this,b);if(b=this.functionArguments)if(b.Raster=this._toRasterFunction(b.Raster),b.Raster2=this._toRasterFunction(b.Raster2),b.DEM=this._toRasterFunction(b.DEM),
b.FillRaster=this._toRasterFunction(b.FillRaster),b.Rasters&&b.Rasters.length)for(a=0;a<b.Rasters.length;a++)b.Rasters[a]=this._toRasterFunction(b.Rasters[a])}},_toRasterFunction:function(b){return b&&(b.rasterFunction||b.functionName)?new c(b):b},_rfToJson:function(b){b&&"esri.layers.RasterFunction"===b.declaredClass&&(b=b.toJson());return b},toJson:function(){var b=e.clone(this.functionArguments||this.arguments);if(b&&(b.Raster=this._rfToJson(b.Raster),b.Raster2=this._rfToJson(b.Raster2),b.DEM=
this._rfToJson(b.DEM),b.FillRaster=this._rfToJson(b.FillRaster),b.Rasters&&b.Rasters.length)){var a,c=[];for(a=0;a<b.Rasters.length;a++)c.push(this._rfToJson(b.Rasters[a]));b.Rasters=c}return d.filter({rasterFunction:this.functionName,rasterFunctionArguments:b,variableName:this.variableName,outputPixelType:this.outputPixelType?this.outputPixelType:null},function(a){if(null!==a&&void 0!==a)return!0})}});h("extend-esri")&&e.setObject("layers.RasterFunction",c,p);return c})},"esri/layers/LercCodec":function(){define([],
function(){var k={defaultNoDataValue:-3.4027999387901484E38,decode:function(h,p){var d;p=p||{};var c=p.inputOffset||0,b=p.encodedMaskData||null===p.encodedMaskData,a={},g=new Uint8Array(h,c,10);a.fileIdentifierString=String.fromCharCode.apply(null,g);if("CntZImage"!=a.fileIdentifierString.trim())throw"Unexpected file identifier string: "+a.fileIdentifierString;var c=c+10,f=new DataView(h,c,24);a.fileVersion=f.getInt32(0,!0);a.imageType=f.getInt32(4,!0);a.height=f.getUint32(8,!0);a.width=f.getUint32(12,
!0);a.maxZError=f.getFloat64(16,!0);c+=24;if(!b)if(f=new DataView(h,c,16),a.mask={},a.mask.numBlocksY=f.getUint32(0,!0),a.mask.numBlocksX=f.getUint32(4,!0),a.mask.numBytes=f.getUint32(8,!0),a.mask.maxValue=f.getFloat32(12,!0),c+=16,0<a.mask.numBytes){var b=new Uint8Array(Math.ceil(a.width*a.height/8)),f=new DataView(h,c,a.mask.numBytes),g=f.getInt16(0,!0),t=2,B=0;do{if(0<g)for(;g--;)b[B++]=f.getUint8(t++);else for(var u=f.getUint8(t++),g=-g;g--;)b[B++]=u;g=f.getInt16(t,!0);t+=2}while(t<a.mask.numBytes);
if(-32768!==g||B<b.length)throw"Unexpected end of mask RLE encoding";a.mask.bitset=b;c+=a.mask.numBytes}else 0==(a.mask.numBytes|a.mask.numBlocksY|a.mask.maxValue)&&(b=new Uint8Array(Math.ceil(a.width*a.height/8)),a.mask.bitset=b);f=new DataView(h,c,16);a.pixels={};a.pixels.numBlocksY=f.getUint32(0,!0);a.pixels.numBlocksX=f.getUint32(4,!0);a.pixels.numBytes=f.getUint32(8,!0);a.pixels.maxValue=f.getFloat32(12,!0);c+=16;b=a.pixels.numBlocksX;g=a.pixels.numBlocksY;b+=0<a.width%b?1:0;g+=0<a.height%g?
1:0;a.pixels.blocks=Array(b*g);t=1E9;for(u=B=0;u<g;u++)for(var y=0;y<b;y++){var m=0,f=new DataView(h,c,Math.min(10,h.byteLength-c)),r={};a.pixels.blocks[B++]=r;var l=f.getUint8(0);m++;r.encoding=l&63;if(3<r.encoding)throw"Invalid block encoding ("+r.encoding+")";if(2===r.encoding)c++,t=Math.min(t,0);else{if(0!==l&&2!==l){l>>=6;r.offsetType=l;if(2===l)r.offset=f.getInt8(1),m++;else if(1===l)r.offset=f.getInt16(1,!0),m+=2;else if(0===l)r.offset=f.getFloat32(1,!0),m+=4;else throw"Invalid block offset type";
t=Math.min(r.offset,t);if(1===r.encoding)if(l=f.getUint8(m),m++,r.bitsPerPixel=l&63,l>>=6,r.numValidPixelsType=l,2===l)r.numValidPixels=f.getUint8(m),m++;else if(1===l)r.numValidPixels=f.getUint16(m,!0),m+=2;else if(0===l)r.numValidPixels=f.getUint32(m,!0),m+=4;else throw"Invalid valid pixel count type";}c+=m;if(3!=r.encoding)if(0===r.encoding){f=(a.pixels.numBytes-1)/4;if(f!==Math.floor(f))throw"uncompressed block has invalid length";m=new ArrayBuffer(4*f);l=new Uint8Array(m);l.set(new Uint8Array(h,
c,4*f));m=new Float32Array(m);for(l=0;l<m.length;l++)t=Math.min(t,m[l]);r.rawData=m;c+=4*f}else 1===r.encoding&&(f=Math.ceil(r.numValidPixels*r.bitsPerPixel/8),m=Math.ceil(f/4),m=new ArrayBuffer(4*m),l=new Uint8Array(m),l.set(new Uint8Array(h,c,f)),r.stuffedData=new Uint32Array(m),c+=f)}}a.pixels.minValue=t;a.eofOffset=c;var c=null!=p.noDataValue?p.noDataValue:k.defaultNoDataValue,g=p.encodedMaskData,m=p.returnMask,t=0,B=a.pixels.numBlocksX,u=a.pixels.numBlocksY,y=Math.floor(a.width/B),r=Math.floor(a.height/
u),f=2*a.maxZError,g=g||(a.mask?a.mask.bitset:null),n,b=new (p.pixelType||Float32Array)(a.width*a.height);m&&g&&(n=new Uint8Array(a.width*a.height));for(var m=new Float32Array(y*r),s,v,l=0;l<=u;l++){var z=l!==u?r:a.height%u;if(0!==z)for(var D=0;D<=B;D++){var C=D!==B?y:a.width%B;if(0!==C){var q=l*a.width*r+D*y,G=a.width-C,A=a.pixels.blocks[t],w,x;if(2>A.encoding){if(0===A.encoding)w=A.rawData;else{w=A.stuffedData;x=A.bitsPerPixel;s=A.numValidPixels;v=A.offset;var M=f,O=m,N=(1<<x)-1,J=0,I=void 0,F=
0,K=void 0,L=void 0,I=4*w.length-Math.ceil(x*s/8);w[w.length-1]<<=8*I;for(I=0;I<s;I++)0===F&&(L=w[J++],F=32),F>=x?(K=L>>>F-x&N,F-=x):(F=x-F,K=(L&N)<<F&N,L=w[J++],F=32-F,K+=L>>>F),O[I]=v+K*M;w=m}x=0}else d=2===A.encoding?0:A.offset;var H;if(g)for(v=0;v<z;v++){q&7&&(H=g[q>>3],H<<=q&7);for(s=0;s<C;s++)q&7||(H=g[q>>3]),H&128?(n&&(n[q]=1),b[q++]=2>A.encoding?w[x++]:d):(n&&(n[q]=0),b[q++]=c),H<<=1;q+=G}else if(2>A.encoding)for(v=0;v<z;v++){for(s=0;s<C;s++)b[q++]=w[x++];q+=G}else for(v=0;v<z;v++){for(s=
0;s<C;s++)b[q++]=d;q+=G}if(1===A.encoding&&x!==A.numValidPixels)throw"Block and Mask do not match";t++}}}d=n;n={width:a.width,height:a.height,pixelData:b,minValue:a.pixels.minValue,maxValue:a.pixels.maxValue,noDataValue:c};d&&(n.maskData=d);p.returnEncodedMask&&a.mask&&(n.encodedMaskData=a.mask.bitset?a.mask.bitset:null);if(p.returnFileInfo&&(n.fileInfo=e(a),p.computeUsedBitDepths)){d=n.fileInfo;H=a.pixels.numBlocksX*a.pixels.numBlocksY;w={};for(x=0;x<H;x++)c=a.pixels.blocks[x],0===c.encoding?w.float32=
!0:1===c.encoding?w[c.bitsPerPixel]=!0:w[0]=!0;a=Object.keys(w);d.bitDepths=a}return n}},e=function(e){return{fileIdentifierString:e.fileIdentifierString,fileVersion:e.fileVersion,imageType:e.imageType,height:e.height,width:e.width,maxZError:e.maxZError,eofOffset:e.eofOffset,mask:e.mask?{numBlocksX:e.mask.numBlocksX,numBlocksY:e.mask.numBlocksY,numBytes:e.mask.numBytes,maxValue:e.mask.maxValue}:null,pixels:{numBlocksX:e.pixels.numBlocksX,numBlocksY:e.pixels.numBlocksY,numBytes:e.pixels.numBytes,maxValue:e.pixels.maxValue,
minValue:e.pixels.minValue,noDataValue:this.noDataValue}}};return k})},"esri/layers/MosaicRule":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../lang ../geometry/Point".split(" "),function(k,e,h,p,d,c){var b=k(null,{declaredClass:"esri.layers.MosaicRule",method:null,where:null,sortField:null,sortValue:null,ascending:!1,lockRasterIds:null,viewpoint:null,objectIds:null,operation:null,multidimensionalDefinition:[],constructor:function(a){e.isObject(a)&&(e.mixin(this,a),a.mosaicMethod&&
(this.method=a.mosaicMethod),this.method&&"esri"!==this.method.toLowerCase().substring(0,4)&&(this.method=this._getMethodEnum(this.method)),a.mosaicOperation&&(this.operation=a.mosaicOperation),this.operation&&"MT_"!==this.operation.toUpperCase().substring(0,3)&&(this.operation=this._getOperatorEnum(this.operation)),a.fids&&(this.objectIds=a.fids),a.viewpoint&&(this.viewpoint=new c(a.viewpoint)))},toJson:function(){var a=null,b=this.multidimensionalDefinition?this.multidimensionalDefinition.length:
0;if(b)for(var a=[],c=0;c<b;c++)a.push("esri.layers.DimensionalDefinition"===this.multidimensionalDefinition[c].declaredClass?this.multidimensionalDefinition[c].toJson():this.multidimensionalDefinition[c]);a={mosaicMethod:this.method,where:this.where,sortField:this.sortField,sortValue:this.sortValue,ascending:this.ascending,lockRasterIds:this.lockRasterIds,viewpoint:this.viewpoint?this.viewpoint.toJson():null,fids:this.objectIds,mosaicOperation:this.operation,multidimensionalDefinition:a};return d.filter(a,
function(a){if(null!==a)return!0})},_getMethodEnum:function(a){if(a){var c=b.METHOD_NONE;switch(a.toLowerCase()){case "byattribute":c=b.METHOD_ATTRIBUTE;break;case "center":c=b.METHOD_CENTER;break;case "lockraster":c=b.METHOD_LOCKRASTER;break;case "nadir":c=b.METHOD_NADIR;break;case "northwest":c=b.METHOD_NORTHWEST;break;case "seamline":c=b.METHOD_SEAMLINE;break;case "viewpoint":c=b.METHOD_VIEWPOINT}return c}},_getOperatorEnum:function(a){if(a)switch(a.toLowerCase()){case "first":return b.OPERATION_FIRST;
case "last":return b.OPERATION_LAST;case "max":return b.OPERATION_MAX;case "min":return b.OPERATION_MIN;case "blend":return b.OPERATION_BLEND;case "mean":return b.OPERATION_MEAN}}});e.mixin(b,{METHOD_NONE:"esriMosaicNone",METHOD_CENTER:"esriMosaicCenter",METHOD_NADIR:"esriMosaicNadir",METHOD_VIEWPOINT:"esriMosaicViewpoint",METHOD_ATTRIBUTE:"esriMosaicAttribute",METHOD_LOCKRASTER:"esriMosaicLockRaster",METHOD_NORTHWEST:"esriMosaicNorthwest",METHOD_SEAMLINE:"esriMosaicSeamline",OPERATION_FIRST:"MT_FIRST",
OPERATION_LAST:"MT_LAST",OPERATION_MIN:"MT_MIN",OPERATION_MAX:"MT_MAX",OPERATION_MEAN:"MT_MEAN",OPERATION_BLEND:"MT_BLEND"});h("extend-esri")&&e.setObject("layers.MosaicRule",b,p);return b})},"esri/tasks/ImageServiceIdentifyParameters":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../lang ../geometry/jsonUtils".split(" "),function(k,e,h,p,d,c,b){k=k(null,{declaredClass:"esri.tasks.ImageServiceIdentifyParameters",geometry:null,mosaicRule:null,renderingRule:null,
pixelSizeX:null,pixelSizeY:null,pixelSize:null,returnGeometry:!1,returnCatalogItems:!0,timeExtent:null,toJson:function(a){var d=a&&a.geometry||this.geometry;a={geometry:d,returnGeometry:this.returnGeometry,returnCatalogItems:this.returnCatalogItems,mosaicRule:this.mosaicRule?h.toJson(this.mosaicRule.toJson()):null,renderingRule:this.renderingRule?h.toJson(this.renderingRule.toJson()):null};d&&(a.geometryType=b.getJsonType(d));d=this.timeExtent;a.time=d?d.toJson().join(","):null;c.isDefined(this.pixelSizeX)&&
c.isDefined(this.pixelSizeY)?a.pixelSize=h.toJson({x:parseFloat(this.pixelSizeX),y:parseFloat(this.pixelSizeY)}):this.pixelSize&&(a.pixelSize=this.pixelSize?h.toJson(this.pixelSize.toJson()):null);return a}});p("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyParameters",k,d);return k})},"esri/layers/DimensionalDefinition":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../lang"],function(k,e,h,p,d){k=k(null,{declaredClass:"esri.layers.DimensionalDefinition",
variableName:null,dimensionName:null,values:[],isSlice:!1,constructor:function(c){e.isObject(c)&&e.mixin(this,c)},toJson:function(){return d.filter({variableName:this.variableName,dimensionName:this.dimensionName,values:this.values,isSlice:this.isSlice},function(c){return null!==c})}});h("extend-esri")&&e.setObject("layers.DimensionalDefinition",k,p);return k})},"esri/layers/pixelFilters/VectorFieldPixelFilter":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../../lang dojo/_base/array".split(" "),
function(k,e,h,p,d,c){k=k(null,{declaredClass:"esri.layers.pixelFilters.VectorFieldPixelFilter",speedUnits:["esriMetersPerSecond","esriKilometersPerHour","esriKnots","esriFeetPerSecond","esriMilesPerHour"],constructor:function(c){e.mixin(this,c);this.isDataUV=c&&c.isDataUV?c.isDataUV:!1;this.computeMagnitudeAndDirection=e.hitch(this,this.computeMagnitudeAndDirection);this.unitConversionFactor=1;this._updateUnitConvFactor()},setUnits:function(c,a){this.inputUnit=c;this.outputUnit=a;this.unitConversionFactor=
1;this._updateUnitConvFactor()},_updateUnitConvFactor:function(){var b=c.indexOf(this.speedUnits,this.inputUnit),a=c.indexOf(this.speedUnits,this.outputUnit);if(this.inputUnit&&this.outputUnit&&0<=b&&0<=a){var d=[1,0.277778,0.514444,0.3048,0.44704,0];this.unitConversionFactor=d[b]/d[a]}},computeMagnitudeAndDirection:function(c){if(!d.isDefined(c))throw"Could not compute magnitude and direction. No pixel data is available.";var a=c.pixelBlock;if(!d.isDefined(a)||2!==a.getPlaneCount())throw"Could not compute magnitude and direction. Pixel data does not contain two bands.";
var e=c.extent,f=(e.xmax-e.xmin)/a.width,h=(e.ymax-e.ymin)/a.height,k=e.xmin+f/2,e=e.ymax-h/2;a.statistics[0].minValue=0;a.statistics[0].maxValue=0;var p=180/Math.PI,y=[],m=0,r=0,l=0,n=!d.isDefined(a.mask),s,v,z,D,C,q,G,A;C=G=Infinity;q=A=-Infinity;for(m=0;m<a.height;m++)for(r=0;r<a.width;r++,l++)if(y.push([k+f*r,e-h*m]),n||a.mask[l])z=s=a.pixels[0][l]*this.unitConversionFactor,D=v=a.pixels[1][l],this.isDataUV&&(z=Math.sqrt(s*s+v*v),D=90-p*Math.atan2(v,s),a.pixels[0][l]=z*this.unitConversionFactor,
a.pixels[1][l]=D),z>q&&(q=z),z<C&&(C=z),D>A&&(A=D),D<G&&(G=D);a.statistics[0].maxValue=q;a.statistics[0].minValue=C;a.statistics[1].maxValue=A;a.statistics[1].minValue=G;c.locations=y;return c}});h("extend-esri")&&e.setObject("layers.pixelFilters.VectorFieldPixelFilter",k,p);return k})},"esri/tasks/ImageServiceIdentifyTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../request ../geometry/normalizeUtils ./Task ./ImageServiceIdentifyResult".split(" "),function(k,e,h,p,
d,c,b,a){k=k(b,{declaredClass:"esri.tasks.ImageServiceIdentifyTask",constructor:function(a){this._url.path+="/identify";this._handler=e.hitch(this,this._handler)},__msigns:[{n:"execute",c:3,a:[{i:0,p:["geometry"]}],e:2}],_handler:function(c,b,d,e,h){try{var k=new a(c);this._successHandler([k],"onComplete",d,h)}catch(m){this._errorHandler(m,e,h)}},execute:function(a,c,b,h){var k=h.assembly;a=this._encode(e.mixin({},this._url.query,{f:"json"},a.toJson(k&&k[0])));var p=this._handler,m=this._errorHandler;
return d({url:this._url.path,content:a,callbackParamName:"callback",load:function(a,d){p(a,d,c,b,h.dfd)},error:function(a){m(a,b,h.dfd)}})},onComplete:function(){}});c._createWrappers(k);h("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyTask",k,p);return k})},"esri/layers/Raster":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/config dojo/json dojo/sniff ../kernel ../Evented ../request ../geometry/Extent ../SpatialReference ../deferredUtils ./PixelBlock ./LercCodec".split(" "),
function(k,e,h,p,d,c,b,a,g,f,t,B,u,y,m){var r=k(g,{declaredClass:"esri.layers.Raster",imageServiceUrl:null,validPixelTypes:"U1 U2 U4 U8 U16 U32 S8 S16 S32 F32".split(" "),validFormats:["lerc"],_eventMap:{"raster-read-complete":["pixelData","params"]},constructor:function(a){if(!a)throw"Image Service URL is not defined";this.imageServiceUrl=a;this.registerConnectEvents()},read:function(a,c,g){var k=this,m=new h(u._dfdCanceller);if(10>b("ie"))throw"This browser is not supported.";if(!a.imageServiceParameters||
!a.nBands)throw"Insufficient parameters to read data";var l=e.clone(a.imageServiceParameters),n=a.nBands,t=a.pixelType;p.some(this.validPixelTypes,function(a){return a===t})||(l.pixelType="F32");p.some(this.validFormats,function(a){return a.toLowerCase()===l.format.toLowerCase()})||(l.format="lerc");this._prepareGetImageParameters(l);m._pendingDfd=f({url:this.imageServiceUrl+"/exportImage",handleAs:"arraybuffer",content:e.mixin(l,{f:"image"}),load:function(a){"LERC"===l.format.toUpperCase()?(a={pixelBlock:r._lercDecode(a,
{width:l.width,height:l.height,planes:n,pixelType:t,noDataValue:l.noData}),extent:l.extent},k._resolve([a,l],"onRasterReadComplete",c,m)):(a=Error("Format '"+l.format+"' is not supported."),a.log=d.isDebug,k._resolve([a],null,g,m,!0))},error:function(a){k._resolve([a],null,g,m,!0)}});return m},onRasterReadComplete:function(){},_prepareGetImageParameters:function(a){if(a.size&&a.bbox){var b=a.size.split(",");a.width=parseFloat(b[0]);a.height=parseFloat(b[1]);a.extent||(b=a.bbox.split(","),a.extent=
new t(parseFloat(b[0]),parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3]),new B(a.bboxSR)))}else{if(!a.width||Math.floor(a.width)!==a.width||!a.height||Math.floor(a.height)!==a.height)throw"Incorrect Image Dimensions";if(!a.extent||"esri.geometry.Extent"!==a.extent.declaredClass)throw"Incorrect extent";var b=a.extent,d=b.spatialReference.wkid||c.toJson(b.spatialReference.toJson());delete a._ts;e.mixin(a,{bbox:b.xmin+","+b.ymin+","+b.xmax+","+b.ymax,imageSR:d,bboxSR:d,size:a.width+","+a.height},a.disableClientCaching?
{_ts:(new Date).getTime()}:{})}},_adjustExtent:function(a,c,b){var d=a.ymax-a.ymin,e=a.xmax-a.xmin;b>=c?a.ymax=a.ymin+e*c/b:(e=d*b/c,a.xmax=a.xmin+e);return a},_resolve:function(a,c,b,d,e){c&&this[c].apply(this,a);b&&b.apply(null,a);d&&u._resDfd(d,a,e)}}),l=null,n=null;r._lercDecode=function(a,c){if(!c.planes||Math.floor(c.planes)!==c.planes)throw"Number of Bands not specified.";if(!c.height||Math.floor(c.height)!==c.height)throw"Height not provided.";if(!c.width||Math.floor(c.width)!==c.width)throw"Width not provided.";
n=c.noDataValue;var b=c.pixelType;"U1"===b||"U2"===b||"U4"===b||"U8"===b?(b="U8",n=Math.pow(2,8)-1,l=Uint8Array):"U16"===b?(n=n||Math.pow(2,16)-1,l=Uint16Array):"U32"===b?(n=n||Math.pow(2,32)-1,l=Uint32Array):"S8"===b?(n=n||0-Math.pow(2,7),l=Int8Array):"S16"===b?(n=n||0-Math.pow(2,15),l=Int16Array):"S32"===b?(n=n||0-Math.pow(2,31),l=Int32Array):l=Float32Array;c.pixelType=b;for(var b=0,d,e=0,f,b=0;b<c.planes;b++){var h=m.decode(a,{inputOffset:e,encodedMaskData:d,returnMask:0===b?!0:!1,returnEncodedMask:0===
b?!0:!1,returnFileInfo:!0,pixelType:l,noDataValue:n}),e=h.fileInfo.eofOffset;0===b&&(d=h.encodedMaskData,f=new y({width:c.width,height:c.height,pixels:[],pixelType:c.pixelType,mask:h.maskData,statistics:[]}));if(h.height!==c.height||h.width!==c.width)throw"The decoded image dimensions are incorrect";f.addData({pixels:h.pixelData,statistics:{minValue:h.minValue,maxValue:h.maxValue,noDataValue:h.noDataValue}})}return f};b("extend-esri")&&e.setObject("layers.Raster",r,a);return r})},"esri/layers/ImageServiceLayerMixin":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/json dojo/_base/config dojo/has dojo/io-query ../kernel ../config ../lang ../request ../deferredUtils ../urlUtils ../geometry/Extent ../geometry/Point ../geometry/Polygon ./MosaicRule ./RasterFunction ./DimensionalDefinition ./Raster ./PixelBlock ./pixelFilters/VectorFieldPixelFilter ./TimeInfo ./Field ../graphic ../tasks/ImageServiceIdentifyTask ../tasks/ImageServiceIdentifyParameters".split(" "),
function(k,e,h,p,d,c,b,a,g,f,t,B,u,y,m,r,l,n,s,v,z,D,C,q,G,A,w,x){k=k(null,{declaredClass:"esri.layers.ImageServiceLayerMixin",_eventMap:{"rendering-change":!0,"mosaic-rule-change":!0},constructor:function(a,c){},_initialize:function(a,c){this._url=y.urlToObject(a);this.raster=new z(a);this.infoTemplate=c&&c.infoTemplate;var b=c&&c.imageServiceParameters;this.format=b&&b.format;this.compressionTolerance=b&&b.compressionTolerance?b.compressionTolerance:0.01;this.interpolation=b?b.interpolation:null;
this.compressionQuality=b?b.compressionQuality:null;this.bandIds=b?b.bandIds:null;this.mosaicRule=b?b.mosaicRule:null;this.renderingRule=b?b.renderingRule:null;this.useMapDimensionValue=c&&c.hasOwnProperty("useMapDimensionValue")?!!c.useMapDimensionValue:!0;this.activeMapDimensions=c&&c.activeMapDimensions;this._params=e.mixin({},this._url.query,{f:"image",interpolation:this.interpolation,format:this.format,compressionQuality:this.compressionQuality,bandIds:this.bandIds?this.bandIds.join(","):null},
b?b.toJson():{});this.pixelFilter=c&&c.pixelFilter;this.originalPixelData=this.pixelData=null;this.hasDataChanged=!0;this._requestDataHandler=e.hitch(this,this._requestDataHandler);this._requestDataErrorHandler=e.hitch(this,this._requestDataErrorHandler);this._initLayer=e.hitch(this,this._initLayer);this._queryVisibleRastersHandler=e.hitch(this,this._queryVisibleRastersHandler);this._visibleRasters=[];this._rasterAttributeTableFields=[];this._rasterAttributeTableFeatures=[];this._loadCallback=c&&
c.loadCallback;(b=c&&c.resourceInfo)?this._initLayer(b):B({url:this._url.path,content:e.mixin({f:"json"},this._url.query),callbackParamName:"callback",load:this._initLayer,error:this._errorHandler});this.registerConnectEvents()},disableClientCaching:!1,_initLayer:function(a,c){if(!(null===a||void 0===a)){this._findCredential();(this.credential&&this.credential.ssl||a&&a._ssl)&&this._useSSL();var b=this.minScale,d=this.maxScale;e.mixin(this,a);this.minScale=b;this.maxScale=d;this.initialExtent=this.fullExtent=
this.extent=new m(a.extent);this.spatialReference=this.initialExtent.spatialReference;this.pixelSizeX=parseFloat(this.pixelSizeX);this.pixelSizeY=parseFloat(this.pixelSizeY);for(var f=this.minValues,h=this.maxValues,g=this.meanValues,k=this.stdvValues,l=this.bands=[],b=0,d=this.bandCount;b<d;b++)l[b]={min:f[b],max:h[b],mean:g[b],stddev:k[b]};this.timeInfo=(b=this.timeInfo)&&b.timeExtent?new q(b):null;d=this.fields=[];if(f=a.fields)for(b=0;b<f.length;b++)d.push(new G(f[b]));this.version=a.currentVersion;
this.version||(this.version="fields"in a||"objectIdField"in a||"timeInfo"in a?10:9.3);t.isDefined(a.minScale)&&!this._hasMin&&this.setMinScale(a.minScale);t.isDefined(a.maxScale)&&!this._hasMax&&this.setMaxScale(a.maxScale);b={};a.defaultMosaicMethod?(b.method=a.defaultMosaicMethod,b.operation=a.mosaicOperator,b.sortField=a.sortField,b.sortValue=a.sortValue):b.method=n.METHOD_NONE;this.defaultMosaicRule=new n(b);this.defaultMosaicRule.ascending=!0;this._setDefaultRenderingRule(!0);this._isScientificData()&&
(!this.mosaicRule||this.mosaicRule&&!this.mosaicRule.multidimensionalDefinition)&&this._setDefaultMultidimensionalDefinition(!0);10<this.version&&this.hasRasterAttributeTable&&this.getRasterAttributeTable().then(e.hitch(this,function(a){a&&(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=e.clone(a.features));a&&(a.fields&&0<a.fields.length)&&(this._rasterAttributeTableFields=e.clone(a.fields))}));this._isVectorData()&&!t.isDefined(this.pixelFilter)&&(this.vectorFieldPixelFilter=
new C,this.vectorFieldPixelFilter.isDataUV="esriImageServiceDataTypeVector-UV"===this.serviceDataType,this.pixelFilter=this.vectorFieldPixelFilter.computeMagnitudeAndDirection,this.getKeyProperties().then(e.hitch(this,this._setFlowRepresentation)));this.loaded=!0;this.onLoad(this);if(b=this._loadCallback)delete this._loadCallback,b(this)}},getKeyProperties:function(){var a=this._url.path+"/keyProperties",b=new h(u._dfdCanceller);10<this.version?(b._pendingDfd=B({url:a,content:{f:"json"},handleAs:"json",
callbackParamName:"callback"}),b._pendingDfd.then(function(a){b.callback(a)},function(a){b.errback(a)})):(a=Error("Layer does not have key properties"),a.log=c.isDebug,b.errback(a));return b},getRasterAttributeTable:function(){var a=this._url.path+"/rasterAttributeTable",b=new h(u._dfdCanceller);10<this.version&&this.hasRasterAttributeTable?(b._pendingDfd=B({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(function(a){b.callback(a)},function(a){b.errback(a)})):
(a=Error("Layer does not support raster attribute table"),a.log=c.isDebug,b.errback(a));return b},_getRasterAttributeTableFeatures:function(){var a=new h;if(this._rasterAttributeTableFeatures&&0<this._rasterAttributeTableFeatures.length)return a.resolve(this._rasterAttributeTableFeatures),a;if(10<this.version&&this.hasRasterAttributeTable)return a=this.getRasterAttributeTable(),a.then(e.hitch(this,function(a){a&&(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=e.clone(a.features))})),
a;a.resolve(this._rasterAttributeTableFeatures);return a},getCustomRasterFields:function(a){var b=a?a.rasterAttributeTableFieldPrefix:"",c={name:"Raster.ItemPixelValue",alias:"Item Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};a=this.fields?e.clone(this.fields):[];var d=a.length;a[d]={name:"Raster.ServicePixelValue",alias:"Service Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};if(this.capabilities&&-1<this.capabilities.toLowerCase().indexOf("catalog")||
this.fields&&0<this.fields.length)a[d+1]=c;if(t.isDefined(this.pixelFilter)&&("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType))a[d+2]={name:"Raster.Magnitude",alias:"Magnitude",domain:null,editable:!1,type:"esriFieldTypeDouble"},a[d+3]={name:"Raster.Direction",alias:"Direction",domain:null,editable:!1,type:"esriFieldTypeDouble"};this._rasterAttributeTableFields&&0<this._rasterAttributeTableFields.length&&(c=p.filter(this._rasterAttributeTableFields,
function(a){return"esriFieldTypeOID"!==a.type&&"value"!==a.name.toLowerCase()}),c=p.map(c,function(a){var c=e.clone(a);c.name=b+a.name;return c}),a=a.concat(c));return a},_prepareGetImageParameters:function(a,b,c,f){f=t.isDefined(f)?f:this._params;var h=a.spatialReference.wkid||d.toJson(a.spatialReference.toJson());delete f._ts;e.mixin(f,{bbox:a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,imageSR:h,bboxSR:h,size:b+","+c},this.disableClientCaching?{_ts:(new Date).getTime()}:{});delete f.compressionTolerance;
f.format&&"LERC"===f.format.toUpperCase()&&(f.compressionTolerance=this.compressionTolerance);f.token=this._getToken()},getImageUrl:function(b,c,d,h,g){g=t.isDefined(g)?g:this._params;this._prepareGetImageParameters(b,c,d,g);b=e.clone(g);this._cleanupRequestParams(b);c=this._url.path+"/exportImage?";d=y.addProxy(c+a.objectToQuery(e.mixin(b,{f:"image"})));var k=b.token;d.length>f.defaults.io.postLength||this.useMapImage?this._jsonRequest=B({url:c,content:e.mixin(b,{f:"json"}),callbackParamName:"callback",
load:function(a,b){var c=a.href;k&&(c+=-1===c.indexOf("?")?"?token\x3d"+k:"\x26token\x3d"+k);h(y.addProxy(c))},error:this._errorHandler}):h(d)},onRenderingChange:function(){},onMosaicRuleChange:function(){},setInterpolation:function(a,b){this.interpolation=this._params.interpolation=a;b||this.refresh(!0)},setCompressionQuality:function(a,b){this.compressionQuality=this._params.compressionQuality=a;b||this.refresh(!0)},setCompressionTolerance:function(a,b){this.compressionTolerance=a;b||this.refresh(!0)},
setBandIds:function(a,b){var c=!1;this.bandIds!==a&&(c=!0);this.bandIds=a;this._params.bandIds=a.join(",");if(c&&!b)this.onRenderingChange();b||this.refresh(!0)},setDefaultBandIds:function(a){this.bandIds=this._params.bandIds=null;a||this.refresh(!0)},setDisableClientCaching:function(a){this.disableClientCaching=a},setMosaicRule:function(a,b){var c=!1;this.mosaicRule!==a&&(c=!0);this.mosaicRule=a;this._params.mosaicRule=d.toJson(a.toJson());if(c&&!b)this.onMosaicRuleChange();b||this.refresh(!0)},
setRenderingRule:function(a,b){var c=!1;this.renderingRule!==a&&(c=!0);this.renderingRule=a;this._params.renderingRule=a?d.toJson(a.toJson()):null;if(c&&!b)this.onRenderingChange();b||this.refresh(!0)},setImageFormat:function(a,b){this.format=this._params.format=a;b||this.refresh(!0)},setInfoTemplate:function(a){this.infoTemplate=a},setDefinitionExpression:function(a,b){var c=this.mosaicRule?this.mosaicRule.toJson():{};this.mosaicRule||(this.defaultMosaicRule?c=this.defaultMosaicRule.toJson():c.method=
n.METHOD_NONE);c.where=a;c=new n(c);this.setMosaicRule(c,b);return this},getDefinitionExpression:function(){return this.mosaicRule?this.mosaicRule.where:null},setPixelFilter:function(a){this.pixelFilter=a},getPixelData:function(a){return a?this.originalPixelData:this.pixelData},redraw:function(){this.hasDataChanged=!1;this._setPixelData(this.originalPixelData)},queryVisibleRasters:function(a,b,c,d){var e=this._map,f=u._fixDfd(new h(u._dfdCanceller));this._visibleRasters=[];var g,k,l=!0,m;if(this.infoTemplate&&
this.infoTemplate.info&&this.infoTemplate.info.fieldInfos&&0<this.infoTemplate.info.fieldInfos.length){l=!1;m=this.infoTemplate.info;for(g=0;g<m.fieldInfos.length;g++)if((k=m.fieldInfos[g])&&"raster.servicepixelvalue"!==k.fieldName.toLowerCase()&&(k.visible||m.title&&-1<m.title.toLowerCase().indexOf(k.fieldName.toLowerCase()))){l=!0;break}}g=new x;g.geometry=a.geometry;g.returnGeometry=this._map.spatialReference.equals(this.spatialReference);g.returnCatalogItems=l;g.timeExtent=a.timeExtent;g.mosaicRule=
this.mosaicRule?this.mosaicRule:null;g.renderingRule=this.renderingRule?this.renderingRule:null;e&&(a=new r((e.extent.xmax-e.extent.xmin)/(2*e.width),(e.extent.ymax-e.extent.ymin)/(2*e.height),e.extent.spatialReference),g.pixelSize=a);var p=this;a=new w(this.url);(f._pendingDfd=a.execute(g)).addCallbacks(function(a){p._queryVisibleRastersHandler(a,b,c,d,f)},function(a){p._resolve([a],null,d,f,!0)});return f},_queryVisibleRastersHandler:function(a,b,c,f,g){function h(){var a=this.getCustomRasterFields(b),
d=this._getDomainFields(a),f=b?b.returnDomainValues:!1,M=b&&b.rasterAttributeTableFieldPrefix,l,q,J,u,s,v,w,x,y;this._getRasterAttributeTableFeatures().then(e.hitch(this,function(a){for(l=0;l<n.length;l++){E=n[l];E.setInfoTemplate(this.infoTemplate);E._layer=this;if(k){q=k;r&&r.length>=l&&(J=r[l],q=J.replace(/ /gi,", "));E.attributes["Raster.ItemPixelValue"]=q;E.attributes["Raster.ServicePixelValue"]=k;if(this.pixelFilter){y=q.replace(" ","").split(",");var b=new D({height:1,width:1,pixelType:"F32",
pixels:[],statistics:[]});p.forEach(y,function(a){b.addData({pixels:[a],statistics:{minValue:a,maxValue:a,noDataValue:null}})});this.pixelFilter({pixelBlock:b,extent:new m(0,0,0,0,this._map.spatialReference)});if("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType)E.attributes["Raster.Magnitude"]=b.pixels[0][0],E.attributes["Raster.Direction"]=b.pixels[1][0]}if(a&&0<a.length&&(u=p.filter(a,function(a){if(a&&a.attributes)return a.attributes.hasOwnProperty("Value")?
a.attributes.Value==q:a.attributes.VALUE==q}),0<u.length&&(s=e.clone(u[0]),M&&s))){x={};for(v in s.attributes)s.attributes.hasOwnProperty(v)&&(w=M+v,x[w]=s.attributes[v]);s.attributes=x;E.attributes=e.mixin(E.attributes,s.attributes)}}f&&(d&&0<d.length)&&p.forEach(d,function(a){if(a){var b=E.attributes[a.name];t.isDefined(b)&&(b=this._getDomainValue(a.domain,b),t.isDefined(b)&&(E.attributes[a.name]=b))}},this);C.push(E);this._visibleRasters.push(E)}this._resolve([C,null,!0],null,c,g)}))}var k=a.value,
r,n,q=0,u=0,s=this,v=this.objectIdField,w;if(a.catalogItems){f=0;var x,y,z=a.catalogItems.features.length;x=0;n=Array(z);r=Array(z);w=Array(z);for(q=0;q<z;q++)-1<a.properties.Values[q].toLowerCase().indexOf("nodata")&&x++;x=z-x;for(q=0;q<z;q++)y=-1<a.properties.Values[q].toLowerCase().indexOf("nodata")?x++:f++,n[y]=a.catalogItems.features[q],r[y]=a.properties.Values[q],w[y]=n[y].attributes[v]}this._visibleRasters=[];var E;a=-1<k.toLowerCase().indexOf("nodata");k&&(!n&&!a)&&(v="ObjectId",n=[],E=new A(new m(this.fullExtent),
null,{ObjectId:0}),n.push(E));var C=[];n?!this._map.spatialReference.equals(this.spatialReference)&&w&&0<w.length?B({url:this._url.path+"/query",content:{f:"json",objectIds:w.join(","),returnGeometry:!0,outSR:d.toJson(s._map.spatialReference.toJson()),outFields:v},handleAs:"json",callbackParamName:"callback",load:function(a){if(0===a.features.length)s._resolve([C,null,null],null,c,g);else{for(q=0;q<a.features.length;q++)for(u=0;u<n.length;u++)n[u].attributes[v]==a.features[q].attributes[v]&&(n[u].geometry=
new l(a.features[q].geometry),n[u].geometry.setSpatialReference(s._map.spatialReference));h.call(s)}},error:function(a){s._resolve([C,null,null],null,c,g)}}):h.call(this):this._resolve([C,null,null],null,c,g)},getVisibleRasters:function(){var a=this._visibleRasters,b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(a[c]);return b},_getDomainFields:function(a){if(a){var b=[];p.forEach(a,function(a){if(a.domain){var c={};c.name=a.name;c.domain=a.domain;b.push(c)}});return b}},_getDomainValue:function(a,
b){if(a&&a.codedValues){var c;p.some(a.codedValues,function(a){return a.code===b?(c=a.name,!0):!1});return c}},_requestData:function(a,b,c){a=e.clone(a);var d=a._normalize(!0);this._prepareGetImageParameters(d,b,c);b=e.clone(this._params);this._cleanupRequestParams(b);b.extent=a;b={imageServiceParameters:b,nBands:Math.min(this.bandCount,3),pixelType:this.pixelType};this.raster.read(b,this._requestDataHandler,this._requestDataErrorHandler)},_requestDataHandler:function(a){this.originalPixelData=a;
this.hasDataChanged=!0;this._setPixelData(a)},_setPixelData:function(a){a=this._clonePixelData(a);this.pixelFilter&&this.pixelFilter(a);this.pixelData=a;this._drawPixelData()},_drawPixelData:function(){},_requestDataErrorHandler:function(a){},_clonePixelData:function(a){if(null===a||void 0===a)return a;var b={};a.extent&&(b.extent=e.clone(a.extent));a=a.pixelBlock;if(null===a||void 0===a)return b;b.pixelBlock=a.clone();return b},getMultidimensionalInfo:function(){var a=this._url.path+"/multiDimensionalInfo",
b=new h(u._dfdCanceller);if(this._multidimensionalInfo)return b.resolve(this._multidimensionalInfo),b;10.3<=this.version&&this.hasMultidimensions?(b._pendingDfd=B({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(e.hitch(this,function(a){this._multidimensionalInfo=a.multidimensionalInfo;b.callback(a.multidimensionalInfo)}),function(a){b.errback(a)})):(a=Error("Layer does not support multidimensional info"),a.log=c.isDebug,b.errback(a));return b},getDefaultMultidimensionalDefinition:function(){var a,
b,c,d,f=[],g=new h(u._dfdCanceller);if(this._defaultMultidimensionalDefinition)return g.resolve(this._defaultMultidimensionalDefinition),g;g._pendingDfd=this.getMultidimensionalInfo();g._pendingDfd.then(e.hitch(this,function(e){a=e;b=a.variables[0].name;c=a.variables[0].dimensions;for(d in c)c.hasOwnProperty(d)&&(c[d].hasRanges&&!0==c[d].hasRanges?f.push(new v({variableName:b,dimensionName:c[d].name,isSlice:!1,values:[c[d].values[0][0],c[d].values[0][1]]})):f.push(new v({variableName:b,dimensionName:c[d].name,
isSlice:!0,values:[c[d].extent[0]]})));this._defaultMultidimensionalDefinition=f;g.callback(f)}),function(a){g.errback(a)});return g},_setDefaultMultidimensionalDefinition:function(a){var b,c={};this.getDefaultMultidimensionalDefinition().then(e.hitch(this,function(d){b=d;0<b.length&&(this.mosaicRule?(c=e.clone(this.mosaicRule),c.multidimensionalDefinition=b):this.defaultMosaicRule?(c=e.clone(this.defaultMosaicRule),c.multidimensionalDefinition=b):c=new n({multidimensionalDefinition:b}),this.setMosaicRule(c,
a))}))},_setDefaultRenderingRule:function(a){var b={};if(!this.renderingRule&&"esri.layers.ArcGISImageServiceVectorLayer"!==this.declaredClass&&this.rasterFunctionInfos&&this.rasterFunctionInfos.length&&"None"!=this.rasterFunctionInfos[0].name)b.rasterFunction=this.rasterFunctionInfos[0].name;else if(!this.renderingRule&&"esri.layers.ArcGISImageServiceVectorLayer"==this.declaredClass&&10.3<this.version){var c="esriImageServiceDataTypeVector-UV"===this.serviceDataType?7:10;new s;b.rasterFunction="Resample";
b.rasterFunctionArguments={ResamplingType:c,InputCellSize:{x:this.pixelSizeX,y:this.pixelSizeY}}}b.hasOwnProperty("rasterFunction")&&(this.defaultRenderingRule=new s(b),this.setRenderingRule(this.defaultRenderingRule,a))},_cleanupRequestParams:function(a){if(!a)return a;if(a.time&&a.mosaicRule){var b=new n(d.fromJson(a.mosaicRule));if(b&&b.multidimensionalDefinition&&0<b.multidimensionalDefinition.length){var c=p.filter(b.multidimensionalDefinition,function(a){return"StdTime"!==a.dimensionName});
b.multidimensionalDefinition=c;a.mosaicRule=dojo.toJson(b.toJson())}}b="displayOnPan drawMode styling id opacity visible resourceInfo useMapDimensionValue extent".split(" ");for(imageParam in b)a.hasOwnProperty(b[imageParam])&&delete a[b[imageParam]];return a},_isScientificData:function(){return"esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType||"esriImageServiceDataTypeScientific "===this.serviceDataType},_isVectorData:function(){return"esriImageServiceDataTypeVector-UV"===
this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType},_createPixelData:function(a){a=new D({width:2,height:2,pixels:a,pixelType:this.pixelType,statistics:a});var b=this.fullExtent.getCenter(),b=new m(b.x,b.y,b.x+this.pixelSizeX,b.y+this.pixelSizeY,this.spatialReference);return{pixelBlock:a,extent:b}},_resolve:function(a,b,c,d,e){b&&this[b].apply(this,a);c&&c.apply(null,a);d&&u._resDfd(d,a,e)}});b("extend-esri")&&e.setObject("layers.ImageServiceLayerMixin",k,g);return k})},
"*noref":1}});
define("esri/layers/ArcGISImageServiceLayer","dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../config ./DynamicMapServiceLayer ./ImageServiceLayerMixin".split(" "),function(k,e,h,p,d,c,b){k=k([c,b],{declaredClass:"esri.layers.ArcGISImageServiceLayer",constructor:function(a,b){this._initialize(a,b);this.useMapImage=b&&b.useMapImage||!1},refresh:function(a){if(a)this.inherited(arguments);else{var b=this.disableClientCaching;this.disableClientCaching=!0;this.inherited(arguments);this.disableClientCaching=
b}},exportMapImage:function(a,b){var c=d.defaults.map,c=e.mixin({size:c.width+","+c.height},this._params,a?a.toJson(this.normalization):{},{f:"json"});delete c._ts;this._exportMapImage(this._url.path+"/exportImage",c,b)}});h("extend-esri")&&e.setObject("layers.ArcGISImageServiceLayer",k,p);return k});