// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"dojo/data/util/filter":function(){define(["../../_base/lang"],function(k){var b={};k.setObject("dojo.data.util.filter",b);b.patternToRegExp=function(b,k){for(var h="^",d=null,a=0;a<b.length;a++)switch(d=b.charAt(a),d){case "\\":h+=d;a++;h+=b.charAt(a);break;case "*":h+=".*";break;case "?":h+=".";break;case "$":case "^":case "/":case "+":case ".":case "|":case "(":case ")":case "{":case "}":case "[":case "]":h+="\\";default:h+=d}h+="$";return k?RegExp(h,"mi"):RegExp(h,"m")};return b})},
"dojo/data/util/simpleFetch":function(){define(["../../_base/lang","../../_base/kernel","./sorter"],function(k,b,n){var p={};k.setObject("dojo.data.util.simpleFetch",p);p.errorHandler=function(h,d){d.onError&&d.onError.call(d.scope||b.global,h,d)};p.fetchHandler=function(h,d){var a=d.abort||null,l=!1,f=d.start?d.start:0,c=d.count&&Infinity!==d.count?f+d.count:h.length;d.abort=function(){l=!0;a&&a.call(d)};var e=d.scope||b.global;d.store||(d.store=this);d.onBegin&&d.onBegin.call(e,h.length,d);d.sort&&
h.sort(n.createSortFunction(d.sort,this));if(d.onItem)for(var g=f;g<h.length&&g<c;++g){var q=h[g];l||d.onItem.call(e,q,d)}d.onComplete&&!l&&(g=null,d.onItem||(g=h.slice(f,c)),d.onComplete.call(e,g,d))};p.fetch=function(b){b=b||{};b.store||(b.store=this);this._fetchItems(b,k.hitch(this,"fetchHandler"),k.hitch(this,"errorHandler"));return b};return p})},"dojo/data/util/sorter":function(){define(["../../_base/lang"],function(k){var b={};k.setObject("dojo.data.util.sorter",b);b.basicComparator=function(b,
k){var h=-1;null===b&&(b=void 0);null===k&&(k=void 0);if(b==k)h=0;else if(b>k||null==b)h=1;return h};b.createSortFunction=function(k,p){function h(a,c,b,e){return function(l,f){var g=e.getValue(l,a),d=e.getValue(f,a);return c*b(g,d)}}for(var d=[],a,l=p.comparatorMap,f=b.basicComparator,c=0;c<k.length;c++){a=k[c];var e=a.attribute;if(e){a=a.descending?-1:1;var g=f;l&&("string"!==typeof e&&"toString"in e&&(e=e.toString()),g=l[e]||f);d.push(h(e,a,g,p))}}return function(a,c){for(var b=0;b<d.length;){var e=
d[b++](a,c);if(0!==e)return e}return 0}};return b})},"esri/arcgis/csv":function(){define("dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/sniff dojo/number dojox/data/CsvStore ../kernel ../config ../request ../SpatialReference ../geometry/jsonUtils ../geometry/webMercatorUtils".split(" "),function(k,b,n,p,h,d,a,l,f,c,e,g){function q(a){var c=0,e="";b.forEach([","," ",";","|","\t"],function(b){var l=a.split(b).length;l>c&&(c=l,e=b)});return e}function C(a,c){if(!a||"[object Date]"!==Object.prototype.toString.call(a)||
isNaN(a.getTime()))return!1;var b=!0;if(p("chrome")&&/\d+\W*$/.test(c)){var e=c.match(/[a-zA-Z]{2,}/);if(e){for(var b=!1,l=0,f=e.length,g=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!b&&l<=f&&!(b=!g.test(e[l]));)l++;b=!b}}return b}function u(a,c,e){var l=a.indexOf("\n"),l=k.trim(a.substr(0,l)),f=c.columnDelimiter;f||(f=q(l));var g=new d({data:a,separator:f});g.fetch({onComplete:function(a,
l){var f=0,y={layerDefinition:c.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},d=y.layerDefinition.objectIdField,q=y.layerDefinition.fields;!d&&!b.some(q,function(a){return"esriFieldTypeOID"===a.type?(d=a.name,!0):!1})&&(q.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1}),d="__OBJECTID");var m,s,x=g._attributes,p=[],n=[];b.forEach(q,function(a){"esriFieldTypeDate"===a.type?p.push(a.name):("esriFieldTypeDouble"===a.type||"esriFieldTypeInteger"===
a.type)&&n.push(a.name)});c.locationInfo&&"coordinates"===c.locationInfo.locationType?(m=c.locationInfo.latitudeFieldName,s=c.locationInfo.longitudeFieldName):b.forEach(x,function(a){var c;c=b.indexOf(z,a.toLowerCase());-1!==c&&(m=a);c=b.indexOf(A,a.toLowerCase());-1!==c&&(s=a)});if(!m||!s)setTimeout(function(){console.error("File does not seem to contain fields with point coordinates.")},1),e&&e(null,Error("File does not seem to contain fields with point coordinates."));else{-1===b.indexOf(n,m)&&
n.push(m);-1===b.indexOf(n,s)&&n.push(s);var r;k.isArray(c.outFields)&&-1===b.indexOf(c.outFields,"*")&&(r=c.outFields);b.forEach(x,function(a){b.some(q,function(c){return a===c.name})||q.push({name:a,alias:a,type:a===m||a===s?"esriFieldTypeDouble":"esriFieldTypeString"})});var x=0,v=a.length;for(x;x<v;x++){var u=a[x],w=g.getAttributes(u),t={};b.forEach(w,function(a){if(a&&(a===m||a===s||!r||-1<b.indexOf(r,a))){var c=a;0===a.length&&b.forEach(q,function(c,e){c.name==="attribute_"+(e-1)&&(a="attribute_"+
(e-1))});if(-1<b.indexOf(p,a)){var c=g.getValue(u,c),e=new Date(c);t[a]=C(e,c)?e.getTime():null}else if(-1<b.indexOf(n,a)){e=h.parse(g.getValue(u,c));if((a===m||a===s)&&(isNaN(e)||181<Math.abs(e)))e=parseFloat(g.getValue(u,c));isNaN(e)?t[a]=null:t[a]=e}else t[a]=g.getValue(u,c)}});t[d]=f;f++;var w=t[m],B=t[s];null==B||(null==w||isNaN(w)||isNaN(B))||(r&&-1===b.indexOf(r,m)&&delete t[m],r&&-1===b.indexOf(r,s)&&delete t[s],y.featureSet.features.push({geometry:{x:B,y:w,spatialReference:{wkid:4326}},attributes:t}))}y.layerDefinition.name=
"csv";e&&e(y)}},onError:function(a){console.error("Error fetching items from CSV store: ",a);e&&e(null,a)}});return!0}function m(a,c,f,d,q,m){0===a.length&&q(null);var h=e.getGeometryType(c),r=[];b.forEach(a,function(a){a=new h(a);a.spatialReference=f;r.push(a)},this);c=[102113,102100,3857];f.wkid&&4326===f.wkid&&d.wkid&&-1<b.indexOf(c,d.wkid)?(b.forEach(r,function(a){a.xmin?(a.xmin=Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99)):a.rings?
b.forEach(a.rings,function(a){b.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.paths?b.forEach(a.paths,function(a){b.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.x&&(a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),89.99))},this),a=[],b.forEach(r,function(c){c=g.geographicToWebMercator(c);102100!==d.wkid&&(c.spatialReference=d);a.push(c.toJson())},
this),q(a)):null!==f.wkid&&-1<b.indexOf(c,f.wkid)&&null!==d.wkid&&4326===d.wkid?(a=[],b.forEach(r,function(c){a.push(g.webMercatorToGeographic(c).toJson())},this),q(a)):(c=function(c,e){c&&c.length===a.length?(a=[],b.forEach(c,function(c){c&&(c.rings&&0<c.rings.length&&0<c.rings[0].length&&0<c.rings[0][0].length&&!isNaN(c.rings[0][0][0])&&!isNaN(c.rings[0][0][1])||c.paths&&0<c.paths.length&&0<c.paths[0].length&&0<c.paths[0][0].length&&!isNaN(c.paths[0][0][0])&&!isNaN(c.paths[0][0][1])||c.xmin&&!isNaN(c.xmin)&&
c.ymin&&!isNaN(c.ymin)||c.x&&!isNaN(c.x)&&c.y&&!isNaN(c.y))?a.push(c.toJson()):a.push(null)},this),q(a)):m(c,e)},l.defaults.geometryService?l.defaults.geometryService.project(r,d,k.hitch(this,c),m):q(null))}function r(a,c){var e=[102113,102100,3857];return a&&c&&a.wkid===c.wkid&&a.wkt===c.wkt||a&&c&&a.wkid&&c.wkid&&-1<b.indexOf(e,a.wkid)&&-1<b.indexOf(e,c.wkid)?!0:!1}function v(a,l,f,d){if(a.featureSet&&0!==a.featureSet.features.length)if(r(f,l))d(a);else{var g,q=function(c){var e=[];b.forEach(a.featureSet.features,
function(a,b){c[b]&&(a.geometry=c[b],e.push(a))},this);d(a)},h=function(c,e){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Final try.");d(a)},n=function(c,e){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Try one more time.");m(g,a.featureSet.geometryType,l,f,k.hitch(this,q),k.hitch(this,h))};a.featureSet.features&&0<a.featureSet.features.length?(g=[],b.forEach(a.featureSet.features,function(c){if(c.geometry.toJson)g.push(c.geometry);else{var b=
e.getGeometryType(a.featureSet.geometryType);g.push(new b(c.geometry))}}),l.toJson||(l=new c(l)),f.toJson||(f=new c(f)),m(g,a.featureSet.geometryType,l,f,k.hitch(this,q),k.hitch(this,n))):d(a)}}var z="lat latitude y ycenter latitude83 latdecdeg POINT-Y".split(" "),A="lon lng long longitude x xcenter longitude83 longdecdeg POINT-X".split(" "),w={latFieldStrings:z,longFieldStrings:A,buildCSVFeatureCollection:function(a){var c=new n,e=function(a,e){e?c.errback(e):c.callback(a)},b={url:a.url,handleAs:"text",
load:function(c){u(c,a,k.hitch(this,e))},error:function(a){c.errback(a);console.error("error: "+a)}};-1<a.url.indexOf("arcgis.com")&&(-1<a.url.indexOf("/content/items")&&-1<a.url.indexOf("/data"))&&(b.headers={"Content-Type":""});f(b,{usePost:!1});return c},projectFeatureCollection:function(a,e,b){var l=new n;b||(b=new c({wkid:4326}));v(a,b,e,k.hitch(this,function(a){l.callback(a)}));return l},generateDefaultPopupInfo:function(a){var c={esriFieldTypeDouble:1,esriFieldTypeSingle:1},e={esriFieldTypeInteger:1,
esriFieldTypeSmallInteger:1},l={esriFieldTypeDate:1},f=null;a=b.map(a.layerDefinition.fields,k.hitch(this,function(a){"NAME"===a.name.toUpperCase()&&(f=a.name);var b="esriFieldTypeOID"!==a.type&&"esriFieldTypeGlobalID"!==a.type&&"esriFieldTypeGeometry"!==a.type,d=null;if(b){var g=a.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+g+",")||-1<g.indexOf("area")||-1<g.indexOf("length")||-1<g.indexOf("shape")||-1<g.indexOf("perimeter")||
-1<g.indexOf("objectid")||g.indexOf("_")===g.length-1||g.indexOf("_i")===g.length-2&&1<g.length)b=!1;a.type in e?d={places:0,digitSeparator:!0}:a.type in c?d={places:2,digitSeparator:!0}:a.type in l&&(d={dateFormat:"shortDateShortTime"})}return k.mixin({},{fieldName:a.name,label:a.alias,isEditable:!0,tooltip:"",visible:b,format:d,stringFieldOption:"textbox"})}));return{title:f?"{"+f+"}":"",fieldInfos:a,description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:q,_isValidDate:C,_processCsvData:u,
_projectGeometries:m,_sameSpatialReference:r,_projectFeatureSet:v};p("extend-esri")&&k.setObject("arcgis.csv",w,a);return w})},"dojox/data/CsvStore":function(){define("dojo/_base/lang dojo/_base/declare dojo/_base/xhr dojo/_base/kernel dojo/data/util/filter dojo/data/util/simpleFetch".split(" "),function(k,b,n,p,h,d){b=b("dojox.data.CsvStore",null,{constructor:function(a){this._attributes=[];this._attributeIndexes={};this._dataArray=[];this._arrayOfAllItems=[];this._loadFinished=!1;a.url&&(this.url=
a.url);this._csvData=a.data;a.label?this.label=a.label:""===this.label&&(this.label=void 0);this._storeProp="_csvStore";this._idProp="_csvId";this._features={"dojo.data.api.Read":!0,"dojo.data.api.Identity":!0};this._loadInProgress=!1;this._queuedFetches=[];this.identifier=a.identifier;""===this.identifier?delete this.identifier:this._idMap={};"separator"in a&&(this.separator=a.separator);"urlPreventCache"in a&&(this.urlPreventCache=a.urlPreventCache?!0:!1)},url:"",label:"",identifier:"",separator:",",
urlPreventCache:!1,_assertIsItem:function(a){if(!this.isItem(a))throw Error(this.declaredClass+": a function was passed an item argument that was not an item");},_getIndex:function(a){a=this.getIdentity(a);this.identifier&&(a=this._idMap[a]);return a},getValue:function(a,b,f){this._assertIsItem(a);var c=f;if("string"===typeof b)b=this._attributeIndexes[b],null!=b&&(c=this._dataArray[this._getIndex(a)][b]||f);else throw Error(this.declaredClass+": a function was passed an attribute argument that was not a string");
return c},getValues:function(a,b){var f=this.getValue(a,b);return f?[f]:[]},getAttributes:function(a){this._assertIsItem(a);var b=[];a=this._dataArray[this._getIndex(a)];for(var f=0;f<a.length;f++)""!==a[f]&&b.push(this._attributes[f]);return b},hasAttribute:function(a,b){this._assertIsItem(a);if("string"===typeof b){var f=this._attributeIndexes[b],c=this._dataArray[this._getIndex(a)];return"undefined"!==typeof f&&f<c.length&&""!==c[f]}throw Error(this.declaredClass+": a function was passed an attribute argument that was not a string");
},containsValue:function(a,b,f){var c=void 0;"string"===typeof f&&(c=h.patternToRegExp(f,!1));return this._containsValue(a,b,f,c)},_containsValue:function(a,b,f,c){a=this.getValues(a,b);for(b=0;b<a.length;++b){var e=a[b];if("string"===typeof e&&c)return null!==e.match(c);if(f===e)return!0}return!1},isItem:function(a){if(a&&a[this._storeProp]===this)if(a=a[this._idProp],this.identifier){if(this._dataArray[this._idMap[a]])return!0}else if(0<=a&&a<this._dataArray.length)return!0;return!1},isItemLoaded:function(a){return this.isItem(a)},
loadItem:function(a){},getFeatures:function(){return this._features},getLabel:function(a){if(this.label&&this.isItem(a))return this.getValue(a,this.label)},getLabelAttributes:function(a){return this.label?[this.label]:null},_fetchItems:function(a,b,f){var c=this,e=function(a,e){var f=null;if(a.query){var g,d,f=[],q=a.queryOptions?a.queryOptions.ignoreCase:!1,k={};for(g in a.query)d=a.query[g],"string"===typeof d&&(k[g]=h.patternToRegExp(d,q));for(q=0;q<e.length;++q){var n=!0,p=e[q];for(g in a.query)d=
a.query[g],c._containsValue(p,g,d,k[g])||(n=!1);n&&f.push(p)}}else f=e.slice(0,e.length);b(f,a)};if(this._loadFinished)e(a,this._arrayOfAllItems);else if(""!==this.url)if(this._loadInProgress)this._queuedFetches.push({args:a,filter:e});else{this._loadInProgress=!0;var g=n.get({url:c.url,handleAs:"text",preventCache:c.urlPreventCache});g.addCallback(function(b){try{c._processData(b),e(a,c._arrayOfAllItems),c._handleQueuedFetches()}catch(g){f(g,a)}});g.addErrback(function(b){c._loadInProgress=!1;if(f)f(b,
a);else throw b;});var d=null;a.abort&&(d=a.abort);a.abort=function(){g&&-1===g.fired&&g.cancel();d&&d.call(a)}}else if(this._csvData)try{this._processData(this._csvData),this._csvData=null,e(a,this._arrayOfAllItems)}catch(k){f(k,a)}else{var p=Error(this.declaredClass+": No CSV source data was provided as either URL or String data input.");if(f)f(p,a);else throw p;}},close:function(a){},_getArrayOfArraysFromCsvFileContents:function(a){if(k.isString(a)){var b=RegExp("^\\s+","g"),f=RegExp("\\s+$","g"),
c=RegExp('""',"g"),e=[],g=this._splitLines(a);for(a=0;a<g.length;++a){var d=g[a];if(0<d.length){for(var d=d.split(this.separator),h=0;h<d.length;){var n=d[h].replace(b,""),m=n.replace(f,""),p=m.charAt(0),v=m.charAt(m.length-1),z=m.charAt(m.length-2),A=m.charAt(m.length-3);if(2===m.length&&'""'==m)d[h]="";else if('"'==p&&('"'!=v||'"'==v&&'"'==z&&'"'!=A)){if(h+1===d.length)return;d[h]=n+this.separator+d[h+1];d.splice(h+1,1)}else'"'==p&&'"'==v&&(m=m.slice(1,m.length-1),m=m.replace(c,'"')),d[h]=m,h+=
1}e.push(d)}}this._attributes=e.shift();for(a=0;a<this._attributes.length;a++)this._attributeIndexes[this._attributes[a]]=a;this._dataArray=e}},_splitLines:function(a){var b=[],d,c="",e=!1;for(d=0;d<a.length;d++){var g=a.charAt(d);switch(g){case '"':e=!e;c+=g;break;case "\r":e?c+=g:(b.push(c),c="",d<a.length-1&&"\n"==a.charAt(d+1)&&d++);break;case "\n":e?c+=g:(b.push(c),c="");break;default:c+=g}}""!==c&&b.push(c);return b},_processData:function(a){this._getArrayOfArraysFromCsvFileContents(a);this._arrayOfAllItems=
[];if(this.identifier&&void 0===this._attributeIndexes[this.identifier])throw Error(this.declaredClass+": Identity specified is not a column header in the data set.");for(a=0;a<this._dataArray.length;a++){var b=a;this.identifier&&(b=this._dataArray[a][this._attributeIndexes[this.identifier]],this._idMap[b]=a);this._arrayOfAllItems.push(this._createItemFromIdentity(b))}this._loadFinished=!0;this._loadInProgress=!1},_createItemFromIdentity:function(a){var b={};b[this._storeProp]=this;b[this._idProp]=
a;return b},getIdentity:function(a){return this.isItem(a)?a[this._idProp]:null},fetchItemByIdentity:function(a){var b,d=a.scope?a.scope:p.global;if(this._loadFinished)b=this._createItemFromIdentity(a.identity),this.isItem(b)||(b=null),a.onItem&&a.onItem.call(d,b);else{var c=this;if(""!==this.url)this._loadInProgress?this._queuedFetches.push({args:a}):(this._loadInProgress=!0,b=n.get({url:c.url,handleAs:"text"}),b.addCallback(function(b){try{c._processData(b);var e=c._createItemFromIdentity(a.identity);
c.isItem(e)||(e=null);a.onItem&&a.onItem.call(d,e);c._handleQueuedFetches()}catch(h){a.onError&&a.onError.call(d,h)}}),b.addErrback(function(c){this._loadInProgress=!1;a.onError&&a.onError.call(d,c)}));else if(this._csvData)try{c._processData(c._csvData),c._csvData=null,b=c._createItemFromIdentity(a.identity),c.isItem(b)||(b=null),a.onItem&&a.onItem.call(d,b)}catch(e){a.onError&&a.onError.call(d,e)}}},getIdentityAttributes:function(a){return this.identifier?[this.identifier]:null},_handleQueuedFetches:function(){if(0<
this._queuedFetches.length){for(var a=0;a<this._queuedFetches.length;a++){var b=this._queuedFetches[a],d=b.filter,c=b.args;d?d(c,this._arrayOfAllItems):this.fetchItemByIdentity(b.args)}this._queuedFetches=[]}}});k.extend(b,d);return b})},"*noref":1}});
define("esri/layers/CSVLayer","dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../arcgis/csv ./FeatureLayer ../geometry/Extent ../tasks/FeatureSet".split(" "),function(k,b,n,p,h,d,a,l,f){b=b(a,{declaredClass:"esri.layers.CSVLayer",_preventInit:!0,_fieldTypeMap:{Date:"esriFieldTypeDate",Number:"esriFieldTypeDouble",String:"esriFieldTypeString"},constructor:function(a,b){this.url=a;b=n.mixin({},b);this.columnDelimiter=b.columnDelimiter;this.latitudeFieldName=b.latitudeFieldName;
this.longitudeFieldName=b.longitudeFieldName;var d=b.layerDefinition;d||(d={fields:b.fields||[],geometryType:"esriGeometryPoint",copyrightText:b.copyright},b.fields&&k.forEach(b.fields,function(a){a.type=this._fieldTypeMap[a.type||"String"];a.alias||(a.alias=a.name)},this));this._buildCsvFcParam={url:this.url,columnDelimiter:this.columnDelimiter,layerDefinition:d,outFields:b.outFields};this.latitudeFieldName&&this.longitudeFieldName&&(this._buildCsvFcParam.locationInfo={locationType:"coordinates",
latitudeFieldName:this.latitudeFieldName,longitudeFieldName:this.longitudeFieldName});this._projectFeatures=n.hitch(this,this._projectFeatures);this._addFeatures=n.hitch(this,this._addFeatures);this._initCSVLayer(b)},refresh:function(){this._fireUpdateStart();this.applyEdits(null,null,this.graphics);this._loadFeatures()},_setMap:function(a){var b=this.inherited(arguments);this._fireUpdateStart();this._projectFeatures(this._csvFC).then(this._addFeatures).otherwise(this._errorHandler);this._csvFC=null;
return b},_initCSVLayer:function(a){var b=this;d.buildCSVFeatureCollection(this._buildCsvFcParam).then(function(d){b._csvFC=d;var f=d.layerDefinition;f.extent=b._getFCExtent(d);a.outFields||(a.outFields=["*"]);b._initFeatureLayer({layerDefinition:f},a)}).otherwise(this._errorHandler)},_loadFeatures:function(){d.buildCSVFeatureCollection(this._buildCsvFcParam).then(this._projectFeatures).then(this._addFeatures).otherwise(this._errorHandler)},_projectFeatures:function(a){return d.projectFeatureCollection(a,
this._map.spatialReference)},_addFeatures:function(a){a=new f(a.featureSet);this.applyEdits(a.features,null,null);this._fireUpdateEnd()},_getFCExtent:function(a){var b;if(a&&a.featureSet&&a.featureSet.features){a=a.featureSet.features;var d=a.length;if(1<d){var f=a[0].geometry;b=new l(f.x,f.y,f.x,f.y);for(d-=1;0<d;d--)f=a[d].geometry,b.xmin=Math.min(b.xmin,f.x),b.ymin=Math.min(b.ymin,f.y),b.xmax=Math.max(b.xmax,f.x),b.ymax=Math.max(b.ymax,f.y);0>=b.getWidth()&&0>=b.getHeight()&&(b=null)}}return b}});
p("extend-esri")&&n.setObject("layers.CSVLayer",b,h);return b});