// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/StreamTrackManager":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../graphic ../geometry/Polyline ./TrackManager".split(" "),function(d,v,g,r,s,w,x,y){d=d([y],{declaredClass:"esri.layers._StreamTrackManager",constructor:function(g){this.inherited(arguments)},initialize:function(g){this.inherited(arguments)},addFeatures:function(d,q){function p(h,e){var a,b,c,f;n[h]||(n[h]=[]);a=n[h];0<k&&(e.length>k&&e.splice(0,e.length-k),c=
e.length+a.length,c>k&&(b=a.splice(0,c-k)));c=e.length;for(f=0;f<c;f+=1)a.push(e[f]);return{deletes:b,adds:e}}var n,e,u,k,l={},h={},t;if(q)return this.inherited(arguments),l;n=this.trackMap;e=this.layer;u=e._trackIdField;k=e.maximumTrackPoints||0;g.forEach(d,function(e){var k=e.attributes[u];e.visible&&(h[k]||(h[k]=[]),h[k].push(e))});for(t in h)h.hasOwnProperty(t)&&(e=p(t,h[t]),l[t]=e);return l},removeFeatures:function(d){var q=[],p=this.layer.objectIdField,n=this.layer._trackIdField;d&&(g.forEach(d,
function(e){var d,k,l,h;k=e.attributes[n];d=e.attributes[p];if(l=this.trackMap[k])for(e=0;e<l.length;e+=1)if(h=l[e],h.attributes[p]===d){this.trackMap[k].splice(e,1);-1===g.indexOf(k)&&q.push(k);break}},this),0<d.length&&this.refreshTracks(q))},drawTracks:function(d){function q(h){var d=e[h],g=d&&1<d.length,l,a,b;if((b=p.trackLineMap[h])&&!g)n.remove(b),delete p.trackLineMap[h],b=null;if(!g)return!1;g=[];for(l=d.length-1;0<=l;l-=1)(a=d[l].geometry)&&g.push([a.x,a.y]);d={};d[k]=h;1<g.length&&(b?(h=
b.geometry,h.removePath(0),h.addPath(g),b.setGeometry(h)):(b=new w(new x({paths:[g],spatialReference:u}),null,d),n.add(b),p.trackLineMap[h]=b))}var p=this,n=this.container,e,u,k,l;if(n)if(e=this.trackMap,u=this.map.spatialReference,k=this.layer._trackIdField,d)g.forEach(d,function(e){q(e)});else for(l in e)e.hasOwnProperty(l)&&q(l)},refreshTracks:function(d){function q(e){var d,g;e=p[e]||[];d=e.length;for(g=0;g<d;g++)n._repaint(e[g],null,!0)}var p=this.trackMap,n=this.layer;n._getRenderer();var e;
this.drawTracks(d);if(d)g.forEach(d,function(e){q(e)});else for(e in p)p.hasOwnProperty(e)&&q(e)},destroy:function(){this.inherited(arguments);this.trackLineMap=null}});r("extend-esri")&&v.setObject("layers._StreamTrackManager",d,s);return d})},"esri/layers/PurgeOptions":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/Stateful","dojo/has","../kernel"],function(d,v,g,r,s){d=d([g],{declaredClass:"esri.layers.PurgeOptions",constructor:function(d,g){this.parent=d;for(var r in g)this[r]=
g[r]},_displayCountSetter:function(d){this.displayCount=d;this.parent.refresh()}});r("extend-esri")&&v.setObject("layers.PurgeOptions",d,s);return d})},"*noref":1}});
define("esri/layers/StreamLayer","dojo/_base/declare dojo/_base/connect dojo/_base/array dojo/_base/Color dojo/_base/lang dojo/has dojo/on dojo/aspect ../kernel ../request ../graphic ./FeatureLayer ./StreamMode ./StreamTrackManager ../geometry/jsonUtils ../symbols/SimpleFillSymbol ../symbols/SimpleLineSymbol ../symbols/SimpleMarkerSymbol ../renderers/SimpleRenderer ./PurgeOptions".split(" "),function(d,v,g,r,s,w,x,y,A,q,p,n,e,u,k,l,h,t,B,z){d=d([n],{declaredClass:"esri.layers.StreamLayer",_preventInit:!0,
constructor:function(a,b){b=b||{};if(!b.mode||b.mode===n.MODE_STREAM)this._isStream=!0,this.currentMode=this.mode=n.MODE_STREAM,this._mode=new e(this);this.purgeOptions=new z(this,b.purgeOptions||{});this.purgeInterval=b.purgeInterval||0;this._reconnectAttempts=0;this.maxReconnectAttempts=10;this.socket=this._reconnectTimeoutId=null;this._keepLatestQueried=!1;this._keepLatestUrl=null;this._relatedQueried=!1;this._joinField=this._relatedUrl=null;this._refreshing=!1;this._attemptReconnect=s.hitch(this,
this._attemptReconnect);this._purge=s.hitch(this,this._purge);this._initFeatureLayer(a,b)},_initLayer:function(a,b){this.inherited(arguments);if(a){var c;if(a.layerDefinition)this.purgeOptions=new z(this,this._params.purgeOptions||{}),this.socketUrl=this._params.socketUrl||a.layerDefinition.socketUrl||void 0;else{if(this._params.socketUrl)this.socketUrl=this._params.socketUrl;else{var f=this._getWebsocketConnectionInfo(a),m=f.urls;m&&m.length?(this._socketUrls=m,this.socketUrl=m[0],this.socketDirection=
"broadcast"===this._params.socketDirection?"broadcast":"subscribe",this.socketUrl+="/"+this.socketDirection,this._websocketToken=f.token,m.length>this.maxReconnectAttempts&&(this.maxReconnectAttempts=m.length)):(this.socketUrl=void 0,f="No web socket urls were retrieved from the Stream Service. Layer will not attempt to connect.","https:"===location.protocol&&(f+=" An insecure web socket connection cannot be made from a secure web page."),this.onError(Error(f)))}if(this._params.filter)try{this._filter=
c=this._makeFilter(this._params.filter)}catch(e){this.onError(Error("Error trying to create filter object: "+e+". Layer will not have filter applied")),this._filter=null}if(this._params.geometryDefinition||this._outFields||this._defnExpr){c=c||{};c.geometry=this._params.geometryDefinition;c.outFields=this._outFields;c.where=this._defnExpr;try{this._filter=c=this._makeFilter(c)}catch(d){this.onError(Error("Error trying to create filter object: "+d+". Layer will not have filter applied")),this._filter=
null}}}this.maximumTrackPoints=this._params.maximumTrackPoints||0===this._params.maximumTrackPoints?this._params.maximumTrackPoints:1;(this._params.refreshRate||0===this._params.refreshRate)&&this._mode&&this._mode._setRefreshRate&&this._mode._setRefreshRate(this._params.refreshRate);this._keepLatestUrl=a.keepLatestArchive?a.keepLatestArchive.featuresUrl:null;a.relatedFeatures&&(a.relatedFeatures.featuresUrl&&a.relatedFeatures.joinField)&&(this._relatedUrl=a.relatedFeatures.featuresUrl,this.objectIdField=
this._joinField=a.relatedFeatures.joinField);this.objectIdField||this._makeObjectIdField();this._map&&(this.socketUrl&&!this._connected)&&this.connect()}},_setMap:function(a){var b=this.inherited(arguments),c=this._getRenderer();if(this.timeInfo&&(this._trackIdField||c&&(c.latestObservationRenderer||c.trackRenderer)))this._trackManager=new u(this),this._trackManager.initialize(a);this.socketUrl&&(!this._connected&&this._map)&&this.connect();return b},_unsetMap:function(a,b){g.forEach(this._connects,
v.disconnect);(this._connected||this._reconnecting||this.socket)&&this.disconnect();this._togglePurgeT();this.inherited(arguments);this._map=null},_suspend:function(){this._togglePurgeT();this.inherited(arguments)},_resume:function(){this.inherited(arguments);this._togglePurgeT(!0)},clear:function(){try{this._mode&&this._mode._clearDrawBuffer&&this._mode._clearDrawBuffer(),this._mode&&this._mode._clearTimeBin&&this._mode._clearTimeBin(),this._mode&&this._mode._clearFeatureMap&&this._mode._clearFeatureMap(),
this._trackManager&&this._trackManager.clearTracks()}catch(a){}this.inherited(arguments)},redraw:function(){this._mode&&this._mode._flushDrawBuffer&&this._mode._flushDrawBuffer();this.inherited(arguments)},setDefinitionExpression:function(a){this.setFilter({where:a})},getDefinitionExpression:function(){var a;this._filter&&(a=this._filter.where);return a},destroy:function(){this.disconnect();this.inherited(arguments)},onResume:function(a){this.inherited(arguments)},setGeometryDefinition:function(a){this.setFilter({geometry:a})},
getGeometryDefinition:function(){var a;this._filter&&(a=this._filter.geometry);return a},connect:function(a){var b=this,c,f=[],m=this._filter,e,d,g=this.socketUrl,h;try{if(!this._connected){if(this._map){if(this._relatedUrl&&!this._relatedQueried&&this._mode._fetchArchive)return c=this.on("update-end",function(){b._relatedQueried=!0;c.remove();c=null;b.connect()}),this._mode._fetchArchive(this._relatedUrl),!1;if(this._keepLatestUrl&&!this._keepLatestQueried&&this._mode._fetchArchive)return c=this.on("update-end",
function(){b._keepLatestQueried=!0;c.remove();c=null;b.connect()}),this._mode._fetchArchive(this._keepLatestUrl),!1}this._websocketToken&&f.push("token\x3d"+this._websocketToken);this._map&&this._map.spatialReference&&this.spatialReference&&this._map.spatialReference.wkid!==this.spatialReference.wkid&&f.push("outSR\x3d"+this._map.spatialReference.wkid);if(m)for(d in m)null!==m[d]&&(e="geometry"===d?JSON.stringify(m[d]):m[d],f.push(d+"\x3d"+e));0<f.length&&(g+="?"+f.join("\x26"));return h=this._createConnection(g,
a)}}catch(k){console.log("Error connecting to data stream: ",k),a&&a(k,!1),this.onConnectionError({error:k})}},disconnect:function(a){var b=this._refreshing?"Disconnecting as part of layer refresh cycle":"Connection closed from client",c=this._refreshing?!0:!1;this._reconnectTimeoutId&&clearTimeout(this._reconnectTimeoutId);this._refreshing=this._reconnecting=this._connected=!1;this.socket&&this.socket.close();this.onDisconnect({willReconnect:c,message:b});a&&a(null,!0)},setFilter:function(a){var b,
c;if(this._collection)return this.onError("Filter can only be set when the source of the layer is a Stream Service"),!1;try{if(void 0!==a.outFields)return c=Error("Outfields property cannot be changed after layer is created"),this.onFilterChange({filter:this.getFilter(),error:c}),!1;b=this._makeFilter(a)}catch(f){return c=Error(f),this.onFilterChange({filter:this.getFilter(),error:c}),!1}if(this.socket)a={filter:b},this.socket.send(JSON.stringify(a));else x.once(this,"connect",function(a){this.setFilter(b)});
return!0},getFilter:function(){var a=this._filter,b={},c=["geometry","outFields","where"];a&&g.forEach(c,function(c){var m=a[c];m&&("geometry"===c?m=k.fromJson(m):"outFields"===c&&(m=m.split(",")),b[c]=m)});return b},setMaximumTrackPoints:function(a){if(!a&&0!==a)return!1;this.maximumTrackPoints=a;this._mode.propertyChangeHandler(3)},getUniqueValues:function(a){var b,c={},f=[];b=this._getField(a,!0);if(!b)return f;a=b.name;g.forEach(this.graphics||[],function(b){b=(b.attributes||{})[a];void 0!==b&&
!c[b]&&(c[b]=1,f.push(b))});f.sort(function(a,b){return a<b?-1:a>b?1:0});return f},setPurgeInterval:function(a){var b=this.purgeInterval;this.purgeInterval=a;this._togglePurgeT();a&&this._togglePurgeT(!0);if(b!==a)this.onPurgeIntervalChange();return this},_togglePurgeT:function(a){if(a&&this.purgeInterval){var b=this;clearTimeout(this._purgeT);this._mode&&this._mode._flushDrawBuffer&&(this._purgeT=setTimeout(function(){!b.updating&&!b.suspended&&(b._mode._flushDrawBuffer(),b._togglePurgeT(!0))},6E4*
this.purgeInterval))}else this._purgeT&&(clearTimeout(this._purgeT),this._refreshT=null)},onMessage:function(){},onConnect:function(){},onDisconnect:function(){},onFilterChange:function(){},onAttemptReconnect:function(){},onConnectionError:function(){},onPurgeIntervalChange:function(){},_createConnection:function(a,b){var c=this,f=new WebSocket(a);f.onopen=function(){c.socket=f;c._connected=!0;c._reconnecting=!1;c._reconnectAttempts=0;c._bind();c.onConnect();b&&b(null,!0)};f.onclose=function(a){var b,
f=!0,d=c._connected,e=null;if(c._connected||c._reconnecting){if(a.code)if(b="Connection failed: ",4400===a.code)b+=a.reason||"Invalid url parameters. Check filter properties.",f=!1;else if(4404===a.code)b+="Service not found",f=!1;else if(4401===a.code||4403===a.code)b+="Not authorized",f=!1;f&&(c._reconnectAttempts+=1,c._reconnectAttempts>c.maxReconnectAttempts&&(b="Maximum reconnect attempts exceeded",f=!1,d=!0));c._connected=!1;d&&(b&&(e=Error(b)),c.onDisconnect({error:e,willReconnect:f}));f?c._attemptReconnect():
c.socket=null}else c.socket||(e=Error("Could not make connection to service"),c.onConnectionError({error:e})),c.socket=null,c._connected=!1};f.onerror=function(a){console.log("Socket error")};return f},_purge:function(){var a,b=[],c;if(this.purgeOptions.displayCount&&this.graphics.length>this.purgeOptions.displayCount)for(a=0;a<this.graphics.length-this.purgeOptions.displayCount;a++)c=this.graphics[a],b.push(c);0<b.length&&(this._mode._removeFeatures(b),this._trackManager&&this._trackManager.removeFeatures(b))},
_bind:function(){var a=this;this.socket.onmessage=function(b){a._onMessage(JSON.parse(b.data))}},_onMessage:function(a){var b=this;this.onMessage(a);var c={create:function(a){b._create(a)},update:function(a){b._update(a)},"delete":function(a){b._delete(a)}};if(a.type)c[a.type](a.feature);else a.hasOwnProperty("filter")?b._handleFilterMessage(a):this._create(a)},_create:function(a){function b(a){if(!c._featureHasOID(a,f)){if(!a.geometry)return!1;a.attributes=a.attributes||{};a.attributes[f]=c._nextId++}a=
a.declaredClass?a:new p(a);c._mode.drawFeature(a)}var c=this,f=c.objectIdField;a.length?a.forEach(function(a){a&&b(a)}):a&&b(a)},_delete:function(a){var b=this,c=a[b.objectIdField]||a.attributes[b.objectIdField],f=!1;this.graphics.forEach(function(a){a.attributes[b.objectIdField]==c&&(f=a)});f&&this.remove(f)},_update:function(a){var b=this,c=!1;this.graphics.forEach(function(f){f.attributes[b.objectIdField]==a.attributes[b.objectIdField]&&(c=f)});c&&(a.attributes&&c.setAttributes(a.attributes),a.geometry&&
c.setGeometry(k.fromJson(a.geometry)))},_makeFilter:function(a){var b,c=null;a=a||{};if(void 0!==a.geometry)if(c=c||{},null===a.geometry)c.geometry=null;else{b="string"===typeof a.geometry?k.fromJson(JSON.parse(a.geometry)):a.geometry.declaredClass?a.geometry:k.fromJson(a.geometry);if(!b||"point"===b.type)throw"Query object contains invalid geometry";"extent"!==b.type&&(b=b.getExtent());if(!b||0===b.getHeight()&&0===b.getWidth())throw"Invalid filter geometry: Extent cannot have a height and width of 0";
c.spatialRel="esriSpatialRelIntersects";c.geometryType="esriGeometryEnvelope";c.geometry=b.toJson()}void 0!==a.where&&(c=c||{},c.where=a.where);if(void 0!==a.outFields&&(c=c||{},a="string"===typeof a.outFields?"*"===a.outFields?null:a.outFields.replace(/,\s+/g,",").split(","):null===a.outFields?null:a.outFields,a=this._makeOutFields(a))){if(a.errors&&0<a.errors.length)throw"Invalid filter outFields. "+a.errors.join(",");c.outFields=a.fields?a.fields.join(","):null}return c},_makeOutFields:function(a){var b=
this,c=[],f=[],d={fields:null};if(!a||0===a.length)return d;g.forEach(a,function(a){if("*"===a)return d;var e=b._getField(a,!0);e?c.push(e.name):f.push("Field named "+a+" not found in schema.")});a=b._getOutFields();g.forEach(a,function(a){b._getField(a)&&-1===g.indexOf(c,a)&&c.push(a)});d.fields=c;d.errors=f;return d},_handleFilterMessage:function(a){a.error?(a=Error(a.error.join(",")),this.onFilterChange({filter:this.getFilter(),error:a})):(a=a.filter,a.geometry&&"string"===typeof a.geometry&&(a.geometry=
JSON.parse(a.geometry)),this._filter=a,this.onFilterChange({filter:this.getFilter()}))},_getWebsocketConnectionInfo:function(a){var b={urls:[]},c,f=[],d=[],e,h,k;a.streamUrls&&g.forEach(a.streamUrls,function(a){"ws"===a.transport&&(c=a.urls,b.token=a.token)});if(!c)return b;g.forEach(c,function(a){0===a.lastIndexOf("wss",0)?d.push(a):f.push(a)});a="https:"===location.protocol||0===this.url.lastIndexOf("https:",0)?d:0===f.length?d:f;if(1<a.length)for(e=0;e<a.length-1;e++)h=e+Math.floor(Math.random()*
(a.length-e)),k=a[h],a[h]=a[e],a[e]=k;b.urls=a;return b},_attemptReconnect:function(){var a=this,b;this._reconnectTimeoutId=null;a._connected=!1;if(!a._socketUrls)return!1;if(!a._collection&&!a._reconnecting&&a.socket&&a.credential)return a._reconnecting=!0,a._getServiceConnectionMetadata(a._attemptReconnect),!1;a._reconnecting=!0;a.socket=null;if(a._reconnectAttempts>a.maxReconnectAttempts)return a._reconnecting=!1;a.socketUrl=a._socketUrls[a._reconnectAttempts>a._socketUrls.length-1?a._reconnectAttempts%
a._socketUrls.length:a._reconnectAttempts];a.socketUrl+="/"+a.socketDirection;b=a._randomIntFromInterval(0,1E3);this._reconnectTimeoutId=setTimeout(function(){a.onAttemptReconnect({count:a._reconnectAttempts,url:a.socketUrl});a.connect()},1E3*a._reconnectAttempts+b)},_getServiceConnectionMetadata:function(a){var b=this,c=b._url.path;a="function"===typeof a?a:null;q({url:c,content:s.mixin({f:"json"},this._url.query),callbackParamName:"callback"}).then(function(c){c=b._getWebsocketConnectionInfo(c);
b._websocketToken=c.token;a&&a()},function(a){b.onError(Error(a))})},_setDefaultRenderer:function(){var a=this.geometryType,b=new r([5,112,176,0.8]),c=new r([255,255,255]),c=new h(h.STYLE_SOLID,c,1),d;if("esriGeometryPoint"===a||"esriGeometryMultipoint"===a)d=new t(t.STYLE_CIRCLE,10,c,b);else if("esriGeometryPolyline"===a)d=new h(h.STYLE_SOLID,b,2);else if("esriGeometryPolygon"===a||"esriGeometryEnvelope"===a)b=new r([5,112,176,0.2]),c=new r([5,112,176,0.8]),c=new h(h.STYLE_SOLID,c,1),d=new l(l.STYLE_SOLID,
c,b);d&&this.setRenderer(new B(d))},_makeObjectIdField:function(){var a=1,b,c,d=[];if(!this.objectIdField){b=this.fields.length;for(c=0;c<b;c++)d.push(this.fields[c].name.toLowerCase());for(;-1!==g.indexOf(d,"objectid_"+a);)a+=1;this.objectIdField="objectid_"+a}},_featureHasOID:function(a,b){return a.attributes&&(a.attributes[b]||0===a.attributes[b])},_randomIntFromInterval:function(a,b){return Math.floor(Math.random()*(b-a+1)+a)}});w("extend-esri")&&s.setObject("layers.StreamLayer",d,A);return d});