define(
   ({
    addDistance: "Dodaj jednostkę odległości",
    addArea: "Dodaj jednostkę powierzchni",
    label: "Etykieta",
    abbr: "Skrót",
    conversion: "Konwersja",
    actions: "Operacje",
    areaUnits: "Jednostki powierzchni",
    distanceUnits: "Jednostki odległości",
    kilometers: "Kilometry",
    miles: "Mile",
    meters: "Metry",
    feet: "Stopy",
    yards: "Jardy",
    squareKilometers: "Kilometry kwadratowe",
    squareMiles: "Mile kwadratowe",
    acres: "Akry",
    hectares: "Hektary",
    squareMeters: "Metry kwadratowe",
    squareFeet: "Stopy kwadratowe",
    squareYards: "Jardy kwadratowe",
    distance: "Odległości",
    area: "Obszary",
    kilometersAbbreviation: "km",
    milesAbbreviation: "mi",
    metersAbbreviation: "m",
    feetAbbreviation: "st.",
    yardsAbbreviation: "jard",
    squareKilometersAbbreviation: "km kw.",
    squareMilesAbbreviation: "mi kw.",
    acresAbbreviation: "akr",
    hectaresAbbreviation: "ha",
    squareMetersAbbreviation: "m kw.",
    squareFeetAbbreviation: "st. kw.",
    squareYardsAbbreviation: "jard kw."
  })
);