define(
   ({
    _widgetLabel: "Attributtabell",
    ok: "OK",
    cancel: "Avbryt",
    unsupportQueryWarning: "Lagret måste ha stöd för frågeåtgärden för att visas i widgeten Attributtabell. Kontrollera att frågefunktionen i tjänsten är påslagen.",
    exportMessage: "Exportera data till CSV-fil?",
    exportFiles: "Exportera till CSV",
    options: "Alternativ",
    zoomto: "Zooma till",
    highlight: "Markera grafik",
    selectAll: "Välj poster på alla sidor",
    selectPage: "Välj poster på aktuell sida",
    clearSelection: "Rensa val",
    filterByExtent: "Filtrera efter kartutbredning",
    showSelectedRecords: "Visa markerade poster",
    showRelatedRecords: "Visa relaterade poster",
    noRelatedRecords: "Inga relaterade poster",
    refresh: "Uppdatera",
    features: "geoobjekt",
    selected: "valt",
    transparent: "Transparent läge",
    indicate: "Hitta val",
    columns: "Visa/dölj kolumner",
    selectionSymbol: "Markeringssymbol",
    closeMessage: "Dölj tabell (expandera den igen från nederkanten)",
    dataNotAvailable: "Data är inte tillgängliga!<br>Klicka på [Uppdatera] för att försöka igen.",
    openTableTip: "Öppna attributtabell",
    closeTableTip: "Dölj attributtabell"
  })
);