define(
   ({
    _widgetLabel: "Tabel de atribute",
    ok: "OK",
    cancel: "Anulare",
    unsupportQueryWarning: "Stratul tematic trebuie să suporte operarea de interogări pentru a fi afişat în widgetul Tabel atribute. Asiguraţi-vă că capacitatea de interogare din serviciu este activată.",
    exportMessage: "Exportaţi datele în fişier CSV?",
    exportFiles: "Export în CSV",
    options: "Opţiuni",
    zoomto: "Transfocare la",
    highlight: "Evidenţiere elemente grafice",
    selectAll: "Selectare înregistrări din toate paginile",
    selectPage: "Selectare înregistrări din pagina curentă",
    clearSelection: "Golire selecţie",
    filterByExtent: "Filtrare după extinderea hărţii",
    showSelectedRecords: "Afişare înregistrări selectate",
    showRelatedRecords: "Afişare înregistrări asociate",
    noRelatedRecords: "Nicio înregistrare asociată",
    refresh: "Reîmprospătare",
    features: "obiecte spaţiale",
    selected: "selectat",
    transparent: "Mod Transparent",
    indicate: "Selectare locaţie",
    columns: "Afişare/Ascundere coloane",
    selectionSymbol: "Simbol pentru selectare",
    closeMessage: "Ascundere tabel (se extinde din nou de jos)",
    dataNotAvailable: "Nu există date disponibile!<br>Faceţi clic pe butonul [Reîmprospătare] pentru a încerca din nou.",
    openTableTip: "Deschidere tabel de atribute",
    closeTableTip: "Ascundere tabel de atribute"
  })
);