define(
   ({
    placeholder: "Vartotojui rodomas tekstas",
    url: "Geokoderio URL",
    name: "Geokoderio pavadinimas",
    example: "Pavyzdys",
    singleLineFieldName: "SingleLineFieldName",
    portalConnectionError: 'Iš portalo negalima gauti geokoderio konfigūracijos',
    actions: "Veiksmai",
    warning: "Tai nepalaikoma geokodavimo paslaugos versija. Šis valdiklis palaiko geokodavimo paslaugos 10.1 ir naujesnes versijas.",
    instruction: "Nustatykite geokoderius šiame valdiklyje. Spustelėkite Pridėti geokoderį, kad nurodytumėte URL, tada nurodykite vartotojui draugišką pavadinimą ir nustatykite kitas savybes. Taip pat galite keisti toliau esančių geokoderių tvarką, juos konfigūruoti ar ištrinti.",
    layerInstruction1: "Konfigūruoti paieškos sąlygą galite ",
    layerInstruction2: "internetinio žemėlapio aprašo puslapyje",
    searchAddress: "Ieškoti pagal adresą",
    searchLayer: "Ieškoti pagal sluoksnį",
    layer: "Sluoksnis",
    field: "Laukas",
    condition: "Sąlyga",
    contains: "įraše yra",
    deleteLastGeocoderError: "Paskutinio geokoderio ištrinti negalima.",
    noSearchFactorError: "Turite pasirinkti bent vieną galimybę (ieškoti pagal adresą arba ieškoti pagal sluoksnį).",
    equals: "Lygu",
    add: "Pridėti geokoderį",
    edit: "Redaguoti geokoderį",
    ok: "Gerai",
    cancel: "Atšaukti",
    geocoderNamePlaceHolder: "Mano geokoderis",
    geocodePlaceHolder: "Surasti adresą arba vietą",
    REPEATING_ERROR: "Kartojasi šie laukai: "
  })
);