define(
   ({
    placeholder: "Platshållartext",
    url: "Geokodarens URL",
    name: "Geokodarens namn",
    example: "Exempel",
    singleLineFieldName: "SingleLineFieldName",
    portalConnectionError: 'Det går inte att hämta konfigurationer för geokodaren från portalen',
    actions: "Åtgärder",
    warning: "Det här är inte version av geokodningstjänsten som stöds. Den här widgeten stöder geokodningstjänsten från och med version 10.1.",
    instruction: "Skapa geokodarna i den här widgeten. Klicka på Lägg till geokodare när du vill referera till en URL, ange ett användarvänligt namn och ställ in eventuella övriga egenskaper. Du kan också arrangera om, konfigurera eller ta bort dina geokodare nedan.",
    layerInstruction1: "Du kan konfigurera sökvillkoret på ",
    layerInstruction2: "sidan med uppgifter för webbkartan",
    searchAddress: "Sök efter adress",
    searchLayer: "Sök efter lager",
    layer: "Lager",
    field: "Fält",
    condition: "Villkor",
    contains: "Innehåller",
    deleteLastGeocoderError: "Den senaste geokodaren går inte att ta bort.",
    noSearchFactorError: "Du måste välja minst en funktion (Sök efter adress eller Sök efter lager).",
    equals: "Lika med",
    add: "Lägg till geokodare",
    edit: "Redigera geokodare",
    ok: "OK",
    cancel: "Avbryt",
    geocoderNamePlaceHolder: "Min geokodare",
    geocodePlaceHolder: "Sök efter adress eller plats",
    REPEATING_ERROR: "Följande fält är upprepade: "
  })
);