define(
   ({
    _widgetLabel: "Рисование",
    selectDrawMode: "Выбрать режим рисования",
    clear: "Очистить",
    point: "Точка",
    line: "Линия",
    polyline: "Линия",
    freehandPolyline: "Линия произвольной формы",
    triangle: "Треугольник",
    extent: "Конверт",
    circle: "Круг",
    ellipse: "Эллипс",
    polygon: "Полигон",
    freehandPolygon: "Полигон произвольной формы",
    text: "Текст",
    style: "Стиль",
    alpha: "Прозрачность",
    width: "Ширина",
    size: "Размер",
    color: "Цвет",
    markerColor: "Цвет маркера",
    outlineColor: "Цвет контура",
    lineColor: "Цвет линии",
    fillColor: "Цвет заливки",
    showMeasurements: "Показать измерения",
    areaUnits: "Единицы площади",
    distanceUnits: "Единицы расстояния",
    kilometers: "Километры",
    miles: "Мили",
    meters: "Метры",
    feet: "Футы",
    yards: "Ярды",
    squareKilometers: "Квадратные километры",
    squareMiles: "Квадратные мили",
    acres: "Акры",
    hectares: "гектары",
    squareMeters: "Квадратные метры",
    squareFeet: "Квадратные футы",
    squareYards: "Квадратные ярды",
    undo: "Отменить",
    redo: "Повторить"
  })
);