define(
   ({
    _widgetLabel: "Tabela de Atributos",
    ok: "OK",
    cancel: "Cancelar",
    unsupportQueryWarning: "A camada tem de suportar operações de consulta para ser exibida no widget de Tabela de Atributos. Garanta que a capacidade de consulta está ligada no serviço.",
    exportMessage: "Exportar dados para ficheiro CSV?",
    exportFiles: "Exportar para CSV",
    options: "Opções",
    zoomto: "Efetuar zoom para",
    highlight: "Destacar Gráficos",
    selectAll: "Selecionar Todas as Páginas",
    selectPage: "Selecionar Página Atual",
    clearSelection: "Limpar Seleção",
    filterByExtent: "Filtrar por Extensão de Mapa",
    showSelectedRecords: "Exibir Registos Selecionados",
    showRelatedRecords: "Exibir Registos Relacionados",
    noRelatedRecords: "Sem Registos Relacionados",
    refresh: "Atualizar",
    features: "elementos",
    selected: "selecionado",
    transparent: "Modo Transparente",
    indicate: "Localizar Seleção",
    columns: "Mostrar/Ocultar Colunas",
    selectionSymbol: "Símbolo de Seleção",
    closeMessage: "Esconder tabela[Voltar as mostrá-la na lista de camadas]",
    dataNotAvailable: "Dados não disponíveis!<br>Clique no botão [Atualizar] para fazer uma tentativa",
    openTableTip: "Abrir tabela de atributos",
    closeTableTip: "Esconder a tabela de atributos"
  })
);