define(
   ({
    showArcgisBasemaps: "Inkludera portalbaskartor",
    settings: "Inställningar",
    add: "Klicka om du vill lägga till en ny baskarta",
    edit: "Egenskaper",
    title: "Titel",
    titlePH: "Baskartans titel",
    thumbnail: "Miniatyrbild",
    thumbnailHint: "Klicka på bilden för att uppdatera den",
    url: "URL",
    urlPH: "Lager-URL",
    addlayer: "Lägg till baskarta",
    actions: "Åtgärder",
    warning: "Felaktiga indata",
    save: "Gå tillbaka och spara",
    back: "Gå tillbaka och avbryt",
    addUrl: "Lägg till URL",
    autoCheck: "Automatisk kontroll",
    checking: "Kontrollerar ...",
    ok: "OK",
    cancel: "Avbryt",
    result: "Sparad",
    spError: "Alla baskartor som läggs till i galleriet måste ha samma geografiska referenser.",
    invalidTitle1:"Baskartan '",
    invalidTitle2:"' finns redan. Välj en annan titel.",
    invalidBasemapUrl1: "Den här typen av lager går inte att använda som baskarta.",
    invalidBasemapUrl2: "Annan geografisk referens från den aktuella kartan.",
    addBaselayer: "Lägg till baskartlager"
  })
);